### PR TITLE
[Device, kindle] early return if kindleGetCurrentProfile() is nil

### LINKED ISSUE #14215: performing my 'turn wifi on' gesture  when the wifi is already on crashes koreader.
### Device

Kindle

### KOReader version

2025.08

### Model and firmware version

kindle 4, firmware v 4.1.4

### Issue description

i have two kindles - K4 (kindle 4th gen) and KT4 (kindle 10th gen). 

on my KT4, i've added 'turn wifi on' option to a quick menu that's mapped to a gesture. tapping that option _when connected to a network_ shows the 'already connected to network x' popup, which makes it very easy for me to know which specific network i'm connected to.

but on my K4, when i click on that same trigger _when connected to a network_, koreader simply crashes. 

p.s clicking it when wifi is off does not cause a crash. it just turns the wifi on. 

### Steps to reproduce

1. set a gesture that triggers 'turn wifi on' option.  
2. connect to a wifi network. 
3. perform the gesture. 
4. koreader will crash. 

### Log

```shell
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/23/25-15:35:41
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2025.08

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: archive [13]
ffi.load: libs/libarchive.so.13
08/23/25-15:35:41 WARN  could not load liblipclua: module 'liblipclua' not found:
	no field package.preload['liblipclua']
	no file 'common/liblipclua.lua'
	no file 'frontend/liblipclua.lua'
	no file 'plugins/exporter.koplugin/liblipclua.lua'
	no file './liblipclua.lua'
	no file '/usr/local/share/luajit-2.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua/init.lua'
	no file 'common/liblipclua.so'
	no file 'common/liblipclua.dll'
	no file '/usr/lib/lua/liblipclua.so'
	no file './liblipclua.so'
	no file '/usr/local/lib/lua/5.1/liblipclua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so' 
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `tequila-keypad` = KEY | PAGINATION_BUTTONS | HOME_BUTTON | MENU_BUTTON
[FBInk] /dev/input/event1: `fiveway` = KEY | DPAD
[FBInk] /dev/input/event2: `volume` = KEY | VOLUME_BUTTONS
[ko-input] Forked off fake event generator (pid: 11363)
08/23/25-15:35:41 INFO  initializing for device Kindle4 
08/23/25-15:35:41 INFO  framebuffer resolution: {
  h = 800,
  w = 600
} --[[table: 0x405f5720]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
08/23/25-15:35:41 INFO  Performing one-time migration for 20200421 
08/23/25-15:35:41 WARN  os.remove: ./cache/fontlist/fontinfo.dat: No such file or directory 
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
08/23/25-15:35:42 INFO  ./cache/fontlist/fontinfo.dat fopen: No such file or directory -> initializing it 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210306 (1/2) 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210306 (2/2) 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210330 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210404 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210409 
08/23/25-15:35:43 WARN  os.rename: ./cache/fontinfo.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210412 
08/23/25-15:35:43 WARN  os.rename: ./cache/calibre-libraries.lua: No such file or directory 
08/23/25-15:35:43 WARN  os.rename: ./cache/calibre-books.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210414 
08/23/25-15:35:43 WARN  os.remove: ./cache/calibre/books.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210503 & 20210508 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210518 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210521 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210531 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210622 
08/23/25-15:35:43 WARN  os.remove: ./cache/fontlist/fontinfo.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210629 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210715 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210720 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210831 
08/23/25-15:35:43 INFO  Performing one-time migration for 20210925 
08/23/25-15:35:43 INFO  Performing one-time migration for 20220116 
08/23/25-15:35:43 INFO  Performing one-time migration for 20220205 
08/23/25-15:35:43 INFO  Performing one-time migration for 20220819 
08/23/25-15:35:43 INFO  Performing one-time migration for 20220914 
08/23/25-15:35:43 WARN  os.remove: ./cache/fontlist/fontinfo.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20220930 
08/23/25-15:35:43 WARN  loadfile: cannot open ./defaults.persistent.lua: No such file or directory 
08/23/25-15:35:43 WARN  os.rename: ./defaults.persistent.lua: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20221027 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230531 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230703 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230707 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230710 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230731 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230802 
08/23/25-15:35:43 INFO  statistics.sqlite3 not found. 
08/23/25-15:35:43 INFO  Performing one-time migration for 20230901 
08/23/25-15:35:43 INFO  Performing one-time migration for 20231217 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240408 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240616 
08/23/25-15:35:43 WARN  os.remove: ./cache/fontlist/fontinfo.dat: No such file or directory 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240731 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240911 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240914 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240915 
08/23/25-15:35:43 INFO  Performing one-time migration for 20240928 
08/23/25-15:35:43 INFO  Performing one-time migration for 20241123 
08/23/25-15:35:43 INFO  Performing one-time migration for 20241207 
08/23/25-15:35:43 INFO  Performing one-time migration for 20241208 
08/23/25-15:35:43 INFO  Performing one-time migration for 20241228 
08/23/25-15:35:43 INFO  Performing one-time migration for 20250207 
08/23/25-15:35:43 INFO  Performing one-time migration for 20250302 
08/23/25-15:35:43 INFO  Performing one-time migration for 20250318 
08/23/25-15:35:43 INFO  Performing one-time migration for 20250405 
08/23/25-15:35:43 INFO  Performing one-time migration for 20250601 
08/23/25-15:35:44 INFO  opening file ./help/quickstart-en-v2025.08.html 
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
08/23/25-15:35:45 INFO  Inhibiting user input 
08/23/25-15:35:45 INFO  Looking for plugins in directory: plugins 
08/23/25-15:35:46 INFO  CoverBrowser: setting default display modes 
08/23/25-15:35:46 WARN  BookInfo cache DB schema updated from version 0 to version 20201210 
08/23/25-15:35:46 WARN  Deleting existing ./settings/bookinfo_cache.sqlite3 to recreate it 
08/23/25-15:35:46 WARN  No hotkeys file or invalid hotkeys file found, copying defaults 
08/23/25-15:35:47 INFO  Restoring user input handling 
08/23/25-15:36:07 WARN  menu id not found: taps_and_gestures 
08/23/25-15:38:28 WARN  menu id not found: taps_and_gestures 
08/23/25-15:38:34 INFO  opening file /mnt/us/koreader/help/quickstart-en-v2025.08.html 
08/23/25-15:38:34 INFO  Inhibiting user input 
08/23/25-15:38:36 INFO  Restoring user input handling 
08/23/25-15:38:46 WARN  menu id not found: taps_and_gestures 
08/23/25-15:38:51 INFO  opening file /mnt/us/koreader/help/quickstart-en-v2025.08.html 
08/23/25-15:38:51 INFO  Inhibiting user input 
08/23/25-15:38:52 INFO  Restoring user input handling 
08/23/25-15:42:33 WARN  menu id not found: taps_and_gestures 
08/23/25-15:45:27 INFO  Preparing to quit UIManager with exit code: 85 
08/23/25-15:45:27 INFO  Tearing down UIManager with exit code: 85 
[ko-input] Closed input device with fd: 6 @ idx: 2 (matched by idx)
[ko-input] Closed input device with fd: 5 @ idx: 1 (matched by idx)
[ko-input] Closed input device with fd: 4 @ idx: 0 (matched by idx)
lipc-wait-event exited normally with status: 0
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/23/25-15:45:27
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2025.08

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: archive [13]
ffi.load: libs/libarchive.so.13
08/23/25-15:45:27 WARN  could not load liblipclua: module 'liblipclua' not found:
	no field package.preload['liblipclua']
	no file 'common/liblipclua.lua'
	no file 'frontend/liblipclua.lua'
	no file 'plugins/exporter.koplugin/liblipclua.lua'
	no file './liblipclua.lua'
	no file '/usr/local/share/luajit-2.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua/init.lua'
	no file 'common/liblipclua.so'
	no file 'common/liblipclua.dll'
	no file '/usr/lib/lua/liblipclua.so'
	no file './liblipclua.so'
	no file '/usr/local/lib/lua/5.1/liblipclua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so' 
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `tequila-keypad` = KEY | PAGINATION_BUTTONS | HOME_BUTTON | MENU_BUTTON
[FBInk] /dev/input/event1: `fiveway` = KEY | DPAD
[FBInk] /dev/input/event2: `volume` = KEY | VOLUME_BUTTONS
[ko-input] Forked off fake event generator (pid: 11677)
08/23/25-15:45:27 INFO  initializing for device Kindle4 
08/23/25-15:45:27 INFO  framebuffer resolution: {
  h = 800,
  w = 600
} --[[table: 0x405dbba8]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
08/23/25-15:45:28 INFO  ./cache/fontlist/fontinfo.dat fopen: No such file or directory -> initializing it 
08/23/25-15:45:29 INFO  Looking for plugins in directory: plugins 
08/23/25-15:45:33 WARN  menu id not found: taps_and_gestures 
08/23/25-15:53:55 INFO  UIManager: No dialogs left to show 
08/23/25-15:53:55 INFO  Tearing down UIManager with exit code: 0 
[ko-input] Closed input device with fd: 6 @ idx: 2 (matched by idx)
[ko-input] Closed input device with fd: 5 @ idx: 1 (matched by idx)
[ko-input] Closed input device with fd: 4 @ idx: 0 (matched by idx)
lipc-wait-event exited normally with status: 0
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/23/25-16:05:28
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2025.08

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: archive [13]
ffi.load: libs/libarchive.so.13
08/23/25-16:05:29 WARN  could not load liblipclua: module 'liblipclua' not found:
	no field package.preload['liblipclua']
	no file 'common/liblipclua.lua'
	no file 'frontend/liblipclua.lua'
	no file 'plugins/exporter.koplugin/liblipclua.lua'
	no file './liblipclua.lua'
	no file '/usr/local/share/luajit-2.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua/init.lua'
	no file 'common/liblipclua.so'
	no file 'common/liblipclua.dll'
	no file '/usr/lib/lua/liblipclua.so'
	no file './liblipclua.so'
	no file '/usr/local/lib/lua/5.1/liblipclua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so' 
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `tequila-keypad` = KEY | PAGINATION_BUTTONS | HOME_BUTTON | MENU_BUTTON
[FBInk] /dev/input/event1: `fiveway` = KEY | DPAD
[FBInk] /dev/input/event2: `volume` = KEY | VOLUME_BUTTONS
[ko-input] Forked off fake event generator (pid: 12265)
08/23/25-16:05:29 INFO  initializing for device Kindle4 
08/23/25-16:05:29 INFO  framebuffer resolution: {
  h = 800,
  w = 600
} --[[table: 0x40799558]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
08/23/25-16:05:30 INFO  Looking for plugins in directory: plugins 
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
08/23/25-16:05:45 WARN  menu id not found: taps_and_gestures 
com.lab126.wan failed to set value for property enable (0x3 lipcErrNoSuchSource)
08/23/25-16:06:08 INFO  Wi-Fi successfully restored (after 6.25 seconds)! 
08/23/25-16:08:58 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
08/23/25-16:08:58 INFO  Inhibiting user input 
08/23/25-16:09:03 INFO  Restoring user input handling 
08/23/25-16:09:28 WARN  menu id not found: taps_and_gestures 
08/23/25-16:26:56 INFO  Inhibiting user input 
08/23/25-16:26:57 INFO  Restoring user input handling 
08/23/25-16:27:02 INFO  Inhibiting user input 
08/23/25-16:27:03 INFO  Restoring user input handling 
com.lab126.wan failed to set value for property enable (0x3 lipcErrNoSuchSource)
08/23/25-16:28:43 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:28:43 INFO  Inhibiting user input 
08/23/25-16:28:44 INFO  Restoring user input handling 
08/23/25-16:29:04 WARN  menu id not found: taps_and_gestures 
com.lab126.wan failed to set value for property enable (0x3 lipcErrNoSuchSource)
08/23/25-16:32:01 INFO  Wi-Fi successfully restored (after 5.25 seconds)! 
08/23/25-16:32:05 WARN  menu id not found: taps_and_gestures 
com.lab126.wan failed to set value for property enable (0x3 lipcErrNoSuchSource)
08/23/25-16:37:52 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:37:52 INFO  Inhibiting user input 
08/23/25-16:37:54 INFO  Restoring user input handling 
08/23/25-16:37:59 WARN  menu id not found: taps_and_gestures 
08/23/25-16:39:16 WARN  menu id not found: taps_and_gestures 
ffi.findlib: leptonica [6]
ffi.load: libs/libleptonica.so.6
ffi.findlib: k2pdfopt [2]
ffi.load: libs/libk2pdfopt.so.2
ffi.findlib: leptonica [6]
ffi.load: libs/libleptonica.so.6
ffi.findlib: k2pdfopt [2]
ffi.load: libs/libk2pdfopt.so.2
08/23/25-16:41:18 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:41:18 INFO  Inhibiting user input 
08/23/25-16:41:20 INFO  Restoring user input handling 
ffi.findlib: lodepng
ffi.load: libs/liblodepng.so
08/23/25-16:43:08 WARN  menu id not found: taps_and_gestures 
08/23/25-16:44:23 INFO  Thumbnails cache: 8/500 (349.0 kB/2.4 MB) 
08/23/25-16:44:40 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:44:40 INFO  Inhibiting user input 
08/23/25-16:44:41 INFO  Restoring user input handling 
08/23/25-16:48:01 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:48:02 INFO  Inhibiting user input 
08/23/25-16:48:03 INFO  Restoring user input handling 
08/23/25-16:51:08 INFO  UIManager: No dialogs left to show 
08/23/25-16:51:08 INFO  Tearing down UIManager with exit code: 0 
[ko-input] Closed input device with fd: 6 @ idx: 2 (matched by idx)
[ko-input] Closed input device with fd: 5 @ idx: 1 (matched by idx)
[ko-input] Closed input device with fd: 4 @ idx: 0 (matched by idx)
lipc-wait-event exited normally with status: 0
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/23/25-16:51:57
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2025.08

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: archive [13]
ffi.load: libs/libarchive.so.13
08/23/25-16:51:57 WARN  could not load liblipclua: module 'liblipclua' not found:
	no field package.preload['liblipclua']
	no file 'common/liblipclua.lua'
	no file 'frontend/liblipclua.lua'
	no file 'plugins/exporter.koplugin/liblipclua.lua'
	no file './liblipclua.lua'
	no file '/usr/local/share/luajit-2.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua.lua'
	no file '/usr/local/share/lua/5.1/liblipclua/init.lua'
	no file 'common/liblipclua.so'
	no file 'common/liblipclua.dll'
	no file '/usr/lib/lua/liblipclua.so'
	no file './liblipclua.so'
	no file '/usr/local/lib/lua/5.1/liblipclua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so' 
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `tequila-keypad` = KEY | PAGINATION_BUTTONS | HOME_BUTTON | MENU_BUTTON
[FBInk] /dev/input/event1: `fiveway` = KEY | DPAD
[FBInk] /dev/input/event2: `volume` = KEY | VOLUME_BUTTONS
[ko-input] Forked off fake event generator (pid: 14003)
08/23/25-16:51:57 INFO  initializing for device Kindle4 
08/23/25-16:51:57 INFO  framebuffer resolution: {
  h = 800,
  w = 600
} --[[table: 0x40799c68]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
08/23/25-16:51:58 INFO  Applying patch: ./patches/2-change-status-bar-color.lua 
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
08/23/25-16:51:59 INFO  Looking for plugins in directory: plugins 
08/23/25-16:53:05 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
08/23/25-16:53:06 INFO  Inhibiting user input 
08/23/25-16:53:08 INFO  Restoring user input handling 
08/23/25-16:53:09 WARN  menu id not found: taps_and_gestures 
com.lab126.wan failed to set value for property enable (0x3 lipcErrNoSuchSource)
08/23/25-16:55:48 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:55:48 INFO  Inhibiting user input 
08/23/25-16:55:50 INFO  Restoring user input handling 
08/23/25-16:56:34 WARN  menu id not found: taps_and_gestures 
08/23/25-16:57:07 INFO  Inhibiting user input 
08/23/25-16:57:08 INFO  Restoring user input handling 
08/23/25-16:57:18 INFO  opening file /mnt/us/būx/currently reading/jamie bartlett - the dark net.epub 
08/23/25-16:57:18 INFO  Inhibiting user input 
08/23/25-16:57:19 INFO  Restoring user input handling 
08/23/25-16:57:27 WARN  menu id not found: taps_and_gestures 
08/23/25-16:57:56 INFO  Inhibiting user input 
08/23
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Commodore64user**
### bug fix

* Improved error handling in `NetworkMgr:getCurrentNetwork()` to safely return an empty table if `kindleGetCurrentProfile()` is nil, preventing possible nil dereference issues.

@NiLuJe needs to bless this one.

fixes #14215

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14219)

### CODE REVIEW

**Comment by NiLuJe** [comment]
The `wpaclient` backend seems to be returning `nil, err` tuples in this case, so I'd rather not deviate from that API and fix it on the other end?

(And, well, honor *that* bit of API in case of errors here, too).

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/blob/bd2e33e6963d6187358b7131d17ed0ad728e678c/frontend/ui/network/wpa_supplicant.lua#L197-L217

Which would imply we just need a nil guard, but we *should* be able to return `nil` here, instead of an empty table.

File: frontend/device/kindle/device.lua [hunk 1]
```diff
@@ -459,6 +459,7 @@ function Kindle:initNetworkManager(NetworkMgr)
     end
 
     function NetworkMgr:getCurrentNetwork()
+        if not kindleGetCurrentProfile() then return {} end
         return { ssid = kindleGetCurrentProfile().essid }
```
Comment (NiLuJe) [inline frontend/device/kindle/device.lua]:
```suggestion
        local nw = kindleGetCurrentProfile()
        if nw ~= nil then
            return { ssid = nw.essid }
        end
```

Comment (NiLuJe) [reply frontend/device/kindle/device.lua]: Something along those lines (untested).

Comment (NiLuJe) [reply frontend/device/kindle/device.lua]: Possibly with fancy debug logging like the WpaClient imp ;o).

Comment (Commodore64user) [reply frontend/device/kindle/device.lua]: fancy enough now?

File: frontend/device/kindle/device.lua [hunk 2]
```diff
@@ -459,7 +459,13 @@ function Kindle:initNetworkManager(NetworkMgr)
...
 
     function NetworkMgr:getCurrentNetwork()
-        return { ssid = kindleGetCurrentProfile().essid }
+        local nw = kindleGetCurrentProfile()
+        if nw ~= nil then
+            logger.dbg("NetworkMgr:getCurrentNetwork: Current network found")
+            return { ssid = nw.essid }
+        end
+        logger.dbg("NetworkMgr:getCurrentNetwork: No current network profile found")
+        return nil
```
Comment (Frenzie) [inline frontend/device/kindle/device.lua]: Don't we normally do this the other way around? (if nil then early return, continue with non-nil)

Comment (Commodore64user) [reply frontend/device/kindle/device.lua]: I thought about that, but I didn't want to make @NiLuJe angry ;)

Comment (NiLuJe) [reply frontend/device/kindle/device.lua]: Yeah, agreed; the layout in WpaClient is weird for some reason ;).

File: frontend/device/kindle/device.lua [hunk 3]
```diff
@@ -459,7 +459,13 @@ function Kindle:initNetworkManager(NetworkMgr)
     end
 
     function NetworkMgr:getCurrentNetwork()
-        return { ssid = kindleGetCurrentProfile().essid }
+        local nw = kindleGetCurrentProfile()
+        if nw == nil then
+            logger.dbg("NetworkMgr:getCurrentNetwork: No current network profile found")
+            return nil
+        end
+        logger.dbg("NetworkMgr:getCurrentNetwork: Current network found")
```
Comment (NiLuJe) [inline frontend/device/kindle/device.lua]: This could even print `nw` (or possibly just `nw.essid`, since IIRC that's the only key in there anyway) ;o).

Comment (Commodore64user) [reply frontend/device/kindle/device.lua]: is there any potentially incriminating info there, we should be privacy conscious no?

Comment (NiLuJe) [reply frontend/device/kindle/device.lua]: It's an SSID; if people are worried about that, they're probably in the wrong place ;).

Comment (Commodore64user) [reply frontend/device/kindle/device.lua]: fun fact: I have seen people with SSIDs that include their [partial] address and/or family names, no joke. Do we really gain anything from knowing Little Timmy's "stay off my wifi"?

File: frontend/device/kindle/device.lua [hunk 4]
```diff
@@ -459,7 +459,13 @@ function Kindle:initNetworkManager(NetworkMgr)
     end
 
     function NetworkMgr:getCurrentNetwork()
-        return { ssid = kindleGetCurrentProfile().essid }
+        local nw = kindleGetCurrentProfile()
+        if nw == nil then
+            logger.dbg("NetworkMgr:getCurrentNetwork: No current network profile found")
```
Comment (Frenzie) [inline frontend/device/kindle/device.lua:464]: The one says profile and the other doesn't. :angel:
