### PR TITLE
[ReaderHighlight] Remove duplicated setting on NT devices

### LINKED ISSUE #11747: Duplicated options on Non-touch
* KOReader version: 2024.03.1-55 (on older versions too)
* Device: Kindle 4/5 (non-touch in general)

#### Issue
There is one option duplicated in the menus, one comes from --#8877 and later #8914-- the other not sure.
Both `NEW: Long-press on text` and `Select on text` appear to be the exact same thing with different names.
#### Steps to reproduce
Open any book, go to "page with bookmark > NEW: Long-press on text" the other is found under "page with text > Select on text"

### PR DESCRIPTION
**Pull request by Commodore64user**
closes #11747

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11750)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -589,11 +589,12 @@ Except when in two columns mode, where this is limited to showing only the previ
...
     })
 
-    -- long_press menu is under taps_and_gestures menu which is not available for non touch device
-    -- Clone long_press menu and change label making much meaning for non touch devices
+    -- long_press setting is under taps_and_gestures menu which is not available for non-touch devices
+    -- Clone long_press setting and change its label, making it much more meaningful for non-touch device users.
     if not Device:isTouchDevice() and Device:hasDPad() then
         menu_items.selection_text = util.tableDeepCopy(menu_items.long_press)
         menu_items.selection_text.text = _("Select on text")
+        menu_items.long_press = nil
```
Comment (hius07) [inline frontend/apps/reader/modules/readerhighlight.lua:597]: With this line added, we do not need `tableDeepCopy` anymore.

**Review by hius07 — APPROVED** [review]

**Comment by Frenzie** [comment]
Thanks!
