### PR TITLE
Text input related fixes & enhancements

### LINKED ISSUE #4129: Hold backspace (virtual keyboard) clears all text from InputDialog
* KOReader version: git master
* Device: emulator

#### Issue
Long press (2 seconds?) backspace key (virtual keyboard) clears all InputDialog text. 
IMHO this is unexpected in multilines texts e.g. news downloader config editor (https://github.com/koreader/koreader/pull/4126 )

Where config is over 1kb (>1000 chars) and hold backspace clears all.
Expected behavior would be to delete char one by one.

#### Steps to reproduce
Open multiline InputDialog eg.#4126 hold backspace to delete line - it clears all configuration.

### PR DESCRIPTION
**Pull request by poire-z**
InputText: checks whether provided content can be given back unaltered, which may not be the case after it is splitted to UTF8 chars if the text is binary content. Prevent editing text if that is the case.
See https://github.com/koreader/koreader/pull/4070#issuecomment-408671971
Added InputText and InputDialog :isEditable() and :isEdited()

Virtual keyboard: Hold on Backspace: delete from cursor to start of line instead of clearing all text content. Shouldn't feel like too much a change on the most common single line InputTexts (it now deletes from cursor, but as these starts with cursor at end, it will work as clear all if used at start), and it is more convenient and useful (quicker lines deletion) on the newly possible multi lines edits. Closes #4129.

Also ensure a minimal size of the scrollbar thumb so it is rendered when huge text with many lines is displayed.
<kbd>image</kbd>

Also accounts for the scrollbar width when measuring text to prevent it from being displayed when not needed. For example:
When we didn't use a ScrollTextWidget:
tbw_noscroll

After the change to use a ScrollTextWidget:
tbw_bad

Still using ScrollTextWidget, but with this fix:
tbw_fixed

### CODE REVIEW

File: frontend/ui/widget/verticalscrollbar.lua [hunk 1]
```diff
@@ -13,6 +13,7 @@ local VerticalScrollBar = Widget:new{
     bordercolor = Blitbuffer.COLOR_BLACK,
     radius = 0,
     rectcolor = Blitbuffer.COLOR_BLACK,
+    min_thumb_size = Size.line.thick,
```
Comment (Frenzie) [inline frontend/ui/widget/verticalscrollbar.lua]: Thumb? Wouldn't min_scrollbar_width or something make more sense or am I misunderstanding it completely?

Comment (NiLuJe) [reply frontend/ui/widget/verticalscrollbar.lua]: It's the actual scrollbar 'notch', not the scrollbar itself. Which I somehow also forgot the usual name of :D.

Comment (poire-z) [reply frontend/ui/widget/verticalscrollbar.lua]: Well, I dunno how to name that little black area inside the full white inner scrollbar, that represents the current page size and position relative to the whole document.
When the document is big, and you're only displaying a little fraction of the document height (like in the screenshot above), the little black thing was sized 0 and not visible. So I decided to ensure a minimal size (actually height rather than width, so I named it "size" :| ).
I googled it and found "thumb" (may be in context where one could actually move it with the mouse or a finger...).
Any other name? notch then. or stick with thumb?
(Size.line.thick, cause it was the right size I needed :), the other Size.line were too small. Yeah, that's not a line, but it becomes a line when too small :) should I add something to Size.item ?)

Comment (Frenzie) [reply frontend/ui/widget/verticalscrollbar.lua]: I thought that was called something like the grip or the knob but Gtk and Microsoft seem to call it the thumb.

https://en.wikipedia.org/wiki/Scrollbar
> The “thumb” has different names in different environments: on the Mac OS X 10.4 it is called a "scroller";[3] on the Java platform it is called "thumb" or "knob"; Microsoft's .NET documentation refers to it as "scroll box" or "scroll thumb"; in other environments it is called "elevator", "quint", "puck", "wiper" or "grip". 

Anyway, carry on then. Maybe add a comment saying what it is? Maybe it's just a weird gap in my knowledge. ;-)

**Comment by poire-z** [comment]
(Let this PR sits for a while, till I am sure these new methods are really usable by the text editor plugin)

**Comment by poire-z** [comment]
Merging soon if no one is bothered by the _Hold on Backspace_ change, so I can add more stuff to these files in a Text Editor plugin PR and avoid conflicts.

**Comment by Frenzie** [comment]
> bothered

I'm negative bothered by it since I think it's an improvement. ;-)
