### PR TITLE
[SortWidget] bug fix: Fix keyboard hold events targeting wrong item

### LINKED ISSUE #13258: NT hold events borked in SortWidget
* KOReader version: 2024.11-169. same issue in 2024.11
* Device: non-touch kindle

#### Issue

`SortWidget` NT hold events seem to be broken and are not working as expected. First item is exclusively always selected or unselected, see footage below

#### Steps to reproduce

Gif

### PR DESCRIPTION
**Pull request by Commodore64user**
### bug fix

When using <kbd>shift</kbd>/<kbd>screenkb</kbd>  + <kbd>press</kbd>  on non-touch devices, hold events were always affecting the first item instead of the focused one. Added onHold() handler to SortWidget that directly targets the focused item, bypassing the coordinate-based gesture system that was causing the misdirection.

* Renamed the `onHold` method to `onHoldTouch` in `SortItemWidget`, ensuring the method does not clash with FocusManager's own Hold events.
* Updated the `registerKeyEvents()` method in `SortWidget` to add a new `HoldNonTouch` event for keyboard-based hold actions, and unified modifier handling for screen keyboard and physical keyboard inputs.
* Added a new `onHoldNonTouch` method in `SortWidget` to handle keyboard-triggered hold events by invoking the `onHoldTouch` method on the currently focused item, enabling consistent hold behaviour for non-touch devices.

### related issues
* fixes #13258

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14252)

### CODE REVIEW

**Comment by hius07** [comment]
It breaks long-press on a touch device.

**Comment by Commodore64user** [comment]
I didn't think of that.

Two methods with early returns based on touch/non-touch?

**Comment by Commodore64user** [comment]
Same here @Frenzie, this does leave some devices falling through cracks though, i.e touch devices with keyboards can only use the touch based approach... so not optimal

File: frontend/ui/widget/sortwidget.lua [hunk 1]
```diff
@@ -611,6 +612,36 @@ function SortWidget:onCancel()
     return true
 end
 
+function SortWidget:onHold()
+    if Device:isTouchDevice() then return false end -- let SortItemWidget:onHold handle it
+    -- Handle keyboard-triggered hold events by acting on the focused item directly
```
Comment (Frenzie) [inline frontend/ui/widget/sortwidget.lua:612]: Why not just let the keyboard trigger onSomethingNotHold?

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:612]: do you mean, a new key event called here as opposed to using FocusManager's onHold?

File: frontend/ui/widget/sortwidget.lua [hunk 2]
```diff
@@ -43,7 +43,7 @@ function SortItemWidget:init()
             range = self.dimen,
         }
     }
-    self.ges_events.Hold = {
+    self.ges_events.HoldTouch = {
```
Comment (hius07) [inline frontend/ui/widget/sortwidget.lua:46]: No need to change this.

File: frontend/ui/widget/sortwidget.lua [hunk 3]
```diff
@@ -611,6 +608,35 @@ function SortWidget:onCancel()
...
+    local page_last = math.min(idx_offset + self.items_per_page, #self.item_table)
+    local items_on_page = page_last - idx_offset
+
+    -- Skip if focus is on footer or invalid
+    if focused_row < 1 or focused_row > items_on_page then
+        return true
+    end
+
+    local item_idx = idx_offset + focused_row
+    local item = self.item_table[item_idx]
```
Comment (hius07) [inline frontend/ui/widget/sortwidget.lua]: Can this be used instead?
https://github.com/koreader/koreader/blob/672be80e4946b646761f305c772f1e5a3302360a/frontend/ui/widget/focusmanager.lua#L431

File: frontend/ui/widget/sortwidget.lua (hunk 2 above)
Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: Actually, this creates an awkward situation where sometimes this is triggered and the same broken behaviour happens, so yeah, name change is needed.

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: I don't think so.
Moreover, `onHoldNonTouch` should not duplicate the code but call `item:onHold`.

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: well I am telling you, naming it `onHold` does in fact interfere and break the functionality sometimes.

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: > break the functionality sometimes

Could you give more details?

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: onHold triggered through FocusManager i suppose, runs before onHoldNT gets a chance to...

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: The "Hold" event is sent by a long-press only:
https://github.com/koreader/koreader/blob/00db7cac9a0b84b2a8bb221ce12b0b31760f37b2/frontend/ui/widget/sortwidget.lua#L46-L51
The "Hold" event cannot be sent by a key.

A key sends the "HoldNonTouch" event, and the handler directly calls the `item:onHold` method, no more events sent.

I do not see a conflict.

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: Why don't you try telling that to the computer?, that does not seem to care. Focus Manager triggers onHold with keys man. For the last time, i am not asking you what you think, I'm pointing out what's actually happening.

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: > Focus Manager triggers onHold with keys

Could you show the code where it's happening?

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: https://github.com/koreader/koreader/blob/00db7cac9a0b84b2a8bb221ce12b0b31760f37b2/frontend/ui/widget/focusmanager.lua#L61-L62

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: Thanks.
Since in this FocusManager instance you introduce new events bound to certain keys, the correct way would be to disable the default ones provided by FocusManager base class.
To avoid sending 2 different events by one key or key combination.
If I remember correctly, you do this in some other places.
`self.key_events[smth] = nil`

Comment (hius07) [reply frontend/ui/widget/sortwidget.lua:46]: But it looks like that we don't do this on regular basis, so I agree with your proposition to rename.

Comment (Commodore64user) [reply frontend/ui/widget/sortwidget.lua:46]: In that case, like and subscribe ;)

**Comment by Frenzie** [comment]
Now it also works for touch+keyboard, correct?

**Comment by Commodore64user** [comment]
Yes, works everywhere. Touch, non touch, touch with keyboards, all covered.

**Comment by Commodore64user** [comment]
7th day... the second coming of koreader is nigh (yeah, I am sprinkling some religious satire as well)
