### PR TITLE
Fix scrolling, add inertial scroll on non-eInk devices

### LINKED ISSUE #7413: View mode: continous - pan moves lines much too fast
* KOReader version: 2021.02
* Device: Xiaomi Mi A1 with Android 9

#### Issue

I just installed KOReader some days ago and I am experimenting and comparing it to other readers, especially to Moon+ Reader (Android) which is my actual favorite reader since long.
One of my most important features is the continous scrolling (not only page by page).
In KOReader this is the bottom menu (or setting) View mode: continous.

But the scrolling ist not at all useable on my device, it scrolls big parts and not only line by line, when I swipe down or up. 
The lines should be moved exactly as I move my finger but there is some acceleration with it so that I cannot swipe line by line at all. 
If I swipe up (or down) only a line (I use Font size 30) the text scrolls with speed up (or down), not at all keeping position of my finger.
I didn't find any fine adjusting for this scrolling, I would expect, that the swipe move would be exactly 1:1 in its movement and not 1:10 or more, no acceleration at all. 
Maybe my display has too high resolution (1080x1920)? I have to set Zoom (dpi) to 300 to show images in the right size. With Zoom (dpi): off they show in about a third of their real size.

I don't know if this is by intention, I couldnt believe it, so I guess it is a bug in this special environment (KOReader 2021.02 for Android on Android 9 at least).

Would be great if that feature were useable :)
Thanks!

frank

### LINKED ISSUE #7487: Buggy android scroll
* KOReader version: v2021.02
* Device: Android

#### Issue
 The scroll sometime fail when reading a pdf and reset to previous scrolled position, which lead to infinite scrolling while not actually scrolling
#### Steps to reproduce
Scroll on android

https://user-images.githubusercontent.com/23508913/113410163-9b383a00-9367-11eb-98ea-e4c2b83d26ef.mp4

### PR DESCRIPTION
**Pull request by poire-z**
Add a new reader module: `ReaderScrolling`, that exposes some `Scrolling>` options to the menu (which are to be used by and implemented in `ReaderPaging` and `ReaderRolling` themselves) and implement some inertial scrolling logic used by both of them.
Default to `Classic scrolling` which is the expected behaviour on phones and tablets. Closes #7413.
The old CreDocument buggy behaviour is available as `Turbo scrolling` for both Paging and Rolling documents.
Added a `On release scrolling` option that might be useful on eInk to avoid dynamic pan/scrolling (I had that in my own patch, and was just happy having pan/scroll work like that, so may be others will like it too - it's the one stop solution to not having conflicts with swipe and multiswipe when you just happen to use scroll mode with PDF fit to content width, and sometimes like to reposition a page when you get both half pages on the screen).

Try to avoid bad interactions between pan and swipe, cancelling unwanted panning if we ended up doing a swipe or multiswipe. Closes #7487.

<kbd>image</kbd> - <kbd>image</kbd>

Rewording (see the `help_text =` in the code) suggestions welcome.

(Note: there are a few other issues with scrolling in ReaderPaging, that were there before this, and that I didn't manage to solve - like on a tall screen showing 2 pages, scrolling to first page of the book, trying to scroll back past the first page will obviously not move past document top, but the top of the 2nd page will get progressively blank as you scroll back.)

Also:
- Fix a few possible crashes
- DictQuickLookup: minor canSearch() tweak ('selected_text' is normally available only on multiple words selection, but is currently available on single word selection thanks to some unrelated side effect), see https://github.com/koreader/koreader/pull/7432#pullrequestreview-648622889
- Reader: remove full refresh on vertical swipes. See https://github.com/koreader/koreader/pull/7595#issuecomment-829315836 , more acceptable after this scrolling PR, as having a defined action associated to vertical swipes would conflict with scrolling with vertical pans. So, best to drop vertical swipe in page mode too.
Tweak how full refresh is done on diagonal swipe according to @NiLuJe advice at https://github.com/koreader/koreader/pull/7595#issuecomment-829787091.
- Update footer when panning inside a multi columns/rows page. See https://github.com/koreader/koreader/pull/6885#issuecomment-743409322

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7646)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Just a quick note that I probably won't be able to properly look at/test this until Sunday ;).

File: frontend/apps/reader/modules/readerpaging.lua [hunk 1]
```diff
@@ -482,12 +548,36 @@ function ReaderPaging:onPanRelease(_, ges)
...
+            -- (Don't do that if called by onSwipe, with ges=nil)
+            self:onPanningRel(-self._pan_prev_relative_y)
+            self._pan_has_scrolled = true
+        end
+        self._pan_prev_relative_y = 0
+        self.view.currently_scrolling = false
+        if self._pan_has_scrolled then
+            self._pan_has_scrolled = false
+            -- Don't do any inertial scrolling if pan events come from
+            -- a mousewheel (which may have itself some inertia)
```
Comment (NiLuJe) [inline frontend/apps/reader/modules/readerpaging.lua:561]: <3 logitech wheels in "free" mode ;p.

**Comment by poire-z** [comment]
Added a commit: Update footer when panning inside a multi columns/rows page. See https://github.com/koreader/koreader/pull/6885#issuecomment-743409322

**Comment by poire-z** [comment]
The latest commit, by adding `self.view.footer_visible`, causing a repaint, cause some failure with a single unit test:
```
[ RUN      ] spec/front/unit/readerpaging_spec.lua @ 65: Readerpaging module Scroll mode should emit EndOfBook event at the end
frontend/ui/widget/textwidget.lua:349: attempt to index field '_xtext' (a nil value)

stack traceback:
	frontend/ui/widget/textwidget.lua:349: in function 'paintTo'
	frontend/ui/widget/container/rightcontainer.lua:24: in function 'paintTo'
	frontend/ui/widget/horizontalgroup.lua:49: in function 'paintTo'
	frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:48: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/container/bottomcontainer.lua:18: in function 'paintTo'
	frontend/ui/uimanager.lua:1532: in function 'widgetRepaint'
	frontend/apps/reader/modules/readerfooter.lua:1990: in function 'updateFooterText'
```
Trying to track what's happening, it looks like a TextWidget:free() might be called, and that TextWidget later re-used (added a few print(), the last true/false being self._updated):
```
updatesize 45 / 45 true
45 / 45
[       OK ] ./spec/front/unit/readerpaging_spec.lua @ 28: Readerpaging module Page mode should emit EndOfBook event at the end (556.58 ms)
free 45 / 45 true
free 1 / 45 false
free 1 / 45 false
updatesize 1 / 45 false
xtext created
updatesize 1 / 45 true
[ RUN      ] ./spec/front/unit/readerpaging_spec.lua @ 65: Readerpaging module Scroll mode should emit EndOfBook event at the end
free 1 / 45 true
updatesize 1 / 45 true
updatesize 1 / 45 true
updatesize 1 / 45 true
updatesize 1 / 45 true
1 / 45
frontend/ui/widget/textwidget.lua:352: attempt to index field '_xtext' (a nil value)
```
Adding:
```diff
 function TextWidget:free()
+    print("free "..self.text.." "..tostring(self._updated))
     --print("TextWidget:free on", self)
     -- Allow not waiting until Lua gc() to cleanup C XText malloc'ed stuff
     if self._xtext then
         self._xtext:free()
         self._xtext = nil
+        self._updated = false
     end
 end
```
would allow re-using a :free()'ed TextWidget, but I'm not sure it's the right thing to do, there might be something fishy in the footer code :/ or this unit test not-doing something that is required - but I can't find out what.

**Comment by Frenzie** [comment]
I'm not sure this is working? It looks to me like panning is pretty much completely broken if I try this.

**Comment by poire-z** [comment]
Works for me on my emulator, my Kobo and my Android phone. May be you played (or I did :) with the default gesture swipe or pan intervals?
What behaviour do you get, on which device? Some swiping, some text selection, some beginnig of scrolling ?

**Comment by Frenzie** [comment]
Maybe the mouse-based panning is just inelegant and I never noticed because scrolling is much more effective on desktop. But the inertia is behaving quite absurdly in any case, especially in combination with "use smaller panning rate".

**Comment by poire-z** [comment]
> But the inertia is behaving quite absurdly in any case, especially in combination with "use smaller panning rate".

Indeed, it then gets a smaller scrolling rate :) It's supposed to be used with the normal 30fps rate on touch devices that supports that (it's disabled on eInk).
(On my emulator over network, it's hard for me to trigger it, and with the debug log rolling...)

> It keeps doing things for many, many seconds.

So, it works :) We can discuss the friction value I used in the code, but I kind of like it on Android (where this feature will be interesting).

And apart from this inertial scrolling, that you can disable, how's the rest?

**Comment by Frenzie** [comment]
It all just comes across as very jerky to me and not smooth the way it used to be.

**Comment by poire-z** [comment]
You'd have to be more precise, because _the way it used to be_ used to differ between EPUB and PDF.
And say what feels jerky: the inertial scrolling, or the rest ? And on what device you tested - because if you're still just on the emulator, where inertial scrolling is enabled just for testing, we could disable it.
Or tune inertial scrolling to stop when the last distance is <= 5px, because it keeps doing a lot of 2px 1px scrolling at the end because of some exponential formula that ends with a lot of that :)

The only thing that could feel jerky to me is on swipe/multiswipe, where we cancel a panning done but not intended, so it does up & down - but it feels better than keeping the unintended modified position.

**Comment by Frenzie** [comment]
I'm talking about paged media. I've never felt any desire to use panning in EPUB (and *almost* never in PDF/DjVu, a bit more in CBZ perhaps).

> And on what device you tested - because if you're still just on the emulator, where inertial scrolling is enabled just for testing, we could disable it.

I'm talking about with and without. On the emulator it's always been good, hasn't it?

**Comment by poire-z** [comment]
> I'm talking about with and without.

On PDF, without inertial scrolling, it should behave as previously. So please be precise in describing any differences :)
Also check with "small" or "normal" pan rate - we could also disable it with "small pan rate", or just not use this smaller pan rate and keep using 30fps.
So, still only tested on the emulator?

> On the emulator it's always been good, hasn't it?

I don't know, never really did any panning, arrow up & down keys or the mousewheel were enough for small adjustments and non-full-page scrolling.

**Comment by Frenzie** [comment]
Okay, besides the inertial scrolling being far too enthusiastic about keeping on going it does behave as it always did. Apparently scrolling is just oddly jerky in the 2col.pdf document for some reason and I just never noticed; it's fine in djvu3spec.djvu.

[Peek 2021-05-09 12-39.mp4.zip](https://github.com/koreader/koreader/files/6447303/Peek.2021-05-09.12-39.mp4.zip)

**Comment by poire-z** [comment]
> here's the inertial scrolling just going and going and going

Well, I have no issue with that :) it would behave like this on Android too. Just touch anywhere on the screen to stop that.
But I'm fine making it stop earlier if that bothers you.
If you could try playing with these tunables:
https://github.com/koreader/koreader/blob/492f9f2b0cf58d047f3f9d357598061db219391c/frontend/apps/reader/modules/readerscrolling.lua#L25
or, probably better to not lose the smoothness with a harder friction, change these `2` to `5` or `10`, so it avoids doing 2px/1px scrolls at the end:
https://github.com/koreader/koreader/blob/492f9f2b0cf58d047f3f9d357598061db219391c/frontend/apps/reader/modules/readerscrolling.lua#L325

Also note that with PDFs, when changing pages when scrolling, there may be a small pause caused by the "hinting"/rendering of the next to next page.

**Comment by Frenzie** [comment]
20 isn't too bad. I think you're probably missing a scaleBySize with a smaller value like 10. It still seems to me it's rather too enthusiastic about really small panning distances near the end of the curve though.

**Comment by poire-z** [comment]
I can add this:
```diff
--- a/frontend/apps/reader/modules/readerscrolling.lua
+++ b/frontend/apps/reader/modules/readerscrolling.lua
@@ -7,2 +7,3 @@ local logger = require("logger")
 local _ = require("gettext")
+local Screen = Device.screen

@@ -25,2 +26,4 @@ local ReaderScrolling = InputContainer:new{
     scroll_friction = 0.2, -- the lower, the sooner inertial scrolling stops
+    -- stop scrolling when we would do scroll steps smaller than this
+    min_scoll_dist = Screen:scaleBySize(10),
     -- no inertial scrolling if 300ms pause without any movement before release
@@ -324,3 +327,3 @@ function ReaderScrolling:_setupAction()

-        if did_scroll and (dist >= 2 or dist <= -2) then
+        if did_scroll and (dist > self.min_scoll_dist or dist < -self.min_scoll_dist) then
             UIManager.refresh_count = 0 -- avoid partial to full promotion
```
But I'd like another opinion about with or without this. Having played with it and small distance scrolling at end of curve for a few days, I'm now surprised and a bit frustrated that it stops that early at a somehow random distance :)

**Comment by Frenzie** [comment]
While I think it's still a bit overly non-resistant that's definitely better, thanks! :-)

**Comment by poire-z** [comment]
> If on release basically co-opted swipes

We can't and don't want to do that, or swipes (or slow swipes, which I do) would not work.

> On release looks like something I'd like on eInk, but it only appears to work with true pans, and those are already hard enough to generate without a swipe on eInk that I can't really test it 

Well, a pan is: don't hold at start, hold at end.
(hold at start = hold = text selection)
(don't hold at end and it's a swipe)
So, easy to test: just wait 1 second before release: that's what I've been doing for pan.

**Comment by poire-z** [comment]
On eInk, please say what you think about the use of "fast" while panning (that is, images and borders/panels becoming black and white and the text a bit lighter)

**Comment by NiLuJe** [comment]
Okay, quick test on Android:

* Classic works, I'm okay with the current inertia setting. It's *much* trickier to use with menu swipes enabled (which happens to be the default), though, because you're tripping the menus approximately 175% of the time instead ;).
* Turbo lives up to its name ;p. Not quite sure how usable that is in practice, but it works ^^.
* On-release is only barely more usable than on the H2O :s.

**Comment by NiLuJe** [comment]
But classic (and turbo, I guess) are essentially doing that: I'm certainly quick swiping there, not panning/holding/releasing.

**Comment by NiLuJe** [comment]
> > What about something based on the amount of consecutive swipe events?
> 
> Uh, but then these are individual and distinct gestures.
> And it changes everything about the highlevel handlers.
> And I don't want it :)

FWIW, that usually goes: <a bunch of pan states in the same direction> culminating in a single swipe gesture.

> 
> > That's kind of highly counter-intuitive given the name, since you essentially have to hold instead of release ;p.
> 
> That's how we manage to support hold and text selection, quick swipes, and panning.
> Anyway, if this is strange to you, it means you've never been panning - and you were fine with the tricks of handling swipe as pan (because there was no other use for swipe) in the movable things (movable container, imageviewer).

Quite likely, that panning/swipe distinction in KOReader has always felt alien/broken/slow to me ;).

> 
> But with your low interval values, you wouldn't need to wait long before release for it to not be emited as a swipe ?
> 

Strangely enough, I still do (hell, sometimes I even actually have to release for it to trip).

> > Another weird thing with on-release on the H2O: I sometimes get an initial tap before the pan events, meaning if you start in a menu tapzone, you pop said menu up.
> 
> Don't remember it might have happened to me. Nothing new on that front I guess. See your debug/verbose logs for what events you get :)
> (A tap is quick release with a small enough move.)

Initial tap then pans. Definitely without lifting the finger ;).

> 
> > If I pan backwards, then, yeah, it's mostly fast, but if I pan forward, I hardly ever get a fast pan, it's mostly ui.
> 
> Don't remember I got that... I'll test again this evening.
> Even if you browse a few forward pages so they are cached, and then go back to pan forward?

Yep. At best i get a single fast in the mix.

**Comment by NiLuJe** [comment]
> > What about something based on the amount of consecutive swipe events?
> 
> Uh, but then these are individual and distinct gestures.
> And it changes everything about the highlevel handlers.
> And I don't want it :)

FWIW, that usually goes: <a bunch of pan states in the same direction> culminating in a single swipe gesture.

> 
> > That's kind of highly counter-intuitive given the name, since you essentially have to hold instead of release ;p.
> 
> That's how we manage to support hold and text selection, quick swipes, and panning.
> Anyway, if this is strange to you, it means you've never been panning - and you were fine with the tricks of handling swipe as pan (because there was no other use for swipe) in the movable things (movable container, imageviewer).

Quite likely, that panning/swipe distinction in KOReader has always felt alien/broken/slow to me ;).

> 
> But with your low interval values, you wouldn't need to wait long before release for it to not be emited as a swipe ?
> 

Strangely enough, I still do (hell, sometimes I even actually have to release for it to trip).

> > Another weird thing with on-release on the H2O: I sometimes get an initial tap before the pan events, meaning if you start in a menu tapzone, you pop said menu up.
> 
> Don't remember it might have happened to me. Nothing new on that front I guess. See your debug/verbose logs for what events you get :)
> (A tap is quick release with a small enough move.)

Initial tap then pans. Definitely without lifting the finger ;).

> 
> > If I pan backwards, then, yeah, it's mostly fast, but if I pan forward, I hardly ever get a fast pan, it's mostly ui.
> 
> Don't remember I got that... I'll test again this evening.
> Even if you browse a few forward pages so they are cached, and then go back to pan forward?

Yep. At best i get a single fast in the mix.

**Comment by NiLuJe** [comment]
I even actually get a succession of `full`s instead of `fast`s :?

(And, err, then I managed to reproduce #7656 :D)

**Comment by poire-z** [comment]
Actually, the current "on release scrolling", not doing anything in onSwipe, and having to wait for the swipe interval delay to pass is what makes it the "the one stop solution to not having conflicts with swipe and multiswipe when you just happen to use scroll mode with PDF fit to content width".
I'm quite used to that :)
So, if you'd really want "on fast release scrolling", it may be another option (handle or not in onSwipe).
Or another checkbox `[ ] after delay only`, that would work will all of the other options (dunno if that makes sense in all). Need more timeval work :/ (raah, it's 4 days old, I was already over it..)

**Comment by NiLuJe** [comment]
I am actually speaking about actual Swipe gestures ;). So, yeah, I wouldn't mind a way to scroll-pan-on-swipe-ges ;).

```
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.600347
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.600355
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.600357
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 1210, time: 1620764260.600358
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 577, time: 1620764260.600360
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.600363
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.600364
05/11/21-22:17:40 DEBUG in tap state...
05/11/21-22:17:40 DEBUG set up hold timer
05/11/21-22:17:40 DEBUG adjusted ges: touch
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.606532
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.606539
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.606541
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 1178, time: 1620764260.606542
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 577, time: 1620764260.606545
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.606547
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.606548
05/11/21-22:17:40 DEBUG in tap state...
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.611299
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.611306
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.611308
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 1141, time: 1620764260.611309
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 577, time: 1620764260.611311
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.611315
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.611317
05/11/21-22:17:40 DEBUG in tap state...
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.622102
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.622109
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.622110
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 1085, time: 1620764260.622112
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 577, time: 1620764260.622114
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.622118
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.622119
05/11/21-22:17:40 DEBUG in tap state...
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.632960
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.632967
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.632969
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 1025, time: 1620764260.632970
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 576, time: 1620764260.632973
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.632976
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.632979
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.643869
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.643877
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.643879
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 956, time: 1620764260.643881
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 573, time: 1620764260.643884
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.643888
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.643890
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.654761
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.654768
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.654769
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 873, time: 1620764260.654771
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 569, time: 1620764260.654773
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.654776
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.654778
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.665729
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.665737
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.665739
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 779, time: 1620764260.665741
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 562, time: 1620764260.665744
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.665747
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.665749
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.676659
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.676666
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.676668
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 691, time: 1620764260.676669
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 553, time: 1620764260.676671
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.676674
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.676675
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.687514
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.687522
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.687523
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 596, time: 1620764260.687525
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 542, time: 1620764260.687527
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.687529
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.687531
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.698429
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.698437
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.698438
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 504, time: 1620764260.698440
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 532, time: 1620764260.698442
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.698446
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.698447
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.709380
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.709388
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.709389
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 421, time: 1620764260.709391
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 519, time: 1620764260.709394
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.709397
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.709399
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.720347
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.720355
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.720356
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 342, time: 1620764260.720358
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 499, time: 1620764260.720360
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.720363
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.720364
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.731182
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.731189
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.731191
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 292, time: 1620764260.731192
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 478, time: 1620764260.731194
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.731196
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.731198
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.742035
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 1, time: 1620764260.742042
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 1, time: 1620764260.742043
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 249, time: 1620764260.742045
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 461, time: 1620764260.742047
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.742049
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.742051
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG adjusted ges: pan north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 1, time: 1620764260.752671
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1620764260.752680
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 50 (ABS_MT_WIDTH_MAJOR), value: 0, time: 1620764260.752681
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 249, time: 1620764260.752683
05/11/21-22:17:40 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 461, time: 1620764260.752686
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1620764260.752689
05/11/21-22:17:40 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1620764260.752691
05/11/21-22:17:40 DEBUG in pan state...
05/11/21-22:17:40 DEBUG swipe north 967.97572283606 detected in slot 1
05/11/21-22:17:40 DEBUG adjusted ges: swipe north
05/11/21-22:17:40 DEBUG AutoSuspend: onInputEvent
05/11/21-22:17:40 DEBUG AutoTurn: onInputEvent
```

**Comment by NiLuJe** [comment]
> Oh hey, I was just trying to fix vertical scrolling on Android - I'm not adopting ReaderPaging and fixing/extending all its demanding horrors :)
> 

:D 

> > So, yeah, I wouldn't mind a way to scroll-pan-on-swipe-ges ;).
> 
> You mean in "on release scrolling", where it does not work ?
> And it's fine in the other modes? (except for small pan_rate on eInk making the last pan events ignored, and your scrolling possibly being smaller than your swipe distance) ?

Yep! (The tiny swipes in the other modes is probably an incentive to teach you how to pan, so I'm fine with that ;p).

**Comment by NiLuJe** [comment]
FWIW, after randomly trying various zoom modes for fun, I *do* get mostly consistent "fast" updates both ways.

I can still reproduce the glitchy "stuck with a series of full", though. Possibly related to the full promotion?

**Comment by NiLuJe** [comment]
I, err, also can't seem to be able to trip the refresh on diagonal swipes anymore?

(And, when "fast" behaves, that means you're stuck with the "fast" rendering, not "ui" or "partial").

**Comment by poire-z** [comment]
Uh, since 2a99b014a27234864b9319c3d42b6684b06dd116, which renamed "readerui.gesture" to "readerui.gestures" (plural), this wasn't doing what it was added for by @Frenzie :/ : 
https://github.com/koreader/koreader/blob/de6f2e84a38c071aee0e24e3836f2c47950cf20d/frontend/apps/reader/modules/readerpaging.lua#L463-L464

@Frenzie : didn't miss it ? :)

So, I tested all the things believeing it was in play and caused no issue :)
I guess it's the solution (pan interval setting, default to 500ms) to the "On release scrolling" different behaviours @NiLuJe and I expect, but it probably shouldn't be used for "classic" and "turbo" scrolling... although it would still keep helping with avoiding issues with swipe/multiswipe interactions - but it makes the scrolling less intuitive from what it was (with the default value of 500ms) - and this setting (pan interval) is in another menu/plugin than this menu...

**Comment by Frenzie** [comment]
> @Frenzie : didn't miss it ? :)

I didn't actually test anything to be clear. I only gave it a quick try.

**Comment by poire-z** [comment]
I mean #4666, the distance_delayed and relative_delayed stuff you added to avoid panning (so, probably mostly in PDF continuous mode) when you're doing swipes or multiswipes.
It must have worked and did what you added it for, between Feb 2019 and Aug 2020.
But it must have stop working since Aug 2020.

**Comment by Frenzie** [comment]
Oh, I have noticed that but I figured I was just exceeding the threshold.

**Comment by Frenzie** [comment]
Oh, I have noticed that but I figured I was just exceeding the threshold.

**Comment by poire-z** [comment]
(rebased, no change)

**Comment by yparitcher** [comment]
> Uh, since [2a99b01](https://github.com/koreader/koreader/commit/2a99b014a27234864b9319c3d42b6684b06dd116), which renamed "readerui.gesture" to "readerui.gestures" (plural), this wasn't doing what it was added for by @Frenzie :/ :
> 
> https://github.com/koreader/koreader/blob/de6f2e84a38c071aee0e24e3836f2c47950cf20d/frontend/apps/reader/modules/readerpaging.lua#L463-L464
> 
Sorry about that :) I did notice this effect but i never knew it had originally worked

**Comment by poire-z** [comment]
> If I pan backwards, then, yeah, it's mostly fast, but if I pan forward, I hardly ever get a fast pan, it's mostly ui.

After much refactoring, I ended up experiencing this like you did :/
Happens because of this:
https://github.com/koreader/koreader/blob/c1892d26192f5561630c0fe114945798f5320eca/frontend/apps/reader/modules/readerpaging.lua#L988-L1006
I added the onUpdateFooter in the first `if` :) ... but this is called in quite a few internal places, and when we go forward, we get:
```
05/14/21-18:01:50 WARN  _gotoPage 4 4
05/14/21-18:01:50 WARN  _gotoPage 4 4
05/14/21-18:01:50 WARN  _gotoPage 4 4
05/14/21-18:01:50 WARN  _gotoPage 4 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
05/14/21-18:01:50 WARN  _gotoPage 5 5
```
but when backward, we get:
```
05/14/21-18:02:20 WARN  _gotoPage 4 5
05/14/21-18:02:20 WARN  _gotoPage 5 4
05/14/21-18:02:20 WARN  _gotoPage 4 5
05/14/21-18:02:20 WARN  _gotoPage 5 4
05/14/21-18:02:20 WARN  _gotoPage 4 5
05/14/21-18:02:21 WARN  _gotoPage 5 4
05/14/21-18:02:21 WARN  _gotoPage 4 5
05/14/21-18:02:21 WARN  _gotoPage 5 4
05/14/21-18:02:21 WARN  _gotoPage 4 5
```
In both cases (either via my explicite updateFooter, or the original Event:new("PageUpdate", ...)), the footer ends up getting its text updated, but somehow with less refresh impact in the later case.
Anyway, ReaderPaging headaches...

This issue can be solved with just
```diff
@@ -1991,9 +1991,9 @@ function ReaderFooter:_updateFooterText(force_repaint, force_recompute)
             -- We've painted it first to ensure self.footer_content.dimen is sane
             UIManager:setDirty(self.view.footer, function()
-                return "ui", self.footer_content.dimen
+                return self.view.currently_scrolling and "fast" or "ui", self.footer_content.dimen
             end)
         else
             UIManager:setDirty(self.view.dialog, function()
-                return "ui", refresh_dim
+                return self.view.currently_scrolling and "fast" or "ui", refresh_dim
             end)
         end
```

**Comment by poire-z** [comment]
(^ rebased, no change)

**Comment by poire-z** [comment]
A bit of refactoring:
- handle pan_rate in this bit of code: process all the pan events (so we don't miss any, including the last ones), but scroll and refresh only according to pan_rate
- add a "activation delay", which would work as the old "pan_delayed_interval" (that I'll remove, as it wasnt used for months) - it adds a bit of resistance when starting a swipe/pan, dunno which value should be the default (0ms, as currently, or 400ms, which is fine for me).
<kbd>image</kbd>

Please play with it again (with PDF and EPUB, with the various scrolling modes, with some activation delay and without), I think I've worked around most of the issues/expectations above (thanks to that activation delay).

(Rewording suggestions welcome for the text depending on how you feel about the usage of this delay.)

**Comment by Frenzie** [comment]
Probably the issue from https://github.com/koreader/koreader/pull/7683 ?
```
./luajit: frontend/ui/geometry.lua:204: attempt to call method 'area' (a nil value)
stack traceback:
	frontend/ui/geometry.lua:204: in function 'notIntersectWith'
	frontend/ui/geometry.lua:221: in function 'intersectWith'
	frontend/ui/widget/configdialog.lua:1455: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
	frontend/ui/uimanager.lua:1142: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1568: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1648: in function 'handleInput'
	frontend/ui/uimanager.lua:1695: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x55679b2167c1
```

**Comment by NiLuJe** [comment]
@Frenzie: Yup!

@poire-z: Very, very, very quick initial test w/ Classic on the H2O: I can still reproduce the "full" streaks. Possibly new is that I think I managed to trip one *during* a scroll, when crossing a page boundary. Subsequent steps in the same scroll were *all* fulls, *and* it continued to affect the subsequent scroll, too, where all steps were full, too.

**Comment by NiLuJe** [comment]
And, yep, you perfectly nailed how I expected on release to behave, :heart: !

**Comment by Frenzie** [comment]
The top speed seems possibly a bit slow to me now? But seems decent to me in any case.

**Comment by poire-z** [comment]
> I can still reproduce the "full" streaks. 

Didn't get any when playing, but greping the emulator output, I see some ui and partial:
```
05/14/21-21:17:01 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:01 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:01 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:02 DEBUG _refresh: Enqueued ui update for region 0 0 300 410
05/14/21-21:17:02 DEBUG _refresh: Enqueued ui update for region 0 0 300 410
05/14/21-21:17:02 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:02 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:02 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:02 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:02 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:03 DEBUG refresh on physical rectangle 0 0 300 410
[...]
05/14/21-21:17:18 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:18 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:18 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:18 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:18 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:18 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:18 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:20 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:20 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:20 DEBUG _refresh: Enqueued partial update for region 0 0 300 410
05/14/21-21:17:20 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:21 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:22 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:22 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:22 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:22 DEBUG refresh on physical rectangle 0 0 300 410
05/14/21-21:17:22 DEBUG _refresh: promote refresh to full
05/14/21-21:17:22 DEBUG _refresh: Enqueued full update for region 0 0 300 410
05/14/21-21:17:22 DEBUG refresh on physical rectangle 0 0 300 410
```
Is it worth chasing them and use the same trick of making them "fast" when currently_scrolling ?

**Comment by poire-z** [comment]
> The top speed seems possibly a bit slow to me now? 

You mean the fastest speed you manage to get?
Might be because we slow down our fingers when about to release, and I no longer ignore the last pans :/
On which device/emulator?

**Comment by poire-z** [comment]
> I can still reproduce the "full" streaks.

Earlier, when testing with paper.pdf, I got quite a few "full" refreshes. _You_ were responsible for them :):
https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/apps/reader/modules/readertoc.lua#L121-L127

Should these be avoided when scrolling ? (Bit bothering having to update unrelated places after this I expected to not intrude elsewhere :/)

**Comment by Frenzie** [comment]
> On which device/emulator?

On emulator. Real Android/iOS/Sailfish and the emulator feel identical to doing it on touchpad or mouse to me.

**Comment by poire-z** [comment]
> Bit bothering having to update unrelated places after this I expected to not intrude elsewhere :/

Should this `self.view.currently_scrolling = true` better be `UIManager.currently_scrolling`, so that UIManager itself every refresh gets to become "fast" ?

**Comment by Frenzie** [comment]
> Should these be avoided when scrolling ? (Bit bothering having to update unrelated places after this I expected to not intrude elsewhere :/)

Not sure how important it is, but in principle yes, you just want the fast A2 update mode until you're done.

**Comment by NiLuJe** [comment]
> > I can still reproduce the "full" streaks.
> 
> Earlier, when testing with paper.pdf, I got quite a few "full" refreshes. _You_ were responsible for them :):
> 
> https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/apps/reader/modules/readertoc.lua#L121-L127
> 
> Should these be avoided when scrolling ? (Bit bothering having to update unrelated places after this I expected to not intrude elsewhere :/)

Yeah, I had the same lightbulb moment while brushing my teeth ;p.

At a quick glance, I don't really see a better solution than the same ! while scrolling nerf than ReaderFooter, no :/.

**Comment by NiLuJe** [comment]
Okay, just read the following messages ;p. The UIManager approach to ban some wf modes while scrolling sounds sensible, let me take a look :).

**Comment by NiLuJe** [comment]
And because I'd forgotten to write that down:

> Also potentially completely unrelated: if I switch to free-zoom (100%) in continuous mode, I can't pan horizontally, only vertically.
> 
> EDIT: Possibly related to the fancy direction stuff, because continuous _also_ breaks the pagination direction in this case.

Yeah, completely orthogonal to this PR? I can reproduce it on master ;).

**Comment by Frenzie** [comment]
That's more or less part of https://github.com/koreader/koreader/issues/5524.

**Comment by NiLuJe** [comment]
@poire-z: On UIManager's side, you'd only need to deal with it around here:

https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/ui/uimanager.lua#L1296-L1335

(Probably right after. You could possibly deal with the partial counter reset around there, too).

**Comment by Frenzie** [comment]
Side note, it seems that page flipping mode has been broken. It's one of the widgets that always allowed enabled double tapping on just itself, but now it only seems to work if you enable it globally.

**Comment by NiLuJe** [comment]
@Frenzie: You'll have to explain and detail the expected vs. current behavior, because I could never understand that thing ;).

**Comment by Frenzie** [comment]
1. You're in page flipping mode.


2. Double tap on a text column to zoom to i. This is somewhat error-prone and there is no way to free zoom in case auto-detection doesn't work out.


Incidentally the inertial scrolling seems to behaving quite oddly in this zoomed mode.

But double tapping now says something about restarting and it doesn't work at will in page flipping mode anymore as it always has.

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/blob/a9977b3453d784cfb75dd74cacbe7d6801752131/frontend/apps/reader/modules/readerzooming.lua#L381-L390

**Comment by Frenzie** [comment]
*whistles*

I guess it may have been me.

https://github.com/koreader/koreader/pull/6322

**Comment by Frenzie** [comment]
Don't get me wrong, as far as I'm concerned this page flipping thing is… not super great. It just happens to have some features.

**Comment by poire-z** [comment]
> or before and shortcutting those two branches. You could possibly deal with the partial counter reset in there, too).

Or just before and not caring too much about shortening (and indenting and git blaming myself :)?
(It's just 2 tests, and a bit more for the avoid_flashing_ui users  like me.)
```diff
@@ -1293,6 +1294,11 @@ function UIManager:_refresh(mode, region, dither)
             return
         end
     end
+    -- Downgrade all refreshes to "fast" if ReaderPaging or ReaderScrolling
+    -- have set this flag when scrolling
+    if self.currently_scrolling then
+        mode = "fast"
+    end
     if not region and mode == "full" then
         self.refresh_count = 0 -- reset counter on explicit full refresh
     end
```
Seems to work.

**Comment by poire-z** [comment]
(Btw, that mobiread user who didn't see "Gesture manager", he probably had the Gestures plugin disabled :/ A bit cumbersome that we exported some core stuff like gesture interval in a plugin :\)

**Comment by Frenzie** [comment]
I completely forgot that was a plugin now.

File: frontend/apps/reader/modules/readerpaging.lua [hunk 2]
```diff
@@ -482,12 +587,40 @@ function ReaderPaging:onPanRelease(_, ges)
...
 
+function ReaderPaging:onHandledAsSwipe()
+    if self._pan_started then
+        -- Restore original position as this pan we've started handling
+        -- has ended up being a multiswipe or handled as a swipe to open
+        -- top or bottom menus
+        if self._pan_has_scrolled then
+            self.view.page_states = self._pan_page_states_to_restore
+            self:_gotoPage(self.view.page_states[#self.view.page_states].page, "scrolling")
+            UIManager:setDirty(self.view.dialog, "fast")
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerpaging.lua:615]: I needed a refresh here to force the page to be repainted - after cancelling the scroll when it happens to be a multiswipe - which will probably show something (which might be a full screen History, or a little Skim widget).
Made it use the cheapest "fast", that will probably get promoted to something else depending on somewidgets else.
Should it be something else like "ui" ?

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerpaging.lua:615]: Assuming it only trips at the end of a gesture, `ui` makes sense, yes. (And it also appears to be the lowest priority after fast).

**Comment by NiLuJe** [comment]
@Frenzie: Err, I can't quit esee how that could have ever worked (at least in the past 4 years, i.e., since #2800), because GestureDetector will *never* emit a `double_tap` gesture without Double Taps being enabled.

I suppose PageFlipping mode would need to fudge that setting, like it already fudges some things? (IIRC, hinting and stuff).

**Comment by Frenzie** [comment]
> I suppose PageFlipping mode would need to fudge that setting, like it already fudges some things? (IIRC, hinting and stuff).

It's not impossible that it hasn't worked in years. But yes, that's exactly what it does, but it doesn't seem to be there anymore.

https://github.com/koreader/koreader/commit/5983050d797bd2c08b9afc365e7c4e6a770498b6#diff-e0f3d649647ba52ee73021c18181dee4c3b010622601c8e1baaf31ee73ddb7f1

It's still a per-widget thing in any case:
https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/ui/uimanager.lua#L437-L442

**Comment by poire-z** [comment]
Any feedback on what should be the default value for this activation delay?
Can't really be decided (and stored) depending on multiswipes enabled, as on an initial installation, multiswipes aren't yet enabled.
If 0, smooth and normal scrolling, but little hiccups (scroll+restore with swipes to open menu and multiswipes).
if 500ms, possibly some frustration with scrolling getting delayed.
if in between, both frustrations :)

Any rewording suggestions?

**Comment by poire-z** [comment]
Can I remove everything related to pan_delayed_interval - as it wasn't used for some time, and is now replaced by this activation delay for this context of scrolling.
https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/plugins/gestures.koplugin/main.lua#L622-L627

File: frontend/apps/reader/modules/readerscrolling.lua [hunk 3]
```diff
@@ -0,0 +1,402 @@
...
+                text_func = function()
+                    return T(_("Activation delay: %1 ms"), self.scroll_activation_delay)
+                end,
+                keep_menu_open = true,
+                callback = function(touchmenu_instance)
+                    local SpinWidget = require("ui/widget/spinwidget")
+                    local widget = SpinWidget:new{
+                        title_text = _("Scroll activation delay"),
+                        info_text = T(_([[
+To avoid scrolling happening when swipes or multiswipes are intended, a delay before it starts can be set.
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerscrolling.lua:145]:
```suggestion
A delay can be used to avoid scrolling when swipes or multiswipes are intended.
```

**Comment by Frenzie** [comment]
That seems fine.

**Comment by NiLuJe** [comment]
> > I suppose PageFlipping mode would need to fudge that setting, like it already fudges some things? (IIRC, hinting and stuff).
> 
> It's not impossible that it hasn't worked in years, but I'm fairly sure it still worked in 2019. But yes, that's exactly what it does, but it doesn't seem to be there anymore. `Input.disable_double_tap = false` when you enter page flipping mode, `Input.disable_double_tap = true` when you exit.
> 
> [5983050#diff-e0f3d649647ba52ee73021c18181dee4c3b010622601c8e1baaf31ee73ddb7f1](https://github.com/koreader/koreader/commit/5983050d797bd2c08b9afc365e7c4e6a770498b6#diff-e0f3d649647ba52ee73021c18181dee4c3b010622601c8e1baaf31ee73ddb7f1)
> 
> It's still a per-widget thing in any case:
> 
> https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/ui/uimanager.lua#L437-L442

Right, I'd missed the fact that the menu checkbox was a different thing that the UIManager flag. Turns out the checkbox basically only disables GestureManager's double_tap handlers.

**Comment by NiLuJe** [comment]
@Frenzie: Okay, so, yeah, reverting that chunk fixes it: https://github.com/koreader/koreader/commit/86db43a0527e94f1ebe2a124dae92f8fd3f70e6e#diff-e0f3d649647ba52ee73021c18181dee4c3b010622601c8e1baaf31ee73ddb7f1

(Provided you don't have something else bound to that same gesture that also opens a widget (i.e., skim), because opening a widget resets the double tap state to disabled).

**Comment by NiLuJe** [comment]
> Any feedback on what should be the default value for this activation delay?
> Can't really be decided (and stored) depending on multiswipes enabled, as on an initial installation, multiswipes aren't yet enabled.
> If 0, smooth and normal scrolling, but little hiccups (scroll+restore with swipes to open menu and multiswipes).
> if 500ms, possibly some frustration with scrolling getting delayed.
> if in between, both frustrations :)

I don't use multiswipes, so I can't really give you any advice there ;p. (Other than I obviously prefer 0 given my setup, but I have no issues about the default being different if it makes more sense given other defaults).

> 
> Any rewording suggestions?

No, I think everything looks fine?

**Comment by Frenzie** [comment]
> @Frenzie: Okay, so, yeah, reverting that chunk fixes it: 86db43a#diff-e0f3d649647ba52ee73021c18181dee4c3b010622601c8e1baaf31ee73ddb7f1

Right, I'll put it in a PR sometime if I remember. :-P I'm not entirely sure why I removed that since I was aware of it; probably more or less by accident. Or perhaps I was planning to properly dive into that whole free zooming thing in order to get rid of page flipping mode once and for all.

**Comment by Frenzie** [comment]
> I don't use multiswipes, so I can't really give you any advice there ;p. (Other than I obviously prefer 0 given my setup, but I have no issues about the default being different if it makes more sense given other defaults).

I'm pretty sure we discussed it very much in depth with a lot of practical experimentation at the time I wrote multiswipes (or at least we as in @poire-z and I). So I'd say that default or something slightly lower is good, higher less so.

**Comment by Frenzie** [comment]
I see it was as high as 500? Personally I think I lean more toward 200 or 300.

**Comment by NiLuJe** [comment]
FWIW, I have most gesture timers set to half the defaults on my actual production devices, so 250ms sounds sensible if you opt for > 0 ;).

**Comment by poire-z** [comment]
When playing on my Kobo, 200/300ms was at the boundary of my multi-swipes durations :) So, I got some scrolling half of the time, which is more suprising than anything.

Either 0 - and swipers will be bothered immediately and will go change the delay duration.
Or 400ms (the min for me and my multiswipes) or 500ms to avoid conflicts for most users - and people will get the pause, which will bother scrollers :) and they'll go change the delay duration to 0.

Of course, all this will only bother PDF readers (in fit to width probably) and the rare continuous EPUBs readers.

It feels 0ms is still the less worse solution, as we don't have to decide between 400/500/600 ms :)

**Comment by Frenzie** [comment]
> Or 400ms (the min for me and my multiswipes) or 500ms to avoid conflicts for most users 

Presumably that's how we ended up with 500 in the past.

**Comment by Frenzie** [comment]
> It feels 0ms is still the less worse solution, as we don't have to decide between 400/500/600 ms :)

Of course I came up with it in the first place, but using it only when multiswipes are enabled seemed pretty decent to me. ;-)

**Comment by poire-z** [comment]
> using it only when multiswipes are enabled seemed pretty decent to me. ;-)

I wrote previously: _Can't really be decided (and stored) depending on multiswipes enabled, as on an initial installation, multiswipes aren't yet enabled._
The default for activate_menu is swipe_tap.
So, new users get swipe for menu (until they disable it).
And most will probably have made a multiswipe gesture at some point and enabled them.
(And others who would have disabled all these to have a low-feature KOReader are probably not using scroll mode.)
I don't mind going with a default of 500ms, if you feel it's safer.

Do you feel I should pick up a different default and current value (until the user explicitely sets a value via the menu), depending on `self.ui.gesture.multiswipes_enabled and activate_menu ~= "tap"` ? 500 if true, 0 if not?

**Comment by Frenzie** [comment]
> I don't mind going with a default of 500ms, if you feel it's safer.

Hm? You were the one arguing for higher values? :-P 400 is fine by me.

**Comment by poire-z** [comment]
You wrote above: _Presumably that's how we ended up with 500 in the past._

400 or 500 wasn't what I was asking, rather 0 vs 500. Please re-read my previous posts :)

**Comment by poire-z** [comment]
> Do you feel I should pick up a different default and current value (until the user explicitely sets a value via the menu), depending on self.ui.gesture.multiswipes_enabled and activate_menu ~= "tap" ? 500 if true, 0 if not?

That's what we had between Feb 2019 and Aug 2020.

But isn't it clumsy and bad UX to have a setting's default value and feature behaviour depending on a few other remote  settings ? For the user himself, and for us trying to make sense of bug reports?
Isn't it better to have a static default value that would only bother the smallest of the two crowds?

**Comment by Frenzie** [comment]
I don't agree with that because the settings are coupled, not separate.
Setting them independently is more for tweaking. But 400 by default either
way should still be fine.

**Comment by poire-z** [comment]
OK, 0 or 500ms as default depending on enabled swipe things.

**Comment by poire-z** [comment]
(^ Just a rebase to master for re-timestamping the commits to now.)

**Comment by NiLuJe** [comment]
`page_states` used to (mistakenly) hang around across Document/ReaderUI instances.

I can't quite recall what actually populates it, though.

**Comment by poire-z** [comment]
~~I think it stores the scroll offset of every page, so when you jump to a page you visited, you find it "aligned/scrolled" as it was. I hate it.~~
No, it's `ReaderPaging.page_positions` that I hate, and that I force it to be empty in my own patch (it's very old, so crappy coding :):
```diff
 function ReaderPaging:setPagePosition(page, pos)
     logger.dbg("set page position", pos)
+    -- only remember one page position (the latest one,
+    -- used when re-opening a book)
+    for k,v in pairs(self.page_positions) do self.page_positions[k]=nil end
     self.page_positions[page] = pos
     self.ui:handleEvent(Event:new("PagePositionUpdated"))
```

But ReaderView.page_states seems to hold that kind of offsets to, + many other kopt things.
