### PR TITLE
NetworkManager: Enable "before wifi action" support on every hasWifiToggle platform

### LINKED ISSUE #10678: "Error connecting to the network" when opening the file browser - KOSync trying to sync with Wi-Fi disabled?
* KOReader version: v2023.06.1
* Device: KindleBasic3 (10th gen 2019)

#### Issue

After upgrading from v2022.05.1 to v2023.06.1, I get the alert: "Error connecting to the network" when I open the file browser from a book (after 30 seconds). Behind the alert, another alert is shown with the message, "Do you want to turn on Wi-Fi?".

I always used the device with Wi-Fi turned off (and airplane mode on the Kindle system), but only after upgrading I started to see this behavior.

From what I could see from the logs, it seems the culprit is the kosync plugin (or "Progress Sync"), and disabling it seems to fix the issue.

If that's the case, I'd expect the plugin not to try to do its thing if the Wi-Fi is disabled.

#### Steps to reproduce

1. Go to the History
2. Open a book
3. Go to the file browser 

##### `crash.log` 

<details>
  <summary>crash.log</summary>

```
07/11/23-14:09:41 INFO  opening file /mnt/us/home/books/fiction/alexandre-dumas_the-count-of-monte-cristo_chapman-and-hall.epub 
CRE: font NotoSerifKR regular: updated weight from 500 to 400
CRE: font NotoSerifKR bold: updated weight from 900 to 700
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
CRE: font NotoSansKR bold: updated weight from 900 to 700
07/11/23-14:09:42 DEBUG CreDocument: using cre call cache 
07/11/23-14:09:42 INFO  Inhibiting user input 
07/11/23-14:09:42 DEBUG DocSettings: data is read from /mnt/us/home/books/fiction/alexandre-dumas_the-count-of-monte-cristo_chapman-and-hall.sdr/metadata.epub.lua 
07/11/23-14:09:42 DEBUG ImageWidget: _render'ing resources/icons/mdlight/book.opened.svg 32 32 
07/11/23-14:09:42 DEBUG renderSVG resources/icons/mdlight/book.opened.svg 0.66666666666667 48 48 > 32 32 0 0 
07/11/23-14:09:42 DEBUG cache image|resources/icons/mdlight/book.opened.svg|32|32false 
07/11/23-14:09:42 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:42 DEBUG CreDocument: applied cr3.ini default settings. 
07/11/23-14:09:42 DEBUG CreDocument: set fallback font faces: Noto Sans CJK SC|Noto Naskh Arabic|Noto Sans Devanagari UI|Noto Sans Bengali UI|FreeSans|FreeSerif|Noto Serif|Noto Sans 
07/11/23-14:09:42 DEBUG CreDocument: set adjusted fallback font sizes true 
07/11/23-14:09:42 DEBUG CreDocument: set monospace font scaling 100 
07/11/23-14:09:42 DEBUG RD loaded plugin SSH at plugins/SSH.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin archiveviewer at plugins/archiveviewer.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin autodim at plugins/autodim.koplugin 
07/11/23-14:09:42 DEBUG AutoSuspend: init 
07/11/23-14:09:42 DEBUG AutoSuspend: start suspend/shutdown timer at 233357.415461 
07/11/23-14:09:42 DEBUG AutoSuspend: scheduling next suspend check in 900 
07/11/23-14:09:42 DEBUG AutoSuspend: start t1 timeout timer at 233357.415461 
07/11/23-14:09:42 DEBUG AutoSuspend: scheduling next t1 timeout check in 300 
07/11/23-14:09:42 DEBUG RD loaded plugin autosuspend at plugins/autosuspend.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin autoturn at plugins/autoturn.koplugin 
07/11/23-14:09:42 DEBUG AutoWarmth: scheduleMidnightUpdate 
07/11/23-14:09:42 DEBUG RD loaded plugin autowarmth at plugins/autowarmth.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin batterystat at plugins/batterystat.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin bookshortcuts at plugins/bookshortcuts.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin calibre at plugins/calibre.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin exporter at plugins/exporter.koplugin 
07/11/23-14:09:42 DEBUG ExternalKeyboard: role device 
07/11/23-14:09:42 DEBUG RD loaded plugin externalkeyboard at plugins/externalkeyboard.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin gestures at plugins/gestures.koplugin 
07/11/23-14:09:42 DEBUG language support: overriding existing japanese plugin 
07/11/23-14:09:42 DEBUG RD loaded plugin japanese at plugins/japanese.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin keepalive at plugins/keepalive.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin kosync at plugins/kosync.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin opds at plugins/opds.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin profiles at plugins/profiles.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin readtimer at plugins/readtimer.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin statistics at plugins/statistics.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin systemstat at plugins/systemstat.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin terminal at plugins/terminal.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin texteditor at plugins/texteditor.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin timesync at plugins/timesync.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin vocabbuilder at plugins/vocabbuilder.koplugin 
07/11/23-14:09:42 DEBUG RD loaded plugin wallabag at plugins/wallabag.koplugin 
07/11/23-14:09:42 DEBUG CreDocument: set view mode page 
07/11/23-14:09:42 DEBUG CreDocument: set status line property 1 
07/11/23-14:09:42 DEBUG made tweak css:
*[type~="note"],
*[type~="endnote"],
*[type~="footnote"],
*[type~="rearnote"],
*[role~="doc-note"],
*[role~="doc-endnote"],
*[role~="doc-footnote"],
*[role~="doc-rearnote"]
{
    -cr-only-if: -fb2-document;
        -cr-hint: footnote-inpage;
        margin: 0 !important;
        font-size: 0.8rem !important;
}
body[name="notes"] section {
    -cr-only-if: fb2-document;
        -cr-hint: footnote-inpage;
        margin: 0 !important;
}
body[name="notes"] > section {
    -cr-only-if: fb2-document;
        font-size: 0.75rem;
}
body[name="notes"] > title {
    -cr-only-if: fb2-document;
        margin-bottom: 0;
        padding-bottom: 0.5em;
}[END] 
07/11/23-14:09:42 DEBUG CreDocument: set style sheet: ./data/epub.css and appended content (649 bytes) 
07/11/23-14:09:42 DEBUG CreDocument: set embedded style sheet 1 
07/11/23-14:09:42 DEBUG CreDocument: set block rendering flags 0x7fffffff 
07/11/23-14:09:42 DEBUG CreDocument: set render dpi 96 
07/11/23-14:09:42 DEBUG CreDocument: set page margins 30 15 30 30 
07/11/23-14:09:42 DEBUG CreDocument: set txt preformatted 1 
07/11/23-14:09:42 DEBUG CreDocument: set smooth scaling false 
07/11/23-14:09:42 DEBUG CreDocument: set nightmode images true 
07/11/23-14:09:42 DEBUG CreDocument: set font face Noto Serif 
07/11/23-14:09:42 DEBUG CreDocument: set header font Noto Sans 
07/11/23-14:09:42 DEBUG CreDocument: set font size 22 
07/11/23-14:09:42 DEBUG CreDocument: set font base weight 0 = 400 
07/11/23-14:09:42 DEBUG CreDocument: set font hinting mode 2 
07/11/23-14:09:42 DEBUG CreDocument: set font kerning mode 3 
07/11/23-14:09:42 DEBUG CreDocument: set space width scale 95 
07/11/23-14:09:42 DEBUG CreDocument: set space condensing 75 
07/11/23-14:09:42 DEBUG CreDocument: set word expansion 0 
07/11/23-14:09:42 DEBUG CreDocument: set cjk width scaling 100 
07/11/23-14:09:42 DEBUG CreDocument: set interline space 100 
07/11/23-14:09:42 DEBUG CreDocument: set gamma index 36 
07/11/23-14:09:42 DEBUG CreDocument: set font-family font faces: ||||||FreeSerif|| 
07/11/23-14:09:42 DEBUG CreDocument: set textlang embedded langs true 
07/11/23-14:09:42 DEBUG CreDocument: set textlang hyphenation enabled true 
07/11/23-14:09:42 DEBUG CreDocument: set hyphenation trust soft hyphens 0 
07/11/23-14:09:42 DEBUG CreDocument: set textlang hyphenation soft hyphens only false 
07/11/23-14:09:42 DEBUG CreDocument: set textlang hyphenation force algorithmic false 
07/11/23-14:09:42 DEBUG CreDocument: set hyphenation left hyphen min 0 
07/11/23-14:09:42 DEBUG CreDocument: set hyphenation right hyphen min 0 
07/11/23-14:09:42 DEBUG CreDocument: set floating punctuation 0 
07/11/23-14:09:42 DEBUG Typography lang: using en-US from doc settings 
07/11/23-14:09:42 DEBUG CreDocument: set textlang main lang en-US 
07/11/23-14:09:42 DEBUG UserHyph: reset user hyphenation dict 
07/11/23-14:09:42 DEBUG CreDocument: requesting DOM version: 20210904 
07/11/23-14:09:42 DEBUG CreDocument: set visible page count 1 
07/11/23-14:09:42 DEBUG CreDocument: loading document... 
07/11/23-14:09:42 DEBUG CreDocument: loading done. 
07/11/23-14:09:42 DEBUG   loading took 0.184 seconds 
07/11/23-14:09:42 DEBUG Typography lang: not overriding en-US with doc language: en-US 
07/11/23-14:09:42 DEBUG CreDocument: rendering document... 
07/11/23-14:09:42 DEBUG CreDocument: rendering done. 
07/11/23-14:09:42 DEBUG   rendering took 0.036 seconds 
07/11/23-14:09:42 DEBUG validateAndFixToc(): quick scan 
07/11/23-14:09:42 DEBUG validateAndFixToc(): TOC is fine 
07/11/23-14:09:42 DEBUG ReaderFooter: scheduled autoRefreshFooter 
07/11/23-14:09:42 DEBUG CreDocument: goto page 1444 flow 0 
07/11/23-14:09:42 DEBUG _refresh: Enqueued partial update for region 0 0 600 800 dithering: false 
07/11/23-14:09:42 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil 
07/11/23-14:09:42 DEBUG ReaderStatistics: No timestamp for previous page 0 
07/11/23-14:09:42 DEBUG CreDocument: goto xpointer /body/DocFragment[68]/body/section/hgroup/h2/text().0 
07/11/23-14:09:42 DEBUG _refresh: Enqueued partial update for region 0 0 600 800 dithering: false 
07/11/23-14:09:42 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil 
07/11/23-14:09:42 DEBUG CreDocument: set bookmarks highlight and internal history false 
07/11/23-14:09:42 DEBUG _refresh: Enqueued partial update for region 0 0 600 800 dithering: false 
07/11/23-14:09:42 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil 
07/11/23-14:09:42 DEBUG Spinning up new ReaderUI instance table: 0x746e4608 
07/11/23-14:09:42 DEBUG show widget: ReaderUI 
07/11/23-14:09:42 DEBUG update_mode: Update refresh mode partial to full 
07/11/23-14:09:42 DEBUG _refresh: Enqueued full update for region 0 0 600 800 dithering: false 
07/11/23-14:09:42 DEBUG setDirty full from widget ReaderUI w/ NO region; dithering: nil 
07/11/23-14:09:42 DEBUG painting widget: ReaderUI 
07/11/23-14:09:42 DEBUG readerview painting "600x800+0+0" to 0 0 
07/11/23-14:09:42 DEBUG CreDocument: goto page 1444 flow 0 
07/11/23-14:09:42 DEBUG _refresh: Enqueued full update for region 0 0 600 800 dithering: false 
07/11/23-14:09:42 DEBUG triggering refresh {
  mode = "full",
  region = "600x800+0+0"
} --[[table: 0x72ab0358]] 
07/11/23-14:09:42 DEBUG refresh: full 0 0 600 800 nil 
07/11/23-14:09:42 DEBUG refresh: wait for submission of (previous) marker 15 
07/11/23-14:09:42 DEBUG refresh: wait for completion of (previous) marker 15 
07/11/23-14:09:42 DEBUG mxc_update: 600x800 region @ (0, 0) with marker 16 (WFM: 2 & UPD: 1) 
07/11/23-14:09:42 DEBUG refresh: wait for completion of marker 16 
07/11/23-14:09:43 INFO  Restoring user input handling 
07/11/23-14:09:43 DEBUG key event => code: 330 (BTN_TOUCH), value: 1, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 1, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 173, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 6, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 14, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.787556 
07/11/23-14:09:43 DEBUG GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG set up hold timer 
07/11/23-14:09:43 DEBUG AutoSuspend: onInputEvent 
07/11/23-14:09:43 DEBUG AutoTurn: onInputEvent 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 173, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 7, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 14, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.820873 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 173, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 11, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 14, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.837359 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 173, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 12, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 14, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.854021 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 173, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 13, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 14, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.870683 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 176, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 25, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 20, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.904115 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 176, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 31, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 23, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.920690 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 178, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 62, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 24, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.937280 
07/11/23-14:09:43 DEBUG slot 0 in tap state... 
07/11/23-14:09:43 DEBUG slot 0 in pan state... 
07/11/23-14:09:43 DEBUG AutoSuspend: onInputEvent 
07/11/23-14:09:43 DEBUG AutoTurn: onInputEvent 
07/11/23-14:09:43 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.navigation.svg 40 40 
07/11/23-14:09:43 DEBUG renderSVG resources/icons/mdlight/appbar.navigation.svg 0.83333333333333 48 48 > 40 40 0 0 
07/11/23-14:09:43 DEBUG cache image|resources/icons/mdlight/appbar.navigation.svg|40|40false 
07/11/23-14:09:43 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:43 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.typeset.svg 40 40 
07/11/23-14:09:43 DEBUG renderSVG resources/icons/mdlight/appbar.typeset.svg 0.83333333333333 48 48 > 40 40 0 0 
07/11/23-14:09:44 DEBUG cache image|resources/icons/mdlight/appbar.typeset.svg|40|40false 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.settings.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.tools.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.search.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.filebrowser.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/appbar.menu.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.up.svg 40 40 
07/11/23-14:09:44 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:44 DEBUG FocusManager: Move focus position to: 1 , 1 
07/11/23-14:09:44 DEBUG setDirty via a func from widget table: 0x74245e40 
07/11/23-14:09:44 DEBUG show widget: table: 0x74245e40 
07/11/23-14:09:44 DEBUG setDirty nil from widget table: 0x74245e40 w/ NO region; dithering: nil 
07/11/23-14:09:44 DEBUG painting widget: table: 0x74245e40 
07/11/23-14:09:44 DEBUG blitFrom 16 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 90 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 164 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 238 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 312 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 386 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 544 7 0 0 40 40 
07/11/23-14:09:44 DEBUG blitFrom 28 558 0 0 40 40 
07/11/23-14:09:44 DEBUG _refresh: Enqueued flashui update for region 0 0 600 606 dithering: false 
07/11/23-14:09:44 DEBUG triggering refresh {
  mode = "flashui",
  region = "600x606+0+0"
} --[[table: 0x759370a8]] 
07/11/23-14:09:44 DEBUG refresh: ui-mode w/ flash 0 0 600 606 nil 
07/11/23-14:09:44 DEBUG mxc_update: 600x606 region @ (0, 0) with marker 17 (WFM: 2 & UPD: 1) 
07/11/23-14:09:44 DEBUG refresh: wait for completion of marker 17 
07/11/23-14:09:44 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 180, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 103, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 24, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.953984 
07/11/23-14:09:44 DEBUG slot 0 in pan state... 
07/11/23-14:09:44 DEBUG key event => code: 330 (BTN_TOUCH), value: 0, time: 1689084583.982559 
07/11/23-14:09:44 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 0, time: 1689084583.982559 
07/11/23-14:09:44 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084583.982559 
07/11/23-14:09:44 DEBUG slot 0 in pan state... 
07/11/23-14:09:44 DEBUG Contact:handleSwipe: swipe south 97.252249331314 detected 
07/11/23-14:09:44 DEBUG AutoSuspend: onInputEvent 
07/11/23-14:09:44 DEBUG AutoTurn: onInputEvent 
07/11/23-14:09:45 DEBUG key event => code: 330 (BTN_TOUCH), value: 1, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 1, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 421, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 24, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 27, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084585.431410 
07/11/23-14:09:45 DEBUG slot 0 in tap state... 
07/11/23-14:09:45 DEBUG set up hold timer 
07/11/23-14:09:45 DEBUG AutoSuspend: onInputEvent 
07/11/23-14:09:45 DEBUG AutoTurn: onInputEvent 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 417, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 24, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 23, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084585.514763 
07/11/23-14:09:45 DEBUG slot 0 in tap state... 
07/11/23-14:09:45 DEBUG key event => code: 330 (BTN_TOUCH), value: 0, time: 1689084585.543265 
07/11/23-14:09:45 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 0, time: 1689084585.543265 
07/11/23-14:09:45 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1689084585.543265 
07/11/23-14:09:45 DEBUG slot 0 in tap state... 
07/11/23-14:09:45 DEBUG Contact:handleDoubleTap: single tap detected @ 417 24 
07/11/23-14:09:45 DEBUG AutoSuspend: onInputEvent 
07/11/23-14:09:45 DEBUG AutoTurn: onInputEvent 
07/11/23-14:09:45 DEBUG Explicit widgetInvert: table: 0x75921be0 @ 386 7 
07/11/23-14:09:45 DEBUG _refresh: Enqueued fast update for region 370 7 72 40 dithering: false 
07/11/23-14:09:45 DEBUG setDirty fast from widget nil w/ region 370 7 72 40 dithering: nil 
07/11/23-14:09:45 DEBUG triggering refresh {
  mode = "fast",
  region = "72x40+370+7"
} --[[table: 0x7412f778]] 
07/11/23-14:09:45 DEBUG refresh: fast 370 7 72 40 nil 
07/11/23-14:09:45 DEBUG mxc_update: 72x40 region @ (370, 7) with marker 18 (WFM: 1 & UPD: 0) 
07/11/23-14:09:45 DEBUG Explicit widgetInvert: table: 0x75921be0 @ 386 7 
07/11/23-14:09:45 DEBUG close widget: table: 0x74245e40 
07/11/23-14:09:45 DEBUG _refresh: Enqueued flashui update for region 0 0 600 800 dithering: false 
07/11/23-14:09:45 DEBUG setDirty flashui from widget nil w/ NO region; dithering: nil 
07/11/23-14:09:45 DEBUG Lower widget ReaderUI covers the full screen 
07/11/23-14:09:45 DEBUG setDirty nil from widget ReaderUI w/ NO region; dithering: nil 
07/11/23-14:09:45 DEBUG closing reader 
07/11/23-14:09:45 DEBUG closing document 
07/11/23-14:09:45 DEBUG ReaderFooter: unschedule autoRefreshFooter 
07/11/23-14:09:45 DEBUG ReaderCoptListener.headerRefresh unscheduled 
07/11/23-14:09:45 DEBUG cre cache used: ./cache/cr3cache/alexandre-du-nd-hall.epub.138c1ab0.1.cr3 
07/11/23-14:09:45 DEBUG AutoTurn: onCloseDocument 
07/11/23-14:09:45 DEBUG KOSync: onCloseDocument 
07/11/23-14:09:45 DEBUG ImageWidget: _render'ing resources/icons/mdlight/notice-question.svg 40 40 
07/11/23-14:09:45 DEBUG renderSVG resources/icons/mdlight/notice-question.svg 0.83333333333333 48 48 > 40 40 0 0 
07/11/23-14:09:45 DEBUG cache image|resources/icons/mdlight/notice-question.svg|40|40true 
07/11/23-14:09:45 DEBUG ImageWidget: initial offsets 0 0 
07/11/23-14:09:45 DEBUG show widget: table: 0x72989950 
07/11/23-14:09:45 DEBUG setDirty nil from widget table: 0x72989950 w/ NO region; dithering: nil 
07/11/23-14:09:45 DEBUG setDirty via a func from widget table: 0x72989950 
07/11/23-14:10:16 INFO  Failed to connect to Wi-Fi after 30s, giving up! 
```
</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
It used to be limited to `hasWifiManager` platforms for some reason (spoiler: that reason was probably I couldn't be arsed to test it on Kindle, and/or it would have been clunky and messy before @yparitcher's cleanup of the network status checks).

Anyway, it's fairly trivial to do now, and, as #10605 showed, we kinda need it, as I was stuck in lala-land assuming everybody had it already, and KOSync is a broken mess without it ^^. (Plus, it really has no technical ties to any kind of NetworkMgr backend).

This involves some minor NetworkMgr refactors, and a few fixes along the way.

(Fix #10678)

To recap:

* Enable before_wifi_action & after_wifi_action on hasWifiToggle platforms (which is basically all of 'em except naked SDL).
* Decouple restoreWifiAsync from hasWifiManger, because we can do that on other platforms (namely, Kindle. Probably PB, too, but WiFi is already a mess there, and I can't test it).
* Implement restoreWifiAsync on Kindle.
* Properly flag rM as hasWifiManager & hasFastWifiStatusQuery, because it is actually both of those (it uses our wpa_supplicant backend).
* Update the KOSync checks to take these changes into account, to properly disable auto_sync if necessary.
* Really made the Network* event signaling consistent. For realz this time.
* In an effort to make the whole beforeWifiAction framework somewhat usable there, we now assume connectivity is always available on !hasWifiToggle platforms...

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Lightly tested (on a 5.9.7 PẄ2), so if you have time to spare, feel free to give it a spin, @hius07 ;).

**Comment by NiLuJe** [comment]
As expected, the network activity check is *hilarious* on Kindle, because tmd is losing its damn mind in the background xD.

```
07/10/23-03:19:43 DEBUG NetworkListener: Significant network activity (delta: 19364 > threshold: 12 [ then: 1615 vs. now: 20979 ]) -> keeping Wi-Fi enabled
```

Ya don't say ;o).

File: frontend/ui/network/manager.lua [hunk 1]
```diff
@@ -624,7 +634,8 @@ end
 function NetworkMgr:getPowersaveMenuTable()
     return {
         text = _("Disable Wi-Fi connection when inactive"),
-        help_text = _([[This will automatically turn Wi-Fi off after a generous period of network inactivity, without disrupting workflows that require a network connection, so you can just keep reading without worrying about battery drain.]]),
+        help_text = Device:isKindle() and _([[This is unlikely to function properly on a stock Kindle, given how chatty the framework is.]]) or
```
Comment (yparitcher) [inline frontend/ui/network/manager.lua:637]: It works just fine for those of us that run frameworkless :)

Comment (NiLuJe) [reply frontend/ui/network/manager.lua:637]: Not over here (the numbers above were from a frameworkless session) ;o).

It's an old device that has almost never been online, which probably plays a part here, but even after letting it sit connected in the framework, I still get deltas of ~360.

**Comment by NiLuJe** [comment]
(Draft, got some more stuff to test/fix tomorrow).

File: frontend/ui/network/manager.lua (hunk 1 above)
Comment (yparitcher) [reply frontend/ui/network/manager.lua:637]: I have iptables rules that only allows outgoing connections on the local lan (i dont need any helpful connections by amazon) so  that is why it works for me

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 2 files at r2, 1 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)* status: all files reviewed, 1 unresolved discussion (waiting on @Frenzie, @pazos, @poire-z, and @yparitcher)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)* status: all files reviewed, 1 unresolved discussion (waiting on @Frenzie, @pazos, @poire-z, and @yparitcher)

**Comment by NiLuJe** [comment]
Okay, re-tested on a PW2 & a H2O, this ought to be ready now ;).

**Review by NiLuJe — COMMENTED** [review]
> Dismissed @yparitcher from a discussion.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Frenzie, @pazos, and @poire-z)

File: frontend/ui/network/manager.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/ui/network/manager.lua:639]: Fyi in case you have any other suggestions. https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=4f0eae549f1bd665#comments

> The English can probably be improved but "talkative, communicative..." is indeed correct. :-) It means the Kindle framework is constantly communicating with Amazon servers or something along those lines.
>
> In Dutch I provisionally translated it as "sends/broadcasts much information," which would likely be clearer in English too.

image

Comment (NiLuJe) [reply frontend/ui/network/manager.lua:639]: Yeah, it's probably a bit jargony. I can't quite think of something else as succinct, though; so the alternative would be to explain it, i.e., the the native system already triggers a lot of network activity on its own.

Comment (Frenzie) [reply frontend/ui/network/manager.lua:639]: Yes, that's probably clearer. "given how much network activity the framework generates" or something.
