### PR TITLE
Bag'o fixes ;p

### LINKED ISSUE #7482: Opensearch spec without a hostname
* KOReader version: v2021.03
* Device: Kobo Aura H2O

#### Issue
It looks that the (new) search functionality in opds only works if a full url is specified. In my case (calibre-web) the spec looks like this

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <LongName>Tario Books</LongName>
   <ShortName>Tario Books</ShortName>
   <Description>Calibre-Web eBook Catalog</Description>
   <Developer>Janeczku</Developer>
   <Contact>https://github.com/janeczku/calibre-web</Contact>
   <Url type="text/html"
        template="/opds/search/{searchTerms}"/>
   <Url type="application/atom+xml"
        template="/opds/search?query={searchTerms}"/>
   <SyndicationRight>open</SyndicationRight>
   <Language>en-EN</Language>
   <OutputEncoding>UTF-8</OutputEncoding>
   <InputEncoding>UTF-8</InputEncoding>
</OpenSearchDescription>
```

This then naturally fails as it's missing the host name of the server.

### LINKED ISSUE #7518: When starting app with 'History', automatic re-orientation doesn't work
* KOReader version: 2021.03
* Device: Libra H20

#### Issue

When you set the device to start with History, the page wont re-orient itself (eg portrait vs inverted portrait) by moving the device physically

#### Steps to reproduce

Self-explanatory as above

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

### LINKED ISSUE #7520: Crash when trying to edit bookmark names on PDFs
* KOReader version: 2021.03 Stable and 2021.03-35 Nightly
* Device: Kobo Clara HD

#### Issue

Every time I try to edit any bookmark name of any PDF KOReader crashes, I tested the stable and nightly build and got the same result.

#### Steps to reproduce

- Open a PDF
- Add a bookmark
- Change the name of that Bookmark

#### Crash log

```
./luajit: frontend/document/pdfdocument.lua:193: attempt to get length of local 'pboxes' (a nil value)
stack traceback:
	frontend/document/pdfdocument.lua:193: in function '_quadpointsFromPboxes'
	frontend/document/pdfdocument.lua:248: in function 'updateHighlightContents'
	frontend/apps/reader/modules/readerbookmark.lua:654: in function 'callback'
	frontend/ui/widget/button.lua:347: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1122: in function 'sendEvent'
	frontend/ui/uimanager.lua:210: in function '__default__'
	frontend/ui/uimanager.lua:1545: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1621: in function 'handleInput'
	frontend/ui/uimanager.lua:1668: in function 'run'
	./reader.lua:320: in main chunk
	[C]: at 0x00014161
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 04/08/21 @ 20:26:12)
Running FW 4.26.16704 on Linux 4.1.15-00089-ga2737fc02713 (#34 SMP PREEMPT Fri Dec 27 17:47:13 CST 2019)
Attempting to restart KOReader . . .
!!!!
```

### PR DESCRIPTION
**Pull request by NiLuJe**
* Move the fontlist cache out of Cache's territory, as discussed in #7510 
* Fix #7520 
* Fix #7518 
* Fix #7482

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7524)

### CODE REVIEW

File: frontend/apps/filemanager/filemanagerhistory.lua [hunk 1]
```diff
@@ -134,6 +134,18 @@ function FileManagerHistory:onShowHist()
...
         _manager = self,
     }
+
+    -- Handle rotation events
+    local this = self
+    function self.hist_menu:onSetRotationMode(rotation)
+        if rotation ~= nil and rotation ~= Screen:getRotationMode() then
+            UIManager:close(this.hist_menu)
+            Screen:setRotationMode(rotation)
+            this:onShowHist()
```
Comment (poire-z) [inline frontend/apps/filemanager/filemanagerhistory.lua:144]: No way to make that a proper method of Menu ? It could access "this" via self._manager we set on line 135.

Comment (NiLuJe) [reply frontend/apps/filemanager/filemanagerhistory.lua:144]: Yeah, I vaguely thought about it but couldn't really find anything nicer than this approach, which is admittedly less than ideal :/.

**Review by poire-z — APPROVED** [review]

File: frontend/apps/filemanager/filemanagerhistory.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/apps/filemanager/filemanagerhistory.lua]: That did lead me to a possibly slightly less redundant approach in c4428de

And I also made it rotate the underlying widget, otherwise you're left with a broken layout there ;).

This means it's potentially slow in ReaderView, because it rotates the book. But it's potentially less weird than just inhibiting rotates inside ReaderView?

Comment (NiLuJe) [reply frontend/apps/filemanager/filemanagerhistory.lua]: And that's only actually slow when orientation lock is *disabled*, which, while the default, is generally not the setup gyro-fans use ;).

**Review by poire-z — APPROVED** [review]

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2.
> Dismissed @poire-z from a discussion.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/7524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NiLuJe)

___
*[frontend/apps/filemanager/filemanagerhistory.lua, line 144 at r1](https://reviewable.io/reviews/koreader/koreader/7524#-MXrmSnCquwfh8x2z0ZN-r1-144:-MXsmFM_45EOJHKViUW2:b-896fix) ([raw file](https://github.com/koreader/koreader/blob/512521d1ba5296f7d4d79d801ee7eefff32eb958/frontend/apps/filemanager/filemanagerhistory.lua#L144)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

And that's only actually slow when orientation lock is *disabled*, which, while the default, is generally not the setup gyro-fans use ;).
</blockquote></details>

Done.
