### PR TITLE
Screensaver: add option to rotate to fit screen

### LINKED ISSUE #11856: Sleep screen image always assumes portrait orientation, even when reading in landscape
* KOReader version: 2024.04
* Device: Kobo Aura (model N514)

#### Issue

Sleep screen image is always displayed in portrait orientation, even when the book was being read in landscape

If a message string is set, the string as well is displayed in portrait mode, i.e. the base of the string is parallel to the short side of the kobo, not the long one

#### Steps to reproduce

1. Set reading orientation to landscape
2. Set a sleep screen image that is 1024 px wide by 768 pixels high
3. Put the device to sleep

#### Expected result:

The image in the sleep screen should fill the whole display, with the long side of the image aligned with the long side of the device, like this (this is how the image is displayed when opened with the viewer):

image

#### Actual result:

The image is scaled down, displayed in the center of the screen, with the long side of the image aligned with the short side of the device

image

#### Final note:

You may say: "why don't you save your image with a rotation to compensate for the above behavior, so that it is 768 px wide and 1024 px high?" 

That may work for solving the problem of the image itself, but the string message would still be displayed conforming to the portrait orientation, while I would like it to appear at the bottom of the image in landscape mode, in order to take advantage of the bigger length of the long side of the device

### PR DESCRIPTION
**Pull request by charrarr**
Checkbox in Wallpaper->Border fill to rotate images to fill as much of the screen as possible. It's basically what NiLuJe suggested in #11856 about checking the image's orientation. Passing a buffer directly avoids the ImageWidget cache trick that loads and stretches in one step.

A note about SVG: They're rendered here in their "native" resolution and so won't scale up correctly when rotated. Some math could fix that, but I doubt many people use SVG wallpapers.

I considered adding a rotate_to_fit setting to ImageWidget instead (ignoring orientation), but rotating *before* stretching a loaded file would require some refactoring, or at least an ugly-specific setting to disable the cache hack in _loadfile().

Test images if you like:
PNG
test-wallpaper
SVG
test-wallpaper

Fix #11856 

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12366)

### CODE REVIEW

File: frontend/ui/elements/screensaver_menu.lua [hunk 1]
```diff
@@ -64,6 +64,16 @@ return {
...
+                    {
+                        text = _("Rotate cover to fit screen"),
+                        checked_func = function()
+                            return G_reader_settings:isTrue("screensaver_autorotate_images")
+                        end,
+                        callback = function(touchmenu_instance)
+                            G_reader_settings:flipNilOrFalse("screensaver_autorotate_images")
+                            touchmenu_instance:updateItems()
+                        end,
+                    }
```
Comment (Commodore64user) [inline frontend/ui/elements/screensaver_menu.lua:76]: this should be nested under `Custom images` not `Border fill`.

File: frontend/ui/screensaver.lua [hunk 2]
```diff
@@ -504,13 +508,15 @@ function Screensaver:show()
         return
     end
 
+    local rotation_mode = Screen:getRotationMode()
+
     -- We mostly always suspend in Portrait/Inverted Portrait mode...
     -- ... except when we just show an InfoMessage or when the screensaver
-    -- is disabled, as it plays badly with Landscape mode (c.f., #4098 and #5290).
+    -- is disabled, as it plays badly with Landscape mode (c.f., #4098 and #5920).
```
Comment (NiLuJe) [inline frontend/ui/screensaver.lua:515]: I have this hunk in a PR somewhere, so this'll conflict ;when I merge it ;).

File: frontend/ui/screensaver.lua [hunk 3]
```diff
@@ -550,10 +556,31 @@ function Screensaver:show()
...
+            end
             widget_settings.alpha = true
         end
+        if G_reader_settings:isTrue("screensaver_autorotate_images") then
+            local angle = rotation_mode == 3 and 180 or 0 -- match mode if possible
+            if (widget_settings.image:getWidth() < widget_settings.image:getHeight())
+                ~= (widget_settings.width < widget_settings.height) then
+                angle = angle + 90
+            end
+            widget_settings.rotation_angle = angle
```
Comment (NiLuJe) [inline frontend/ui/screensaver.lua:582]: This could be honoring the `imageviewer_rotation_portrait_invert` & `imageviewer_rotation_landscape_invert` settings for consistency's sake ;).

Comment (NiLuJe) [reply frontend/ui/screensaver.lua:582]: Well, landscape, really, as Portrait will follow the current rotation.

File: frontend/ui/screensaver.lua [hunk 4]
```diff
@@ -550,10 +556,31 @@ function Screensaver:show()
...
+                widget_settings.file = self.image_file
+                widget_settings.file_do_cache = false
+            end
             widget_settings.alpha = true
         end
+        if G_reader_settings:isTrue("screensaver_autorotate_images") then
+            local angle = rotation_mode == 3 and 180 or 0 -- match mode if possible
+            if (widget_settings.image:getWidth() < widget_settings.image:getHeight())
+                ~= (widget_settings.width < widget_settings.height) then
+                angle = angle + 90
```
Comment (NiLuJe) [inline frontend/ui/screensaver.lua:580]:
```suggestion
                angle = angle + G_reader_settings:isTrue("imageviewer_rotation_landscape_invert") and -90 or 90
```

Comment (NiLuJe) [reply frontend/ui/screensaver.lua:580]: (blitbuffer will handle the wraparound automatically)

File: frontend/ui/elements/screensaver_menu.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua:76]: I suppose a case could also be made in favor of reusing `imageviewer_rotate_auto_for_best_fit` instead of duplicating a ScreenSaver-specific variant?

Comment (poire-z) [reply frontend/ui/elements/screensaver_menu.lua:76]: Dunno if that setting should be reused - but the new one may keep the same name suffix:
`screensaver_rotate_auto_for_best_fit`

File: frontend/ui/screensaver.lua [hunk 5]
```diff
@@ -550,10 +556,31 @@ function Screensaver:show()
...
+            else
+                widget_settings.file = self.image_file
+                widget_settings.file_do_cache = false
+            end
             widget_settings.alpha = true
         end
+        if G_reader_settings:isTrue("screensaver_autorotate_images") then
+            local angle = rotation_mode == 3 and 180 or 0 -- match mode if possible
+            if (widget_settings.image:getWidth() < widget_settings.image:getHeight())
+                ~= (widget_settings.width < widget_settings.height) then
```
Comment (poire-z) [inline frontend/ui/screensaver.lua:579]: This doesn't read well - best to keep it all on a single line.

File: frontend/ui/elements/screensaver_menu.lua (hunk 1 above)
Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua:76]: @Commodore64user It would be confusing to have stretch and rotate in different menus. Maybe move both to `Custom images`?
@NiLuJe I don't think it should be tied to the image viewer. A user might want their screensavers to look pretty and fill the screen, while preferring images to stay upright in the reader.
@poire-z Sounds good

File: frontend/ui/screensaver.lua (hunk 4 above)
Comment (charrarr) [reply frontend/ui/screensaver.lua:580]: Adding to commit

File: frontend/ui/elements/screensaver_menu.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: Fair enough, I'm not the target audience for either use-cases, so that's perfectly fine by me ;).

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: > @Commodore64user It would be confusing to have stretch and rotate in different menus. Maybe move both to `Custom images`?

On the other hand, this *only* applies to custom images, while the border fill stuff applies to *all* images ;).

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: Rotation applies to both covers and custom images

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: Oh, right, my bad, hadn't re-read the code ;).

Then, err, meh, no strong feelings about either ;p.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: It's a big chunky if statement, a comment is in order. Commodore64user, what do you think?

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: > Maybe move both to Custom images

no, to that one.

Are covers in the wrong orientation…? In any case border fill has things related to adjusting (or reducing them) borders, while rotation is an entirely different thing… perhaps you could rename it, to border fill and rotation but i am not convinced (thinking about it)

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: The more i think about this, the more i realise it belongs in “custom images” (sorry if you need to move from one place to another to adjust things). I am all for people having cats, pandas or cows as their sleep screen image but let’s keep things where they belong. Otherwise we’ll just end up with the mess things become when one starts leaving them in the “everyday” table.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: The rotation is meant to reduce borders, at least that was the use case I had in mind (it never rotates if the borders would become wider). "Border fill" already read awkwardly to me - it relies on "fill" being both a noun (black fill) and a verb (fill the screen). How about "Border fill and fit"? That matches the language used in the options.

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua]: Does it relate to everything or only to a custom image?

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: > The rotation is meant to reduce borders, at 

This is just you trying to force the wrong piece in the wrong spot.

> Border fill" already read awkwardly to me

Border and background fill are legitimate terms used in image retouching and editing.

> Does it relate to everything or only to a custom image?

This is what i have been trying to get at...
Are you solving #12308 as well? If yes then we should rename the parent, if not, it goes with "custom images"

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: > This is just you trying to force the wrong piece in the wrong spot. Not buying it
I made this feature specifically to reduce pillarboxing, i.e., borders, and as you said, border fill is for adjusting or reducing borders. I don't know what else you think this feature is for.

> Border and background fill are legitimate terms used in image retouching and editing.
They refer to stretching an image to fill borders?

> Does it relate to everything or only to a custom image?
> Rotation applies to both covers and custom images.

This is what i have been trying to get at...
Are you solving #12308 as well? If yes then we should rename the parent, if not, it goes with "custom images"
That issue seems to be specific to devices with hardware rotation (not sure) but inverted portrait normally works fine without rotation.

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: Border fill is just to paint the border, or fill the borders with black or white. Stretch image just seems to be in the same direction. Filling the borders with a stretched out cover.

> I made this feature specifically to reduce pillarboxing,

could you show screenshots with this on and off… 

> That issue seems to be specific to devices with hardware rotation (not sure) but inverted portrait normally works fine without rotation

that is what i was afraid of, the only reason i can see for rotating a book cover is this as far as i can see.

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua]: I don't think https://github.com/koreader/koreader/issues/12308 is really the same thing as "I want it to fill up as much space as possible regardless of rotation"

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: Another option could be to use the same enabled function as custom images https://github.com/koreader/koreader/blob/91c15d52778708b580e0bd0bcc6e364051e98cbc/frontend/ui/elements/screensaver_menu.lua#L82-L85 because i can't still fathom why anyone would want to use this with a legitimate book cover.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: I'll upload screenshots later today.

Off the top of my head, children's picture books and PDF slideshows have horizontal covers. The option also rotates vertical covers on a horizontal device, though I can't confirm right now if KOReader considers any devices to have a horizontal resolution (tablets?)

Anyway, why limit it to images when it works for both? Vertical covers aren't affected whether it's on or off.

Comment (hius07) [reply frontend/ui/elements/screensaver_menu.lua]: I'm for "Border fill".

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: > "Border fill and fit"?

Sounds good to me!

> Does it relate to everything or only to a custom image?

Everything, which is why moving this in "Custom images" would be problematic.

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: > though I can't confirm right now if KOReader considers any devices to have a horizontal resolution (tablets?)

We don't discriminate ;p.

Whatever the native layout is happens to be "Portrait" ;p. (i.e., on a TV, UR would look landscape-y).

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: Rest assured that very very few things are left using getScreenMode in the codebase ;).

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: > Off the top of my head, children's picture books and PDF slideshows have horizontal covers. 

not sure there are many 3 year olds using KOReader though. as for slideshows, not books.

> The option also rotates vertical covers on a horizontal device,

which again, I don't personally understand why anyone would want this done. But that just might be me.

> Anyway, why limit it to images when it works for both? 

because it might be possible, but whether it should be done is a completely different issue, then again we (or I) can only be sure with examples.

> Vertical covers aren't affected whether it's on or off.

but this here just _might_ be how you snatch victory from the jaws of defeat.

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua]: > because it might be possible, but whether it should be done is a completely different issue, then again we (or I) can only be sure with examples.

PDFs might be a legitimate use-cases where te cover (or first page when lacking) one is genuinely in a different orientation than the device.

Say, for example, a landscape page on a Portrait device ;).

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: > PDFs might be a legitimate use-cases where the cover (or first page when lacking one) is genuinely in a different orientation than the device.

that might seal the deal then. I _might_ have to stand corrected then.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua]: Alright then, I'll mark this comment thread as resolved for now and change the menu name.

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua]: not yet, still waiting for those screenshots.

File: frontend/ui/elements/screensaver_menu.lua [hunk 6]
```diff
@@ -38,7 +38,7 @@ return {
             genMenuItem(_("Leave screen as-is"), "screensaver_type", "disable", nil, true),
             separator = true,
             {
-                text = _("Border fill"),
+                text = _("Border fill and fit"),
```
Comment (Commodore64user) [inline frontend/ui/elements/screensaver_menu.lua:41]: but where are the screenshots. you are running a marathon but stopping short of the finishing line.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua:41]: Rotation off:
v-rnor

Rotation on:
v-rnor

Rotation off:
h--

Rotation on:
h-r

Rotation and stretch on:
hsr

If you're not satisfied with that, you can pull my branch and run your own tests.

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: stop marking it as resolved so other can see them too.

yes, I can see how you setting should live next to the stretch one. However I am not convinced now that the wording for said setting is appropriate `"Rotate cover to fit screen`. As far as I see, you just rotate the image and then stretch with the existing stretch-setting.

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua:41]: I'll unresolve since you raised a new issue.

True, it's not clear what the setting does from the name. How about the same language as the image viewer setting: "Auto-rotate cover for best fit"

Comment (NiLuJe) [reply frontend/ui/elements/screensaver_menu.lua:41]: > True, it's not clear what the setting does from the name. How about the same language as the image viewer setting: "Auto-rotate cover for best fit"

Yup, I seem to remember there was already a lot of back-and-forth on that one so let's avoid any more useless bike-shedding on that front ;).

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua:41]: 👍

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: I can live with “Auto-rotate cover for best fit“ and “Border fill, fit and rotation”. But lets see if anyone comes up with anything else.

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:41]: > However I am not convinced now that the wording for said setting is appropriate `"Rotate cover to fit screen`. As far as I see, you just rotate the image and then stretch with the existing stretch-setting. @Frenzie

Sounds like excellent, clear wording to me. Could you explain in what way this could be construed as confusing?

File: frontend/ui/elements/screensaver_menu.lua [hunk 7]
```diff
@@ -64,6 +64,16 @@ return {
                             Screensaver:setStretchLimit(touchmenu_instance)
                         end,
                     },
+                    {
+                        text = _("Auto-rotate cover for best fit"),
```
Comment (Frenzie) [inline frontend/ui/elements/screensaver_menu.lua:68]: Meh. Waking up to an ugly string change is never fun. :-)

File: frontend/ui/elements/screensaver_menu.lua (hunk 6 above)
Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: Because according to that wording both image 3 and 4 technically satisfy the criteria of the string. They both "fit" by using the maximum height or width of the  screen. Furthermore since the rotation does not always happen, one might think said setting doesn't really work, if like me, you always have sane covers that wouldn't be rotated at all with this. "Best fit" however i am not overly fond of but at least sort of hints at checking which of the two options would use a larger area of the display removing the example 3.

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:41]: Well of course. 3 fits properly, 4 fills up all the space as per the stretch setting. But that's not the part of the string I'm concerned about. It's the "auto" that's an eyesore.

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: What's wrong with it? Even Apple doesn't mind it image

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:41]: While indeed hideous, that's completely different. "Autocapitalize" is the same thing as "Capitalize first letter" in the same way that "Autorotate" is the same thing as "Rotate for best fit."

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: Okay, "rotate for best fit" and "border fill, rotation and fit" are fine.

Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:41]: I'm happy with that. You could also turn it around: `Best-fit rotation`.

But perhaps that would imply too much…
https://matthias-research.github.io/pages/publications/stablePolarDecompSlides.pdf
image

Comment (charrarr) [reply frontend/ui/elements/screensaver_menu.lua:41]: I'm not willing to devote more attention to this PR. I appreciate the suggestions and discussions that were proportionate to understanding, but if anyone wants to develop it further, please submit a new PR :)

Comment (Commodore64user) [reply frontend/ui/elements/screensaver_menu.lua:41]: People are very passionate about their reading experience around here, and anything that can improve said experience is always welcome, even if sometimes things can get a bit frisky ;). Having said that, I don't think anyone expects you to implement that "Robust Method to Extract the Rotational Part of Deformations". Common, you are almost there.

And btw, than you for implementing this. I'm sure plenty of folks will be glad to finally be able to display landscape-shot pics of their feline friends on their screens.

File: frontend/ui/elements/screensaver_menu.lua (hunk 7 above)
Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:68]:
```suggestion
                        text = _("Rotate cover for best fit"),
```

File: frontend/ui/elements/screensaver_menu.lua (hunk 6 above)
Comment (Frenzie) [reply frontend/ui/elements/screensaver_menu.lua:41]:
```suggestion
                text = _("Border fill, rotation, and fit"),
```

**Comment by Frenzie** [comment]
No need. ;-) Thanks!

**Comment by NiLuJe** [comment]
Thanks, I clearly had my nose too close to ImageWidget when I posted that original comment, and didn't even think about simply punting off the _loadfile part to ScreenSaver to deal with it ;)

**Comment by charrarr** [comment]
@NiLuJe That's funny, because I got halfway through refactoring ImageWidget before just doing it in screensaver, and only then thought to search for related issues.
