### PR TITLE
Footer and header tweaks and fixes

### LINKED ISSUE #11561: Issue with "left pages number"
* KOReader version: 2024.03.1 (Latest)
* Device: PocketBook 633 Color

I enabled the function to show only as many pages as in the physical book.

And I ran into this problem:
In the status bar it shows the same on different indicators, that is, it shows only one thing correctly - the current page in the book.

And the same number is shown in “how many pages are left until the end of the book”, although there should be a different number, a different indicator.

I hope I explained clearly...

The photo shows and makes it clear what the problem is (circled in red)

How to fix this problem? Can you help me?
Please fix it!!!

I adore KOReader!

### PR DESCRIPTION
**Pull request by poire-z**
#### ReaderFooter: fix minor issues with pages left & chapter progress

When using Reference page numbers, "Pages left" was showing the same info as "Current page", because Reference pages, being strings, couldn't be used for arithmetics. But we can just count the number of items left in the Reference pages array of strings.
Closes #11561 (I think I've seen this discussed elsewhere too.)

Also fix edge case with "page progress" with hidden flow when we are before the first chapter with a hidden flow before.
Noticed at https://github.com/koreader/koreader/issues/10193#issuecomment-2106274054.

#### AltStatusBar: show page info similar as in footer

We now build the "page/total %" string ourselves, with the same logic as used in the footer (including when hidden flows or reference page numbers are used) and give it to crengine to be displayed instead of its own way of doing it.
Uses bits previously added by https://github.com/koreader/koreader/pull/11863.
Discussed in and around https://github.com/koreader/koreader/issues/9020#issuecomment-2045865939.
(Not super tested, we'll see.)

#### userpatch: add a few helpers that can be used in userpatches

Make the few tricks we discovered readily available, which should make user patch simpler.
Example of how to use them at https://github.com/koreader/koreader/pull/11838#issuecomment-2124493747.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11873)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

File: frontend/userpatch.lua [hunk 1]
```diff
@@ -103,4 +103,73 @@ function userpatch.applyPatches(priority)
...
+
+-- On each new Reader/FileManager, plugins are dofile()d, and then
+-- instantiated through createPluginInstance. We need to catch and
+-- patch them each time they are instantiated.
+local orig_PluginLoader_createPluginInstance
+local patch_plugin_funcs = {}
+function userpatch.registerPatchPluginFunc(plugin_name, patch_func)
+    if not orig_PluginLoader_createPluginInstance then
+        local PluginLoader = require("pluginloader")
+        local orig_PluginLoader_createPluginInstance = PluginLoader.createPluginInstance
```
Comment (Frenzie) [inline frontend/userpatch.lua:156]: Is that supposed to shadow or should it just be removed from line 151?

Comment (poire-z) [reply frontend/userpatch.lua]: CircleCI told me before you :) Should now be fixed.

**Comment by skylarsoulmate** [comment]
Is it already available in the nightly build? Sorry for being stupid girl...

Does it work (or changes) in this patch too? Because I'm using it always.
https://github.com/koreader/koreader/issues/9020#issuecomment-2033259217

I haven’t read this topic in full, but I understand that they will finally make displaying of how many pages are left in the book with paperback pages (before left and current pages were the same)? 


Sorry my English is so bad...

**Comment by benoit-pierre** [comment]
> Is it already available in the nightly build? Sorry for being stupid girl...

It does not look like it's part of the latest nightly, so you'll have to wait for tomorrow.

**Comment by skylarsoulmate** [comment]
> > Is it already available in the nightly build? Sorry for being stupid girl...
> 
> It does not look like it's part of the latest nightly, so you'll have to wait for tomorrow.

Thank you very much 🙏

**Comment by skylarsoulmate** [comment]
> Looks like we reach the 25/26th of the month, when our Azure or something quota is reached...
> There won't be any nightly for a few days.

So that left pages number thing won't be available tomorrow? A little sad, but thanks anyway.

**Comment by Frenzie** [comment]
I set up @pazos server to trigger https://gitlab.com/koreader/nightly-builds/-/jobs btw so it'll be there tomorrow.

@skylarsoulmate Which device?

**Comment by skylarsoulmate** [comment]
> I set up @pazos server to trigger https://gitlab.com/koreader/nightly-builds/-/jobs btw so it'll be there tomorrow.
> 
> @skylarsoulmate Which device?

PocketBook 633 Color

IT'S GREAT NEWS. NOW I'M A HAPPY GIRL 🫶 THANKS

**Comment by Frenzie** [comment]
Try https://gitlab.com/koreader/nightly-builds/-/jobs/6940092674 (download is on the right)

**Comment by skylarsoulmate** [comment]
> Try https://gitlab.com/koreader/nightly-builds/-/jobs/6940092674 (download is on the right)

Sorry, I don't see the download button anyway...
I just will wait for the new nightly build... today right? After 1 hour approximately?

**Comment by skylarsoulmate** [comment]
> Try https://gitlab.com/koreader/nightly-builds/-/jobs/6940092674 (download is on the right)

Then I need to extract and put files in the KOReader folder?

**Comment by poire-z** [comment]
Ok, crappy non-boolean cre settings :)
This should fix it:
```diff
--- a/frontend/apps/reader/modules/readercoptlistener.lua
+++ b/frontend/apps/reader/modules/readercoptlistener.lua
@@ -128 +128 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-    if self.page_number or self.page_count then
+    if self.page_number == 1 or self.page_count == 1 then
@@ -130 +130 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-        if self.page_number then
+        if self.page_number == 1 then
@@ -132 +132 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-            if self.page_count then
+            if self.page_count == 1 then
@@ -136 +136 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-        if self.page_count then
+        if self.page_count == 1 then
@@ -140 +140 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-        if self.reading_percent then
+        if self.reading_percent == 1 then
@@ -144 +144 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
-    if self.reading_percent then
+    if self.reading_percent == 1 then
```

**Comment by poire-z** [comment]
I wonder how I managed to test that when I made this PR :/ I swear I did test it :\
