### PR TITLE
android: call EPD test from within KOReader

### LINKED ISSUE #5730: Crash if no dictionary is installed
* KOReader version: 2019.12
* Device: Tolino Epos 2

#### Issue
Crash if a word in the book is selected an no dictionaries are installed.

#### Steps to reproduce
Select a word -> Crash

### PR DESCRIPTION
**Pull request by pazos**
Most users can call it from the developers menu:

test (1)

On some devices, where KOReader doesn't work at all, it can be called using adb with:

`adb shell am start -n org.koreader.launcher/.EPDTestActivity`

Fixes #5730 too

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5737)

### CODE REVIEW

File: frontend/apps/filemanager/filemanagermenu.lua [hunk 1]
```diff
@@ -387,6 +387,15 @@ function FileManagerMenu:setUpdateItemTable()
             end,
         })
     end
+    if Device:isAndroid() then
+        table.insert(self.menu_items.developer_options.sub_item_table, {
+            text = _("Start Eink Test"),
```
Comment (Frenzie) [inline frontend/apps/filemanager/filemanagermenu.lua]: I believe it's spelled E-ink in the rest of the program. (Please ignore if I recall incorrectly. ;-) )
```suggestion
            text = _("Start E-ink Test"),
```
