### PR TITLE
Fix touch input on the 3G KOA

### LINKED ISSUE #2181: Unresponsive screen on Oasis.
* KOReader version:koreader-kindle-arm-linux-gnueabi-v2015.11-533-g1d2150c
* Device:Oasis 3g, 5.7.4 and 5.8.1.0.1

#### Issue
Screen is not responsive to touches.

#### Steps to reproduce
I follow this instruction to install, http://lifehacker.com/how-to-jailbreak-your-kindle-1783864074

Tried both KPV and KUAL, same problem.

### PR DESCRIPTION
**Pull request by NiLuJe**
There's an extra controller in there screwing things up for us,
because reasons, I guess?

Fix #2181

### CODE REVIEW

File: frontend/device/kindle/device.lua [hunk 1]
```diff
@@ -336,7 +336,13 @@ function KindleOasis:init()
...
     Kindle.init(self)
 
-    self.input.open("/dev/input/event3")
+    --[[
+    -- NOTE: Points to event3 on WiFi devices, event4 on 3G devices...
+    --       3G devices apparently have an extra SX9500 Proximity/Capacitive controller for mysterious purposes...
+    --       This evidently screws the ordering, so, use the by-path path instead to avoid hackier workarounds.
+    --       cf. #2181
+    --]]
+    self.input.open("/dev/input/by-path/platform-imx-i2c.1-event")
```
Comment (houqp) [inline frontend/device/kindle/device.lua]: Any reason not to use `self.input.open(self.touch_dev)` instead here?

Comment (NiLuJe) [inline frontend/device/kindle/device.lua]: None at all, good point ;).
