### PR TITLE
ReaderFooter: fix tapping footer to browse in flipping mode

### LINKED ISSUE #2649: Crash: Toggle minibar in page-flip mode
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue
Koreader crashes if attempting to toggle the minibar in page-flip mode.
```
03/15/17-13:05:55 INFO  setting zoom mode to page
./luajit: frontend/apps/reader/modules/readerfooter.lua:575: attempt to index local 'ges' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerfooter.lua:575: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:197: in function 'handleEvent'
	frontend/ui/uimanager.lua:379: in function 'sendEvent'
	frontend/ui/uimanager.lua:114: in function '__default__'
	frontend/ui/uimanager.lua:653: in function 'handleInput'
	frontend/ui/uimanager.lua:698: in function 'run'
	./reader.lua:188: in main chunk
	[C]: at 0x00013e85
```
Discovered this further testing bug #2636 as trying to look up words in the bookmark tap zone enables flipping mode, then accidentally toggling the minibar.

#### Steps to reproduce
1. Open a pdf document
2. Enable page-flip mode
3. Touch minibar toggle touch zone

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes #2649.

### CODE REVIEW

**Comment by Frenzie** [comment]
Oh, hold on. I forgot to rearrange the requires.

File: frontend/apps/reader/modules/readerfooter.lua [hunk 1]
```diff
@@ -1,20 +1,20 @@
...
-local Device = require("device")
-local Screen = require("device").screen
-local Geom = require("ui/geometry")
-local Event = require("ui/event")
-local Font = require("ui/font")
+local WidgetContainer = require("ui/widget/container/widgetcontainer")
+local util = require("util")
 local _ = require("gettext")
-local util  = require("util")
+local Screen = require("device").screen
```
Comment (houqp) [inline frontend/apps/reader/modules/readerfooter.lua]: `local Screen = Device.screen`

File: frontend/apps/reader/modules/readerfooter.lua [hunk 2]
```diff
@@ -230,7 +230,7 @@ function ReaderFooter:setupTouchZones()
             id = "readerfooter_tap",
             ges = "tap",
             screen_zone = footer_screen_zone,
-            handler = function() return self:onTapFooter() end,
+            handler = function(ev) return self:onTapFooter(ev) end,
```
Comment (houqp) [inline frontend/apps/reader/modules/readerfooter.lua]: nitpick, can we keep the variable name as `ges` instead of `ev` to keep it consistent with the rest of the code like readerpaging?

**Comment by houqp** [comment]
Good catch :+1:

**Comment by Frenzie** [comment]
Should be good now.
