### PR TITLE
Text selection: option to disable corner scroll; show top left icon on very-long-press

### LINKED ISSUE #11223: Text scrolling unexpectedly when highlighting from corner
* KOReader version: 2023.10-52
* Device: Kobo Aura H2O

#### Issue

Very often, when starting a highlight in the upper left hand corner of the screen, the text scrolls backward even though I'm moving in the forward direction and do not intend to highlight anything from the previous page. This interferes with my highlighting process. It doesn't happen every time, but often enough that it's rather bothersome. (Increasing the margin would prevent it but  that would waste valuable screen space.)

https://github.com/koreader/koreader/assets/95502269/60fa47d4-540c-4895-bac3-db4aed0abbfa

#### Steps to reproduce

1. Start highlighting from upper left corner in the forward direction
2. Observe text moving backwards

#### Suggested solution

If there is no easy fix without unintended side effects (or even if there is), please consider making the text-scrolling-while-highlighting feature an option that can be disabled entirely. In my opinion, the `Select` feature is much better suited for inter-page highlights on e-readers and makes the scrolling unnecessary.

##### `crash.log` (if applicable)

Will gladly provide if needed.

Thank you for your help.

### PR DESCRIPTION
**Pull request by poire-z**
Things discussed all along #11223. Closes #11223.

#### Text selection: add option to disable corner scroll

People using 2-steps text selection (via the Select button) may want to not be annoyed by this feature.
Also tweak a bit its behaviour, requiring now the text selection to come from outside a corder into a corner to activate it, which should allow starting text selection from a corner without triggering a scroll yet.
Some help_text and menu item text wording to be reviewed.

#### Text selection: show top left icon when very-long-press delay reached

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11327)

### CODE REVIEW

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/11327)* status: all files reviewed, 2 unresolved discussions (waiting on @poire-z)

___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 574 at r1](https://reviewable.io/reviews/koreader/koreader/11327#-Nnj0vfE4lTKhfpVh-Bm:-Nnj0vfE4lTKhfpVh-Bn:bac9nfn) ([raw file](https://github.com/koreader/koreader/blob/45b000bdd5495cf2f1037503301bc8a61db7d8a1/frontend/apps/reader/modules/readerhighlight.lua#L574)):*
> ```Lua
>     if self.ui.rolling then
>         table.insert(menu_items.long_press.sub_item_table, {
>             text = _("Scroll page when selection reaches corners"),
> ```

`Auto-scroll when selection reaches a corner`
___
*[`frontend/apps/reader/modules/readerhighlight.lua` line 576 at r1](https://reviewable.io/reviews/koreader/koreader/11327#-Nnj10Z53HDH3Oan4QZA:-Nnj10Z53HDH3Oan4QZB:b-papsj3) ([raw file](https://github.com/koreader/koreader/blob/45b000bdd5495cf2f1037503301bc8a61db7d8a1/frontend/apps/reader/modules/readerhighlight.lua#L576)):*
> ```Lua
>             text = _("Scroll page when selection reaches corners"),
>             help_text = _([[
> Auto scroll to show some parts of the previous page when your text selection reaches the top left corner, or of the next page when it reaches the bottom right corner.
> ```

`Auto-scroll to show part of the previous page...`



_Code quote:_
```Lua
Auto scroll to show some parts of the previous page when your text selection reaches the top left corner, or of the next page when it reaches the bottom right corner.
```

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -568,6 +568,26 @@ function ReaderHighlight:addToMainMenu(menu_items)
             UIManager:show(items)
         end,
     })
+
+    if self.ui.rolling then
```
Comment (hius07) [inline frontend/apps/reader/modules/readerhighlight.lua:572]: Is it the first menu item in the **Settings** that is (not) shown depending on the type of the document?
On the contrary, we show "Save highlights to PDF" item when cre document is opened.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:572]: > Is it the first menu item in the **Settings** that is (not) shown depending on the type of the document?

Yes, I think it is.

> On the contrary, we show "Save highlights to PDF" item when cre document is opened.

So, what are you suggesting ?
I guess it's not about moving `Save highlights` to this menu (which even if things are named Highlight... is more about text selection).
Are you suggesting always showing both, possibly making this one unchecked and disabled on non-CRE documents?

Comment (hius07) [reply frontend/apps/reader/modules/readerhighlight.lua:572]: No, I do not mean moving anything.

I think that general settings should be always visible and accessible.
(The first time I felt uncomfortable when met disabled "Scrolling" item in the Taps&Gestures menu).

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:572]: I think the disabled Scrolling is fine: if it wasn't, and scroll mode was off, the user would see the menu and its subitems, would tweak some of them, without any effect, and would think it's crap and doesn't work.
Showing it disabled, the user knows this doesn't apply currently, and would go looking for the other thing that would get it enabled. There is the much more similar behaviour in the bottom menu.

Same if we were showing fully enabled and actionable this "Auto-scroll in corner" on PDF: it would not work. Better let it be shown that it doesn't apply, and there's no need to allow the user to toggle stuff in a context where it doesn't apply and it can't verify what option is best for him.
