### PR TITLE
bump crengine: various fixes and FB2 tweaks

### LINKED ISSUE #6391: Koreader crashes when turning to a particular page
* KOReader version: 2020.06
* Device: Kobo Forma

#### Issue

Koreader crashes when turning to a particular page. I'd include the epub, but it's copyrighted :)

I get a popup to sync reading position, and then a crash when I go to a particular page.

Crash log attached.
[crash.log](https://github.com/koreader/koreader/files/4942203/crash.log)

### LINKED ISSUE #6394: KOReader crashes when opening epub with embedded fonts
* KOReader version: v2020.06-60
* Device: Kobo Aura One

#### Issue

When opening some ePub with embedded fonts, KOReader crashes with the following message:

`CRE: document loaded, but styles re-init needed (cause: embedded fonts)
CRE: styles re-init needed after load, re-rendering
Segmentation fault
!!!!
Uh oh, something went awry... (Crash nÂ°1: 07/19/20 @ 14:03:07)`

If I open the epub with the stable release v2020.06 the book opens fine.
If I remove the embedded font information with Calibre the book also opens fine in v2020.06-60.

#### Steps to reproduce

Open attached embedded_font_crash_scrambled.epub file

[embedded_font_crash_scrambled.zip](https://github.com/koreader/koreader/files/4943634/embedded_font_crash_scrambled.zip)

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/4943631/crash.log)

### PR DESCRIPTION
**Pull request by poire-z**
Includes:
- New German hyphenation patterns https://github.com/koreader/crengine/pull/356
- CSS: adds `text-align-last: -cr-right-if-not-first` private keywords https://github.com/koreader/crengine/pull/357
- CSS: adds `-cr-only-if: fb2-document`
- fb2.css: fix verses, minor cleanup
- FB2 footnotes: fix spacing between number and text
- ldomTextCollector: guess block boundaries better
- Text: fix read/write outside array bounds
- Text: fix read outside array bounds https://github.com/koreader/crengine/pull/358
- Fix crash when more than 64 nested elements - Closes #6391 
- Fix possible crash on book with embedded fonts load - Closes #6394 
- (Upstream) lvstsheet: avoid compilation warnings https://github.com/koreader/crengine/pull/359
- Strut confining: don't when there is no strut
- CSS: switch `-cr-hint` from enum to bitmap

`Style tweaks: limit EPUB/FB2 footnotes to these formats`
Avoid conflicts having "In-page EPUB footnotes (smaller)" affects FB2 documents that use `<a type=note>12</a>` which would then get smaller if both tweaks are enabled (which they are, by default). See https://github.com/koreader/koreader/issues/6344#issuecomment-658273890
Footnote popups: add styles for some non-HTML FB2 tags, so MuPDF can render them as expected. See https://github.com/koreader/koreader/issues/6344#issuecomment-657007634 (I just styled the obvious, may be more styling is needed, dunno.)

This PR fixes most issues with FB2 noticed from https://github.com/koreader/koreader/issues/6344#issuecomment-655936850 and later comments.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6405)

### CODE REVIEW

File: frontend/ui/data/css_tweaks.lua [hunk 1]
```diff
@@ -650,12 +650,16 @@ This is just an example, that will need to be adapted into a user style tweak.]]
                     title = _("In-page FB2 footnotes"),
                     description = _([[
 Show FB2 footnote text at the bottom of pages that contain links to them.]]),
+                    -- Restrict this to FB2 documents, even if we won't probably
+                    -- match in any other kind of document
                     css = [[
 body[name="notes"] section {
+-cr-only-if: fb2-document;
```
Comment (Frenzie) [inline frontend/ui/data/css_tweaks.lua:657]: This rather… distracting indentation is on purpose to make it stand out?

Comment (poire-z) [reply frontend/ui/data/css_tweaks.lua:657]: Yes. I used that kind of layout to express more clearly what the "only if" affects, as in:
https://github.com/koreader/koreader/blob/201d3d8ad1c9e6432283439e3c14abfd9569bc2f/frontend/ui/wikipedia.lua#L1015-L1039
I can add another level of indentation if you prefer, we have enough width to show them non wrapped:
image
=>
image

Comment (Frenzie) [reply frontend/ui/data/css_tweaks.lua:657]: I think that would be nicer to look at (like in the Wikipedia one). :+1:

**Comment by poire-z** [comment]
Don't merge yet - I forgot some simplifications in the style tweaks, now that we have inheritance, we can replace i.e. `* { -cr-hint: strut-confined }` with just setting it on BODY.
