### PR TITLE
Fix #6929

### LINKED ISSUE #6929: Crash when tapping on image
* KOReader version: v2020.11-25-g4ed9f19b_2020-11-29 (after #6885)
* Device: Tolino

#### Issue
After opening an image PNG, JPG and tap on the right or left I get a crash.
It seems that this bug was introduced with #6885

#### Steps to reproduce
see above

##### `crash.log` (if applicable)
[log.txt](https://github.com/koreader/koreader/files/5614710/log.txt)

### PR DESCRIPTION
**Pull request by jperon**
A check was missing on a flag not defined for images.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6930)

### CODE REVIEW

File: frontend/apps/reader/modules/readerpaging.lua [hunk 1]
```diff
@@ -844,7 +844,8 @@ function ReaderPaging:onGotoPageRel(diff)
     logger.dbg("goto relative page:", diff)
     local new_va = self.visible_area:copy()
     local x_pan_off, y_pan_off = 0, 0
-    local right_to_left = (self.ui.document.configurable.writing_direction > 0)
+    local right_to_left = self.ui.document.configurable.writing_direction
+                        and self.ui.document.configurable.writing_direction > 0
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerpaging.lua:848]: Alignment would look nicer like this. But no objection to sticking it on one line on my part, probably clearer if anything.
```suggestion
                          and self.ui.document.configurable.writing_direction > 0
```

Comment (jperon) [reply frontend/apps/reader/modules/readerpaging.lua:848]: Even though it makes the line longer than 120 characters (usual limit in Lua) ?

Comment (Frenzie) [reply frontend/apps/reader/modules/readerpaging.lua:848]: A line that's more than some 100-120 characters is a rough indicator that there might be too much nested complexity. Other than that line length has no particular significance.

Comment (jperon) [reply frontend/apps/reader/modules/readerpaging.lua]: OK. Till now, I thought the main reason for that was to avoid lines getting out the screen in editors.

**Review by Frenzie — COMMENTED** [review]
I think you included something with luajit-launcher by accident.

**Comment by jperon** [comment]
I had thought about it the commit just before… :)
