### PR TITLE
Some more Kobo tweaks

### LINKED ISSUE #8748: Strange image artifact
KOReader version: 2022.01-57 
Device: Kobo Sage (same thing on Forma and Libra 2)
#### Issue
Strange artifact in picture.
#### Steps to reproduce
If picture has some gray level it appears some strange artifact on the picture
the picture with KOREADER is the image opened with Koreader
Koreader
The picture with kobo is the same file but opened with the standard reader of Kobo
Lettore Kobo

I'm missing some setting ?
Thanks in advance for your help

### PR DESCRIPTION
**Pull request by NiLuJe**
* Mainly, the initial round of Libra 2 epdc race mitigations (no wait_for ioctls, no jump markers) (re #8414).
* Allow toggling SW dithering in PDF & co, and enforce SW dithering in PicDocument, achieving feature-parity with devices w/ HW dithering support (fix #8748).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8775)

### CODE REVIEW

File: frontend/document/document.lua [hunk 1]
```diff
@@ -495,11 +495,21 @@ Draw page content to blitbuffer.
...
 function Document:drawPage(target, x, y, rect, pageno, zoom, rotation, gamma, render_mode)
     local tile = self:renderPage(pageno, rect, zoom, rotation, gamma, render_mode)
-    target:blitFrom(tile.bb,
-        x, y,
-        rect.x - tile.excerpt.x,
-        rect.y - tile.excerpt.y,
-        rect.w, rect.h)
+    -- Enable SW dithering if requested (only available in koptoptions)
+    -- Much Like ReaderView, also enforce SW dithering in PicDocument if the device can't do HW dithering...
+    if (self.is_pic and CanvasContext:hasEinkScreen() and not CanvasContext:canHWDither() and CanvasContext.fb_bpp == 8) or (self.configurable.sw_dithering and self.configurable.sw_dithering == 1) then
```
Comment (poire-z) [inline frontend/document/document.lua:500]: This record breaking 202 chars long line deserves to be contemplated more easily, and so shown on more than one line :)

File: frontend/ui/data/onetime_migration.lua [hunk 2]
```diff
@@ -355,5 +355,16 @@ if last_migration_date < 20220116 then
...
 
+-- Disable the jump marker on the Libra 2, to avoid the worst of epdc race issues...
+-- c.f., https://github.com/koreader/koreader/issues/8414
+if last_migration_date < 20220205 then
+    logger.info("Performing one-time migration for 20220205")
+
+    local Device = require("device")
+    if Device:isKobo() and Device.model == "Kobo_io" then
+        G_reader_settings:makeFalse("followed_link_marker")
+    end
```
Comment (poire-z) [inline frontend/ui/data/onetime_migration.lua:366]: Is this worth an entry in onetime_migration.lua - assuming one day, we might solve the issue, and we'll have to add as much to remove that setting. (Or we can just replace the date, and makeFalse with delSetting?)
Can't we stick this in kobo/device.lua ? (Although the day we don't need it, we'll have to revert it in onetime_migration....)
Well, ok, just sharing these passing thoughts :)

**Review by poire-z — APPROVED** [review]

**Review by Frenzie — APPROVED** [review]

File: frontend/document/document.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/document/document.lua:500]: Heh, it did not feel as long as that over here ;p.

The curse of giant widescreens, I guess ;p.

File: frontend/ui/data/onetime_migration.lua (hunk 2 above)
Comment (NiLuJe) [reply frontend/ui/data/onetime_migration.lua:366]: Yeah, I'm happier with a couple entries in here that fiddling with it in Device, where it would feel clunkier.

**Comment by NiLuJe** [comment]
Another though: the final commit removed the possibility of having both a "HW Dithering" *and* "SW Dithering* toggle, so, should I just rename them *both* to "Dithering*?

**Comment by NiLuJe** [comment]
Switched tacks with the latest commit, to make the runtime checks simpler.

More boilerplate code, though ^^.

File: frontend/apps/reader/modules/readerview.lua [hunk 3]
```diff
@@ -164,7 +164,7 @@ function ReaderView:paintTo(bb, x, y)
     end
 
     -- draw page content
-    if self.ui.document.info.has_pages then
+    if self.document.info.has_pages then
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerview.lua:167]: The new trend is to replace `if self.ui.document.info.has_pages` with `if self.ui.paging` (and `if not...` with `if self.ui.rolling`.
