### PR TITLE
Workaround luxl's issue with self-closing tags once and for all

### LINKED ISSUE #6993: OPDS Browser Incorrectly Handling Some Formats
* KOReader version: v2020.11-57-g222e752
* Device: Kindle Paperwhite 3

#### Issue
When opening some submenus on a amusewiki OPDS servers, only the first entry of each page is displayed.

#### Steps to reproduce

1. Add the following OPDS server entry to your catalog: https://staging.amusewiki.org/opds
2. Open the server.
3. Select Topics or Authors
4. Observe the entries and compare to the OPDS files from the server.

### PR DESCRIPTION
**Pull request by NiLuJe**
By basically fixing *all* of them with a Lua pattern, instead of discovering new ones every few weeks ;).

Fix #6993

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6994)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Double-checked that this didn't regress on my various Calibre testcases from #6902, and it deals with #6993's `<content/>` tags.

File: frontend/ui/opdsparser.lua [hunk 1]
```diff
@@ -78,16 +78,11 @@ function OPDSParser:parse(text)
     text = text:gsub('<content type="xhtml">.-</content>', '')
     -- luxl doesn't handle XML comments, so strip them
     text = text:gsub("<!%-%-.-%-%->", "")
-    -- luxl prefers <br />, the other two forms are valid in HTML, but will kick luxl's ass
+    -- luxl is also particular about the syntax for self-closing, empty & orphaned tags...
+    text = text:gsub("<(%a+)/>", "<%1 />")
```
Comment (Frenzie) [inline frontend/ui/opdsparser.lua:82]: Characters like `=`, `'` and `"` count as letters? This can be things like ``.

**Comment by NiLuJe** [comment]
Quick question: tag names are supposed to be lowercase, right?

File: frontend/ui/opdsparser.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/opdsparser.lua:82]: I sure hope not, I'm blindly assuming it's basically `[a-Z]` ^^.

**Comment by Frenzie** [comment]
> Quick question: tag names are supposed to be lowercase, right?

If you mean XHTML tag names, theoretically yes. In XML `<STRONG>` is a different element than `<strong>`. In practice, who knows? ;-) In any case `<STRONG>` is well-formed XML, even if it's meaningless XHTML.

File: frontend/ui/opdsparser.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/ui/opdsparser.lua]: Well, then there are a lot of self-closing tags that'll still close issues, surely? ;-) But it's more efficient than manually adding the next `<hr/>`, yes.

**Comment by NiLuJe** [comment]
Oh, well, the rest of the mangling only deals with lowercase anyway, so, at least this way it's consistent with the rest ;p.

File: frontend/ui/opdsparser.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/opdsparser.lua]:
```
> foo="<blah/>" 
> print(foo:gsub("<(%l+)/>", "<%1 />"))
<blah />        1
> foo='<img src="wheee"/>'
> print(foo:gsub("<(%l+)/>", "<%1 />"))
<img src="wheee"/>      0
```

IIRC, as long as there are attributes, luxl is fine with the space-less `/>`, so this ought to do ;).

Comment (Frenzie) [reply frontend/ui/opdsparser.lua]: > as long as there are attributes, luxl is fine with the space-less 

Well, all right then. O_o

**Comment by NiLuJe** [comment]
> (Double-checked that this didn't regress on my various Calibre testcases from #6902, and it deals with #6993's `<content/>` tags.)

Hell, my Calibre stuff even works without scrapping the whole `content` block now, whee!

(In case someone ever wants to make something out of what's in there one day ^^).
