### PR TITLE
ReaderHandMade: fix handmade hidden flow starting from page 1

### LINKED ISSUE #13102: "Go to page" only supports absolute page numbers
* KOReader version: 2024.11
* Device: KOBO Reader

#### Issue

When in "Go to page" I select a number in the main flow, I get a page with that absolute number.

#### Steps to reproduce

1. Take an ebook and make the first, say, 10 pages a hidden flow.
2. Select "Go to page"
3. In the menu, choose as new page number "[5]".
4. KOReader will select the page with the absolute number 5, not a page in the main flow.

### PR DESCRIPTION
**Pull request by hius07**
- Closes #13102

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14502)

### CODE REVIEW

File: frontend/apps/reader/modules/readerhandmade.lua [hunk 1]
```diff
@@ -643,23 +643,17 @@ function ReaderHandMade:updateDocFlows()
...
-    for i, flow in ipairs(flows) do
-        if not prev_flow or prev_flow[1] + prev_flow[2] < flow[1] then
-            if not first_linear_page and flow[1] > 1 then
-                first_linear_page = prev_flow and prev_flow[1] + prev_flow[2] or 1
-            end
+    local first_linear_page = 1
+    local last_linear_page = nb_pages
+    if #flows > 0 then
+        local flow = flows[1]
+        if flow[1] == 1 then -- book first page is in a hidden flow
```
Comment (Commodore64user) [inline frontend/apps/reader/modules/readerhandmade.lua:650]: Shouldn’t this be: “the book’s first page is in a hidden flow”?

**Review by poire-z — APPROVED** [review]
No longer familiar with my code about fist/last_linear_page , and hard to grasp.
You code reads fine and simpler, so I guess it's ok. Anyway, trusting you.

File: frontend/apps/reader/modules/readerhandmade.lua (hunk 1 above)
Comment (poire-z) [reply frontend/apps/reader/modules/readerhandmade.lua:650]: I might also have written it like this in native american's English :) but if this reads better, why not.

Comment (Frenzie) [reply frontend/apps/reader/modules/readerhandmade.lua:650]: > Shouldn’t this be: “the book’s first page is in a hidden flow”?

It should probably be "the first page of the book," if you're nitpicking. ;-)

But instead I'd just drop the "book."

(No need; I'm not nitpicking here.)
