### PR TITLE
Fullscreen refactor

### LINKED ISSUE #9235: Touchmenu is not resized while on the foreground.
#### Issue

Touchmenu is not resized to new screen size.

#### Steps to reproduce

On desktop: resize a window with touchmenu opened.
On android: toggle rotation between portrait and landscape modes with touchmenu opened.

#### More info:

I've been aware of the issue for a long time but never bothered me enough to open a ticket. Now I want to refactor the fullscreen behaviour on desktop/android and found it a bit nastier.

Any hint on why it happens is very welcome. Maybe we lack an event that tells the touch menu instance to redraw itself, like both the reader and the filemanager do?

#### Gif:
Peek 2022-06-19 23-29

### PR DESCRIPTION
**Pull request by pazos**
* Add generic fullscreen device methods
* Migrate android to generic methods and rename/label accordly
* Add support for toggling fullscreen on SDL desktop platforms
* Add fullscreen toggle to the dispatcher and map it to F11.
* Hide touchmenu when resizing

Requires https://github.com/koreader/koreader-base/pull/1492
Fixes #9235

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9237)

### CODE REVIEW

**Comment by pazos** [comment]
> VPlus?

Yup. https://github.com/koreader/koreader/blob/master/frontend/device/sdl/event_map_sdl2.lua#L60

**Comment by Frenzie** [comment]
That looks like a trick to test some Kindle shenanigans. I don't like the idea of entrenching such a confusing name outside of that specific context given that it doesn't seem to be yet.

I'd propose to simply name it F11, possibly with VPlus commented out underneath.

I'm not 100% happy with the way event maps work regardless, but these aspects in the SDL event map are clearly quite tailored to the original concept of it being a Kindle emulator to help with development.

**Comment by pazos** [comment]
@Frenzie: it isn't too old. From https://github.com/koreader/koreader/pull/7037

F1 and F2 are already mapped to "Menu" and "Power" respectively, which is kind of non-generic (F1 is used mostly for in-app help and F2 is left unhandled by common apps).

Shall I remove those mappings and rename all function keys to "Fn"?

**Comment by Frenzie** [comment]
> it isn't too old. From https://github.com/koreader/koreader/pull/7037

It is, the prior situation just didn't include the rest of F*n* (other than F4 which I added years ago for Alt+F4). ;-)

> Shall I remove those mappings and rename all function keys to "Fn"?

Off the cuff I'm in favor of that, but that'd stray outside of the confines of this PR. I can easily see there being a lot of discussion and suggestions that'd needlessly delay what's already as good as done.

File: frontend/device/input.lua [hunk 1]
```diff
@@ -528,6 +528,12 @@ function Input:handleKeyBoardEv(ev)
         end
     end
 
+    -- F11 is used on Linux to toggle fullscreen
+    if self:isEvKeyPress(ev) and keycode == "VPlus" and jit.os == "Linux" then
```
Comment (Frenzie) [inline frontend/device/input.lua:532]: This should be something like self.device:isDesktop() I believe? It could be OSX, it could (more theoretically) be Windows, etc.

Comment (pazos) [reply frontend/device/input.lua:532]: IIRC there's already a key sequence that does the native fullscreen switch on mac. It shouldn't hurt to map it to F11 cause function keys on mac by default are used for mac stuff things. Anyways I think it is handy to have it available on the emulator too, which is not desktop.

So maybe

`if self:evKeyPress(ev) and keycode = "F11" and not self:device:isAlwaysFullscreen()`

? I don't know. I'm open to recommendations :)

Comment (Frenzie) [reply frontend/device/input.lua:532]: > IIRC there's already a key sequence that does the native fullscreen switch on mac

That's Alt+F11 in my Xfce (which is default); my KWin doesn't seem to have any such binding by default, but presumably all WMs offer it.

> So maybe

Yes, that makes sense to me.

**Comment by pazos** [comment]
@Frenzie: it seems that Google fixed the ICS emulator. I can test again :)

Screenshot_20220623_230435

File: frontend/device/input.lua (hunk 1 above)
Comment (pazos) [reply frontend/device/input.lua:532]: > That's Alt+F11 in my Xfce

On Gnome that's F11 but Alt+F11 also works for me.

**Comment by Frenzie** [comment]
Amazing! Wonders never cease. :-)

**Comment by pazos** [comment]
@NiLuJe: is it safe to bump base to https://github.com/koreader/koreader-base/tree/e5b008dfd2f854463b45d6ae9e6b2a8c9f902412?

Bumping FBInk & KoboUSBMS?

**Comment by NiLuJe** [comment]
I think I did that already?

**Comment by pazos** [comment]
And here's the main usage of the feature for me: toggling fullscreen with a gesture:

https://user-images.githubusercontent.com/975883/175540182-0b761123-aeca-4e6e-b618-f6245afcf5d4.mp4

I don't know why it glitches in chromeOS. It works fine on plain linux.

**Review by Frenzie — APPROVED** [review]
Looks decent

**Comment by pazos** [comment]
> I think I did that already?

Yup. Sorry. I've got my local branches messed up (or my brain, I dunno :p)
