### PR TITLE
ReaderHighlight: don't try to write page bookmarks into PDF

### LINKED ISSUE #15078: Crashes when saving pdf notes
### Before submitting

- [x] Reproduced the issue with external plugins and user-patches disabled.
- [x] Tested on the latest nightly build ([more information](https://github.com/koreader/koreader/issues/11068)).
- [x] Searched existing issues for similar reports.

### Device

Android

### KOReader version

v2025.10

### Model and firmware version

android v12

### Issue description

Saving a note in a PDF bookmark causes the app to crash.

KOReader v1025.10

The same issue occurs on KOBO Aura One and Android v12.

### Regression

Yes

### Last working version

koreader-android-arm64-v2025.10.apk

### Steps to reproduce

1. Open PDF file
2. Menu Bookmarks
3. add note
4. [Save] button
5. Crash

### Log

```shell
--------- beginning of system
03-06 21:09:36.706 I/ViewRootImpl(22845): ViewRoot's Touch Event : ACTION_DOWN
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hius07**
- Closes #15078

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/15097)

### CODE REVIEW

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -2259,7 +2259,7 @@ function ReaderHighlight:saveHighlight(extend_to_sentence)
 end
 
 function ReaderHighlight:writePdfAnnotation(action, item, content)
-    if self.ui.rolling or not self.highlight_write_into_pdf then
+    if not (self.document.is_pdf and self.highlight_write_into_pdf and item.drawer) then
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua:2262]: Is item always defined?

Comment (hius07) [reply frontend/apps/reader/modules/readerhighlight.lua:2262]: It is, an existing annotation.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:2262]: Might be more readable if you had 2 `if`s ?
```
if self.ui.rolling then return end
if [the paging/pdf conditions] then return end
```

Comment (hius07) [reply frontend/apps/reader/modules/readerhighlight.lua:2262]: I think `is_pdf` is more informative here than rolling/paging.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:2262]: ok.
