### PR TITLE
Screensaver: skip showing without UI instance

### LINKED ISSUE #14558: KOReader crashes after exiting with device shutdown
### Device

Pocketbook

### KOReader version

v2025.08-145-g340732f03_2025-10-31

### Model and firmware version

Pocketbook PB 626 (U626.5.20.1157)

### Issue description

KOReader crashes after exiting with option device shutdown

### Steps to reproduce

1. Start KOReader
2. Exit KOReader from menu with option device shutdown

### Log
[crash_shutdown.log](https://github.com/user-attachments/files/23292218/crash_shutdown.log

crash.log includes 2 crashes with attempting to exit with option "device shutdown" and last log is only exit KOReader which behaves normal.

### Additional information

11/02/25-11:37:54 DEBUG Tearing down FileManager table: 0x43534160 
./luajit: frontend/ui/screensaver.lua:415: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/ui/screensaver.lua:415: in function 'setup'
	frontend/ui/uimanager.lua:82: in function 'action'
	frontend/ui/uimanager.lua:1001: in function '_checkTasks'
	frontend/ui/uimanager.lua:1447: in function 'handleInput'
	frontend/ui/uimanager.lua:1567: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x00013ee1
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 11/02/25 @ 11:37:55)
Attempting to restart KOReader . . .
!!!!

### PR DESCRIPTION
**Pull request by hius07**
Screensaver extensively uses the UI instance (Reader or FM) and cannot be shown without it.
This PR safeguards that.
- Closes #14558

Unfortunately, without the device, I cannot trace the source of calling the Screensaver in the above issue that is done **after** closing the FM.
On "PowerOff", the screensaver is setup and shown **before** the UI instance is closed.
https://github.com/koreader/koreader/blob/8726233277a86575c3139b7bcb1ce735361dafc9/frontend/ui/uimanager.lua#L76-L83
Respective part of the crash.log:
```
11/02/25-11:37:54 INFO  Powering off the device... 
11/02/25-11:37:54 DEBUG close widget: table: 0x437831d0 
11/02/25-11:37:54 DEBUG close widget: filemanager 
11/02/25-11:37:54 DEBUG CoverMenu:onCloseWidget: terminating jobs if needed 
11/02/25-11:37:54 DEBUG close filemanager 
11/02/25-11:37:54 DEBUG close widget: table: 0x43534160 
11/02/25-11:37:54 DEBUG AutoStandby:onCloseWidget() instance= table: 0x43e430b8 
11/02/25-11:37:54 DEBUG Tearing down FileManager table: 0x43534160 
./luajit: frontend/ui/screensaver.lua:415: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/ui/screensaver.lua:415: in function 'setup'
	frontend/ui/uimanager.lua:82: in function 'action'
	frontend/ui/uimanager.lua:1001: in function '_checkTasks'
	frontend/ui/uimanager.lua:1447: in function 'handleInput'
	frontend/ui/uimanager.lua:1567: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x00013ee1
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14561)

### CODE REVIEW

File: frontend/ui/screensaver.lua [hunk 1]
```diff
@@ -332,6 +332,12 @@ function Screensaver:withBackground()
 end
 
 function Screensaver:setup(event, event_message)
+    self.ui = require("apps/reader/readerui").instance or require("apps/filemanager/filemanager").instance
+    if not self.ui then
+        logger.dbg("Screensaver called without UI instance, skipped")
```
Comment (Frenzie) [inline frontend/ui/screensaver.lua]: warning surely :-)
