### PR TITLE
[android]: misc fixes & enhacements

### LINKED ISSUE #4471: [Android] ABI and API requirements
We ship builds for two android ABIs: armeabi-v7a and x86.
We target code for a minimum API of 9 (2.3)

Most devices running on API 9 (including the emulator) are using an older ABI (armeabi) so the program will crash in those devices (because luajit is built for an incompatible arch)

We have two solutions here:

- Add a target for android legacy devices (armeabi w/ minimum API 9).
- Bump requirements to API 14 (Android 4.0) where 99'9% of devices out there are using a compatible ABI.

TBH, I see no real gain in supporting old Android 2.3 devices and probably nobody is using them (we would see more issues here). I would suggest setting KOReader requirements to API14 and deprecatting launcher methods used in SDK < 11.

Skipping these older devices would allow us to refactor a bunch of old luajit-launcher code:

* Fullscreen/Viewport switching (just show/hide the statusbar when API > 16)
* Clipboard interface
* ...

### PR DESCRIPTION
**Pull request by pazos**
requires https://github.com/koreader/android-luajit-launcher/pull/91. 
Bumping luajit-launcher fixes #4471 

- use product as device model
- print android version + api at launch.
- exit the application properly. (at least better than Generic.exit(self))
- fix fullscreen switching (and disable it on newer android versions) 

```
I/KOReader( 4447): Android 4.0.4 - Ice Cream Sandwich (API 15)
I/KOReader( 4447):  initializing for device sdk_x86
I/KOReader( 4447):  framebuffer resolution: {
I/KOReader( 4447):     ["h"] = 800,
I/KOReader( 4447):     ["w"] = 480
I/KOReader( 4447): }

```

### CODE REVIEW

File: frontend/device/android/device.lua [hunk 1]
```diff
@@ -8,7 +8,7 @@ local function yes() return true end
 local function no() return false end
 
 local Device = Generic:new{
-    model = "Android",
+    model = "Android_" .. android.getProduct(),
```
Comment (Frenzie) [inline frontend/device/android/device.lua]: I've been meaning to add something like that. :-)

File: frontend/ui/elements/screen_android.lua [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+    if is_fullscreen and Screen.viewport then
+        Input:registerEventAdjustHook(
+            Input.adjustTouchTranslate,
+            {x = 0 - Screen.viewport.x, y = 0 - Screen.viewport.y})
+    end
+end
+
+local function flipWakelock()
+    is_wakelock = not G_reader_settings:isTrue("disable_android_wakelock")
```
Comment (Frenzie) [inline frontend/ui/elements/screen_android.lua]: What's the intended scope for this variable? Since it looks to be used only here, it should be:

```suggestion
    local is_wakelock = not G_reader_settings:isTrue("disable_android_wakelock")
```

**Comment by pazos** [comment]
Now with pretty logs:

```
I/KOReader( 3809): Android Ice Cream Sandwich (API 15)
I/KOReader( 3809):  initializing for device sdk_x86
I/KOReader( 3809):  framebuffer resolution: {
I/KOReader( 3809):     ["h"] = 800,
I/KOReader( 3809):     ["w"] = 480
I/KOReader( 3809): }
```

File: frontend/device/android/device.lua (hunk 1 above)
Comment (pazos) [reply frontend/device/android/device.lua]: I will leave model = android.getProduct()

Hopefully some day we will need to differenciate between models that have full e-ink support.

**Comment by pazos** [comment]
We can add as many android.os.Build strings as we want. Sadly the "pretty" codename is not one of those.

What kind of string do we need? "Android Pie 9.0 (API x) ?.  Release versions can be determined by codename + api. It is possible to determine the codename from release version + api or any other combo.

**Comment by Frenzie** [comment]
Actually that's `9`, not `9.0`. (They wouldn't, you say? Not after a decade, you say? Oh, but they did! They did…)

But yes, that string looks good to me. We can pull the 8.0/9 from android.os.Build then.

**Comment by pazos** [comment]
@Frenzie: ready to rock

File: frontend/gettext.lua [hunk 3]
```diff
@@ -51,7 +51,7 @@ function GetText_mt.__index.changeLang(new_lang)
     local po = io.open(file, "r")
 
     if not po then
-        logger.warn("cannot open translation file:", file)
+        logger.dbg("cannot open translation file:", file)
```
[the remark this answers is not in the document]
Comment (pazos) [reply frontend/gettext.lua]: This string is displayed early at start, just after device init. On some crashes this is the last string you'll get on the logs, not just on Android.  I'm not sure if this is a matter of personal preference or what. Anyways, it can be left as a warning...

[the remark this answers is not in the document]
Comment (Frenzie) [reply frontend/gettext.lua]: My comment isn't about the change itself, but about using `git blame` in the future. ;-)
