### PR TITLE
android: fix ko paths when primary storage is a SD card

### LINKED ISSUE #5487: Unable to launch KO if external sdcard is used as main partition.
* KOReader version: all
* Platform: android

#### Issue

Unable to launch KO if external sdcard is used as main partition. 

#### Steps to reproduce
On android settings use the sdcard as the primary storage. System will reboot or not based on vendor. Launch KO. 

It will start on /sdcard which is now empty, because it is hardcoded on llapp_main.lua.

We're in a good position to fix this because the new path is already recognized:

```adb logcat
10-13 00:48:55.251  8588  8588 V KOReader: Application info {
10-13 00:48:55.251  8588  8588 V KOReader:   Flags: user.
10-13 00:48:55.251  8588  8588 V KOReader:   Paths {
10-13 00:48:55.251  8588  8588 V KOReader:     Assets: /data/user/0/org.koreader.launcher/files
10-13 00:48:55.251  8588  8588 V KOReader:     Library: /data/app/org.koreader.launcher-xM0Q166albC8kw0pQAKtYA==/lib/arm
10-13 00:48:55.251  8588  8588 V KOReader:     Storage: /storage/3837-3661
```

So we need to use reported storage as an argument to start KOReader instead of "/sdcard".

### PR DESCRIPTION
**Pull request by pazos**
Requires https://github.com/koreader/android-luajit-launcher/pull/195

Fixes #5487

~~to-do:~~
Removed: 
https://github.com/koreader/koreader/blob/5209493ba881f25e94cb4682d92416d515b2fb7c/defaults.lua#L238

### CODE REVIEW

**Comment by pazos** [comment]
damn, not sure how to fix those unit test

**Comment by Frenzie** [comment]
Because you removed a line, that means that everything following will be off by one. So it's as simple as changing 112 to 111.

https://github.com/koreader/koreader/blob/40ba01fd72193d3dbc355f69405b3164d61126c5/spec/unit/defaults_spec.lua#L26

This one should probably be 56:

https://github.com/koreader/koreader/blob/40ba01fd72193d3dbc355f69405b3164d61126c5/spec/unit/defaults_spec.lua#L103-L104

That default file/the way the unit test for it is written is slightly annoying. ;-)

File: frontend/ui/elements/font_settings.lua [hunk 1]
```diff
@@ -54,6 +54,21 @@ function FontSettings:getPath()
     return getUserDir()
 end
 
+function FontSettings:getAndroidPath()
+    local A, android = pcall(require, "android")
+    local system_path = "/system/fonts"
+    local user_path = "/koreader/fonts"
+    local legacy_font_dirs = system_path..";".."/sdcard"..user_path
+
+    if not A then return legacy_font_dirs end
```
Comment (Frenzie) [inline frontend/ui/elements/font_settings.lua]: Bit confused by this? For easier testing (in the emulator)?

Comment (Frenzie) [reply frontend/ui/elements/font_settings.lua]: That is, /system/fonts or /sdcard/koreader/fonts won't be very useful on non-Android platforms regardless.

Comment (pazos) [reply frontend/ui/elements/font_settings.lua]: yeah, more than anything a future proof thingy. I guess nobody will want to call FontSettings:getAndroidPath() outside of android. But if someone tries that it will receive the "legacy" android path.

Not sure if this is a good idea but is safer in the case we cannot load the android module.

Comment (Frenzie) [reply frontend/ui/elements/font_settings.lua]: Why not just nil or an empty string?
