### PR TITLE
util.findFiles: Don't die on broken symlinks

### LINKED ISSUE #7818: KOReader crashes on first run on Linux (because of symlink in system font directory)
* KOReader version: v2021.05
* Device: x86_64 / Linux / KDE Desktop Environment

#### Issue
- KOReader crashes on first run after installation from .deb package or when running as AppImage. 
- It creates config directory hierarchy (with all sub directories empty), then dies. 
- My guess from crash log: KOReader doesn't like some font file in my .fonts directory (I have around 300 fonts installed).

I checked my font directory and all fonts have Latin-1 characters as names, no funny letters in name. There are some PDF and TXT files for font licences. Maybe these confuse KOReader.

#### Steps to reproduce
Install .deb or run AppImage directly

<details>
  <summary>Terminal output</summary>

```
---------------------------------------------
launching...
_  _____  ____                _
| |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
| ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
| . \ |_| |  _ <  __/ (_| | (_| |  __/ |
|_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

It's a scroll... It's a codex... It's KOReader!

[*] Current time: 06/08/21-07:43:33
[*] Version: v2021.05

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
06/08/21-07:43:33 INFO  platform thirdparty apps
-> Goldendict (goldendict), role: dict, available: false

Starting SDL in /tmp/.mount_koreadfagE13/
ffi.load: libs/liblodepng.so
06/08/21-07:43:33 WARN  ./ffi/SDL2_0.lua:437: /tmp/.mount_koreadfagE13/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
06/08/21-07:43:33 INFO  initializing for device AppImage
06/08/21-07:43:33 INFO  framebuffer resolution: {
["w"] = 600,
["h"] = 800,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
06/08/21-07:43:33 INFO  Performing one-time migration for 20191129
06/08/21-07:43:33 INFO  Performing one-time migration for 20200421
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
06/08/21-07:43:33 INFO  /home/user/.config/koreader/cache/fontlist/fontinfo.dat [string "/home/user/.config/koreader/cache/fontlist/fon..."]:1: unexpected symbol near '/' initializing it
./luajit: frontend/util.lua:703: attempt to index local 'attr' (a nil value)
stack traceback:
frontend/util.lua:703: in function 'scan'
frontend/util.lua:712: in function 'findFiles'
frontend/fontlist.lua:141: in function '_readList'
frontend/fontlist.lua:187: in function 'getFontList'
frontend/ui/font.lua:262: in function 'getFace'
frontend/ui/widget/textboxwidget.lua:87: in main chunk
[C]: in function 'require'
frontend/ui/widget/scrolltextwidget.lua:14: in main chunk
[C]: in function 'require'
frontend/ui/widget/infomessage.lua:38: in main chunk
[C]: in function 'require'
frontend/apps/reader/modules/readertypography.lua:4: in main chunk
[C]: in function 'require'
frontend/ui/data/onetime_migration.lua:35: in main chunk
[C]: in function 'require'
./reader.lua:180: in main chunk
[C]: at 0x00405150
```
</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #7818

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7829)

### CODE REVIEW

File: frontend/util.lua [hunk 1]
```diff
@@ -699,7 +699,8 @@ function util.findFiles(dir, cb)
         if not ok then return end
         for f in iter, dir_obj do
             local path = current.."/"..f
-            local attr = lfs.attributes(path)
+            -- lfs can return nil here, as it will follow symlinks!
+            local attr = lfs.attributes(path) or {}
```
Comment (Frenzie) [inline frontend/util.lua:703]: Does this problem apply elsewhere?

**Review by Frenzie — APPROVED** [review]

File: frontend/util.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/util.lua:703]: At a quick glance, most lfs callers ask for a specific attribute, meaning there's no "trying to index a table that doesn't exist" issue down the line. We can't do that here because the callback expects the full attributes table.

The few that do something similar either do this or have nil guards in place.
