### PR TITLE
[MultiInputDialog] split password field and checkbox

### LINKED ISSUE #15165: Can't type into password text box (Linux)
### Before submitting

- [x] Reproduced the issue with external plugins and user-patches disabled.
- [x] Searched existing issues for similar reports.
- [ ] Tested on the latest nightly build ([more information](/koreader/koreader/issues/11068)).

### Device

Linux (Flatpak)

### KOReader version

2026.03

### Model and firmware version

_No response_

### Issue description

Just Can't type into password box for KOReader OPDS catalog default plugin. Tried flathub version and tar.xz version as well. Downloaded 2025.10 for troubleshoot and all worked as expected.

### Regression

Yes

### Last working version

2025.10

### Steps to reproduce

1. Click on Mangnifier
2. Click on OPDS catalog
3. Sandwich menu
4. Add catalog
5. try to add some text on password textbox. wont work

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Commodore64user**
### bug fix

* Refactored the password toggle logic in `InputText`: the "Show password" checkbox is now initialised in a dedicated `initPasswordToggle` method, and the toggle widget is managed separately from the main input field, ensuring cleaner code and more predictable behaviour. 
* Added a `getPasswordToggleWidget` method to `InputText`, allowing dialogs to retrieve and position the password toggle widget as needed.
* Updated `InputDialog` and `MultiInputDialog` to insert the password toggle widget (when present) into their layouts, ensuring that it appears in the correct position and is included in the focus order. 
* Improved focus handling for password fields by using the new `getFocusableWidgets` method, so both the input field and the toggle are accessible via keyboard or D-Pad navigation. 

### related issues

* closes #15165

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/15234)

### CODE REVIEW

File: frontend/ui/widget/inputtext.lua [hunk 1]
```diff
@@ -427,8 +417,40 @@ function InputText:init()
...
+function InputText:getFocusableWidgets()
+    if self._password_toggle then
+        return { self, self._password_toggle }
+    end
+    return { self }
+end
+
 -- This will be called when we add or del chars, as we need to recreate
--- the text widget to have the new text splittted into possibly different
+-- the text widget to have the new text split into possibly different
```
Comment (Frenzie) [inline frontend/ui/widget/inputtext.lua:450]: But the poetry of the three Ts makes up for the fake past tense. ;p

File: frontend/ui/widget/inputdialog.lua [hunk 2]
```diff
@@ -430,6 +434,24 @@ function InputDialog:init()
...
+                w = self.width,
+                h = self._password_toggle_widget:getSize().h,
+            },
+            self._password_toggle_widget,
+        }
+        -- Keep password toggle between input field and the post-input spacer.
+        local insert_idx = #self.vgroup + 1
+        for i, widget in ipairs(self.vgroup) do
+            if widget == vspan_after_input_text then
+                insert_idx = i
```
Comment (hius07) [inline frontend/ui/widget/inputdialog.lua]: Looks like insert_idx is 4.

File: frontend/ui/widget/multiinputdialog.lua [hunk 3]
```diff
@@ -158,10 +159,12 @@ function MultiInputDialog:init()
             enter_callback = self.enter_callback,
         }
         table.insert(self.input_fields, input_field_tmp)
-        --- @fixme: This is semi-broken when text_type is password, as we actually end up with the checkbox instead of the field,
-        --          and a "Press" on the checkbox will actually focus the password field and *not* check the box.
-        -- addWidget may have added stuff below us, so make sure we insert above that...
-        table.insert(self.layout, i, { input_field_tmp })
+        local focus_widgets = input_field_tmp:getFocusableWidgets()
+        for _, focus_widget in ipairs(focus_widgets) do
```
Comment (hius07) [inline frontend/ui/widget/multiinputdialog.lua]: Can this be done within the same loop below?

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: mmm, I don't know let me try

File: frontend/ui/widget/inputdialog.lua (hunk 2 above)
Comment (Commodore64user) [reply frontend/ui/widget/inputdialog.lua]: so...

Comment (hius07) [reply frontend/ui/widget/inputdialog.lua]: So `table.insert(self.vgroup, 4, toggle_row)`

Comment (Commodore64user) [reply frontend/ui/widget/inputdialog.lua]: i didn't want to hardcode anything but whatever

File: frontend/ui/widget/inputtext.lua [hunk 4]
```diff
@@ -427,8 +417,40 @@ function InputText:init()
...
+    }
+end
+
+function InputText:getPasswordToggleWidget()
+    return self._password_toggle
+end
+
+function InputText:getFocusableWidgets()
+    if self._password_toggle then
+        return { self, self._password_toggle }
```
Comment (hius07) [inline frontend/ui/widget/inputtext.lua]: You can keep just this one line in the method, and remove the others.

**Comment by hius07** [comment]
Works fine in WSL.

**Review by hius07 — APPROVED** [review]
