### PR TITLE
avoid writting to read-only pdfs

### LINKED ISSUE #5881: koreader crash after turn autosave pdf on and close the pdf when pdf is in read-only storage
* KOReader version: v2020.02
* Device: Hisense A5

#### Issue
koreader crash after turn autosave pdf on and close the pdf when pdf is from android external sd card

#### Steps to reproduce
1. Open a pdf file from android external sd card
2. Turn the autosave pdf when close file option on
3. Highlight some text in pdf and then click file browser button to close the pdf file
4. Koreader crash at this moment. 
Maybe it is related to the write permission of Android external sd card. However, the highlights of pdf are auto-saved after 5 minutes when pdf is kept open.
Note: The path /storage/85CA-1D08 is an android external sd card.

##### `crash.log` (if applicable)
```
02-19 11:25:04.735  1299 16078 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity bnds=[10,1216][150,1356] (has extras)} from uid 10031
02-19 11:25:04.831  1299  1347 I ActivityManager: Start proc 14749:com.hmct.quickappsprovider/u0a30 for content provider com.hmct.quickappsprovider/.QuickAppsProvider
02-19 11:25:04.855  1299  1347 I ActivityManager: Start proc 14756:org.koreader.launcher/u0a154 for activity org.koreader.launcher/.MainActivity
02-19 11:25:05.035 14756 14756 I KOReader: Application started
02-19 11:25:05.035 14756 14756 I KOReader: Application info {
02-19 11:25:05.035 14756 14756 I KOReader:   VM heap: 192MB (normal)
02-19 11:25:05.035 14756 14756 I KOReader:   Flags: user, legacy storage.
02-19 11:25:05.035 14756 14756 I KOReader:   Paths {
02-19 11:25:05.035 14756 14756 I KOReader:     Assets: /data/user/0/org.koreader.launcher/files
02-19 11:25:05.035 14756 14756 I KOReader:     Library: /data/app/org.koreader.launcher-9OlifBctIMHPojjOxjj2pA==/lib/arm
02-19 11:25:05.035 14756 14756 I KOReader:     Storage: /storage/emulated/0
02-19 11:25:05.035 14756 14756 I KOReader:   }
02-19 11:25:05.035 14756 14756 I KOReader: }
02-19 11:25:05.073  1299 13270 W ActivityManager: getTaskSnapshot: taskId=1226 not found
02-19 11:25:05.234 14756 14783 I KOReader: Check file in asset module: koreader-v2020.02.zip
02-19 11:25:05.244 14756 14783 I KOReader: Skip installation for revision v2020.02
02-19 11:25:05.245  1299  1339 I ActivityManager: Displayed org.koreader.launcher/.MainActivity: +480ms
02-19 11:25:05.246 14756 14783 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
02-19 11:25:05.304 14756 14783 I KOReader: command chmod 755 ./sdcv returned 0
02-19 11:25:05.328 14756 14783 I KOReader: command chmod 755 ./tar returned 0
02-19 11:25:05.477 14756 14783 I KOReader: Android 9 - Pie (API 28) - flavor: rocks
02-19 11:25:05.527 14756 14783 I KOReader:  initializing for device hlte202n
02-19 11:25:05.528 14756 14783 I KOReader:  framebuffer resolution: {
02-19 11:25:05.528 14756 14783 I KOReader:     ["h"] = 1440,
02-19 11:25:05.528 14756 14783 I KOReader:     ["w"] = 720
02-19 11:25:05.528 14756 14783 I KOReader: }
02-19 11:25:06.061 14756 14783 I KOReader:  opening file /storage/85CA-1D08/webpage/work/五大世界级社交平台流量源，选哪个？.pdf
02-19 11:25:06.758 14756 14783 I KOReader:  Loading plugins from directory: plugins
02-19 11:25:06.776 14756 14783 I KOReader:  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
02-19 11:25:06.816 14756 14783 I KOReader:  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
02-19 11:25:06.824 14756 14783 I KOReader:  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
02-19 11:25:06.930 14756 14783 I KOReader:  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
02-19 11:25:06.941 14756 14783 I KOReader:  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
02-19 11:25:06.944 14756 14783 I KOReader:  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
02-19 11:25:06.944 14756 14783 I KOReader:  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
02-19 11:25:06.962 14756 14783 I KOReader:  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
02-19 11:25:06.962 14756 14783 I KOReader:  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
02-19 11:25:06.965 14756 14783 I KOReader:  RD loaded plugin statistics at plugins/statistics.koplugin
02-19 11:25:06.975 14756 14783 I KOReader:  setting zoom mode to contentwidth
02-19 11:25:17.973 14756 14783 I KOReader:  writing document to /storage/85CA-1D08/webpage/work/五大世界级社交平台流量源，选哪个？.pdf
02-19 11:25:17.974 14756 14783 E KOReader: [NativeThread]: failed to run script: ffi/mupdf.lua:67: could not write document: cannot open file '/storage/85CA-1D08/webpage/work/五大世界级社交平台流量源，选哪个？.pdf': Permission denied (2)
02-19 11:25:17.974 14756 14783 E KOReader: [NativeThread]: Stopping due to previous errors
02-19 11:25:18.142  1299  1520 I ActivityManager: Process org.koreader.launcher (pid 14756) has died: fore TOP 
02-19 11:25:18.205  1299  1379 W ActivityManager: setHasOverlayUi called on unknown pid: 14756
```

### LINKED ISSUE #5888: Koreader doesn't display codepoints of the chars 139 and 155 in dictionary.
Still checking the html-rendering of mupdf, I stumbled over another rendering problem. I think it is not a font problem nor a missing glyph problem.

Screenshot from 2020-02-20 21-32-44
Both on Linux desktop and Kobo H2O v.2020.02

However, on Goldendict on the Linux desktop it displays well:
Screenshot from 2020-02-20 21-35-07

The output from sdcv (after prettifying) is:
```html
[{"dict": "Duden 7.Aufl. 2011","word":"ab","definition":"\n<blockquote>
    <blockquote><sup>1&#8204;</sup><b><b>a</b></b><b>b</b><b> </b>
        <blockquote>&#139;Pr&#xE4;p. mit Dativ&#155; [mhd. ab(e), ahd. ab(a), verw. mit griech. ap&#xF3; = von, ab]: </blockquote><b>1.</b> (BES. KAUFMANNSSPR., VERKEHRSW.) von ... an, von ... weg: <i>[frei] ab Werk; </i> <i>ab [unserem] Lager; </i> <i>wir fliegen ab allen deutschen Flugh&#xE4;fen. </i> <b>2.</b> &#139;bei artikellosen Substantiven mit adj. Attribut gelegtl. auch mit Akk.&#155; (ZEITLICH) von ... an: <i>ab dem 35. Lebensjahr; </i> <i>Jugendliche ab 18 Jahren/(AUCH:) Jahre; </i> <i>ab kommendem/(AUCH:) kommenden Montag; </i> <i>ab Mai; </i> <i>ab 1990; </i> <i>ab heute [Nacht]; </i> <i>ab morgen wird gefastet. </i> <b>3.</b> &#139;bei artikellosen Substantiven mit adj. Attribut gelegtl. auch mit Akk.&#155; bei einer Reihenfolge, Rangfolge o.&#xA0;&#xC4;.; von ... an: <i>die Dienstgrade ab Unteroffizier; </i> <i>ab n&#xE4;chster/(AUCH:) n&#xE4;chste Ausgabe.</i>
    </blockquote>
</blockquote>\n<blockquote>
    <blockquote><sub> </sub><sup> </sup><sup>2&#8204;</sup><b><b>a</b></b><b>b</b><b> </b>&#139;Adv.&#155; [<span><b></b></span>&#xA0;<sup><span>1</span></sup>ab]: <b>1.</b> weg, fort, entfernt: <i>gleich hinter der Kreuzung links ab; </i> <i>nicht sehr weit ab vom Weg liegen; </i> <i>die H&#xFC;tte soll weit von jeder menschlichen Behausung ab sein; </i> <i>zwei Kilometer ab [von dieser Stelle]; </i> (VERKEHRSW.:) <i>Darmstadt ab 7:30; </i> <i>Bayrischer Bahnhof ab, ab Bayrischer Bahnhof; </i> <i>(oft in Aufforderungen:) los, ab ins Bett!; </i> <i>(als B&#xFC;hnenanweisung:) ab (geht ab, soll abgehen); </i> <sup>*</sup><b>ab trim</b><u>o</u><b>/tr&#xFC;m</b><u>o</u><b> </b>(LANDSCH.; weg, ab; verschwinde!; H.&#xA0;u.) <b>2.</b> <b>a)</b> herunter, hinunter, nieder (gew&#xF6;hnlich in milit&#xE4;r. Kommandos): <i>Gewehr ab!; </i> <i>Helm ab zum Gebet!; </i> <b>b)</b> losgel&#xF6;st, abgetrennt, abgegangen: <i>der Knopf wird bald ab sein; </i> <i>die Farbe ist fast ganz ab. </i> <b>3.</b> <sup>*</sup><b>ab und zu </b>(gelegentlich; von Zeit zu Zeit. VERALTEND; [in Bezug auf eine Bewegung] weg u. wieder herbei; aus u. ein: <i>die Bedienung ging ab und zu); </i> <sup>*</sup><b>ab und an </b>(BES. NORDD.; gelegentlich; von Zeit zu Zeit: <i>er kommt ab und an mal vorbei).</i> </blockquote>
</blockquote>"}]
```

I've changed them to &#8B; and &#9B and the displays remained the same. 

However, when I substituted them with their characters they did display.
```perl
s~&#139;~‹~sg;
s~&#155;~›~sg;
```
Screenshot from 2020-02-20 21-56-32

### PR DESCRIPTION
**Pull request by pazos**
Fixes #5881

Poor atempt to fix issues with read-only pdfs, when auto or manual save settings is triggered. I don't like it because it adds UI stuff to a document. Probably there are better ways of doing this without messing with InfoMessages in pdfdocument.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5889)

### CODE REVIEW

**Comment by poire-z** [comment]
(Wrong issue number in "Fixes #..." :)

**Comment by pazos** [comment]
Sorry, I linked the wrong issue (again) :man_facepalming:

**Comment by poire-z** [comment]
Or may be do that writable check in `PdfDocument:saveHighlight()`, cache the result there as `self.is_readonly` - just like `self.is_edited`, but before it - and return `false` before `self.is_edited`.
https://github.com/koreader/koreader/blob/69f4144dc187186a249580fde006676673e7833f/frontend/document/pdfdocument.lua#L174-L178

Then, get the return value there, and it is `false`: do the UI stuff here (and cache the fact that you did warn so it's done only once):
https://github.com/koreader/koreader/blob/69f4144dc187186a249580fde006676673e7833f/frontend/apps/reader/modules/readerhighlight.lua#L1169-L1172

**Comment by Frenzie** [comment]
Where's it called from? Perhaps it might make more logical sense there?

**Comment by pazos** [comment]
> Or may be do that writable check in PdfDocument:saveHighlight(), cache the result there as self.is_readonly - just like self.is_edited, but before it - and return false before self.is_edited.

Sounds good, but I would like to keep highlights on the "centralized" history file. Right now it seems that we're doing both:

- store highlights and anotations on history (will fallback to history/nameOfTheBook.mime.lua on RO storage)
- try to write settings on the pdf itself (which makes mupdf crash)

I don't know where the first thing happens but I would like to keep it as is, if that is possible.

**Comment by poire-z** [comment]
> Sounds good, but I would like to keep highlights on the "centralized" history file.

Sounds still good :)
```diff
function PdfDocument:saveHighlight(pageno, item)
    local suffix = util.getFileNameSuffix(self.file)
    if string.lower(suffix) ~= "pdf" then return end
+    if self.is_writable == nil then
+       -- do the writable check here
+       self.is_writable = true -- or false
+    end
+    if self.is_writable == false then
+        return false
+    end
    self.is_edited = true
    [...]
```

```diff
function ReaderHighlight:exportToDocument(page, item)
    logger.dbg("export highlight to document", item)
-    self.ui.document:saveHighlight(page, item)
+    local can_write = self.ui.document:saveHighlight(page, item)
+    if can_write == false and not self.warned_once then
+        self.warned_once = true
+        -- UI warn
+    end
end
```

And ReaderHighlight:saveHighlight() stays unmodified and will save the highlight in the metadata.lua or history/nameOfTheBook.mime.lua. It's just the `self:exportToDocument()` it does near the end that will not have done anything (and will not have set is_edited=true, so no attempt to write on close).
https://github.com/koreader/koreader/blob/69f4144dc187186a249580fde006676673e7833f/frontend/apps/reader/modules/readerhighlight.lua#L1112-L1148

**Comment by poire-z** [comment]
You might want to check for this `save_document` setting:
https://github.com/koreader/koreader/blob/7b1ae4e486b9a920c0553cd654adc08668265116/frontend/apps/reader/readerui.lua#L641-L652
so to not warn a used that has set it to "disable" (so users can use that option to also stop being bothered by this warning :)
(may be it could even be checked in ReaderHighlight:exportToDocument() so to return early and not even call `self.ui.document:saveHighlight()` if `save_document=="disable"`.)

File: frontend/document/pdfdocument.lua [hunk 1]
```diff
@@ -174,7 +174,15 @@ end
 function PdfDocument:saveHighlight(pageno, item)
     local suffix = util.getFileNameSuffix(self.file)
     if string.lower(suffix) ~= "pdf" then return end
-
+    if self.is_writable == nil then
+        local handle = io.open(self.file, 'r+b')
+        local writable = handle ~= nil
+        if handle then handle:close() end
+        self.is_writable = writable
```
Comment (poire-z) [inline frontend/document/pdfdocument.lua]: Save one line with :)
```lua
self.is_writable = handle ~= nil
if handle then handle:close() end
```

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 2]
```diff
@@ -1167,8 +1167,17 @@ end
...
 function ReaderHighlight:exportToDocument(page, item)
+    local setting = G_reader_settings:readSetting("save_document")
+    if setting == "disable" then return end
     logger.dbg("export highlight to document", item)
-    self.ui.document:saveHighlight(page, item)
+    local can_write = self.ui.document:saveHighlight(page, item)
+    if can_write == false and not self.warned_once then
+        self.warned_once = true
+        UIManager:show(InfoMessage:new{
+            text = _("Document is read only. Cannot write to it"),
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua]: May be something a bit more explicite, like "Document is read only. Your highlights will not be written into it." There's surely a better wording :) @Frenzie?

Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua]: Probably best to make it two lines. Something like this:
```
This document is set to read-only.
Highlights can't be saved into a read-only document.
```

Comment (pazos) [reply frontend/apps/reader/modules/readerhighlight.lua]: Well, I'm not good at english and no good at verbosity

```
Cannot write highlights: document is read only.
```
 ?

Or maybe with explicit implications:
```
Cannot write highlights: document is read only.
Hightlights won't be saved on this document.
If you want to edit the document itself please move it to a writable dir first.
```

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua]: Users may not even know highlights get written in the PDF itself.
And we want to assure them the thing they just highlighted will be highlighted next time, as it is saved in the metadata.lua.
So, may be something a bit less negative, and verbose:

> The highlights you'll be making on this document will be saved in the setting file, but won't be written in the PDF itself, as this PDF file is in a read-only location.
If you wish your highlights to be saved in the PDF file itself, just move it to a writable directory, so it can be updated.

Comment (pazos) [reply frontend/apps/reader/modules/readerhighlight.lua]: @poire-z the first statement is true, the second is not in this particular case.

metadata is saved to history/ because sidecar dir can't be created in RO. I don't know if metadata is ported when a user copies/moves documents within the program, but when doing it outside the user is expected to replace the file manually in order to keep highlights in place. Hence my "copy/move first", because that's actually easier to explain that "copy/move, open once, exit and copy metadata from history to sidecar".

I'm actually happy avoiding the crash. Any nits I could have on the string are just from user pov when facing with this message (probably android, reading a document from sdcard) and to avoid future bug reports related to this issue.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua]: So, just add a "first" :)
> If you wish your highlights to be saved in the PDF file itself, move this PDF file _first_ to a writable directory, so it can be rewritten.

and let the discovery of the technical steps involved to the user.
(I guess most will not care if we tell them they are saved anyway in the first sentence.)

Comment (pazos) [reply frontend/apps/reader/modules/readerhighlight.lua]: updated the PR to match your suggestion. I've skipped the PDF references by calling them "documents" but I'm aware that this should apply to pdf's only.

**Comment by poire-z** [comment]
(Just fixed a few bits.)
Any other comment on the wording @Frenzie ?

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 3]
```diff
@@ -1174,9 +1174,10 @@ function ReaderHighlight:exportToDocument(page, item)
     if can_write == false and not self.warned_once then
         self.warned_once = true
         UIManager:show(InfoMessage:new{
-            text = _([[The highlights you'll be making on this document will be saved in the setting file but won't be written in the document itself, as the file is in a read-only location.
+            text = _([[
+The highlights you'll be making on this document will be saved in the setting file but won't be written in the document itself, as the file is in a read-only location.
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua]: (bit more succinct)
```suggestion
Highlights in this document will be saved in the settings file, but they won't be written in the document itself because the file is in a read-only location.
```

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 4]
```diff
@@ -1174,9 +1174,10 @@ function ReaderHighlight:exportToDocument(page, item)
...
 
-If you wish your highlights to be saved in the document just move it first to a writable directory]]),
+If you wish your highlights to be saved in the document, just move it first to a writable directory.]]),
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua]: (grammar)
```suggestion
If you wish your highlights to be saved in the document, just move it to a writable directory first.]]),
```
