### PR TITLE
ReaderZooming: Fix defaults handling

### LINKED ISSUE #7461: Default zoom fit option not taken into account for CBZ, always fit the width
* KOReader version:v2021.03
* Device: PB740 Pocketbook inkpad 3 (Vivlio firmware) 

#### Issue
For CBZ files, the zoom is set by default to fit the width of the page even though it is supposed to be height or full
#### Steps to reproduce
I select zoom 4 and fit to full by default. Whenever I open a new CBZ file, it behaves as if it is set to fit the width by default, even though when I go to change the zoom option, I can see that my default is selected (i.e. zoom 4 and fit to full). I have to change the fit option and then put it back to full again for it to behave as expected.

### PR DESCRIPTION
**Pull request by NiLuJe**
It appears the fancy split settings from #6885 were not being honored at all.

Fix #7461, #7228, #7192

(Also, re-ensured "pagewidth" is actually the default zoom mode, "full" had sneaked in as the default state of the zoom type toggle).

Also, display human-readable values in the "Make as default" popup, instead of the raw, meaningless numerical setting.

Also, disable zoom options when reflow is enabled, and restore 'em properly when it's disabled.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7463)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Looks okay, no time to test.

**Comment by Galunid** [comment]
It should close https://github.com/koreader/koreader/issues/7228 too (as #7461 is a duplicate of #7228)

**Comment by poire-z** [comment]
Mhhh, as you are in Pan Zoom Fix Mode, I'll shamelessly hint 2 other related issues/questions:
https://github.com/koreader/koreader/pull/6885#issuecomment-743409322 footer (time) not upated when panning
https://github.com/koreader/koreader/pull/6885#issuecomment-757911409 refresh glitches when reflow enabled
Just in case you feel like having more :)

**Comment by NiLuJe** [comment]
@poire-z: Haha, nooope. :D.

Unless we're okay with disabling the icons if reflow is enabled, that I can (probably ;p) do?

File: frontend/ui/data/koptoptions.lua [hunk 1]
```diff
@@ -259,6 +260,16 @@ In 'semi-auto' and 'manual' modes, you may need to define areas once on an odd p
                 },
                 alternate = false,
                 values = {7, 6, 5, 4, 3, 2, 1, 0},
+                labels = {
+                    _("Left to Right, Top to Bottom"),
```
Comment (NiLuJe) [inline frontend/ui/data/koptoptions.lua:264]: FWIW, CamelCase was voluntary here.

(One, it helped me make sure I didn't get it wrong, two, I kind of like it? ^^).

**Comment by Frenzie** [comment]
> Unless we're okay with disabling the icons if reflow is enabled, that, I can (probably ;p) do?

Iirc nothing other than page and page width makes sense combined with reflow.

**Comment by NiLuJe** [comment]
If I close my eyes and sing *lalala* really loud, can I assume that *enabling* reflow murders the settings in question and I don't have to even check for that? ^^.

**Comment by Galunid** [comment]
@NiLuJe Seems closing your eyes and singing *lalala* didn't work https://github.com/koreader/koreader/pull/6885#issuecomment-757911409

**Comment by poire-z** [comment]
> can I assume that enabling reflow murders the settings in question and I don't even have to check for that

I don't read PDF often enough to have any kind of workflow - but I guess if I have sen pan/zoom settings to my liking, and I hit Reflow on (to see, for testing, or by error), and hit Reflow off, I'll be sad losing my previous settings :)
So, may be just don't close your eyes, don(t sing (really!), and don't fix it :)

**Comment by NiLuJe** [comment]
@poire-z: That actually works.... as long as the document stays open.

Al bets are off after a close, when toggling reflow off actually resets the zoom to default.

So, I kept that weirdness alive because I have no intention of ever looking at reflow code, and it will reset the zoom mode properly on doc open if reflow is on.

**Comment by NiLuJe** [comment]
Eh, fixed it.

**Review by poire-z — APPROVED** [review]
Thanks!
Not tested, and not familiar with that code, but looks allright :)

**Comment by poire-z** [comment]
> Just in case you feel like having more :)

Just in case ... https://github.com/koreader/koreader-base/pull/1203 :)

**Comment by NiLuJe** [comment]
Well played ;p.

**Comment by Frenzie** [comment]
> Just in case ... koreader/koreader-base#1203 :)

The biggest problem is I don't really know what's not done about it yet. I tested it on desktop and it seemed to be hunky dory, but I'm guessing on some target (*cough*Android presumably*cough*) there's still work to be done.

**Comment by NiLuJe** [comment]
I skimmed it a few weeks ago and there *is* some possibly non-trivial stuff missing (or papered over).
