### PR TITLE
ReaderRolling: save percent_finished on flushing settings

### LINKED ISSUE #14783: Save book metadata, does not update "percent_finished"
### Device

Kobo

### KOReader version

20251000071

### Model and firmware version

Kobo Libra Color

### Issue description

If i use the Save book metadata action the field "percent_finished" is not updated. But Eg. "last_xpointer" is updated.

If i close the book by going to the file browser "percent_finished" is getting updated.

As it is a part of the metadata I think it should be updated with the action and is a bug as it is right now.

### Steps to reproduce

1. Go to a book
2. read a bit
3.use Save book metadata action 
4. "percent_finished" is not changing in the metadata.pub.lua (inside the .sdr folder of the book)

I opened the file via ssh to check if it changes.

### Log

[crash.log.log](https://github.com/user-attachments/files/24402088/crash.log.log)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hius07**
- Closes #14783

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14787)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Looks a bit odd :-)

**Comment by hius07** [comment]
It's a complement to
https://github.com/koreader/koreader/blob/7353a2e5a4fe28a0f7eaa879c0ed4cb5f7151d98/frontend/apps/reader/modules/readerrolling.lua#L287-L288

**Comment by poire-z** [comment]
Fine with me.
(The alternative I guess would be to update a self.percent_finished on each page turn, which would cost a little and is not really needed.)

**Comment by Frenzie** [comment]
Tomorrow: how come that value isn't up to date from HTTP inspector :p

**Comment by hius07** [comment]
Yes, for the currently opened book `percent_finished` is not up-to-date.
The History/Collection opened over the reader shows its saved, not actual, value.

**Comment by poire-z** [comment]
If it is not used internally, can't we just compute some value from currentpage/totalpages ? We (and external users/tools) probably don't really care if it's accurate or not.

**Comment by hius07** [comment]
Maybe. It would require the CoverBrowser to distinguish currently opened book from others.

**Comment by poire-z** [comment]
I meant: on each page turned, compute self.percent_finished = curpage/totalpages, and save it just as/when we do curpage, so it's no longer something special.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/7353a2e5a4fe28a0f7eaa879c0ed4cb5f7151d98/frontend/apps/reader/modules/readerfooter.lua#L2488-L2495

**Comment by hius07** [comment]
We can do this on every page turn, save it to the BookList cache, and then use in the footer, by the CoverBrowser, and even in SaveSettings.

**Comment by poire-z** [comment]
Sounds like the thing to do, I guess percent_finished and book progress sounds like the same thing and there's no reason their values to be different ?

**Comment by hius07** [comment]
Yes (except for hidden flows?)
Is the current calculation more accurate?
https://github.com/koreader/koreader/blob/7353a2e5a4fe28a0f7eaa879c0ed4cb5f7151d98/frontend/apps/reader/modules/readerrolling.lua#L508-L509

**Comment by poire-z** [comment]
I don't know, no real opinion what the value should be.
I guess the getPosFromXPointer(getXPointer) can cost a little (although their value may be cached by cre_call_cache).
But I think what matters is the hiddenflow stuff done in getBookProgress: do we want hidden flows to impact that percent_finished/bookprogress ? (No real opinion, but it feels yes).

**Comment by hius07** [comment]
Paging and rolling `getLastPercent()` are kept for plugins.

File: frontend/apps/reader/modules/readerfooter.lua [hunk 1]
```diff
@@ -2307,6 +2308,10 @@ function ReaderFooter:onPageUpdate(pageno)
             end
         end
     end
+    if self.pages then
+        self.percent_finished = self:getBookProgress()
+        BookList.setBookInfoCacheProperty(self.ui.document.file, "percent_finished", self.percent_finished)
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerfooter.lua:2313]: Not too expensive (vs. everything else) ?

Comment (hius07) [reply frontend/apps/reader/modules/readerfooter.lua:2313]: https://github.com/koreader/koreader/blob/7353a2e5a4fe28a0f7eaa879c0ed4cb5f7151d98/frontend/ui/widget/booklist.lua#L295-L303
Current book cache is already created, so just setting two table values.

Comment (hius07) [reply frontend/apps/reader/modules/readerfooter.lua:2313]: The cached percentage is actual and is used by CoverBrowser, History and Collections are correct.

Comment (hius07) [reply frontend/apps/reader/modules/readerfooter.lua:2313]: If a user has enabled showing book progress in the status bar, the cached value is used, no double calculations.

**Review by poire-z — APPROVED** [review]
