### PR TITLE
Natural sorting refactor

### LINKED ISSUE #10009: Calibre plugin: series are not ordered correctly
* KOReader version: latest stable (v2022.11)
* Device: Kobo Aura One

#### Issue
Calibre plugin: series are not ordered correctly when visualized. 
#### Steps to reproduce
Import a calibre series with a large number of elements (> 100), go to calibre metadata search->browse series, type (click) on the series and you'll see that element 100 is next one to 10 (and so on). 

The following workaround solves my use case, but (since I'm not fluent in LUA) I don't think it's the correct fix.  I presume the correct fix is related to line 274

https://github.com/koreader/koreader/blob/843c4bfe66727d59460c37cb79fdd3317a735d74/plugins/calibre.koplugin/search.lua#L278

becomes

`entry.text = string.format("%03d.%s | %s - %s", major, minor, book.title, book.authors[1])`

### PR DESCRIPTION
**Pull request by NiLuJe**
* Move natural sorting algo to a dedicated sort module to avoid code duplication
* Speed up natural sorting by caching intermediary strings (~~depends on https://github.com/koreader/koreader-base/pull/1573~~).
* Calibre: Use natural sorting in metadata search (fix #10009)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10023)

### CODE REVIEW

**Comment by NiLuJe** [comment]
RFC: This implementation fixes minor inconsistencies (quoting Kulchenko's example):

> when a number in one string is in a position where a number is absent in some other string. For example: when sorting `{"dir\\file.lua", "dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua"}` using the algorithm above, you'd get `{"dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua", "dir\\file.lua"}`, which is probably not what you'd expect.

> If you sort the same table using this function, you'll get the sorted table you'd likely expect: `{"dir\\file.lua", "dir2\\file.lua", "dir3\\file.lua", "dir3\\file2.lua"}`.

The drawback being that it is roughly twice as expensive. Now, I don't actually use this myself in the FM (I sort by most recent, and the fact that it is fast was a factor in my choice, FWIW), but when trying it on a H2O, the delay *is* noticeable (then again, it's already noticeable with the faster implementation ;p).
Should we care?
Should we keep both imps and use the faster one in the FM?
Should we just use the faster imp, period, and document (in code) the caveats?

File: frontend/util.lua [hunk 1]
```diff
@@ -1311,6 +1311,41 @@ function util.stringSearch(txt, str, case_sensitive, start_pos)
...
+        end
+        res = res..c:gsub("[%z\1-\127\192-\255]", "\0%0")
+    end
+    return res
+end
+function util.natsort(a, b)
+    local ca, cb = natsort_conv(a), natsort_conv(b)
+    return ca < cb or ca == cb and a < b
+end
+
```
Comment (zwim) [inline frontend/util.lua:1348]: If you want to speed up things, you can cache a bit :)

My tests showed an improvement (on a Laptop, with 100.000 strings) of `table.sort` from 10.4 seconds to 0.46 seconds, which is not bad :-)

A cached implementation could look like
```
local util.cache = {}
local function natsort(a, b)
    local ca, cb

    if util.cache[a] then
        ca = util.cache[a]
    else
        ca = natsort_conv(a)
        util.cache[a] = ca
    end
    if util.cache[b] then
        cb = util.cache[b]
    else
        cb = natsort_conv(b)
        util.cache[b] = cb
    end

    return ca < cb or ca == cb and a < b
end
```
and to clean up the cache after a sort (just to save memory, can be omitted if it is clear, that only a few entries where sorted)
```
util.cache = {}
```

If you want that automated you can use something like
```
tablesort_orig = table.sort
table.sort = function(array, sort_func)
    tablesort_orig(array, sort_func)
    cache = {}
end
```

Comment (NiLuJe) [reply frontend/util.lua]: Yup, that works... *really* well ;).

I tweaked the idea and switched to an LRU cache, which means we don't need to care about maintenance, and the persistence helps the FM use-case.

**Comment by zwim** [comment]
@Niluje: Right now, moving `G_defaults' before the first userpatch call should work. But I can not foresee what the future brings.

Could it be an option to 
1.) do a thumb initialization of the LRU-cache-size to let's say 1024 (as I assume we won't ever have more than 1024 userpatches at one time),
2.) add a function to reinitialize the LRU-cache (delete the old cache create a new one) to util,
3.) call that function after the userpatch calls but before the first sort usage (maybe in line 32 of reader.lua)?

**Comment by NiLuJe** [comment]
Yup, sounds good, I'll deal with that after dinner ;).

**Comment by zwim** [comment]
Enjoy the meal.

**Comment by poire-z** [comment]
Mhhh, I don't think this cache size should be a user-modifiable default: who would set a different value and why ? So, just set it to 1024 and don't be tied to G_defaults.

And your global cache would keep unrelated items for ages.
I guess the cache should be per site (I mean: the bits of code using the natural sorting function): either they would request a cache and store it on their side - or ask the natsort module to use a cache with that size and a "tag", and whether to keep it longer or if one-time use. Or have a nat_sort_function_factory return a natsort function suitable for sorting with its own invisible cache.

**Comment by zwim** [comment]
@NiLuJe : I don't want to disturb you during your deserved dinner.

Just brainstorming here:
1.) What about starting the LRU with let's say 1024 (that won't waste memory, if we have less than 1024 strings for natural sort).
2.) We wrap `table.sort` as shown above. Before calling the real `table.sort` we check 
a) if the sorting function is natural_sort and
b) if the current table size is greater than the current lru-cache size.
if either a) or b) are false, go on,
otherwise (else) we increase *) the LRU-size with something like (This should be O(N)).
```
new_cache = lru.new(new_size, nil)
-- move the old cache to the new one
for key, value in pairs(cache) do
    new_cache:set(key,value)
    cache:delete(key)
end
cache = new_cache
```
Benefits/drawbacks of this strategy:
+) No explicit cache_size has to be set anywhere, it grows,
+) now need to remember anything,
+) we are scaling well with huge libraries,
+) we are fast,
+) we cache as much as possible,

-) Cache size might get larger and larger (but not much more than twice the size of all names of all files on the disk). On my Laptop this would be 2*16MB for my regular user -> So this is negligible for an E-Reader.

+) It might be possible, that we need some sort of cache cleanup (a restart of KOReader will do that automagically).

---------------------------------------------------------------

*) Let's think about the size increase: What do we sort? File-Names. So a cache size equal the number of files on the disk(s) would surely be enough, but maybe to big (and expensive to get).

Performance-optimal would be old_size plus new_size, but that wastes memory. From my research in signal processing strategies I know that a good compromise is to often to use the new necessary size plus a percentage of the old size.

So I would suggest using the new table size plus (1/4) of the old size.

**Comment by zwim** [comment]
> Mhhh, I don't think this cache size should be a user-modifiable default: who would set a different value and why ? So, just set it to 1024 and don't be tied to G_defaults.
 
Yepp, see my brainstorming comment above.


> And your global cache would keep unrelated items for ages. 

Only until a restart, but it would also be possible to delete a tiny fraction of it (LRU -> `cache:delete`) from time to time.

> I guess the cache should be per site (I mean: the bits of code using the natural sorting function): either they would request a cache and store it on their side - or ask the natsort module to use a cache with that size and a "tag", and whether to keep it longer or if one-time use. Or have a nat_sort_function_factory return a natsort function suitable for sorting with its own invisible cache.

Are we changing roles now ;-) ;-) and you will be PO(verengeneered)IRE-Z now, or are you a jokestere now?

**Comment by poire-z** [comment]
> Are we changing roles ;-) ;-) and you will be PO(verengeneered)IRE-Z now, or are you a jokestere now?

I was going to throw that at you, reading your above above post :)
I was just throwing ideas for NiLuJe's brain to pick the simplest parts and trust he would find out something simple and nice  :)

I'm a bit against you brainstorm thoughts: I don't think we should keep a cache for longer that needed, and need such cleanup/growing strategies (that feels like over engineering :) for such a non-essential util, and it doesn't need a global cache).
I think we should have transient lru cache, and don't need a longer cache, and we can compute the sorting value once for each item each time we need to do the full sort (so, N computations, which is peanuts, is ok - and already a lot better than the naive initial approach).

**Comment by zwim** [comment]
> I'm a bit against you brainstorm thoughts: I don't think we should keep a cache for longer that needed, and need such cleanup/growing strategies (that feels like over engineering :) for such a non-essential util, and it doesn't need a global cache).

Well this is exactly the usage of the LRU-cache thing. -> The cache is persistent until we do something with it. Why not grow or shrink it. 

> I think we should have transient lru cache, and don't need a longer cache, and we can compute the sorting value once for each item each time we need to do the full sort (so, N computations, which is peanuts, is ok - and already a lot better than the naive initial approach).

We're talking past each other. The initial naive approach _did_ exactly what you want. Create a cache of the right size, and delete that right after the sorting. But @NiLuJe realized that a persistent cache would speed up the FM thingies (which sound good to me).

And here we meet again. I am also throwing ideas to @NiLuJe brains, to let him pick what he likes (as this is his PR). I won't want touch this part of code (the next few months).

**Comment by poire-z** [comment]
> The initial naive approach did exactly what you want. Create a cache of the right size, and delete that right after the sorting. 

Oh, right. Well, _naive_ is nice :)
And lru feels overkill then. We usually don't keep little thingies (such as strings) lingering around (we do for PDF pages bb, or some metadata fetched expensively from docsettings in coverbrowser, or the expensive cre calls results), so keeping a collection of unrelated "naturally transformed" strings would feel quite strange.

**Comment by NiLuJe** [comment]
There are currently a grand total of... drumroll... *three* call sites:

* userpatch, so, it'll happen once and caching is mostly irrelevant here.
* Calibre metadata
* FileManager

The last two end up being fairly similar in practice, in that you *will* go-back to stuff you've already shown during navigation, so keeping stuff around does make sense ;).

So, I understand the appeal of call-specific caches, but, currently, it doesn't feel worth it given the few call sites.

I like the idea of using the table size as the cache size, but it requires dealing with wrapping, which feels clunky (and is not entirely straight forward for the FM case, as the sorting function is lexically "far" from the actual sorting.

Hence the defaults compromise ;o).

The impact on memory usage is insignificant, we're dealing with very small strings here, a random widget tree is liable to take more spaces that 1K slots ;).

**Comment by NiLuJe** [comment]
(I should be done with the slew of edits on the above post, but GH is wonky on my end, and I'm not seeing the final version...).

Letting the thoughts simmer, I'll see if a bright idea strikes ;p.

**Comment by NiLuJe** [comment]
What's missing from the last visible edit is that we're not always passing `natsort` directly to `table.sort`, it's often (like, in two out of three cases... and all the ones that matter ;D) wrapped as we want to sort a specific field in a table; this would severely complicate any wrapping approach.

**Comment by NiLuJe** [comment]
And moving the cache maintenance to the caller would be mostly wasted effort, as the life-cycle would be tied to the caller's instance life-cycle, which kills *some* of the persistance gains (i.e., it would only persist until an app (FM/ReaderUI) switch).

**Comment by NiLuJe** [comment]
So far, it looks like my luadefaults compromise still stands as the least painful approach ;p.

**Comment by poire-z** [comment]
Least painful, but most ugly :)
It still feels that letting any wanted persistence to the lower level util function (as a single unique cache of _torchons et serviettes_) is awkward design.
Moreover, all the lru "last recently usage" accounting will do a lot of uneeded work: for each comparison, it will move the 2 compared thingies to top, and even if that's cheap (haven't look at lru.lua), it'd be done many many times, shuffling all the items to top numerous times.

**Comment by NiLuJe** [comment]
LRU is *really, really* fast ;).

But I agree that a dumb hash-map would have made more sense for a transient, site-specific approach.

**Comment by NiLuJe** [comment]
As an extra data point, 35 pages of FM stuff will occupy roughly ~320 slots.

**Comment by zwim** [comment]
To summarize to all thoughts here, maybe we can to fix a consensus:
1.) The size of the cache is not big (just the size of the filename - strings). Here on my Laptop and my e-reader this will be far less than a few MBs.
2.) Caching might really speed up things for going back, show views of some already shown folders again (seems advantageous for me.)
3.) Using a cache of the table size of the last sort (plus some small overhead (25%)) might speed up things really a lot. (its not large).
4.) The/this cache is only used by natural sort things. So no impact on users not using this feature.
5.) The cache can be reduced by deleting some entries from time to time (with `cache:delete`). But only users with really huge libraries are affected (but then the question arises: A huge library on a device with inferior memory???, does that work anyway)
6.) Usage of this cache make sense as there is a noticeable speed improvement (in some cases, in other cases it does no harm (speed, resources).
7.) 

>  And lru feels overkill then. We usually don't keep little thingies (such as strings) lingering around (we do for PDF pages bb, or some metadata fetched expensively from docsettings in coverbrowser, or the expensive cre calls results), so keeping a collection of unrelated "naturally transformed" strings would feel quite strange.

Here I am not d'accord, as calling often (really often) the same little thingies might also take some time. Especially on a sort thingie where the order might be something in between O(n^2) and O(n log(n)), caching as a trade-off between speed and memory is the winner.

---------------

And as an overall summarization: If we have memory, we should use it for speed up things (on our slow readers)!

So my conclusion is: The cache does not eat much memory, but saves a lot of calculation power, so use an LRU cache. Users using natural sort (which is the only true thing beside time and size) will benefit, users not using it, will not notice it.

**Comment by NiLuJe** [comment]
Okay, [2d016ff](https://github.com/koreader/koreader/pull/10023/commits/2d016ff5700e4b79a88d4adcbf0ae082fa71fb95) is a PoC for a not-terribly awful API for call-specific caches.

Implemented with a dumb hashmap for the PoC (which makes call-specific caches stupid, but bear with me ;p).

**Comment by zwim** [comment]
(All together I feel like this is again a dispute as:
"A dispute about the emperor's beard".
I don't know if this saying is translated correctly.

The long story: A discussion, which is circling around the same thing again and again.

We can circle around what is caching for. It helps to speed up things, but it uses memory.

Now we have memory, but we only want to use it for valuable things like pages (valuable = what the user sees).
On the other hand, why should we waste memory _forever_ as we need memory for pages. But sorting file names is also sometimes necessary (the user also sees file names).

And so on and so on. I am happy, that this is not my PR. So I don't need to argue, why a lru-cache is perfect for this use case.

IMHO, summarized, not negotiable: A lru cache, which is growing is necessary!
Users not using that feature won't be affected. 
Users who want natural sorting, need that feature and the cache! (If they have problems. well you can't get everything, a fast device with a lot of memory ....)
)

This is my last post on this PR! @NiLuJe  @probonopd  @Frenzie make something out of it.

**Comment by NiLuJe** [comment]
Benched the PoC w/ an LRU implementation, and it's barely any slower (yay, LuaJIT), so I might be able to make everybody happy ;o).

(Don't worry guys, I'm having fun :}).

**Comment by poire-z** [comment]
> This is my last post on this PR! 

Come on :) (and ping my right nickname, and not some person who has nothing to do in this business :)

I understand all your points, but between these 2 extreems:
- no cache, compute the "natural name" at each comparisons - which is really slow
- compute the "natural name" once, and keep it cached (for some time, in some size you have to manage), which is _really really really fast_

There is a 3rd option:
- compute the "natural name" once for each table.sort() - and throw it away when table sorted - which, I expect  to be _really really fast_, and hardly distinguisable by your benchmarks from the _really really really fast_, without any memory taken once done, or questions about cache, size, times, cleanup to ask and answer.

**Comment by poire-z** [comment]
I indeed prefer the "tag" approach, not mixing torchons and serviettes, and that would be not-to-ugly enough for me - even if I find the complexity useless.
You could probably not need the `natsort_set_cache()` and the "global state" `natsort_cache`, and just provide the tag on the call:
```diff
-    sort.natsort_set_cache("calibre")
-    table.sort(t, function(v1, v2) return sort.natsort(v1.text, v2.text) end)
+   table.sort(t, function(v1, v2) return sort.natsort(tag)(v1.text, v2.text) end)
```

**Comment by NiLuJe** [comment]
> There is a 3rd option:
> 
>     * compute the "natural name" once for each table.sort() - and throw it away when table sorted - which, I expect  to be _really really fast_, and hardly distinguisable by your benchmarks from the _really really really fast_, without any memory taken once done, or questions about cache, size, times, cleanup to ask and answer.

Measuring that was part of the intent behind the first iteration of the PoC (i.e., dumb hash-map, since we're going to trash it immediately).

It's... measurably slower (~25%) ;o).  Not awful, but measurable and noticeable with my 350 strings ;).

**Comment by NiLuJe** [comment]
> You could probably not need the `natsort_set_cache()` and the "global state" `natsort_cache`, and just provide the tag on the call

That unfortunately wouldn't help for FileChooser, because we don't know the size when the sorting method is set ;).

**Comment by poire-z** [comment]
> It's... measurably slower (~25%) ;o). Not awful, but measurable and noticeable with my 350 strings ;).

On the first call ? On the second++ calls ? It can't be slower on the first call.

**Comment by NiLuJe** [comment]
> On the first call ? On the second++ calls ? It can't be slower on the first call.

There's no longer a difference if we trash the cache (barring JIT shenanigans). But, yeah, I was comparing an uncached run (~200 to ~250ms) to a cached one (~150ms, which matches numerical sorting on file attributes).

**Comment by poire-z** [comment]
And how these 250ms or 150ms compare to the timing if not using any cache (your noticably slow first try)?
250ms vs 4000ms is worth it, ganing 100ms would be hardly noticable to the user, so I would personally don't bother with a long-living cache.
But up to you.

(And if we start caching these, why not also cache lfs.attributes, so all sort benefits from a gain from 150ms to... 50 ms ! we could imagine many more caches :/)

**Comment by NiLuJe** [comment]
> lfs.attributes

The kernel does that for us ;o).

Snark aside, this is a salient point: these are transformations *we* are responsible for, so it does make sense that *we* be the one to handle/cache (as opposed to untransformed data we get from the system, e.g., lfs).

**Comment by NiLuJe** [comment]
> And how these 250ms or 150ms compare to the timing if not using any cache (your noticably slow first try)?

That's ~650ms (which is past unusable for me, but I'm fairly anal about UI latency).

**Comment by poire-z** [comment]
(In coverbrowser, I cache some docsetting info for the current browsing session, and trash it all when we go read a book. I still think "strings reproducibly transformed by a few regexps" would not need to survive past the current browsing session. Users would get 250ms each time they go back to filebrowser, and get 150ms when they go up and down directories. The initial 100ms addition would not be noticable.)

**Comment by NiLuJe** [comment]
Despite the fact that I *do* notice a 100ms difference; invalidating the cache on app switch would be an entirely sensible decision.

It would be slightly gnarly to implement here, because of the CoverBrowser shenanigans w/ monkey-patching FileChooseer's onCloseWidget...

File: frontend/userpatch.lua [hunk 2]
```diff
@@ -55,16 +56,7 @@ local function runUserPatchTasks(dir, priority)
...
-        local dec, n = string.match(d, "(%.?)0*(.+)")
-        return #dec > 0 and ("%.12f"):format(d) or ("%s%03d%s"):format(dec, #n, n)
-    end
-    local function sorting(a, b)
-        return tostring(a):gsub("%.?%d+", addLeadingZeroes)..("%3d"):format(#b)
-            < tostring(b):gsub("%.?%d+", addLeadingZeroes)..("%3d"):format(#a)
-    end
-
-    table.sort(patches, sorting)
+    table.sort(patches, sort.natsort)
```
Comment (poire-z) [inline frontend/userpatch.lua:59]: And because these natural transformed strings has no need to stay in memory, you probably should use a tag:
```lua
sort.natsort_set_cache("userpatches")
table.sort(patches, sort.natsort)
sort.natsort_clear_cache("userpatches")
```

**Comment by poire-z** [comment]
(Another idea, for a cleaner API and a longer night up for you :), add a natsort method to `table`:
```lua
table.natsort(function(v) return v.text end) --  only a temporary internal cache
table.natsort(function(v) return v.text end, "filechooser", 1024)
-- or, to not even have to store the caches in the natsort module
-- (which is the only remaining thing I find ugly, but it can get some
-- advocacy, hiding it from the caller)
self.reusable_cache = table.natsort(function(v) return v.text end, self.reusable_cache, 1024)
    -- that is, if you don't store the returned value, the cache it's trashed
    -- if you don't provide any, a new one is created and returned
    -- if you provide one, it's used and lru'ed
```
)

**Comment by NiLuJe** [comment]
> (Another idea, for a cleaner API and a longer night up for you :), add a natsort method to `table`:

The way FileChooser handles things makes this tricky (much like it did the wrapping approach discussed earlier) :/.

(Because, yeah, assuming we drop caches on destroy, it makes sense to have the caller hold the cache).

**Comment by NiLuJe** [comment]
> The way FileChooser handles things makes this tricky (much like it did the wrapping approach discussed earlier) :/.

And without wrapping, the closest I can come to is something like this, which still requires an explicit destructor in the caller to drop the natsort reference to its instance object (meaning this is objectively worse ;p).

```diff
diff --git a/frontend/sort.lua b/frontend/sort.lua
index 3488ca0ce..65f1d35f5 100644
--- a/frontend/sort.lua
+++ b/frontend/sort.lua
@@ -76,10 +76,8 @@ end
 
 -- LRU => cold, ~200 to 250ms; hot ~150 to 175ms (which is barely any slower than a dumb hash-map, yay, LRU and LuaJIT magic).
 local lru = require("ffi/lru")
-local natsort_caches = {
-    global = lru.new(512, nil, false),
-}
-local natsort_cache = natsort_caches.global
+local global_natsort_cache = lru.new(512, nil, false)
+local natsort_cache = global_natsort_cache
 
 function sort.natsort(a, b)
     local ca, cb = natsort_cache:get(a), natsort_cache:get(b)
@@ -95,8 +93,8 @@ function sort.natsort(a, b)
     return ca < cb or ca == cb and a < b
 end
 
-function sort.natsort_set_cache(tag, slots)
-    print("sort.natsort_set_cache", tag, slots)
+function sort.natsort_set_cache(cache, slots)
+    print("sort.natsort_set_cache", cache, slots)
     -- Add a bit of scratch space to account for subsequent calls
     if slots then
         slots = math.ceil(slots * 1.25)
@@ -104,22 +102,22 @@ function sort.natsort_set_cache(tag, slots)
         slots = 1024
     end
 
-    if not natsort_caches[tag] then
-        print("settings up", slots, "slots for", tag)
-        natsort_caches[tag] = lru.new(slots, nil, false)
+    if not cache then
+        cache = lru.new(slots, nil, false)
+        print("settings up", slots, "slots as", cache)
     else
-        if slots > natsort_caches[tag]:total_slots() then
-            print("growing", tag, "from", natsort_caches[tag]:total_slots(), "to", slots)
-            natsort_caches[tag]:resize_slots(slots)
+        if slots > cache:total_slots() then
+            print("growing", cache, "from", cache:total_slots(), "to", slots)
+            cache:resize_slots(slots)
         end
     end
 
-    natsort_cache = natsort_caches[tag]
+    natsort_cache = cache
+    return cache
 end
 
-function sort.natsort_destroy_cache(tag)
-    natsort_caches[tag] = nil
-    natsort_cache = natsort_caches.global
+function sort.natsort_reset_cache()
+    natsort_cache = global_natsort_cache
 end
 
 return sort
diff --git a/frontend/ui/widget/filechooser.lua b/frontend/ui/widget/filechooser.lua
index ccd4e7375..c8e01b10c 100644
--- a/frontend/ui/widget/filechooser.lua
+++ b/frontend/ui/widget/filechooser.lua
@@ -239,7 +239,7 @@ function FileChooser:getSortingFunction(collate, reverse_collate, data_length)
         sorting = function(a, b)
             return sort.natsort(a.name, b.name)
         end
-        sort.natsort_set_cache("filechooser", data_length)
+        self.natsort_cache = sort.natsort_set_cache(self.natsort_cache, data_length)
     else
         sorting = function(a, b)
             return a.name < b.name
@@ -647,7 +647,7 @@ end
 function FileChooser:onCloseWidget()
     print("FileChooser:onCloseWidget", self)
     -- Drop our natsort cache
-    sort.natsort_destroy_cache("filechooser")
+    sort.natsort_reset_cache()
     Menu.onCloseWidget(self)
 end
```

**Comment by NiLuJe** [comment]
> (Another idea, for a cleaner API and a longer night up for you :), add a natsort method to `table`:
> 
> ```lua
> table.natsort(function(v) return v.text end) --  only a temporary internal cache
> table.natsort(function(v) return v.text end, "filechooser", 1024)
> -- or, to not even have to store the caches in the natsort module
> -- (which is the only remaining thing I find ugly, but it can get some
> -- advocacy, hiding it from the caller)
> self.reusable_cache = table.natsort(function(v) return v.text end, self.reusable_cache, 1024)
>     -- that is, if you don't store the returned value, the cache it's trashed
>     -- if you don't provide any, a new one is created and returned
>     -- if you provide one, it's used and lru'ed
> ```
> 
> Dunno if we already plug methods into existing object, and how expensive it would be if available on all tables and never used on most of them. But well, I'd rather not touch my natural tables and keep them pure :) )

Getting a bit cross-eyed, so I'll see if sleeping on it helps, but this doesn't make any sense to me anymore :D.

`table.sort` only take two arguments: an input table, and an optional comparison function that should emulate the operator `<` (i.e., returns true or false), and which itself only takes two arguments (left and right side operands).

We often use closure magic to implement sorting on a specific field via a custom comparison function.

`table.sort` will call that function *a lot*.

My brain cannot comprehend anymore how you'd want to wrap things around so that more stuff happens inside this very strict construct ;o).

**Comment by NiLuJe** [comment]
Yeaaah, last commit is getting there, it'll make more sense tomorrow :D.

**Comment by Frenzie** [comment]
@zwim 
Semi-randomly skimming a rather huge discussion…
> The cache can be reduced by deleting some entries from time to time (with cache:delete). But only users with really huge libraries are affected (but then the question arises: A huge library on a device with inferior memory???, does that work anyway)

I don't understand what you're trying to say with this train of thought. All you need to have a very large library is many thousands of books from Project Gutenberg, most of which will work rather well even on extremely weak devices.

**Comment by poire-z** [comment]
> table.sort only take two arguments: an input table, and an optional comparison function that should emulate the operator < (i.e., returns true or false), and which itself only takes two arguments (left and right side operands).
We often use closure magic to implement sorting on a specific field via a custom comparison function.
table.sort will call that function a lot.
My brain cannot comprehend anymore how you'd want to wrap things around so that more stuff happens inside this very rigid construct ;o).

Yeah, I was thinking about that (that a table.natsort would need unwelcome changes to filechooser to not use `table.sort()` in one case) while in bed, and was too lazy walking up to write that a cleaner solution (not hacking `table`) would just be to use a `natsort.table_sort(table, params...)` - which is what you ended up doing :) but you still had to hack filechooser.
Which is ok if you find it ok.

A solution not requiring changes to fileChooser's use of `table.sort()` could be something like
```
sorting_function, self.natsort_cache = natsort.get_sorting_function(function(v) return v.text end, self.natsort_cache)
table.sort(files, sorting_function)
```

> table.sort will call that function a lot.

It would call the `function(v) return v.text end` once for each item. Your `field` parameter would limit a bit the capabilities of that natural sorting utility.

**Comment by NiLuJe** [comment]
@poire-z: Yeah, I'm currently on a similar train of thought to see if there's a feasible way to wrap the cmp function so as to keep the original flexibility of table.sort instead of my quick field hack...

TBD ;p.

**Comment by NiLuJe** [comment]
Okay, I think this one might be it (in terms of API design, at least).

I'll test the other call sites, and swap to a simple has-map, since the main interest in using LRU was no maintenance because of its persistence; since we got rid of the persistence, there are no upsides to it anymore.

**Comment by NiLuJe** [comment]
There, dealt with FileSearcher ;p.

**Comment by poire-z** [comment]
> Okay, I think this one might be it (in terms of API design, at least).

Yep, perfectly happy with it ! :+1:

File: frontend/ui/widget/filechooser.lua [hunk 3]
```diff
@@ -355,6 +357,9 @@ function FileChooser:genItemTableFromPath(path)
         end
     end
 
+    local end_time = time.now()
+    print(string.format("FileChooser:genItemTableFromPath: Took %9.3f ms w/ collate: %s", time.to_ms(end_time - start_time), self.collate))
```
Comment (Frenzie) [inline frontend/ui/widget/filechooser.lua:361]: Leftover debug

**Review by Frenzie — APPROVED** [review]
lgtm

File: frontend/ui/widget/filechooser.lua (hunk 3 above)
Comment (NiLuJe) [reply frontend/ui/widget/filechooser.lua:361]: Yup, I was sidetracked by LDoc ;p.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 7 of 9 files at r8, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10023)* status: all files reviewed, 3 unresolved discussions (waiting on @Frenzie, @poire-z, and @zwim)

**Comment by NiLuJe** [comment]
(Trials and tribulations will be archived in [this branch](https://github.com/NiLuJe/koreader/tree/natsort_cache), since that kinda grew exponentially from its original quick fix intent (which is why this was on my master branch) ;p.

**Comment by Frenzie** [comment]
Another and possibly more future proof way is to make a PR from that branch to here and then close it. Then it'll remain even if you delete the branch or the repo thanks to GH, provided GH sticks around.

**Comment by NiLuJe** [comment]
Yup, we'd lose the comments to the PR attached to the merge commit though, which is why I'm not fond of that approach ;) (I mean, we'd just have to link to this one, but, still... :D).

**Comment by Frenzie** [comment]
The reverse is the same thing. ;-) (I.e., close this one and open a new one that's rebased etc.)

**Comment by NiLuJe** [comment]
@poire-z: I had another lightbulb moment, the latest commit simplifies the API and leaves the cmp wrapping to the caller like a standard cmp function.

It's slightly more verbose for wrapping callers because they have to store a reference to the generated cmp so as not to run the generator on every cmp call done by table.sort, but gets rid of the slightly off syntax of the operands_func thingy I had before ;p.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10023)* status: all files reviewed, 3 unresolved discussions (waiting on @Frenzie, @poire-z, and @zwim)

File: frontend/sort.lua [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+        end
+        cache[s] = res
+        return res
+    end
+
+    local function natsort(a, b)
+        local ca, cb = cache[a] or natsort_conv(a), cache[b] or natsort_conv(b)
+
+        return ca < cb or ca == cb and a < b
+    end
```
Comment (poire-z) [inline frontend/sort.lua:130]: (Uneeded blank line in there now :)

**Review by poire-z — APPROVED** [review]
> I had another lightbulb moment

Looks glaring to me :)
