### PR TITLE
[fix] ReaderZooming: work around tiles that are too large

### LINKED ISSUE #3491: Page stuck in PDF
* KOReader version: 2538189473241ecab9013ffcd48fb469fdf20561
* Device: Kobo H2O

#### Issue

Trying to get past page 63 by going to next or previous page doesn't work. Going straight to p. 62 or 64 does.

http://gallica.bnf.fr/ark:/12148/bpt6k76171n

I haven't investigated atm. It might be an issue with `zoom to fit content width`.

Edit: darn, I just checked and I can't reproduce this on the emulator. Weird. I'll see if I can get some more debugging info out of it tomorrow and if clearing SDR works.

### PR DESCRIPTION
**Pull request by Frenzie**
Zooms out until a page can fit in the cache. It's a bit ugly, but better than being stuck. Fixes #3491.

### CODE REVIEW

File: frontend/apps/reader/modules/readerzooming.lua [hunk 1]
```diff
@@ -276,6 +277,23 @@ function ReaderZooming:getZoom(pageno)
     elseif self.zoom_mode == "free" then
         zoom = self.zoom
     end
+    if zoom and zoom > 10 and not Cache:willAccept(zoom * (self.dimen.w * self.dimen.h + 64)) then
+        logger.dbg("zoom too large, adjusting")
+        while not Cache:willAccept(zoom * (self.dimen.w * self.dimen.h + 64)) do
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerzooming.lua]: @poire-z There should be a second condition in here to prevent the possibility of endless loops, but I'm not sure what exactly. A simple `max_iterations = 50`?

Comment (poire-z) [reply frontend/apps/reader/modules/readerzooming.lua]: Dunno. When going towards zero, it should fit isn't it?
But at one point you'll reach zero, or a negative number, so you should probably take care of that too.

Comment (Frenzie) [reply frontend/apps/reader/modules/readerzooming.lua]: Good point, a simple > 0 should do the trick.
