### PR TITLE
A small round of fixes

### LINKED ISSUE #9674: Libra2 Frontlight toggle doesn't turn off light with some values.
* KOReader version: v2022.10
* Device: Kobo Libra 2 

#### Issue
When Frontlight value is set to 6,7,12, 14,23,24,28... (I didn't check out every value) and when I tap left bottom corner (Frontlight Toggle), the light is not turning off completely. Even if brightness value is set to 0. The same is when I use Menu/Settings/Frontlight and tap Toggle button. Any other values I use 1..5, 8..11, etc.. Work as It should. 

One thing else. If I close my Kobo cover book (with dimmed frontlight), and then (after few seconds) I open it again frontlight is turned off complettely as it should!

Sorry for my english. I just want to help improving this great reading application. 

#### Steps to reproduce
1 Set frontlight brightness to 5 or 6 or 12... on Kobo Libra 2
2 Tap left down corner 
3 Frontlight is dimmed but not turned off complettely

Here is a part i have found on crash.log

error in subprocess:	./ffi/kobolight.lua:28: Wrong brightness value given!
stack traceback:
	[C]: in function 'assert'
	./ffi/kobolight.lua:28: in function 'setBrightness'
	frontend/device/sysfs_light.lua:78: in function 'setNaturalBrightness'
	frontend/device/sysfs_light.lua:41: in function 'setBrightness'
	frontend/device/kobo/powerd.lua:248: in function 'setIntensityHW'
	frontend/device/kobo/powerd.lua:306: in function 'func'
	./ffi/util.lua:348: in function <./ffi/util.lua:319>
	[C]: in function 'xpcall'
	./ffi/util.lua:319: in function 'runInSubProcess'
	frontend/device/kobo/powerd.lua:304: in function 'turnOffFrontlightHW'
	frontend/device/generic/powerd.lua:109: in function 'toggleFrontlight'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:788: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1313: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1407: in function 'handleInput'
	frontend/ui/uimanager.lua:1456: in function 'run'
	./reader.lua:302: in main chunk
	[C]: at 0x000140bd
error in subprocess:	./ffi/kobolight.lua:28: Wrong brightness value given!
stack traceback:
	[C]: in function 'assert'
	./ffi/kobolight.lua:28: in function 'setBrightness'
	frontend/device/sysfs_light.lua:78: in function 'setNaturalBrightness'
	frontend/device/sysfs_light.lua:41: in function 'setBrightness'
	frontend/device/kobo/powerd.lua:248: in function 'setIntensityHW'
	frontend/device/kobo/powerd.lua:306: in function 'func'
	./ffi/util.lua:348: in function <./ffi/util.lua:319>
	[C]: in function 'xpcall'
	./ffi/util.lua:319: in function 'runInSubProcess'
	frontend/device/kobo/powerd.lua:304: in function 'turnOffFrontlightHW'
	frontend/device/generic/powerd.lua:109: in function 'toggleFrontlight'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:788: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1313: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1407: in function 'handleInput'
	frontend/ui/uimanager.lua:1456: in function 'run'
	./reader.lua:302: in main chunk
	[C]: at 0x000140bd

regards

### PR DESCRIPTION
**Pull request by NiLuJe**
* Kobo: Unbreak frontlight toggle for some speciifc values (fix #9674, regression since #9609)
* ScreenSaver: Actually enable the `onAnyKeyPressed` handler (allowing one to close the ScreenSaver with page-turn buttons, for instance). [This is properly disabled when using the child lock pattern mode, because @poire-z rules ;)].
* Previous commit lead to a general cleanup of those handlers in the codebase, because it turns out it was *really* not the only dumb unused code c/p around ;).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9676)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Rebase me)

File: frontend/device/kobo/powerd.lua [hunk 1]
```diff
@@ -335,8 +339,8 @@ function KoboPowerD:turnOnFrontlightHW()
         return
     end
     ffiUtil.runInSubProcess(function()
-        for i = 1,5 do
-            self:setIntensityHW(math.ceil(self.fl_min + ((self.fl_intensity * (1/5)) * i)))
+        for i = 1, 5 do
+            self:setIntensityHW(math.ceil(self.fl_min + (self.fl_intensity / 5 * i)))
```
Comment (Frenzie) [inline frontend/device/kobo/powerd.lua:343]:
```suggestion
            self:setIntensityHW(math.ceil(self.fl_min + (self.fl_intensity / 5 * i))) -- @zwim don't change me :-P
```

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
> * [This is properly disabled when using the child lock pattern mode, because @poire-z rules ;)]

Actually... almost ;o). `key_events` & `ges_events` cannot be nil, we run an unchecked pairs on 'em. I'll fix that tomorrow ;).

**Comment by NiLuJe** [comment]
Ping @zwim for https://github.com/koreader/koreader/pull/9676/commits/d034e1a71955b45ce02587fdcd0a58b9f491de50 to confirm I didn't fuck it up ;).

File: frontend/device/kobo/powerd.lua (hunk 1 above)
Comment (mcdenko) [reply frontend/device/kobo/powerd.lua:343]: I dont know if it is important, but after applying these changes, Toggling frontlight on Kobo Libra 2 works as it should!
Thank You very much! :)

File: frontend/ui/time.lua [hunk 2]
```diff
@@ -171,7 +171,7 @@ end
 function time.split_s_us(time_fts)
     if not time_fts then return nil, nil end
     local sec = math.floor(time_fts * FTS2S)
-    local usec = math.floor(time_fts - sec * S2FTS) * FTS2US
+    local usec = math.floor((time_fts - (sec * S2FTS)) * FTS2US)
```
Comment (zwim) [inline frontend/ui/time.lua:174]: Good catch. The original line is buggy. Your version works. The innermost parenthesis are superfluous. So maybe write 
```
local usec = math.floor((time_fts - sec * S2FTS) * FTS2US)
```

The good news is, that this bug is not noticeable by now, as `PRECISION` can be stored in a double without precision loss; `US2FTS` is exactly 1 and `FTS2US` is exactly 1, too. But for future (if someone wants to tune the thing by using a different `PRECISION` value (e.g. a power of 2), this buggy line would cause an issue).

**Comment by NiLuJe** [comment]
> Does the frontlight issue fix deserves a v2022.10.1 (not affected, can't judge criticity) ?

That's a good question. It breaks toggle off on a not insignificant number of frontlight values, which is mildly annoying, but can be worked-around by just changing the fl value by +/- 1, so, eeeeh.

Might be annoying to field those issues for a month, though ;).

**Comment by poire-z** [comment]
OK, so it does not prevent anybody from using the software. We mostly did some rerelease when it crashed at start I guess. With v2022.10, they can upgrade to dev channel and get it fixed. Or live with it, they deserve it :) for not helping us fixing stuff by being on the dev channel :)

We can remove "Chinese, Japanese and Korean typography: some questions" from the pinned issue if we want a slot to pin the frontlight issue until v2022.11, and may be avoid some duplicates opening.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9676)* status: all files reviewed, 2 unresolved discussions (waiting on @Frenzie, @pazos, @poire-z, and @zwim)
