### PR TITLE
Fix a couple of potentially spurious footer refreshes

### LINKED ISSUE #12323: Status bar overlaps other windows
* KOReader version: v2024.07-74
* Device: PB 628

#### Issue
Sometimes the status bar overlaps other windows for some time, such as the footnote pop-ups, the bookmark list and the keyboard.

Reader_2024-08-09_202249 (Medium)

Reader_2024-08-09_202753 (Medium)

Reader_2024-08-09_202859 (Medium)

Reader_2024-08-09_203003 (Medium)

### PR DESCRIPTION
**Pull request by NiLuJe**
One from ReadTimer, for sure; and one that maaaaybe could be tripped via BookMetadataChanged ;).

Fix #12323

(rebase me)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12422)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

File: frontend/apps/reader/modules/readerfooter.lua [hunk 1]
```diff
@@ -2464,7 +2464,14 @@ end
 
 function ReaderFooter:onBookMetadataChanged(prop_updated)
     if prop_updated and (prop_updated.metadata_key_updated == "title" or prop_updated.metadata_key_updated == "authors") then
-        self:updateFooterText()
+        self:maybeUpdateFooter()
```
Comment (hius07) [inline frontend/apps/reader/modules/readerfooter.lua:2467]: No harm, but no reasons actually I believe.

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerfooter.lua:2467]: Yeah, that was my read also, just being cautious ;).

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerfooter.lua:2467]: (It's also a question of setting a precedent: that's the only way things should request a footer refresh, short of very very very specific cases ;)).
