### PR TITLE
[InputText, ReaderStyleTweak] add copy/paste to NT devices

### LINKED ISSUE #12772: [Kindle NT] Text Input field - missing right-click option (to copy, etc)
* KOReader version: 2024.07-285-gfd3727274 (legacy)
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
@Commodore64user 
Maybe I am missing it somehow, but is there a way to do "right-click" on the text field to be able to copy whole text, just line (and do other things which I don't remember).

#### Steps to reproduce
Currently, "right click" while keyboard is up does "right click" on each letter (which is great).

For example, from within a book, open Top Menu - second tab - Style tweaks - long-press on Book-Specific tweaks (with `ScreenKB+Press`).

Book style tweak editor appears.
Input a few character (optional).
Close keyboard using `Back` button, scroll down once to focus on the text field, then do "right-click (`ScreenKB+Press`): nothing happens. What I expected was a nice popup menu which shows the same text in a text field and a bunch of options to copy it, or copy just a line, paste, etc.

#### Other Questions about Book-Specific Style Tweaks text input field, or rather `text editor` module maybe (and maybe other ones that have extra buttons above the keyboard, like Terminal Emulator)
I can also close keyboard while editing with `ScreenKB+Home` combo. However, this one is different from closing it with `Back` in the sense that focus stays inside the text field. So, Dpad buttons move cursor inside the text rather than moving focus around buttons.
Is this intended behavior?
I scratched my head a little bit, then figured I need to hit `Back` button **twice** to lose focus to be able to move around the buttons.

##### `crash.log` (if applicable)
Let me know if it is needed, but I think this feature is simply missing.

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

* Replaced `InputContainer` with `FocusManager` in `TweakInfoWidget`, enabling better focus handling and D-pad navigation for the CSS tweak info widget (`frontend/apps/reader/modules/readerstyletweak.lua`). 
* Added D-pad support and focus callbacks in the CSS tweak widget, so users can copy CSS text to clipboard using D-pad and receive visual feedback on focus state (`frontend/apps/reader/modules/readerstyletweak.lua`).
* Refactored clipboard copy logic into a new `copyTextToClipboard` method, used both for tap and D-pad press events, reducing code duplication (`frontend/apps/reader/modules/readerstyletweak.lua`). 

* Moved clipboard dialog and selection logic from `onHoldTextBox` to a new reusable `holdTextBox` method in `InputText`, simplifying event handling and enabling invocation from both touch and keyboard events (`frontend/ui/widget/inputtext.lua`). 
* Enabled triggering the clipboard dialog via keyboard "Press" events, improving accessibility for keyboard users (`frontend/ui/widget/inputtext.lua`).

### related issues

* closes https://github.com/koreader/koreader/issues/12772

### screen recording

 <details>
  <summary>expand to see</summary>
  
<div align="center">
  name
</div>
  
</details>

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14941)

### CODE REVIEW

File: frontend/apps/reader/modules/readerstyletweak.lua [hunk 1]
```diff
@@ -158,6 +158,28 @@ function TweakInfoWidget:init()
...
 
+    if Device:hasDPad() then
+        self.css_frame.onFocus = function(this)
+            this.bordersize = Size.border.thick
+            UIManager:setDirty(this, "ui")
+        end
+        self.css_frame.onUnfocus = function(this)
+            this.bordersize = Size.border.thin
+            UIManager:setDirty(this, "ui")
+        end
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerstyletweak.lua]: (When launched, it seems initially unfocused (thin border), but Enter gets "CSS test copied to clipboard" shown.
Also, thick/thin border change is not centered, but the frame grows/shrinks on the right.
Just mentionning that, if fixing it adds more kludge, don't fix it.)

File: frontend/apps/reader/modules/readerstyletweak.lua [hunk 2]
```diff
@@ -207,10 +229,7 @@ function TweakInfoWidget:onTap(arg, ges)
         -- Tap inside CSS text copies it into clipboard (so it
         -- can be pasted into the book-specific tweak editor)
         -- (Add \n on both sides for easier pasting)
-        Device.input.setClipboardText("\n"..self.css_text.."\n")
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerstyletweak.lua:210]: The 2 first lines of comments should stay here.
The 3rd line should go into the function where we actually add these `\n`.

File: frontend/ui/widget/inputtext.lua [hunk 3]
```diff
@@ -173,117 +173,7 @@ local function initTouchEvents()
         end
 
         function InputText:onHoldTextBox(arg, ges)
-            if self.parent.onSwitchFocus then
-                self.parent:onSwitchFocus(self)
-            end
-            -- clipboard dialog
```
Comment (poire-z) [inline frontend/ui/widget/inputtext.lua:179]: (I have verified there is zero difference in the body of this function before vs. after it has been moved.)

Still a bit sad to see it moved away from its neighbours who deal with related stuff (ie. _hold_handled).
But, can't you just have ?
```lua
        elseif key["Press"] then
            self:onHoldTextBox()
```
I guess the answer is currently "no" , because all of these are set up only in a initTouchEvents().
Not sure why we have it done that way, and not just defined always whether we use them - like we do mostly everywhere else, no ? It's just the ges_events that gets setup if touchdevice, but the methods are usually always defined.
It fells akward to just externalize one of them :/ I would clean it all.

As the adage say: _if it's not broken, don't fix it - if it's broken on NT, break everything else_ :)

Comment (Commodore64user) [reply frontend/ui/widget/inputtext.lua:179]: > (I have verified there is zero difference in the body of this function before vs. after it has been moved.)

where you expecting it to change?

> Not sure why we have it done that way

because you were selfish and wanted to keep it all to yourselves, those not challenged in the touch screen department.

> It fells akward to just externalize one of them :/ I would clean it all.

the other ones are proceeding functions, this one on the other hand is just a menu declaration, I don't know.. be my guess I suppose.

> As the adage say: _if it's not broken, don't fix it - if it's broken on NT, break everything else_ :)

trueeee

File: frontend/apps/reader/modules/readerstyletweak.lua (hunk 1 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerstyletweak.lua]: it does look like a drop shadow, I don't know how to centre it though... any ideas?

Comment (poire-z) [reply frontend/apps/reader/modules/readerstyletweak.lua]: I remember we have used `focus_inner_border = true` (a property of FrameContainer I think) in keyvaluepage.lua to solve a similar issue.

Comment (Commodore64user) [reply frontend/apps/reader/modules/readerstyletweak.lua]: I believe now is perfectly centred, have a look

Comment (poire-z) [reply frontend/apps/reader/modules/readerstyletweak.lua]: yep it is.

File: frontend/ui/widget/inputtext.lua (hunk 3 above)
Comment (poire-z) [reply frontend/ui/widget/inputtext.lua:179]: > > It fells akward to just externalize one of them :/ I would clean it all.
> 
> the other ones are proceeding functions, this one on the other hand is just a menu declaration, I don't know.. be my guess I suppose.

I'm not sure I understand.
I'm talking about these:
```
        function InputText:onTapTextBox(arg, ges)
        function InputText:onHoldTextBox(arg, ges)   - the one you're somehov moving up in the module
        function InputText:onSwipeTextBox(arg, ges)
        function InputText:onFocus()
        function InputText:onUnfocus()
```
Usually, in most other widgets, all these methods are defined no matter we use them or not depending on touch/key device. It's just the ges_events / key_events that are created or not depending on device capabilities.

Anyway, you moved InputText:holdTextBox a bit far away from its buddies, . It would make more sense to have it nearer (ie. just below InputText.initInputEvents()) if we move around just this one.

Comment (Commodore64user) [reply frontend/ui/widget/inputtext.lua:179]: whether those should or should not be defined there, is not my PR business, ;). Having it too close however means a big chunk of code history goes away as most of al gets attributed to me, is weird..

File: frontend/ui/widget/inputtext.lua [hunk 4]
```diff
@@ -173,117 +173,7 @@ local function initTouchEvents()
...
-                                    self:addChars(clipboard_value)
-                                end,
-                            },
-                        },
-                    },
-                }
-                UIManager:show(clipboard_dialog)
-            end
-            self._hold_handled = true
+            self:holdTextBox(arg, ges)
```
Comment (poire-z) [inline frontend/ui/widget/inputtext.lua:177]: You could add this comment:
`-- Logic moved below as it is also used when not isTouchDevice`
so we won't be wondering when in 5 years when all NT devices eventually get dead batteries, we decide to remove all this non-touch ugly legacy code :)

File: frontend/ui/widget/inputtext.lua (hunk 3 above)
Comment (poire-z) [reply frontend/ui/widget/inputtext.lua:179]: The attribution should just impact these lines moved, wherever you moved them. Not the other lines in-between or above or below.
And yes, history/context for the section you moved is gone :/

Comment (Commodore64user) [reply frontend/ui/widget/inputtext.lua:179]: what I meant was, originally I was moving them to just the end of that init, and somehow it was rewriting all the history, even from lines I wasn't touching, to attribute them to me.

File: frontend/ui/widget/inputtext.lua (hunk 4 above)
Comment (Commodore64user) [reply frontend/ui/widget/inputtext.lua:177]: done

File: frontend/apps/reader/modules/readerstyletweak.lua [hunk 5]
```diff
@@ -158,6 +161,20 @@ function TweakInfoWidget:init()
...
 
+    if Device:hasDPad() then
+        self.css_frame.onPress = function()
+            local item = self:getFocusItem()
+            if item == self.css_frame and Device:hasClipboard() then
+                self:copyTextToClipboard(self.css_text)
+                return true
+            end
+        end
+        self.layout = {}
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerstyletweak.lua]: Can't the Device:hasClipboard() be put upper ?
:hasDPad() and :hasClipboard()
or
if Device:hasClipboard()  then self.css_frame.onPress  ?

**Review by poire-z — APPROVED** [review]
