### PR TITLE
[KeyValuePage] back button returns to parent

### LINKED ISSUE #14266: (kindle NT) no way to go back to previous window when inside a widget.
### Device

Kindle

### KOReader version

2025.08

### Model and firmware version

kindle 4, fw 4.1.4

### Issue description

Image

this is _reading statistics:show time range>books by month_. i can't find a way to click the _go back to previous page_ button on the bottom left corner (or the '<<' and '>>' buttons).

in file browser, i've mapped the 'back' button to take me one step up the folder tree, so that's no issue, but inside widgets, there's no way to go back to the previous window. back button just closes the entire thing. i tried every possible button combination. nothing works. 

### Steps to reproduce

- open _reading stats:show time range_ and click any option in that window. 
- try going back to the previous window. 

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

* Added a new `onCloseWithKey()` method that checks for a return arrow and callback before invoking the appropriate close or return logic, providing clearer behavior when closing the page via a key event.

*  fix #14266

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14270)

### CODE REVIEW

**Comment by zenixlabs** [comment]
thanks. is there any way to emulate taps on << and >> buttons?

File: frontend/ui/widget/keyvaluepage.lua [hunk 1]
```diff
@@ -818,6 +818,15 @@ function KeyValuePage:onClose()
     return true
 end
 
+function KeyValuePage:onCloseWithKey()
+    if self.page_return_arrow and self.callback_return ~= nil then
+        self:onReturn()
```
Comment (Frenzie) [inline frontend/ui/widget/keyvaluepage.lua]: This kind of reads like it should say something like

```lua
    if self.page_return_arrow and self.callback_return then
        self:callback_return()
```

?

Comment (Commodore64user) [reply frontend/ui/widget/keyvaluepage.lua]: although the `~= nil` could theoretically go, the call to `self:callback_return()` would mean it never gets to exit the widget, so `onReturn()` is correct, furthermore it does the screen cleaning as well.

edit: ignore that, it makes sense if you (unlike me) don't return early

**Comment by Commodore64user** [comment]
> thanks. is there any way to emulate taps on << and >> buttons?

in FM yes, <kbd>screenkb</kbd> + <kbd>page up/down</kbd> , this widget, nope. I wasn't even aware of this widget, I wasn't even aware you could go multiple layer deep into the statistics

File: frontend/ui/widget/keyvaluepage.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/ui/widget/keyvaluepage.lua]: It looks like the weird thing was simply that `if self.callback_return`. With that removed it'd also have made sense since onReturn() seems to already do that check. It just read strangely as it was because it reads unrelated.

https://github.com/koreader/koreader/blob/c78047b0fef0a4beab58e9d75075ce4793e7f0ec/frontend/ui/widget/keyvaluepage.lua#L839-L845

Comment (Frenzie) [reply frontend/ui/widget/keyvaluepage.lua]: That being said, it's probably clearer the way it is written now, clearly indicating that a callback is used etc.

**Comment by Commodore64user** [comment]
I promise I haven’t been sitting on this, waiting for day 7 to dawn ;) Any further comments? @Frenzie
