### PR TITLE
fullscreen toggle for Jelly Bean devices

### LINKED ISSUE #4794: [Android 4.x]: Bottom of Screen being cut-off by navigation bar.
#####KOreader version
KoReader 2019.03

######Device Information
Energy Sistems Ereader Pro Plus
Model Number : Energy_eReaderProP
Android Version : 4.2.2
Kernel Version : Energy_ereaderProP_2016011214
Build No : Energy_ereaderProP_V2.0.0_2016011214
Energy Version : 3.0.0B

####### Other Information :
Running the e-Ink Test returns :
Manufacturer : Energy_Sistem
Brand : Energy_Sistem
Model : eReaderProPlus
Product : Energy_eReaderProP
Hardware : rk30board

fake update = does nothing
rk30xx normal update = screen refresh
rk30xx forced update = screen refresh

#### Issue
The lowest part of the screen is used by Android for the "Home", "Back" etc buttons. This obscures the lowest part of KoReader's display and it is impossible to see all of the bottom menu and dependant on font size, margins etc the bottom lines of text in a book are also obscured.

There is no "Full Screen" option visible in the KoReader settings menu.

Two photo's of the screen are attached - one shows the display with the Android System Menu (Back, Home, Frontlight etc) as a hidden (Black) display attempting to display the KOreader bottom menu The other a menu screen where "Full Screen " option would be expected and with the Android System Menu (visible this time) cutting off the lowest lines of the book text.

#### Illustrations
KoReader-1

KoReader2

##### `crash.log` (if applicable)
`N/A

### PR DESCRIPTION
**Pull request by pazos**
Work in progress: 

Things work but the new viewport is not changed without reloading current app (I mean the reader or the file manager). 
Move the old toggleFullscreen for apis 14-16 to device/android/device.lua?

requires https://github.com/koreader/android-luajit-launcher/pull/148
fixes #4794

### CODE REVIEW

File: frontend/ui/elements/common_settings_menu_table.lua [hunk 1]
```diff
@@ -166,8 +166,8 @@ if Device:isAndroid() then
         }
     end
 
-    -- fullscreen toggle on devices with compatible fullscreen methods (apis 14-16)
-    if Device.firmware_rev <= 16 then
+    -- fullscreen toggle on devices with compatible fullscreen methods (apis 14-18)
+    if Device.firmware_rev < 19 then
```
Comment (Frenzie) [inline frontend/ui/elements/common_settings_menu_table.lua]: Maybe a little info message that a restart is required for changes to take effect?

Comment (pazos) [reply frontend/ui/elements/common_settings_menu_table.lua]: done, but only for jelly bean apis.

**Comment by pazos** [comment]
Also removed the patch.lua workaround now that is useless

**Comment by pazos** [comment]
### before -> toggle -> after
Sin nombre

**Comment by poire-z** [comment]
> Also removed the patch.lua workaround now that is useless

Might be useless in your context of fixing screen geometry, but it could be useful in other contexts :)
I haven't played with it much recently, but on Android, there's nothing much else to be able to play and tweak stuff, eg https://github.com/koreader/koreader/issues/3871#issuecomment-381229246.

So, I don't know. Do you really need to get rid of it so current users who had it to tweak viewport don't go mess with your latest changes?
If not, it would be best to keep that available as a possibility for quick tweaks/tests.

**Comment by pazos** [comment]
> > Also removed the patch.lua workaround now that is useless
> 
> Might be useless in your context of fixing screen geometry, but it could be useful in other contexts :)
> I haven't played with it much recently, but on Android, there's nothing much else to be able to play and tweak stuff, eg [#3871 (comment)](https://github.com/koreader/koreader/issues/3871#issuecomment-381229246).
> 
> So, I don't know. Do you really need to get rid of it so current users who had it to tweak viewport don't go mess with your latest changes?
> If not, it would be best to keep that available as a possibility for quick tweaks/tests.

A half approach would be renaming patch.lua to runtime.lua, so old users who added fancy things there can rename their patch file and users who added things to workaround screen.height can forget about it.

What do you think?

**Comment by poire-z** [comment]
That's fine with me :)
(patch.lua was a nice and explicite filename, runtime.lua a bit less, but better than nothing at all :)

**Comment by pazos** [comment]
The worst thing that can happen if we leave patch.lua as is: bug reports from people saying "the window doesn't fill the screen". I can live with that :+1:

**Comment by NiLuJe** [comment]
I don't know how feasible and/or annoying that would be, but perhaps add a, unobtrusive visual indicator somewhere if a patch.lua is in effect?

**Comment by pazos** [comment]
> I don't know how feasible and/or annoying that would be, but perhaps add an unobtrusive visual indicator somewhere if a patch.lua is in effect?

I don't want to do that unless it can be done with a Text to Speech engine :smile:

**Comment by zeroheure** [comment]
thanks!

**Comment by szebrowski** [comment]
bump?

**Comment by Frenzie** [comment]
@szebrowski This was merged over a year ago. Please ask on the forum or report a bug.
