### PR TITLE
[MultiInputDialog] vertically centre multi input dialogue

### LINKED ISSUE #12914: multi input widgets not vertically centred
* KOReader version: 2024.11
* Device: kindle 3/4

#### Issue

`MultiInputDialog` widget (`WidgetContainer` too) is not vertically centred when `[ ] Show virtual keyboard` is unchecked (i.e they appear to assume the VK is still present when it is not). As far as I can see, all other widgets seem to behave just fine, they've made it to the "good list", just the multiple input ones making it to the "naughty list".

#### Steps to reproduce

uncheck show virtual keyboard
go to a setting with a multi input widget

##### screenshots

<p align="center">
 

</p>

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

* [`frontend/ui/widget/multiinputdialog.lua`](diffhunk://#diff-ec760af17116d6a9eb1ebd6cfcb2a3dd5ecf8d242af8cb2b061cdec5dbac583dR113-R119): Added initialization for the `keyboard_visible` property in the `MultiInputDialog:init()` function to determine if the keyboard should be visible based on device and reader settings.
* [`frontend/ui/widget/multiinputdialog.lua`](diffhunk://#diff-ec760af17116d6a9eb1ebd6cfcb2a3dd5ecf8d242af8cb2b061cdec5dbac583dR218-R222): Adjusted the height of the `CenterContainer` to account for the keyboard height only if the keyboard is visible.
* Removed pesky whitespaces

### screenshots

<p align="center">
before/after
</p> 
<p align="center">

 
</p>

* fix #12914

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12951)

### CODE REVIEW

**Comment by poire-z** [comment]
Looks alright and simple.
Let's see what @NiLuJe thinks.

File: frontend/ui/widget/multiinputdialog.lua [hunk 1]
```diff
@@ -110,6 +110,13 @@ function MultiInputDialog:init()
     self:onCloseKeyboard()
     self._input_widget:onCloseWidget()
 
+    -- Initialize keyboard_visible
+    if (Device:hasKeyboard() or Device:hasScreenKB()) and G_reader_settings:isFalse("virtual_keyboard_enabled") then
+        self.keyboard_visible = false
+    else
+        self.keyboard_visible = true
+    end
```
Comment (NiLuJe) [inline frontend/ui/widget/multiinputdialog.lua:118]: This should already be handled via the call to the super class's init (i.e., `InputDialog.init(self)`), whihc handles the `false` branch, couplmed with the fact that the (super) class default is `true`.

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua:118]: I believe that `onCloseKeyboard` kills the tracking because, any further attempt to call `self.keyboard_visible` is always nil

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua:118]: I believe that `onCloseKeyboard` kills the tracking because, any further attempt to call `self.keyboard_visible` is always nil

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua:118]: disregard the previous comment. however `self.keyboard_visible` is simply `true` even when it shouldn't

```lua
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "1")
    -- init title and buttons in base class
    InputDialog.init(self)
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "2")
    -- Kick InputDialog's own field out of the layout, we're not using it
    table.remove(self.layout, 1)
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "3")
    -- Also murder said input field *and* its VK, or we get two of them and shit gets hilariously broken real fast...
    self:onCloseKeyboard()
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "4")
    self._input_widget:onCloseWidget()
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "5")

    -- Initialize keyboard_visible
    -- if (Device:hasKeyboard() or Device:hasScreenKB()) and G_reader_settings:isFalse("virtual_keyboard_enabled") then
    --     self.keyboard_visible = false
    -- else
    --     self.keyboard_visible = true
    -- end
    logger.dbg("MultiInputDialog:", self.keyboard_visible, "6")
```

```
12/28/24-22:33:56 DEBUG MultiInputDialog: true 1 
12/28/24-22:33:57 DEBUG MultiInputDialog: false 2 
12/28/24-22:33:57 DEBUG MultiInputDialog: false 3 
12/28/24-22:33:57 DEBUG MultiInputDialog: true 4 
12/28/24-22:33:57 DEBUG MultiInputDialog: true 5 
12/28/24-22:33:57 DEBUG MultiInputDialog: true 6 
```

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: or should we do this instead?

```lua
function InputDialog:onCloseKeyboard()
    self._input_widget:onCloseKeyboard()
    if (Device:hasKeyboard() or Device:hasScreenKB()) and G_reader_settings:isFalse("virtual_keyboard_enabled") then
        return
    end
    self.keyboard_visible = self._input_widget:isKeyboardVisible()
end
```

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: Hmm. Probably less mysterious with the duplication you went with, as it sort of matches the super class.

I would *definitely* add a comment about this being needed *because* ` InputDialog:onCloseKeyboard` updates `InputDialog:onCloseKeyboard` though ;).

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: > Hmm. Probably less mysterious with the duplication you went with, as it sort of matches the super class.

By which I meant, less chance of unintended and unexpected side-effects ;).

Couldn't word that properly this morning ;p.

**Review by NiLuJe — APPROVED** [review]
Untested, but looks sensible & sound.

File: frontend/ui/widget/multiinputdialog.lua [hunk 2]
```diff
@@ -110,6 +110,12 @@ function MultiInputDialog:init()
     self:onCloseKeyboard()
     self._input_widget:onCloseWidget()
 
+    -- Update self.keyboard_visible, this is needed because InputDialog:onCloseKeyboard updates it regardless of whether
+    -- G_reader_settings("virtual_keyboard_enabled") is disabled, which can lead to an incorrect keyboard visibility state.
```
Comment (hius07) [inline frontend/ui/widget/multiinputdialog.lua:114]: Can you find out why so? Maybe it should be fixed somewhere?

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua:114]: That's what I meant by https://github.com/koreader/koreader/pull/12951#discussion_r1900437021

`InputDialog:onCloseKeyoard` does what it says on the tin: it closes the KB, which means it's no longer visible.

Modifying its behavior just to fix this very specific interaction seems like it could lead to more unintended consequences than just dealing with it this way here.

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua:114]: > `InputDialog:onCloseKeyoard` does what it says on the tin: it closes the KB, which means it's no longer visible, so it forcibly always sets the visibility flag to `false`.

Well, technically, to `self._input_widget:isKeyboardVisible()`, which should pretty much always lead to a `false` after `InputText:onCloseKeyboard()` ;).

File: frontend/ui/widget/multiinputdialog.lua (hunk 1 above)
Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: this happens when we are not hiding the VK, i.e default case for all devices.
```
01/02/25-00:14:44 DEBUG MultiInputDialog: true 2 
01/02/25-00:14:44 DEBUG MultiInputDialog: true 3 
01/02/25-00:14:44 DEBUG MultiInputDialog: true 4 
01/02/25-00:14:44 DEBUG MultiInputDialog: true 5 
```

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: Yep, that's what I meant by "it defaults to`true` in the superclass".

c.f., 
https://github.com/koreader/koreader/blob/016592e0a3300ad645583df4b6c36f5efd1e708e/frontend/ui/widget/inputdialog.lua#L144-L145

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: > Yep, that's what I meant by "it defaults totrue in the superclass".

Yes i get that bit, but shouldn't the onClose set it to false?
But then multiinput would not know that a new keyboard is incoming with the onOpenKB handler (for whatever specific instance) and would always place it in the middle. I might be losing my mind...

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: Which onClose are we talking about, where, and when?

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: The one just above `logger.dbg("MultiInputDialog:", self.keyboard_visible, "4")`

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: Huh. that's... interesting. Absolutely no time to check, but might be an artifact from being in `init` on all sides still.

Comment (NiLuJe) [reply frontend/ui/widget/multiinputdialog.lua]: Had a Eureka moment on the toilet. #12994

Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: > Had a Eureka moment on the toilet. #12994

I hope you only had one eureka moment there, and if you had more than one, please don’t share number 2. ;)

Comment (Frenzie) [reply frontend/ui/widget/multiinputdialog.lua]: In binary that'd be equal volume number 1.

I'll see myself out.

**Review by NiLuJe — APPROVED** [review]
LGTM!

(Now depends on #12994 though)

File: frontend/ui/widget/multiinputdialog.lua (hunk 1 above)
Comment (Commodore64user) [reply frontend/ui/widget/multiinputdialog.lua]: Defecation joke tally: ~~No. 2~~

Oops. No. 3 now...
