### PR TITLE
android bugfixes

### LINKED ISSUE #5221: Android/Amazon Fire OS slowdown after 2019.04
* KOReader version: 2019.05 and higher
* Device: Amazon Fire HD 8.9" (2012, Fire OS 8.5.1, Android 4.0.3 based), Amazon Fire HD 7 (2013, Fire OS 8.5.5.3, Android 4.4 based)

#### Issue

koreader release 2019.04 is snappy and overall works quite well on these devices. koreader release 2019.05 and higher, including the current 2019.08 release, seem to be quick at starting up and loading a PDF file and turning the page. Yet, the menu interface and the file browser are slow and lag significantly responding to input. I timed repeating the same actions in 2019.04 and 2019.05 and found significant lag on the slower Amazon Fire HD 8.9".

File browser speed:
* 2019.04 - page 2 load time < 1 sec, page 1 load time < 1 sec
* 2019.05 - page 2 load time ~15 secs, page 1 load time ~24 secs.

The other Fire device was noticeably slower as well but less obviously so, presumably due to faster hardware.

#### Steps to reproduce

Download 2019.04 release and 2019.05 release for Android ARM on to an older or low-end Android device. Install one at a time and time performing menu actions and loading file browser screens, esp. where the browser has a long list of file to draw previews and spans more than one screen.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

### LINKED ISSUE #5228: Installed the last night build and can't start Koreader in android
I' was using a nighty build from the previous month and resolved to install the last nighty build from today and Koreader for android can't start anymore.

Follow the log:

[android.log](https://github.com/koreader/koreader/files/3517973/android.log)

### PR DESCRIPTION
**Pull request by pazos**
Fixes  #5228  (by fixing my own stupidity on #5207)
Hopefully fixes #5221  on any problematic device (aside from Tolinos on fw10).

### CODE REVIEW

File: frontend/device/android/device.lua [hunk 1]
```diff
@@ -173,14 +173,13 @@ function Device:init()
...
-        if timeout > 0 then
+        if timeout and timeout > 0 then
             -- set a custom timeout if we already have write settings permission.
             -- do not attempt to request permissions here.
             if android.canWriteSettings() then
                 android.setScreenOffTimeout(timeout)
             end
-        elseif timeout == -1 then
+        elseif timeout and timeout == -1 then
             android.setScreenOffTimeout(timeout)
```
Comment (poire-z) [inline frontend/device/android/device.lua]: You don't need to check `if android.canWriteSettings()`  in the `timeout == -1` case?

Comment (pazos) [reply frontend/device/android/device.lua]: nope, wakelock doesn't need write permissions.

Comment (pazos) [reply frontend/device/android/device.lua]: the same happens if android.needsWakelocks()
