### PR TITLE
A couple of minor UI fixes

### LINKED ISSUE #7230: Black leftovers when long-pressing bookmarks
* KOReader version: v2021.01.1-21-g285fc75a_2021-02-02
* Device: emulator

#### Issue

When long-pressing an entry in the list of bookmarks to get the "delete" option, the entry is highlighted in black, a dialog is shown on top (the black highlight can be seen on the sides), and when the dialog is dismissed the black highlight on the sides remains.

On my device (Kobo Aura, v2021.01.1) it looks almost the opposite: the black highlight that should be covered by the dialog shows on top of it instead, but the sides remain white. Either this has been "fixed" since then, or it's a device-specific behavior?

#### Steps to reproduce

1. Create a few bookmarks (1 is enough, but 2-3 allows more testing).
2. Go to Bookmarks.
3. Long-press one of the entries.
4. Press on Close

The highlight "behind" the dialog.
Screenshot_1

The leftover after closing the dialog.
Screenshot_2

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #7230 & #7231

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7232)

### CODE REVIEW

File: frontend/ui/data/creoptions.lua [hunk 1]
```diff
@@ -337,6 +337,7 @@ Note that your selected font size is not affected by this setting.]]),
         options = {
             {
                 name = "font_size",
+                alt_name_text = _("Font Size"),
```
Comment (Frenzie) [inline frontend/ui/data/creoptions.lua:340]:
```suggestion
                alt_name_text = _("Font size"),
```

**Review by Frenzie — APPROVED** [review]
lgtm

**Review by poire-z — APPROVED** [review]
