### PR TITLE
Fix file transfer from Calibre to Remarkable Paper Pro

### LINKED ISSUE #13731: File transfer from Calibre to the Remarkable Paper Pro fails
### Device

ReMarkable

### KOReader version

latest master branch

### Model and firmware version

Remarkable Paper Pro firmware 3.18

### Issue description

Attempting to transfer files to the rmpp via Calibre with koreader running on the rmpp results in an error about no free space on device.

### PR DESCRIPTION
**Pull request by gray-open**
The output of df wraps on to multiple lines on the rmpp due to the device mapped mount points. Enabling the posix -P option to df prevents this and allow the output to be parsed as normal.

Closes #13731

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/13732)

### CODE REVIEW

File: frontend/util.lua [hunk 1]
```diff
@@ -920,7 +920,7 @@ end
 function util.diskUsage(dir)
     -- safe way of testing df & awk
     local function doCommand(d)
-        local handle = io.popen("df -k " .. util.shell_escape({d}) .. " 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
+        local handle = io.popen("df -kP " .. util.shell_escape({d}) .. " 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
```
Comment (Frenzie) [inline frontend/util.lua:923]: Supported on busybox since 2008, so should be fine.

**Review by Frenzie — APPROVED** [review]
