### PR TITLE
Fix for OTA updates w/ zsync

### LINKED ISSUE #12115: OTA manager crash: getZsyncFilename
* KOReader version: anything after commit number 205 

https://github.com/koreader/koreader/commit/617618d5878591f47f7b0b35de9042de3d19a950#diff-78c3d893c874173e65c3668e2ea45fdc791c5abb719f3c90ff43111c7aa61bce

image

* Device: Kindle Scribe (5.16.2)

#### Issue
Crash on KOReader update after it finds there is a new version and I hit Update.
Pinging @pazos 

##### `crash.log` (if applicable)
Full: [ota_crashlog.txt](https://github.com/user-attachments/files/16033087/ota_crashlog.txt)

Crash:
```
./luajit: frontend/ui/otamanager.lua:371: attempt to call method 'getZsyncFilename' (a nil value)
stack traceback:
	frontend/ui/otamanager.lua:371: in function 'zsync'
	frontend/ui/otamanager.lua:229: in function 'action'
	frontend/ui/uimanager.lua:1020: in function '_checkTasks'
	frontend/ui/uimanager.lua:1470: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013ebd
lipc-wait-event exited normally with status: 0
```

### PR DESCRIPTION
**Pull request by pazos**
Fixes #12115

Kobos, Kindles, Remarkables, Cervantes and Pocketbooks that updated to latest (couple of?) nightlies need to perform a manual update.

Sorry :/

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12120)

### CODE REVIEW

**Comment by Frenzie** [comment]
Ultimately it's what they're there for. ^_^

Btw,
```
    frontend/ui/otamanager.lua:77:39: accessing undefined variable model
    frontend/ui/otamanager.lua:77:46: accessing undefined variable channel
```

File: frontend/ui/otamanager.lua [hunk 1]
```diff
@@ -73,12 +73,16 @@ function OTAManager:setOTAChannel(channel)
     G_reader_settings:saveSetting("ota_channel", channel)
 end
 
+function OTAManager:getZsyncFilename()
+    return self.zsync_template:format(model, channel)
```
Comment (Frenzie) [inline frontend/ui/otamanager.lua:77]: Probably best to use it as it was?
```suggestion
    return self.zsync_template:format(self:getOTAModel(), self:getOTAChannel())
```

**Comment by mergen3107** [comment]
> that updated to latest (couple of?) nightlies

It is precisely -209 and -213:
```
![image](https://github.com/koreader/koreader/assets/6279855/ef1db8ef-bba7-4463-8301-a8d5ad3302fd)
```

By the way, -212 only has android stuff. @Frenzie did the build fail or something?
```
![image](https://github.com/koreader/koreader/assets/6279855/f5bbb545-07cf-493a-b3ac-ae4eecdc68fa)
```

File: frontend/ui/otamanager.lua [hunk 2]
```diff
@@ -73,17 +73,22 @@ function OTAManager:setOTAChannel(channel)
     G_reader_settings:saveSetting("ota_channel", channel)
 end
 
+
```
Comment (Frenzie) [inline frontend/ui/otamanager.lua:76]: pssht :-P

```suggestion
```

**Comment by Frenzie** [comment]
> By the way, -212 only has android stuff. @Frenzie did the build fail or something?

Yes, lua-Spore was down.

**Comment by mergen3107** [comment]
So with current diff tapping on `Check for updates` got KOReader stuck, and it doesn't time out. I only see info message with the hour glass icon.

Diff:
```
diff --git a/frontend/ui/otamanager.lua b/frontend/ui/otamanager.lua
index be2f2c210bbf..ebbb9bdafb69 100644
--- a/frontend/ui/otamanager.lua
+++ b/frontend/ui/otamanager.lua
@@ -73,17 +73,22 @@ function OTAManager:setOTAChannel(channel)
     G_reader_settings:saveSetting("ota_channel", channel)
 end
 
+
 function OTAManager:getFilename(kind)
     if type(kind) ~= "string" then return end
     local model = Device:otaModel()
     local channel = self:getOTAChannel()
     if kind == "ota" then
-        return self.zsync_template:format(model, channel)
+        return self:getZsyncFilename()
     elseif kind == "link" then
         return self.link_template:format(model, channel)
     end
 end
 
+function OTAManager:getZsyncFilename()
+    return self:getFilename("ota")
+end
+
 function OTAManager:checkUpdate()
     if Device:isDeprecated() then return -1 end
     local http = require("socket.http")
```

**Comment by mergen3107** [comment]
Crash.log didn't update neither, so I don't know what's going on

**Comment by mergen3107** [comment]
This is probably because these two functions are now in an infinite loop once `getZsyncFilename()` is called:
```
function OTAManager:getFilename(kind)
    if type(kind) ~= "string" then return end
    local model = Device:otaModel()
    local channel = self:getOTAChannel()
    if kind == "ota" then
        return self:getZsyncFilename()
    elseif kind == "link" then
        return self.link_template:format(model, channel)
    end
end

function OTAManager:getZsyncFilename()
    return self:getFilename("ota")
end
```

**Comment by mergen3107** [comment]
I think I fixed it by replacing 
```
if kind == "ota" then
        return self:getZsyncFilename()
```

by
```
if kind == "ota" then
        return self.zsync_template:format(model, channel)
```

I was able to check back stable and it reported correctly.

**Comment by pazos** [comment]
Thanks @mergen3107, the fix was worse than the bug :p
