### PR TITLE
Remember the final rotation during Reboot/PowerOff/AutoSuspend, too

### LINKED ISSUE #7125: PB626: screen rotation across views is not preserved after power off or restart device option is tapped
* KOReader version: v2020.12-91-g1c9c40f_2021-01-07
* Device: PB626 sw:U626.5.20.1157

#### Issue
Screen rotation across views is not preserved after power off or restart device option is tapped.

#### Steps to reproduce
1. Open Koreader
2. Exit Koreader with option Power off or Reboot the device
3. Open Koreader
4. Screen rotation is set to 0° even I have 90° clockwise defaulted - star icon

If I "exit" Koreader with option Restart Koreader or Exit, the screen rotation is preserved. Before I used v2020.12-30-gb78d9c1_2020-12-23 and this issue was not there.

Could you please check / fix it?
Thanks

### PR DESCRIPTION
**Pull request by NiLuJe**
Re #7096, Fix #7125

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7133)

### CODE REVIEW

File: reader.lua [hunk 1]
```diff
@@ -339,8 +339,8 @@ local function exitReader()
     -- Save any device settings before closing G_reader_settings
     Device:saveSettings()
 
-    --  Save current rotation to have it for next startup
-    G_reader_settings:saveSetting("closed_rotation_mode", Device.screen:getRotationMode())
+    -- Save current rotation (or the actual rotation if ScreenSaver temporarily modified it) to remember it for next startup
```
Comment (yparitcher) [inline reader.lua:342]:
```suggestion
    -- Save current rotation (or the original rotation if ScreenSaver temporarily modified it) to remember it for next startup
```

**Review by Frenzie — APPROVED** [review]
