### PR TITLE
Kindle Scribe: fix touch input

### LINKED ISSUE #11199: KOL/KUAL: freeze of touch right after Kindle reboot
* KOReader version: v2023.10-37, -41, -55
* Device: Kindle Scribe (5.16.2)

#### Issue and Steps to reproduce
I noticed that frequently (about 6/10 times) this happens:
1) I reboot Kindle normally
2) Wait until home screen shows up
3) Very soon (within 3-5 seconds once it is loaded) hit KOL 1.3.6 icon to start KOReader in normal mode directly.
4) KOReader shows up OK, opens the book.
5) However, touch input is not working, both taps and swipes. I can press power button - usual screensaver shows up, press power button again - it wakes up, so KOReader and the system are not frozen, just the input lost somewhere in between those two. SSH works as well, but `lipc` command to call home doesn't work, probably `awesome` & Co. are shutdown at the moment.

I then just end up hard restarting by power button. Upon boot, I need to re-enable device passcode, because KOReader was shutdown and didn't have a chance to restore it.

I tried with and without USBnet - by uninstalling it via mrpi (which every time worked, but then a new KPV-something-something error log showed up in the /documents folder, but that's another story :D).

Launching from KUAL - KOReader menu works OK every time, so I am pretty sure it is KOL.

##### `crash.log` (if applicable)
KOReader's crash.log (this one is from yesterday, but today's "freezes" were about the same: 
[crash_KOL_startup_freeze.txt](https://github.com/koreader/koreader/files/13541244/crash_KOL_startup_freeze.txt)

In these cases, it always ends at this line:
```
12/02/23-23:28:35 INFO  Restoring user input handling 
```

FWIW, here is the `/var/log/messages` file that I backed up: 
[messages.txt](https://github.com/koreader/koreader/files/13541261/messages.txt)

**P.S.**
After all this and when I found that KUAL-launch works OK every time, I removed KOL for now. Then also disabled Amazon logging. I plan to just read upcoming weekdays, but I can come back to logs next weekend and try to reproduce if needed.

Please let me know what else I can provide in the meanwhile.

### PR DESCRIPTION
**Pull request by mergen3107**
Closes #11199 , that reported about touch input unresponsiveness if KOReader was started very soon after a fresh Kindle reboot, both via KUAL and KOL.

Context: the old touch device was in fact a Wacom Digitizer (`event3`).
The new `touch` device is the true touch device, `event2`.

Why the old input device worked in all other cases (at all!) is still a lab126 mistery. My suspicion is that down the road of startup, Wacom Digitizer is then duplicated as a touch. However, this transition doesn't seem to have enough time to kick in, and probably gets murdered among other stuff that `koreader.sh` needs to murder during its startup.

Thank you @NiLuJe !

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11285)

### CODE REVIEW

File: frontend/device/kindle/device.lua [hunk 1]
```diff
@@ -638,7 +638,7 @@ local KindleScribe = Kindle:extend{
     hasLightSensor = yes,
     hasGSensor = yes,
     display_dpi = 300,
-    touch_dev = "/dev/input/by-path/platform-1001e000.i2c-event",
+    touch_dev = "/dev/input/touch",
```
Comment (Frenzie) [inline frontend/device/kindle/device.lua:641]: This is better on all devices? It looks a bit suspicious as a diff.

Comment (mergen3107) [reply frontend/device/kindle/device.lua:641]: I don't know about any other device, but this is the only solution for Kindle Scribe.

Comment (mergen3107) [reply frontend/device/kindle/device.lua:641]: P.S. NiLuJe and I discussed this in length today from https://github.com/koreader/koreader/issues/11199#issuecomment-1870512410 and on

**Review by NiLuJe — APPROVED** [review]

File: frontend/device/kindle/device.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/device/kindle/device.lua:641]: I'd missed that it wasn't in the generic definition through the mobile diff.
