### PR TITLE
Unbreak OTA on Kindle

### LINKED ISSUE #5721: Cannot be relaunched after update
* KOReader version:v2019.11-51-ge8f91ab_2019-12-03
* Device:KPW3-32G

Cannot be relaunched after update. Just like issue #5269.
[crash.log](https://github.com/koreader/koreader/files/4014171/crash.log)

### PR DESCRIPTION
**Pull request by NiLuJe**
Regression since #5715 (because I forgot to test with tarballs, and links be weird).

Also, pile on yet another stupid Kindle workaround to make sure an OTA update won't break the launcher script itself because of truncation, which would break the exit sequence, leaving the user with an apparently hung device, simply because the WM was never unpaused...

Yay Kindle. -_-"

Fix #5721

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5758)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Wasn't technically broken (well, more broken than usual :D) in the previous stable, so not putting this in a milestone).

**Comment by Frenzie** [comment]
> (Wasn't technically broken (well, more broken than usual :D) in the previous stable, so not putting this in a milestone).

I'm not sure if that quite makes sense. I see it more as things that are part of it, in any case.

File: Makefile [hunk 1]
```diff
@@ -202,7 +202,7 @@ kindleupdate: all
 	# note that the targz file extension is intended to keep ISP from caching
 	# the file, see koreader#1644.
 	cd $(INSTALL_DIR) && \
-		tar -I"gzip --rsyncable" -cah --no-recursion -f ../$(KINDLE_PACKAGE_OTA) \
+		tar --hard-dereference -I"gzip --rsyncable" -cah --no-recursion -f ../$(KINDLE_PACKAGE_OTA) \
```
Comment (Frenzie) [inline Makefile]: This is technically only for Kindle?

(I'm fine keeping it the same everywhere for simplicity; just asking.)

File: platform/kindle/koreader.sh [hunk 2]
```diff
@@ -1,4 +1,15 @@
 #!/bin/sh
+
+# NOTE: Stupid workaround to make sure the script we end up running is a *copy*,
+# living in a magical land that doesn't suffer from gross filesystem deficiencies.
+# Otherwise, the vfat+fuse mess means an OTA update will break the script on exit,
+# and potentially leave the user in a broken state, with the WM still paused...
+if [ "$(dirname "${0}")" != "/var/tmp" ]; then
```
Comment (Frenzie) [inline platform/kindle/koreader.sh]: Does it need to be preserved on reboot?

Comment (NiLuJe) [reply platform/kindle/koreader.sh]: It's a tmpfs, so it'll go poof on reboot.

I'm fine with leaving however kb this takes when we exit, it's 32MB by default, we've got more than enough space in there ;).

File: Makefile (hunk 1 above)
Comment (NiLuJe) [reply Makefile]: Yeah, although I figured this couldn't hurt, since most of those will be deployed on vfat anyway, and all of them were already using `--dereference` (`h`).

File: platform/kindle/koreader.sh (hunk 2 above)
Comment (NiLuJe) [reply platform/kindle/koreader.sh]: Although, since it's no longer on a crappy FS, it also wouldn't hurt to unlink on exit, now that I think about it ;).

Comment (Frenzie) [reply platform/kindle/koreader.sh]: It will? Hmm… odd.

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s15.html
>5.15. /var/tmp : Temporary files preserved between system reboots
>5.15.1. Purpose
>
>The /var/tmp directory is made available for programs that require temporary files or directories that are preserved between system reboots. Therefore, data stored in /var/tmp is more persistent than data in /tmp.
>
>Files and directories located in /var/tmp must not be deleted when the system is booted. Although data stored in /var/tmp is typically deleted in a site-specific manner, it is recommended that deletions occur at a less frequent interval than /tmp.

Comment (Frenzie) [reply platform/kindle/koreader.sh]: Anyway, I guess I mean that /var/tmp seems needlessly longer than /tmp if there's no special reason to prefer /var/tmp

Comment (NiLuJe) [reply platform/kindle/koreader.sh]: I don't have the Kindle plugged in for details, but /var is a tmpfs on Kindle, and /tmp is either not one at all, or another, much smaller one, and that one might be noexec in some setups.

So, yeah, /var/tmp should be a safer bet than /tmp, on Kindle at least ;).

(FWIW, both /tmp and /var/tmp are tmpfs on my desktop ^^).

Comment (NiLuJe) [reply platform/kindle/koreader.sh]: The TL;DR being: That was a concerted decision after checking the state of /tmp vs. /var/tmp on various Kindle generations ;).

**Comment by Hzj-jie** [comment]
Interesting, on my voyage, /var is tmpfs, no /tmp entry. E.g. it's rootfs?

**Comment by NiLuJe** [comment]
Possibly (so, triple threat: not a tmpfs, noexec, and, worst of all, ro :D).
