### PR TITLE
Startup: Instantiate FileManagerHistory properly

### LINKED ISSUE #7617: Crash upon attempt to re-orient device when starting on HISTORY
* KOReader version: 2021.04 (latest avab via in-app update)
* Device: kobo libra h20

#### Issue

Crash upon attempt to re-orient device when starting on HISTORY

#### Steps to reproduce
1. Start app (on HISTORY page)

2. It's upside down: turn the device to orient it the right way

3. Crash

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
Original fb rotation is set @ 2
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Libra H2O (384 => Storm @ Mark 7)
Variable fb info: 1264x1680 (1280x1792), 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 5120 bytes
Device's expected Portrait orientation should be: 0 (Upright, 0°)!

Switching fb to 8bpp @ rotation 0 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 0 (Upright, 0°)

Variable fb info: 1264x1680 (1280x3584), 8bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/21-09:16:57
 [*] Version: v2021.04

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
04/29/21-09:16:57 DEBUG FB info (post fixup) {
    ["yoffset"] = 0,
    ["xres_virtual"] = 1264,
    ["yres_virtual"] = 1680,
    ["smem_len"] = 9175040,
    ["mmio_len"] = 0,
    ["width_mm"] = 4294967295,
    ["xres"] = 1264,
    ["yres"] = 1680,
    ["height_mm"] = 4294967295,
    ["line_length"] = 1280,
    ["fb_size"] = 2150400,
    ["type"] = 0,
    ["stride_pixels"] = 1280,
    ["rotate"] = 0,
    ["bpp"] = 8,
    ["xoffset"] = 0,
}
04/29/21-09:16:57 DEBUG FB mapped at cdata<void *>: 0x76958000 of 2150400 bytes
04/29/21-09:16:57 DEBUG set light intensity 100
04/29/21-09:16:57 DEBUG TimeVal: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
04/29/21-09:16:57 DEBUG TimeVal: Preferred REALTIME clock source is CLOCK_REALTIME
04/29/21-09:16:57 INFO  initializing for device Kobo_storm
04/29/21-09:16:57 INFO  framebuffer resolution: {
    ["h"] = 1680,
    ["w"] = 1264,
}
[ko-input] Forked off fake event generator (pid: 1572)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Naskh Arabic
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Nimbus Sans L
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Nimbus Roman No9 L
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Sans Arabic UI
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Sans
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  NotoSans Nerd Font
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Nimbus Mono
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Sans Devanagari UI
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Serif
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  FreeSans
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Noto Sans CJK SC
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Standard Symbols L
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Droid Sans Mono
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  FreeSerif
04/29/21-09:16:58 DEBUG FONTNAMES ADD:  Dingbats
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=11.966 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 11.966/11.966/11.966 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=13.255 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 13.255/13.255/13.255 ms
04/29/21-09:16:58 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/home.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/home.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/home.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/plus.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/plus.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/plus.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/chevron.left.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/chevron.left.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/chevron.right.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/chevron.right.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/chevron.first.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/chevron.first.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/chevron.last.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/chevron.last.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:16:58 DEBUG renderSVG resources/icons/mdlight/back.top.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:16:58 DEBUG cache image|resources/icons/mdlight/back.top.svg|85|85
04/29/21-09:16:58 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:58 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:16:58 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:58 DEBUG setDirty via a func from widget table: 0x75969ff8
# 04/29/21-09:16:58  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:344: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:952: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:188: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:500: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1123: in function 'showFiles'
	./reader.lua:295: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:16:58 DEBUG Getting list of dictionaries
04/29/21-09:16:58 DEBUG found 0 dictionaries
04/29/21-09:16:58 DEBUG data is read from  ./settings/lookup_history.lua
04/29/21-09:16:58 INFO  Loading plugins from directory: plugins
04/29/21-09:16:58 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/29/21-09:16:58 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
04/29/21-09:16:58 DEBUG BackgroundRunnerWidget: no job, not running @  1619651818
ffi.load: sqlite3
04/29/21-09:16:59 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
04/29/21-09:16:59 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/29/21-09:16:59 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
04/29/21-09:16:59 DEBUG AutoSuspend: init
04/29/21-09:16:59 DEBUG AutoSuspend: unschedule
04/29/21-09:16:59 DEBUG AutoSuspend: start at 162.7982
04/29/21-09:16:59 DEBUG AutoSuspend: scheduling next suspend check in 3600
04/29/21-09:16:59 DEBUG AutoSuspend: scheduling next shutdown check in 259200
04/29/21-09:16:59 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/29/21-09:16:59 DEBUG CoverBrowser: setting FileManager display mode to: list_image_filename
04/29/21-09:16:59 DEBUG CoverBrowser: setting History display mode to: mosaic_image
04/29/21-09:16:59 DEBUG CoverBrowser: setting Collection display mode to: classic
04/29/21-09:16:59 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/29/21-09:16:59 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/29/21-09:16:59 DEBUG show widget: table: 0x75969ff8
04/29/21-09:16:59 DEBUG setDirty nil from widget table: 0x75969ff8 w/ NO region 
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:16:59 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:16:59 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:16:59 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:16:59 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:16:59 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:16:59 DEBUG setDirty via a func from widget table: 0x745299e8
# 04/29/21-09:16:59  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/menu.lua:954: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanagerhistory.lua:144: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing data
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing data
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing data
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing data
04/29/21-09:16:59 DEBUG ImageWidget: _render'ing data
04/29/21-09:16:59 DEBUG setDirty via a func from widget table: 0x745299e8
# 04/29/21-09:16:59  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
	plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:16:59 DEBUG show widget: table: 0x745299e8
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:16:59 DEBUG setDirty nil from widget table: 0x745299e8 w/ NO region AND w/ HW dithering
04/29/21-09:16:59 DEBUG not painting 1 covered widget(s)
04/29/21-09:16:59 DEBUG painting widget: table: 0x75a71cc8
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:16:59 DEBUG blitFrom 65 131 0 0 305 458
04/29/21-09:16:59 DEBUG blitFrom 65 616 0 0 306 458
04/29/21-09:16:59 DEBUG blitFrom 469 616 0 0 325 458
04/29/21-09:16:59 DEBUG blitFrom 874 616 0 0 344 458
04/29/21-09:16:59 DEBUG blitFrom 897 1101 0 0 297 458
04/29/21-09:16:59 DEBUG blitFrom 194 1590 0 0 85 85
04/29/21-09:16:59 DEBUG blitFrom 357 1590 0 0 85 85
04/29/21-09:16:59 DEBUG blitFrom 822 1590 0 0 85 85
04/29/21-09:16:59 DEBUG blitFrom 985 1590 0 0 85 85
04/29/21-09:16:59 DEBUG _repaint: it was dithered, infecting the refresh queue
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
# 04/29/21-09:16:59  triggering refresh {
    ["region"] = {
        ["h"] = 1680,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1264,
    },
    ["dither"] = true,
    ["mode"] = "ui",
}
04/29/21-09:16:59 DEBUG refresh: ui-mode 0 0 1264 1680 w/ HW dithering
04/29/21-09:16:59 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 1 (WFM: 257 & UPD: 0)
04/29/21-09:16:59 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:16:59 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:16:59 DEBUG Found font: NotoSansArabicUI-Bold.ttf in ./fonts/noto/NotoSansArabicUI-Bold.ttf
04/29/21-09:16:59 DEBUG setDirty via a func from widget table: 0x75969ff8
04/29/21-09:16:59 DEBUG setDirty via a func from widget table: 0x75969ff8
04/29/21-09:16:59 DEBUG not painting 1 covered widget(s)
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1511 
04/29/21-09:16:59 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 
# 04/29/21-09:16:59  triggering refresh {
    ["region"] = {
        ["h"] = 1680,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1264,
    },
    ["dither"] = false,
    ["mode"] = "ui",
}
04/29/21-09:16:59 DEBUG refresh: ui-mode 0 0 1264 1680 false
04/29/21-09:16:59 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 2 (WFM: 257 & UPD: 0)
04/29/21-09:16:59 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:00 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:01 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 23, time: 1619651821.968365
04/29/21-09:17:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651821.968365
04/29/21-09:17:01 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:01 DEBUG close widget: table: 0x745299e8
04/29/21-09:17:01 DEBUG CoverMenu:onCloseWidget: terminating jobs if needed
04/29/21-09:17:01 DEBUG terminating 0 subprocesses
04/29/21-09:17:01 DEBUG _refresh: Enqueued partial update for region 0 0 1264 1680 
04/29/21-09:17:01 DEBUG setDirty partial from widget nil w/ NO region 
04/29/21-09:17:01 DEBUG Lower widget table: 0x75969ff8 covers the full screen
04/29/21-09:17:01 DEBUG setDirty nil from widget table: 0x75969ff8 w/ NO region 
./luajit: frontend/apps/filemanager/filemanagerhistory.lua:131: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/apps/filemanager/filemanagerhistory.lua:131: in function 'handleEvent'
	frontend/ui/uimanager.lua:1107: in function 'sendEvent'
	frontend/ui/uimanager.lua:222: in function '__default__'
	frontend/ui/uimanager.lua:1557: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1637: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
!!!!
Uh oh, something went awry... (Crash n°1: 04/29/21 @ 09:17:02)
Running FW 4.26.16704 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/21-09:17:05
 [*] Version: v2021.04

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
04/29/21-09:17:05 DEBUG FB info (post fixup) {
    ["xoffset"] = 0,
    ["yoffset"] = 0,
    ["xres_virtual"] = 1264,
    ["yres_virtual"] = 1680,
    ["smem_len"] = 9175040,
    ["mmio_len"] = 0,
    ["width_mm"] = 4294967295,
    ["xres"] = 1264,
    ["yres"] = 1680,
    ["height_mm"] = 4294967295,
    ["line_length"] = 1280,
    ["fb_size"] = 2150400,
    ["type"] = 0,
    ["stride_pixels"] = 1280,
    ["rotate"] = 0,
    ["bpp"] = 8,
}
04/29/21-09:17:05 DEBUG FB mapped at cdata<void *>: 0x769e6000 of 2150400 bytes
04/29/21-09:17:05 DEBUG set light intensity 100
04/29/21-09:17:05 DEBUG TimeVal: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
04/29/21-09:17:05 DEBUG TimeVal: Preferred REALTIME clock source is CLOCK_REALTIME
04/29/21-09:17:05 INFO  initializing for device Kobo_storm
04/29/21-09:17:05 INFO  framebuffer resolution: {
    ["h"] = 1680,
    ["w"] = 1264,
}
[ko-input] Forked off fake event generator (pid: 1605)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Sans
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  NotoSans Nerd Font
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Sans CJK SC
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Dingbats
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Nimbus Mono
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Naskh Arabic
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Serif
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Nimbus Roman No9 L
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Standard Symbols L
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Sans Devanagari UI
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Nimbus Sans L
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  FreeSans
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Droid Sans Mono
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  Noto Sans Arabic UI
04/29/21-09:17:06 DEBUG FONTNAMES ADD:  FreeSerif
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=5.592 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 5.592/5.592/5.592 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=4.302 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.302/4.302/4.302 ms
04/29/21-09:17:06 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/home.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/home.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/home.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/plus.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/plus.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/plus.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/chevron.left.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/chevron.left.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/chevron.right.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/chevron.right.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/chevron.first.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/chevron.first.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/chevron.last.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/chevron.last.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:06 DEBUG renderSVG resources/icons/mdlight/back.top.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:06 DEBUG cache image|resources/icons/mdlight/back.top.svg|85|85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:06 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:06 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:06 DEBUG setDirty via a func from widget table: 0x7599ee20
# 04/29/21-09:17:06  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:344: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:952: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:188: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:500: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1123: in function 'showFiles'
	./reader.lua:295: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:06 DEBUG Getting list of dictionaries
04/29/21-09:17:06 DEBUG found 0 dictionaries
04/29/21-09:17:06 DEBUG data is read from  ./settings/lookup_history.lua
04/29/21-09:17:06 INFO  Loading plugins from directory: plugins
04/29/21-09:17:06 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/29/21-09:17:06 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
04/29/21-09:17:06 DEBUG BackgroundRunnerWidget: no job, not running @  1619651826
ffi.load: sqlite3
04/29/21-09:17:06 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
04/29/21-09:17:06 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/29/21-09:17:06 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
04/29/21-09:17:06 DEBUG AutoSuspend: init
04/29/21-09:17:06 DEBUG AutoSuspend: unschedule
04/29/21-09:17:06 DEBUG AutoSuspend: start at 170.5417
04/29/21-09:17:06 DEBUG AutoSuspend: scheduling next suspend check in 3600
04/29/21-09:17:06 DEBUG AutoSuspend: scheduling next shutdown check in 259200
04/29/21-09:17:06 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/29/21-09:17:06 DEBUG CoverBrowser: setting FileManager display mode to: list_image_filename
04/29/21-09:17:06 DEBUG CoverBrowser: setting History display mode to: mosaic_image
04/29/21-09:17:06 DEBUG CoverBrowser: setting Collection display mode to: classic
04/29/21-09:17:06 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/29/21-09:17:06 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/29/21-09:17:06 DEBUG show widget: table: 0x7599ee20
04/29/21-09:17:06 DEBUG setDirty nil from widget table: 0x7599ee20 w/ NO region 
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:06 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:06 DEBUG setDirty via a func from widget table: 0x74466188
# 04/29/21-09:17:06  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/menu.lua:954: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanagerhistory.lua:144: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:06 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:06 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:07 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:07 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:07 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:07 DEBUG setDirty via a func from widget table: 0x74466188
# 04/29/21-09:17:07  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
	plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:07 DEBUG show widget: table: 0x74466188
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:07 DEBUG setDirty nil from widget table: 0x74466188 w/ NO region AND w/ HW dithering
04/29/21-09:17:07 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:07 DEBUG painting widget: table: 0x76c20ad0
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:07 DEBUG blitFrom 65 131 0 0 305 458
04/29/21-09:17:07 DEBUG blitFrom 65 616 0 0 306 458
04/29/21-09:17:07 DEBUG blitFrom 469 616 0 0 325 458
04/29/21-09:17:07 DEBUG blitFrom 874 616 0 0 344 458
04/29/21-09:17:07 DEBUG blitFrom 897 1101 0 0 297 458
04/29/21-09:17:07 DEBUG blitFrom 194 1590 0 0 85 85
04/29/21-09:17:07 DEBUG blitFrom 357 1590 0 0 85 85
04/29/21-09:17:07 DEBUG blitFrom 822 1590 0 0 85 85
04/29/21-09:17:07 DEBUG blitFrom 985 1590 0 0 85 85
04/29/21-09:17:07 DEBUG _repaint: it was dithered, infecting the refresh queue
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
# 04/29/21-09:17:07  triggering refresh {
    ["dither"] = true,
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1264,
    },
}
04/29/21-09:17:07 DEBUG refresh: ui-mode 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:07 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 1 (WFM: 257 & UPD: 0)
04/29/21-09:17:07 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:07 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:07 DEBUG Found font: NotoSansArabicUI-Bold.ttf in ./fonts/noto/NotoSansArabicUI-Bold.ttf
04/29/21-09:17:07 DEBUG setDirty via a func from widget table: 0x7599ee20
04/29/21-09:17:07 DEBUG setDirty via a func from widget table: 0x7599ee20
04/29/21-09:17:07 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1511 
04/29/21-09:17:07 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 
# 04/29/21-09:17:07  triggering refresh {
    ["dither"] = false,
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1264,
    },
}
04/29/21-09:17:07 DEBUG refresh: ui-mode 0 0 1264 1680 false
04/29/21-09:17:07 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 2 (WFM: 257 & UPD: 0)
04/29/21-09:17:07 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 734, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1240, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 32, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.853505
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.853505
04/29/21-09:17:07 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG set up hold timer
04/29/21-09:17:07 DEBUG adjusted ges: touch
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 737, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1241, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 31, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.866950
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 740, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1243, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 29, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.880393
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 743, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1245, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 27, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.893725
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 745, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1264, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 26, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.907018
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 748, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1264, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 25, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.920564
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 749, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1264, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 22, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.933864
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG key event => code: 330 (BTN_TOUCH), value: 0, time: 1619651825.959282
04/29/21-09:17:07 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 0, time: 1619651825.959282
04/29/21-09:17:07 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651825.959282
04/29/21-09:17:07 DEBUG in tap state...
04/29/21-09:17:07 DEBUG single tap detected in slot 0 {
    ["h"] = 0,
    ["x"] = 0,
    ["y"] = 749,
    ["w"] = 0,
}
04/29/21-09:17:07 DEBUG adjusted ges: tap
04/29/21-09:17:07 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:07 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:07 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:08 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:10 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 26, time: 1619651830.764687
04/29/21-09:17:10 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651830.764687
04/29/21-09:17:10 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:10 DEBUG close widget: table: 0x74466188
04/29/21-09:17:10 DEBUG CoverMenu:onCloseWidget: terminating jobs if needed
04/29/21-09:17:10 DEBUG terminating 0 subprocesses
04/29/21-09:17:10 DEBUG _refresh: Enqueued partial update for region 0 0 1264 1680 
04/29/21-09:17:10 DEBUG setDirty partial from widget nil w/ NO region 
04/29/21-09:17:10 DEBUG Lower widget table: 0x7599ee20 covers the full screen
04/29/21-09:17:10 DEBUG setDirty nil from widget table: 0x7599ee20 w/ NO region 
./luajit: frontend/apps/filemanager/filemanagerhistory.lua:131: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/apps/filemanager/filemanagerhistory.lua:131: in function 'handleEvent'
	frontend/ui/uimanager.lua:1107: in function 'sendEvent'
	frontend/ui/uimanager.lua:222: in function '__default__'
	frontend/ui/uimanager.lua:1557: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1637: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
!!!!
Uh oh, something went awry... (Crash n°2: 04/29/21 @ 09:17:11)
Running FW 4.26.16704 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/21-09:17:11
 [*] Version: v2021.04

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
04/29/21-09:17:11 DEBUG FB info (post fixup) {
    ["height_mm"] = 4294967295,
    ["xoffset"] = 0,
    ["yoffset"] = 0,
    ["xres_virtual"] = 1264,
    ["yres_virtual"] = 1680,
    ["smem_len"] = 9175040,
    ["mmio_len"] = 0,
    ["width_mm"] = 4294967295,
    ["xres"] = 1264,
    ["yres"] = 1680,
    ["rotate"] = 0,
    ["line_length"] = 1280,
    ["fb_size"] = 2150400,
    ["type"] = 0,
    ["stride_pixels"] = 1280,
    ["bpp"] = 8,
}
04/29/21-09:17:11 DEBUG FB mapped at cdata<void *>: 0x769d1000 of 2150400 bytes
04/29/21-09:17:11 DEBUG set light intensity 100
04/29/21-09:17:11 DEBUG TimeVal: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
04/29/21-09:17:11 DEBUG TimeVal: Preferred REALTIME clock source is CLOCK_REALTIME
04/29/21-09:17:11 INFO  initializing for device Kobo_storm
04/29/21-09:17:11 INFO  framebuffer resolution: {
    ["w"] = 1264,
    ["h"] = 1680,
}
[ko-input] Forked off fake event generator (pid: 1637)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Naskh Arabic
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Sans
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Nimbus Sans L
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Serif
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Sans CJK SC
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Nimbus Roman No9 L
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Sans Arabic UI
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  FreeSans
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Dingbats
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Nimbus Mono
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  FreeSerif
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Standard Symbols L
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Noto Sans Devanagari UI
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  Droid Sans Mono
04/29/21-09:17:11 DEBUG FONTNAMES ADD:  NotoSans Nerd Font
04/29/21-09:17:11 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:11 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:11 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:11 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:11 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:11 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:11 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=8.886 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 8.886/8.886/8.886 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=4.329 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.329/4.329/4.329 ms
04/29/21-09:17:11 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/home.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/home.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/home.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/plus.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/plus.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/plus.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/chevron.left.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/chevron.left.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/chevron.right.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/chevron.right.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/chevron.first.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/chevron.first.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/chevron.last.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/chevron.last.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:12 DEBUG renderSVG resources/icons/mdlight/back.top.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:12 DEBUG cache image|resources/icons/mdlight/back.top.svg|85|85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:12 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG setDirty via a func from widget table: 0x75a368b8
# 04/29/21-09:17:12  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:344: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:952: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:188: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:500: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1123: in function 'showFiles'
	./reader.lua:295: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:12 DEBUG Getting list of dictionaries
04/29/21-09:17:12 DEBUG found 0 dictionaries
04/29/21-09:17:12 DEBUG data is read from  ./settings/lookup_history.lua
04/29/21-09:17:12 INFO  Loading plugins from directory: plugins
04/29/21-09:17:12 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/29/21-09:17:12 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
04/29/21-09:17:12 DEBUG BackgroundRunnerWidget: no job, not running @  1619651832
ffi.load: sqlite3
04/29/21-09:17:12 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
04/29/21-09:17:12 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/29/21-09:17:12 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
04/29/21-09:17:12 DEBUG AutoSuspend: init
04/29/21-09:17:12 DEBUG AutoSuspend: unschedule
04/29/21-09:17:12 DEBUG AutoSuspend: start at 175.966
04/29/21-09:17:12 DEBUG AutoSuspend: scheduling next suspend check in 3600
04/29/21-09:17:12 DEBUG AutoSuspend: scheduling next shutdown check in 259200
04/29/21-09:17:12 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/29/21-09:17:12 DEBUG CoverBrowser: setting FileManager display mode to: list_image_filename
04/29/21-09:17:12 DEBUG CoverBrowser: setting History display mode to: mosaic_image
04/29/21-09:17:12 DEBUG CoverBrowser: setting Collection display mode to: classic
04/29/21-09:17:12 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/29/21-09:17:12 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/29/21-09:17:12 DEBUG show widget: table: 0x75a368b8
04/29/21-09:17:12 DEBUG setDirty nil from widget table: 0x75a368b8 w/ NO region 
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:12 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:12 DEBUG setDirty via a func from widget table: 0x76997068
# 04/29/21-09:17:12  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/menu.lua:954: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanagerhistory.lua:144: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:12 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:12 DEBUG setDirty via a func from widget table: 0x76997068
# 04/29/21-09:17:12  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
	plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:12 DEBUG show widget: table: 0x76997068
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:12 DEBUG setDirty nil from widget table: 0x76997068 w/ NO region AND w/ HW dithering
04/29/21-09:17:12 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:12 DEBUG painting widget: table: 0x75dff940
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:12 DEBUG blitFrom 65 131 0 0 305 458
04/29/21-09:17:12 DEBUG blitFrom 65 616 0 0 306 458
04/29/21-09:17:12 DEBUG blitFrom 469 616 0 0 325 458
04/29/21-09:17:12 DEBUG blitFrom 874 616 0 0 344 458
04/29/21-09:17:12 DEBUG blitFrom 897 1101 0 0 297 458
04/29/21-09:17:12 DEBUG blitFrom 194 1590 0 0 85 85
04/29/21-09:17:12 DEBUG blitFrom 357 1590 0 0 85 85
04/29/21-09:17:12 DEBUG blitFrom 822 1590 0 0 85 85
04/29/21-09:17:12 DEBUG blitFrom 985 1590 0 0 85 85
04/29/21-09:17:12 DEBUG _repaint: it was dithered, infecting the refresh queue
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
# 04/29/21-09:17:12  triggering refresh {
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["mode"] = "ui",
    ["dither"] = true,
}
04/29/21-09:17:12 DEBUG refresh: ui-mode 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:12 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 1 (WFM: 257 & UPD: 0)
04/29/21-09:17:12 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:12 DEBUG Found font: NotoSansArabicUI-Bold.ttf in ./fonts/noto/NotoSansArabicUI-Bold.ttf
04/29/21-09:17:12 DEBUG setDirty via a func from widget table: 0x75a368b8
04/29/21-09:17:12 DEBUG setDirty via a func from widget table: 0x75a368b8
04/29/21-09:17:12 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1511 
04/29/21-09:17:12 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 
# 04/29/21-09:17:12  triggering refresh {
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["mode"] = "ui",
    ["dither"] = false,
}
04/29/21-09:17:12 DEBUG refresh: ui-mode 0 0 1264 1680 false
04/29/21-09:17:12 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 2 (WFM: 257 & UPD: 0)
04/29/21-09:17:12 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:12 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 23, time: 1619651832.805287
04/29/21-09:17:12 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651832.805287
04/29/21-09:17:12 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:12 DEBUG close widget: table: 0x76997068
04/29/21-09:17:12 DEBUG CoverMenu:onCloseWidget: terminating jobs if needed
04/29/21-09:17:12 DEBUG terminating 0 subprocesses
04/29/21-09:17:12 DEBUG _refresh: Enqueued partial update for region 0 0 1264 1680 
04/29/21-09:17:12 DEBUG setDirty partial from widget nil w/ NO region 
04/29/21-09:17:12 DEBUG Lower widget table: 0x75a368b8 covers the full screen
04/29/21-09:17:12 DEBUG setDirty nil from widget table: 0x75a368b8 w/ NO region 
./luajit: frontend/apps/filemanager/filemanagerhistory.lua:131: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/apps/filemanager/filemanagerhistory.lua:131: in function 'handleEvent'
	frontend/ui/uimanager.lua:1107: in function 'sendEvent'
	frontend/ui/uimanager.lua:222: in function '__default__'
	frontend/ui/uimanager.lua:1557: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1637: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
!!!!
Uh oh, something went awry... (Crash n°3: 04/29/21 @ 09:17:13)
Running FW 4.26.16704 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/21-09:17:13
 [*] Version: v2021.04

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
04/29/21-09:17:13 DEBUG FB info (post fixup) {
    ["smem_len"] = 9175040,
    ["mmio_len"] = 0,
    ["width_mm"] = 4294967295,
    ["xres"] = 1264,
    ["yres"] = 1680,
    ["height_mm"] = 4294967295,
    ["line_length"] = 1280,
    ["bpp"] = 8,
    ["rotate"] = 0,
    ["stride_pixels"] = 1280,
    ["type"] = 0,
    ["fb_size"] = 2150400,
    ["xoffset"] = 0,
    ["yoffset"] = 0,
    ["xres_virtual"] = 1264,
    ["yres_virtual"] = 1680,
}
04/29/21-09:17:13 DEBUG FB mapped at cdata<void *>: 0x76a48000 of 2150400 bytes
04/29/21-09:17:13 DEBUG set light intensity 100
04/29/21-09:17:13 DEBUG TimeVal: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
04/29/21-09:17:13 DEBUG TimeVal: Preferred REALTIME clock source is CLOCK_REALTIME
04/29/21-09:17:13 INFO  initializing for device Kobo_storm
04/29/21-09:17:13 INFO  framebuffer resolution: {
    ["w"] = 1264,
    ["h"] = 1680,
}
[ko-input] Forked off fake event generator (pid: 1669)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Sans CJK SC
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Nimbus Roman No9 L
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Nimbus Mono
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Nimbus Sans L
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  FreeSerif
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Sans Devanagari UI
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Sans Arabic UI
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  NotoSans Nerd Font
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Sans
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  FreeSans
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Naskh Arabic
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Noto Serif
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Standard Symbols L
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Droid Sans Mono
04/29/21-09:17:13 DEBUG FONTNAMES ADD:  Dingbats
04/29/21-09:17:13 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:13 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:13 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:13 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:13 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:13 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:13 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=13.981 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 13.981/13.981/13.981 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=2.310 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 2.310/2.310/2.310 ms
04/29/21-09:17:13 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/home.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/home.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/home.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/plus.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/plus.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/plus.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/chevron.left.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/chevron.left.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/chevron.right.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/chevron.right.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/chevron.first.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/chevron.first.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/chevron.last.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/chevron.last.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:14 DEBUG renderSVG resources/icons/mdlight/back.top.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:14 DEBUG cache image|resources/icons/mdlight/back.top.svg|85|85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:14 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG setDirty via a func from widget table: 0x759e1800
# 04/29/21-09:17:14  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:344: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:952: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:188: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:500: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1123: in function 'showFiles'
	./reader.lua:295: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:14 DEBUG Getting list of dictionaries
04/29/21-09:17:14 DEBUG found 0 dictionaries
04/29/21-09:17:14 DEBUG data is read from  ./settings/lookup_history.lua
04/29/21-09:17:14 INFO  Loading plugins from directory: plugins
04/29/21-09:17:14 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/29/21-09:17:14 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
04/29/21-09:17:14 DEBUG BackgroundRunnerWidget: no job, not running @  1619651834
ffi.load: sqlite3
04/29/21-09:17:14 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
04/29/21-09:17:14 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/29/21-09:17:14 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
04/29/21-09:17:14 DEBUG AutoSuspend: init
04/29/21-09:17:14 DEBUG AutoSuspend: unschedule
04/29/21-09:17:14 DEBUG AutoSuspend: start at 178.0028
04/29/21-09:17:14 DEBUG AutoSuspend: scheduling next suspend check in 3600
04/29/21-09:17:14 DEBUG AutoSuspend: scheduling next shutdown check in 259200
04/29/21-09:17:14 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/29/21-09:17:14 DEBUG CoverBrowser: setting FileManager display mode to: list_image_filename
04/29/21-09:17:14 DEBUG CoverBrowser: setting History display mode to: mosaic_image
04/29/21-09:17:14 DEBUG CoverBrowser: setting Collection display mode to: classic
04/29/21-09:17:14 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/29/21-09:17:14 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/29/21-09:17:14 DEBUG show widget: table: 0x759e1800
04/29/21-09:17:14 DEBUG setDirty nil from widget table: 0x759e1800 w/ NO region 
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:14 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:14 DEBUG setDirty via a func from widget table: 0x744eed88
# 04/29/21-09:17:14  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/menu.lua:954: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanagerhistory.lua:144: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:14 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:14 DEBUG setDirty via a func from widget table: 0x744eed88
# 04/29/21-09:17:14  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
	plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:14 DEBUG show widget: table: 0x744eed88
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:14 DEBUG setDirty nil from widget table: 0x744eed88 w/ NO region AND w/ HW dithering
04/29/21-09:17:14 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:14 DEBUG painting widget: table: 0x75eb6098
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:14 DEBUG blitFrom 65 131 0 0 305 458
04/29/21-09:17:14 DEBUG blitFrom 65 616 0 0 306 458
04/29/21-09:17:14 DEBUG blitFrom 469 616 0 0 325 458
04/29/21-09:17:14 DEBUG blitFrom 874 616 0 0 344 458
04/29/21-09:17:14 DEBUG blitFrom 897 1101 0 0 297 458
04/29/21-09:17:14 DEBUG blitFrom 194 1590 0 0 85 85
04/29/21-09:17:14 DEBUG blitFrom 357 1590 0 0 85 85
04/29/21-09:17:14 DEBUG blitFrom 822 1590 0 0 85 85
04/29/21-09:17:14 DEBUG blitFrom 985 1590 0 0 85 85
04/29/21-09:17:14 DEBUG _repaint: it was dithered, infecting the refresh queue
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
# 04/29/21-09:17:14  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["dither"] = true,
}
04/29/21-09:17:14 DEBUG refresh: ui-mode 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:14 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 1 (WFM: 257 & UPD: 0)
04/29/21-09:17:14 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:14 DEBUG Found font: NotoSansArabicUI-Bold.ttf in ./fonts/noto/NotoSansArabicUI-Bold.ttf
04/29/21-09:17:14 DEBUG setDirty via a func from widget table: 0x759e1800
04/29/21-09:17:14 DEBUG setDirty via a func from widget table: 0x759e1800
04/29/21-09:17:14 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1511 
04/29/21-09:17:14 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 
# 04/29/21-09:17:14  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["dither"] = false,
}
04/29/21-09:17:14 DEBUG refresh: ui-mode 0 0 1264 1680 false
04/29/21-09:17:14 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 2 (WFM: 257 & UPD: 0)
04/29/21-09:17:14 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:14 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 28, time: 1619651833.747306
04/29/21-09:17:14 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651833.747306
04/29/21-09:17:14 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 23, time: 1619651833.982666
04/29/21-09:17:14 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651833.982666
04/29/21-09:17:14 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:14 DEBUG close widget: table: 0x744eed88
04/29/21-09:17:14 DEBUG CoverMenu:onCloseWidget: terminating jobs if needed
04/29/21-09:17:14 DEBUG terminating 0 subprocesses
04/29/21-09:17:14 DEBUG _refresh: Enqueued partial update for region 0 0 1264 1680 
04/29/21-09:17:14 DEBUG setDirty partial from widget nil w/ NO region 
04/29/21-09:17:14 DEBUG Lower widget table: 0x759e1800 covers the full screen
04/29/21-09:17:14 DEBUG setDirty nil from widget table: 0x759e1800 w/ NO region 
./luajit: frontend/apps/filemanager/filemanagerhistory.lua:131: attempt to index field 'ui' (a nil value)
stack traceback:
	frontend/apps/filemanager/filemanagerhistory.lua:131: in function 'handleEvent'
	frontend/ui/uimanager.lua:1107: in function 'sendEvent'
	frontend/ui/uimanager.lua:222: in function '__default__'
	frontend/ui/uimanager.lua:1557: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1637: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
!!!!
Uh oh, something went awry... (Crash n°4: 04/29/21 @ 09:17:15)
Running FW 4.26.16704 on Linux 4.1.15-00416-gfc725f43860b (#99 SMP PREEMPT Mon Apr 6 14:55:22 CST 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/21-09:17:15
 [*] Version: v2021.04

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
04/29/21-09:17:15 DEBUG FB info (post fixup) {
    ["height_mm"] = 4294967295,
    ["xoffset"] = 0,
    ["yoffset"] = 0,
    ["xres_virtual"] = 1264,
    ["yres_virtual"] = 1680,
    ["smem_len"] = 9175040,
    ["mmio_len"] = 0,
    ["width_mm"] = 4294967295,
    ["xres"] = 1264,
    ["yres"] = 1680,
    ["rotate"] = 0,
    ["line_length"] = 1280,
    ["fb_size"] = 2150400,
    ["type"] = 0,
    ["stride_pixels"] = 1280,
    ["bpp"] = 8,
}
04/29/21-09:17:15 DEBUG FB mapped at cdata<void *>: 0x769f1000 of 2150400 bytes
04/29/21-09:17:15 DEBUG set light intensity 100
04/29/21-09:17:15 DEBUG TimeVal: Preferred MONOTONIC clock source is CLOCK_MONOTONIC
04/29/21-09:17:15 DEBUG TimeVal: Preferred REALTIME clock source is CLOCK_REALTIME
04/29/21-09:17:15 INFO  initializing for device Kobo_storm
04/29/21-09:17:15 INFO  framebuffer resolution: {
    ["w"] = 1264,
    ["h"] = 1680,
}
[ko-input] Forked off fake event generator (pid: 1701)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Sans
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Nimbus Mono
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Nimbus Roman No9 L
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  FreeSerif
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Sans Arabic UI
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Serif
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  NotoSans Nerd Font
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Nimbus Sans L
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Droid Sans Mono
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  FreeSans
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Naskh Arabic
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Sans Devanagari UI
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Dingbats
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Noto Sans CJK SC
04/29/21-09:17:15 DEBUG FONTNAMES ADD:  Standard Symbols L
04/29/21-09:17:15 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:15 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:15 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:15 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:15 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:15 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:15 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=4.479 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.479/4.479/4.479 ms
PING 192.168.20.1 (192.168.20.1): 56 data bytes
64 bytes from 192.168.20.1: seq=0 ttl=64 time=2.159 ms

--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 2.159/2.159/2.159 ms
04/29/21-09:17:15 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/home.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/home.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/home.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/plus.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/plus.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/plus.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/chevron.left.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/chevron.left.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/chevron.right.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/chevron.right.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/chevron.first.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/chevron.first.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/chevron.last.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/chevron.last.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/back.top.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/back.top.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:16 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x75af3f88
# 04/29/21-09:17:16  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/filechooser.lua:344: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:952: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:188: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:500: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1123: in function 'showFiles'
	./reader.lua:295: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:16 DEBUG Getting list of dictionaries
04/29/21-09:17:16 DEBUG found 0 dictionaries
04/29/21-09:17:16 DEBUG data is read from  ./settings/lookup_history.lua
04/29/21-09:17:16 INFO  Loading plugins from directory: plugins
04/29/21-09:17:16 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/29/21-09:17:16 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
04/29/21-09:17:16 DEBUG BackgroundRunnerWidget: no job, not running @  1619651836
ffi.load: sqlite3
04/29/21-09:17:16 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
04/29/21-09:17:16 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/29/21-09:17:16 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
04/29/21-09:17:16 DEBUG AutoSuspend: init
04/29/21-09:17:16 DEBUG AutoSuspend: unschedule
04/29/21-09:17:16 DEBUG AutoSuspend: start at 180.0313
04/29/21-09:17:16 DEBUG AutoSuspend: scheduling next suspend check in 3600
04/29/21-09:17:16 DEBUG AutoSuspend: scheduling next shutdown check in 259200
04/29/21-09:17:16 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
04/29/21-09:17:16 DEBUG CoverBrowser: setting FileManager display mode to: list_image_filename
04/29/21-09:17:16 DEBUG CoverBrowser: setting History display mode to: mosaic_image
04/29/21-09:17:16 DEBUG CoverBrowser: setting Collection display mode to: classic
04/29/21-09:17:16 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin opds at plugins/opds.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin qrclipboard at plugins/qrclipboard.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
04/29/21-09:17:16 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
04/29/21-09:17:16 DEBUG show widget: table: 0x75af3f88
04/29/21-09:17:16 DEBUG setDirty nil from widget table: 0x75af3f88 w/ NO region 
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.left.svg 85 85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.right.svg 85 85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.first.svg 85 85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/chevron.last.svg 85 85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/back.top.svg 85 85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x75a5f0a8
# 04/29/21-09:17:16  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	frontend/ui/widget/menu.lua:1083: in function 'updateItems'
	frontend/ui/widget/menu.lua:954: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanagerhistory.lua:144: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG Found font: NotoSans-Regular.ttf in ./fonts/noto/NotoSans-Regular.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing data
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x75a5f0a8
# 04/29/21-09:17:16  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:871: in function 'post_guard'
	frontend/dbg.lua:45: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1133: in function 'switchItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
	plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
	frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
	./reader.lua:302: in function 'action'
	frontend/ui/uimanager.lua:1182: in function '_checkTasks'
	frontend/ui/uimanager.lua:1576: in function 'handleInput'
	frontend/ui/uimanager.lua:1684: in function 'run'
	./reader.lua:319: in main chunk
	[C]: at 0x00014161
04/29/21-09:17:16 DEBUG show widget: table: 0x75a5f0a8
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:16 DEBUG setDirty nil from widget table: 0x75a5f0a8 w/ NO region AND w/ HW dithering
04/29/21-09:17:16 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:16 DEBUG painting widget: table: 0x7449a958
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG Found font: NotoSansCJKsc-Regular.otf in ./fonts/noto/NotoSansCJKsc-Regular.otf
04/29/21-09:17:16 DEBUG blitFrom 65 131 0 0 305 458
04/29/21-09:17:16 DEBUG blitFrom 65 616 0 0 306 458
04/29/21-09:17:16 DEBUG blitFrom 469 616 0 0 325 458
04/29/21-09:17:16 DEBUG blitFrom 874 616 0 0 344 458
04/29/21-09:17:16 DEBUG blitFrom 897 1101 0 0 297 458
04/29/21-09:17:16 DEBUG blitFrom 194 1590 0 0 85 85
04/29/21-09:17:16 DEBUG blitFrom 357 1590 0 0 85 85
04/29/21-09:17:16 DEBUG blitFrom 822 1590 0 0 85 85
04/29/21-09:17:16 DEBUG blitFrom 985 1590 0 0 85 85
04/29/21-09:17:16 DEBUG _repaint: it was dithered, infecting the refresh queue
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 w/ HW dithering
# 04/29/21-09:17:16  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["dither"] = true,
}
04/29/21-09:17:16 DEBUG refresh: ui-mode 0 0 1264 1680 w/ HW dithering
04/29/21-09:17:16 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 1 (WFM: 257 & UPD: 0)
04/29/21-09:17:16 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSans-Bold.ttf in ./fonts/noto/NotoSans-Bold.ttf
04/29/21-09:17:16 DEBUG Found font: NotoSansArabicUI-Bold.ttf in ./fonts/noto/NotoSansArabicUI-Bold.ttf
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x75af3f88
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x75af3f88
04/29/21-09:17:16 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1511 
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 0 0 1264 1680 
# 04/29/21-09:17:16  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 1680,
        ["y"] = 0,
        ["w"] = 1264,
        ["x"] = 0,
    },
    ["dither"] = false,
}
04/29/21-09:17:16 DEBUG refresh: ui-mode 0 0 1264 1680 false
04/29/21-09:17:16 DEBUG mxc_update: 1264x1680 region @ (0, 0) with marker 2 (WFM: 257 & UPD: 0)
04/29/21-09:17:16 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:16 DEBUG key event => code: 10010 (UsbPlugIn), value: 1, time: 0.0
04/29/21-09:17:16 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:16 DEBUG ImageWidget: _render'ing resources/icons/mdlight/notice-question.svg 85 85
04/29/21-09:17:16 DEBUG renderSVG resources/icons/mdlight/notice-question.svg 1.7708333333333 48 48 > 85 85 0 0
04/29/21-09:17:16 DEBUG cache image|resources/icons/mdlight/notice-question.svg|85|85
04/29/21-09:17:16 DEBUG ImageWidget: initial offsets 0 0
04/29/21-09:17:16 DEBUG show widget: table: 0x7451f8c8
04/29/21-09:17:16 DEBUG setDirty nil from widget table: 0x7451f8c8 w/ NO region 
04/29/21-09:17:16 DEBUG setDirty via a func from widget table: 0x7451f8c8
04/29/21-09:17:16 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:16 DEBUG painting widget: table: 0x745e2260
04/29/21-09:17:16 DEBUG blitFrom 157 742 0 0 85 85
04/29/21-09:17:16 DEBUG _refresh: Enqueued ui update for region 131 716 1001 248 
# 04/29/21-09:17:16  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["x"] = 131,
        ["y"] = 716,
        ["w"] = 1001,
        ["h"] = 248,
    },
    ["dither"] = false,
}
04/29/21-09:17:16 DEBUG refresh: ui-mode 131 716 1001 248 false
04/29/21-09:17:16 DEBUG mxc_update: 1001x248 region @ (131, 716) with marker 3 (WFM: 257 & UPD: 0)
04/29/21-09:17:17 DEBUG input event => type: 4 (EV_MSC), code: 3 (MSC_RAW), value: 28, time: 1619651837.832628
04/29/21-09:17:17 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651837.832628
04/29/21-09:17:17 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:17 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 1, time: 1619651841.479275
04/29/21-09:17:21 DEBUG key event => code: 330 (BTN_TOUCH), value: 1, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 892, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 21, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.479275
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.479275
04/29/21-09:17:21 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG set up hold timer
04/29/21-09:17:21 DEBUG adjusted ges: touch
04/29/21-09:17:21 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:21 DEBUG MovableContainer:onMovableTouch {
    ["ges"] = "touch",
    ["pos"] = {
        ["h"] = 0,
        ["y"] = 892,
        ["w"] = 0,
        ["x"] = 900,
    },
    ["time"] = {
        ["usec"] = 479275,
        ["sec"] = 1619651841,
    },
}
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 894, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 24, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.492384
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 896, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 27, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.505760
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 898, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 28, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.518259
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 899, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 29, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.531660
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 900, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 364, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 29, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.545097
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 59 (ABS_MT_DISTANCE), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 900, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 362, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 58 (ABS_MT_PRESSURE), value: 27, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 48 (ABS_MT_TOUCH_MAJOR), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 49 (ABS_MT_TOUCH_MINOR), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 3 (EV_ABS), code: 52 (ABS_MT_ORIENTATION), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 2 (SYN_MT_REPORT), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.571897
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
04/29/21-09:17:21 DEBUG key event => code: 330 (BTN_TOUCH), value: 0, time: 1619651841.597304
04/29/21-09:17:21 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 0, time: 1619651841.597304
04/29/21-09:17:21 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1619651841.597304
04/29/21-09:17:21 DEBUG in tap state...
04/29/21-09:17:21 DEBUG single tap detected in slot 0 {
    ["h"] = 0,
    ["y"] = 900,
    ["w"] = 0,
    ["x"] = 902,
}
04/29/21-09:17:21 DEBUG adjusted ges: tap
04/29/21-09:17:21 DEBUG AutoSuspend: onInputEvent
04/29/21-09:17:21 DEBUG Explicit widgetRepaint: table: 0x744b91c8 @ ( 633 , 857 )
04/29/21-09:17:21 DEBUG _refresh: Enqueued fast update for region 633 857 472 87 
04/29/21-09:17:21 DEBUG setDirty fast from widget nil w/ region 633 857 472 87 
04/29/21-09:17:21 DEBUG not painting 1 covered widget(s)
# 04/29/21-09:17:21  triggering refresh {
    ["mode"] = "fast",
    ["region"] = {
        ["h"] = 87,
        ["y"] = 857,
        ["w"] = 472,
        ["x"] = 633,
    },
    ["dither"] = false,
}
04/29/21-09:17:21 DEBUG refresh: fast 633 857 472 87 false
04/29/21-09:17:21 DEBUG mxc_update: 472x87 region @ (633, 857) with marker 4 (WFM: 1 & UPD: 0)
04/29/21-09:17:21 DEBUG Explicit widgetRepaint: table: 0x744b91c8 @ ( 633 , 857 )
04/29/21-09:17:21 DEBUG _refresh: Enqueued fast update for region 633 857 472 87 
04/29/21-09:17:21 DEBUG setDirty fast from widget nil w/ region 633 857 472 87 
04/29/21-09:17:21 INFO  quitting uimanager
04/29/21-09:17:21 DEBUG close widget: table: 0x7451f8c8
04/29/21-09:17:21 DEBUG setDirty via a func from widget nil
04/29/21-09:17:21 DEBUG update_mode: Update refresh mode fast to ui
04/29/21-09:17:21 DEBUG _refresh: Enqueued ui update for region 131 716 1001 248 
# 04/29/21-09:17:21  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["h"] = 248,
        ["y"] = 716,
        ["w"] = 1001,
        ["x"] = 131,
    },
    ["dither"] = false,
}
04/29/21-09:17:21 DEBUG refresh: ui-mode 131 716 1001 248 false
04/29/21-09:17:21 DEBUG mxc_update: 1001x248 region @ (131, 716) with marker 5 (WFM: 257 & UPD: 0)
```

</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #7617

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7620)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Also includes the wording tweaks mentioned in https://github.com/koreader/koreader/pull/7616#discussion_r622732969

weights

**Comment by NiLuJe** [comment]
Mildly wondering if it would even be worth mapping the numerical classes to their standard English names? (e.g., Light, Regular, SemiBold, Bold, Black, etc.)?

**Comment by poire-z** [comment]
> Mildly wondering if it would even be worth mapping the numerical classes to their standard English names?

I don't think that's needed: it would add length to this text and increase its height/decrease font size.
And @ptrm knows what these numbers mean - other users shouldn't need to care much about them :)

**Comment by NiLuJe** [comment]
Oh, I like them, too, FWIW ^^.

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
Do as you like it then :) no real objection.

**Comment by NiLuJe** [comment]
Looks like that if we keep adding the raw value:

weights3

**Comment by NiLuJe** [comment]
Minor query @Frenzie about the I18N context stuff: do we have to describe what a context means in more details somewhere, or is that enough?

File: frontend/ui/data/creoptions.lua [hunk 1]
```diff
@@ -15,6 +15,36 @@ local tableOfNumbersToTableOfStrings = function(numbers)
...
+    [700] = C_("Font weight class", "Bold"),
+    [800] = C_("Font weight class", "Extra-bold"),
+    [900] = C_("Font weight class", "Black"),
+}
+
+local function weightClassToString(weight)
+    if usWeightClass[weight] then
+        return usWeightClass[weight] .. " (" .. weight .. ")"
+    else
+        return string.format("%d", weight)
```
Comment (poire-z) [inline frontend/ui/data/creoptions.lua:36]: Or just `tostring(weight)`

File: frontend/ui/data/creoptions.lua [hunk 2]
```diff
@@ -537,19 +567,19 @@ Note that your selected font size is not affected by this setting.]]),
...
+- 0 will use the "Regular (400)" variation of a font.
+- +1 will use the "Medium (500)" variation of a font if available.
+- +3 will use the "Bold (700)" variation of a font if available.
+If a font variation is not available, as well as for fractional adjustments, it will be synthesized from the nearest available weight.]]),
                 help_text_func = function(configurable, document)
                     local font_face = document:getFontFace()
-                    local available_weights = cre.getFontFaceAvailableWeights(font_face)
-                    return T(_("The default font '%1' is available in %2."), font_face, table.concat(available_weights, ", "))
+                    local available_weights = prettifyCreWeights(cre.getFontFaceAvailableWeights(font_face))
+                    return T(_("The default font '%1' provides the following weight classes: %2."), font_face, table.concat(available_weights, ", "))
```
Comment (Frenzie) [inline frontend/ui/data/creoptions.lua:577]: I think in Chinese they might prefer the full-width comma, though hopefully it matters little. It's not something you'd be looking at every day.

Comment (NiLuJe) [reply frontend/ui/data/creoptions.lua:577]: As the concat token, you mean?

That'd be tricky to make CJK-only, and would look ugly in LGC otherwise, no?

Comment (Frenzie) [reply frontend/ui/data/creoptions.lua:577]: It's a semi-random specific example for a more generic remark.

> That'd be tricky to

Er, that's why we have our gettext implementation in the first place? ;-)

Comment (NiLuJe) [reply frontend/ui/data/creoptions.lua:577]: Oh, right, you meant simply by making it translatable :D.

**Comment by NiLuJe** [comment]
Includes the random OPDS test timeout shenanigan I mentioned somewhere the other day ;).

File: frontend/ui/data/creoptions.lua [hunk 3]
```diff
@@ -15,6 +15,36 @@ local tableOfNumbersToTableOfStrings = function(numbers)
...
+    [500] = C_("Font weight class", "Medium"),
+    [600] = C_("Font weight class", "Semi-bold"),
+    [700] = C_("Font weight class", "Bold"),
+    [800] = C_("Font weight class", "Extra-bold"),
+    [900] = C_("Font weight class", "Black"),
+}
+
+local function weightClassToString(weight)
+    if usWeightClass[weight] then
+        return usWeightClass[weight] .. " (" .. weight .. ")"
```
Comment (Frenzie) [inline frontend/ui/data/creoptions.lua:34]: Same remark as for the comma. I think we probably already have something fairly silly looking like `%1 (%2)` in there.

**Review by Frenzie — APPROVED** [review]

File: frontend/ui/data/creoptions.lua (hunk 3 above)
Comment (NiLuJe) [reply frontend/ui/data/creoptions.lua:34]: Mostly have a whole bunch of literals using that syntax pretty much everywhere ^^.

Comment (Frenzie) [reply frontend/ui/data/creoptions.lua]: Judging by a quick look at strings with parentheses among the translations it may not be an issue.
