### PR TITLE
TOC settings: add bind chapter navigation/titles to ticks

### LINKED ISSUE #7271: FR: History - tap on deleted file
Deleted files in History are greyed so we obviously know they are deleted.

Current behaviour on tap: open last book, show message 'File doesn't exist'

Proposed behaviour on tap: do nothing

### LINKED ISSUE #7276: Bookmarks - 'Go to page' dialog on empty list
* KOReader version: 2021.01.1-28
* Device: Kindle PW2

#### Issue
'Go to page' dialog should not be called
#### Steps to reproduce
Bookmarks empty window - long tap in the bottom of the screen, on 'No choices available'.

I managed to call the dialog with not empty bookmark list, but it is unstable.

---

---

### PR DESCRIPTION
**Pull request by poire-z**
#### TOC settings: add bind chapter navigation/titles to ticks

Add 2 convenience settings, allowing ToC ignored depths settings to apply further than just the progress bars.
See https://github.com/koreader/koreader/pull/7238#issuecomment-774729725 and followups.

<kbd>image</kbd>

<kbd>image</kbd>

Also includes:

~~#### Button: don't handle long-press when not enabled~~

~~It was only not handled when hold_callback. Do that also when hold_input/hold_input_func.
Menu: prevent long-press on "No choice available", as there's then no page to navigate to.
Closes #7276.~~
^ Updated commit included in hotfix #7300.

#### History: avoid opening non-existent files

Mostly just so we don't get the History closed when erroneously tapping on a deleted file.
See https://github.com/koreader/koreader/issues/7271#issuecomment-778280742. Closes #7271.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7280)

### CODE REVIEW

**Review by NiLuJe — APPROVED** [review]

**Comment by poire-z** [comment]
Fixed the lowercase "checking" and added some quotes (as the line break in my first screenshot above made it hard to read :) : 
<kbd>image</kbd>

**Comment by NiLuJe** [comment]
> Fixed the lowercase "checking" and added some quotes (as the line break in my first screenshot above made it hard to read :) :
> image

Speaking of, not sure if "Enabling" instead of "Checking" wouldn't be better?

**Comment by poire-z** [comment]
Yep. Switched the 2 Checking to Enabling. (But we currently have none of these :) Feels like we have a few that just says "This will...". Well, waiting for @Frenzie usual feedback on my english :)

**Review by yparitcher — APPROVED** [review]

File: frontend/apps/reader/modules/readertoc.lua [hunk 1]
```diff
@@ -915,6 +951,38 @@ See Style tweaks → Miscellaneous → Alternative ToC hints.]]),
                     break
                 end
             end
+            toc_ticks_levels[#toc_ticks_levels].separator = true
+            table.insert(toc_ticks_levels, {
+                text = _("Bind chapter navigation to ticks"),
+                help_text = _([[Entries from ToC levels ignored in the progress bars are still used for chapter navigation and 'page/time left until next chapter' in the footer.
+Enabling this will restrict them to progress bars ticks.]]),
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua:958]:
```suggestion
Enabling this will restrict chapter nativation to progress bar ticks.]]),
```

File: frontend/apps/reader/modules/readertoc.lua [hunk 2]
```diff
@@ -915,6 +951,38 @@ See Style tweaks → Miscellaneous → Alternative ToC hints.]]),
                     break
                 end
             end
+            toc_ticks_levels[#toc_ticks_levels].separator = true
+            table.insert(toc_ticks_levels, {
+                text = _("Bind chapter navigation to ticks"),
+                help_text = _([[Entries from ToC levels ignored in the progress bars are still used for chapter navigation and 'page/time left until next chapter' in the footer.
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua:957]:
```suggestion
                help_text = _([[Entries from ToC levels that are ignored in the progress bars will still be used for chapter navigation and 'page/time left until next chapter' in the footer.
```

File: frontend/apps/reader/modules/readertoc.lua [hunk 3]
```diff
@@ -915,6 +951,38 @@ See Style tweaks → Miscellaneous → Alternative ToC hints.]]),
...
+                end,
+                callback = function()
+                    self.toc_chapter_navigation_bind_to_ticks = not self.toc_chapter_navigation_bind_to_ticks
+                    self:onUpdateToc()
+                    self.view.footer:onUpdateFooter(self.view.footer_visible)
+                end,
+            })
+            table.insert(toc_ticks_levels, {
+                text = _("Chapter titles from ticks only"),
+                help_text = _([[Entries from ToC levels ignored in the progress bars are still used for displaying the current chapter's title in the footer and in bookmarks.
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua:973]:
```suggestion
                help_text = _([[Entries from ToC levels that are ignored in the progress bars will still be used for displaying the title of the current chapter in the footer and in bookmarks.
```

File: frontend/apps/reader/modules/readertoc.lua [hunk 4]
```diff
@@ -915,6 +951,38 @@ See Style tweaks → Miscellaneous → Alternative ToC hints.]]),
...
+Enabling this will restrict it to be chapter titles of progress bars ticks.]]),
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua:974]:
```suggestion
Enabling this option will restrict display to the chapter titles of progress bar ticks.]]),
```

**Comment by poire-z** [comment]
Removed "Button" commit, as it has been included in hotfix #7300.
