### PR TITLE
Dispatcher: nil guard against access to a document instance

### LINKED ISSUE #7388: Dispatcher crash when Dispatcher attempts to set Reader settings in the FM
Btw, not sure if this is meant for here, but there is some crash going on when trying to rotate screen with long tap set at left and right corner on Aura One reader. Works ok when you have a book opened, happens just on homescreen.
https://imgur.com/a/c6hs9J7

_Originally posted by @ReaLx3m in https://github.com/koreader/koreader/issues/7304#issuecomment-791396658_

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #7388

Related fixes:

* Unbreak the Rotation submenu entries since #7306
* Actually update the touchzones properly when the FM is rotated

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7389)

### CODE REVIEW

**Comment by NiLuJe** [comment]
@yparitcher: Should the ConfigDialog stuff even be *visible* in the FM's gesture manager menus?

**Comment by yparitcher** [comment]
Dispatcher is reader/FM agnostic, gestures happens to use different instances, however profiles is the same across both (each profile can be used everywhere). This usually works well as events are safe to send even when no handler is registered. to separate then would mean a lot of work for little gain, and would cause ui/menu inconsistencies.

**Review by yparitcher — COMMENTED** [review]
cleaner
```diff
                 local arg = v ~= 0 and v or gesture or 0
                 ui:handleEvent(Event:new(settingsList[k].event, arg))
             end
-            if settingsList[k].configurable ~= nil then
-                 local value = v
-                 if type(v) ~= "number" then
-                     for i, r in ipairs(settingsList[k].args) do
+            if settingsList[k].configurable ~= nil and ui.document then
+                local value = v
+                if type(v) ~= "number" then
+                    for i, r in ipairs(settingsList[k].args) do
                         if v == r then value = settingsList[k].configurable.values[i] break end
-                     end
-                 end
-                 ui.document.configurable[settingsList[k].configurable.name] = value
+                    end
+                end
+                ui.document.configurable[settingsList[k].configurable.name] = value
             end
         end
     end
```

File: frontend/dispatcher.lua [hunk 1]
```diff
@@ -623,14 +623,14 @@ function Dispatcher:execute(ui, settings, gesture)
                 local arg = v ~= 0 and v or gesture or 0
                 ui:handleEvent(Event:new(settingsList[k].event, arg))
             end
-            if settingsList[k].configurable ~= nil then
-                 local value = v
-                 if type(v) ~= "number" then
-                     for i, r in ipairs(settingsList[k].args) do
+            if settingsList[k].configurable ~= nil and ui.document then
```
Comment (Frenzie) [inline frontend/dispatcher.lua:626]: Or the other way around?

**Review by Frenzie — APPROVED** [review]

File: frontend/dispatcher.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/dispatcher.lua:626]: Hmm, arguably, you're less likely to hit a configurable than not being in the Reader, but it's pretty much a coin toss ;).

Comment (Frenzie) [reply frontend/dispatcher.lua]: I was talking more or less exclusively about ease of reading, although it could potentially make an impossibly small performance impact one way or the other. ;-)
