### PR TITLE
Gestures/profiles: allow disabling popup messages

### LINKED ISSUE #13457: Actions with popup messages prevent subsequent actions from running
* KOReader version: 2024.11
* Device: Kobo Libra 2

#### Issue

(This issue happens both with profiles, and when assigning multiple actions to a gesture)

I have a setup where I want to toggle both the SSH server on my device and the Wi-Fi. The problem is that when I try to execute the actions all at once (either by running the profile, or performing the gesture), only the first action will be run - after the popup message(s) for the first action close, the second action is not run.

#### Steps to reproduce

This can most easily be seen by creating a profile with one action that has popups and another action that doesn't, and then swapping the execution order. So for example, I created a profile called "test", with two actions: Screen and lights > Toggle night mode, and Device > Toggle Wi-Fi. When night mode is first, night mode is successfully toggled, as is the Wi-Fi. But when arranging it so Wi-Fi is first, the Wi-Fi is successfully toggled, but the night mode is not.

### LINKED ISSUE #14116: Move to archive bug?
### Device

Pocketbook

### KOReader version

v2025.04-174-g5009d36d7

### Model and firmware version

Era

### Issue description

I have set up a gesture that moves the current book to the archive and then displays the favourites. After the book has been moved to the archive, the prompt "Would you like to open it from the archive folder?" appears. However, after confirming or cancelling, the favourites are not displayed. What do I have to do?
Or is this a bug in the plugin?

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Log

```shell

```

### Additional information

_No response_

### LINKED ISSUE #14542: Gesture only executes the first command when multiple are assigned
### Device

Kindle

### KOReader version

2025.08.143

### Model and firmware version

Kindle Paperwhite 12th, firmware 5.18.5.0.1

### Issue description

I use a two-finger swipe down gesture to synchronize my reading statistics, reading progress, and highlights (with the [AnnotationSync.koplugin](https://github.com/dani84bs/AnnotationSync.koplugin) plug-in) all at once, instead of having to trigger each one separately. Only the first assigned command runs; the others are ignored.

### Steps to reproduce

1. Assign multiple commands to a gesture
2. Trigger the gesture.

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hius07**
In multi-actions gestures/profiles, the popup infomessages/confirmboxes prevent executing of the following actions.
Add a setting to hide the output.

-----

- Closes #13457
- Closes #14116 
- Closes #14542

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14543)

### CODE REVIEW

File: frontend/dispatcher.lua [hunk 1]
```diff
@@ -1209,8 +1226,11 @@ function Dispatcher:execute(settings, exec_props)
         UIManager:broadcastEvent(Event:new("BatchedUpdate"))
     end
     Notification:setNotifySource(Notification.SOURCE_DISPATCHER)
-    if settings.settings and settings.settings.notify then
-        Notification:notify(T(_("Executing profile: %1"), settings.settings.name))
+    if settings.settings then
+        if settings.settings.notify then
+            Notification:notify(T(_("Executing profile: %1"), settings.settings.name))
+        end
+        UIManager.disable_show = settings.settings.disable_show
```
Comment (poire-z) [inline frontend/dispatcher.lua]: Feels really ugly to store that state as a (kinda global) UIManager property (and what if it crashes and you won't reset it to nil, nothing will ever show again).

Comment (hius07) [reply frontend/dispatcher.lua]: It's not the first case.
https://github.com/koreader/koreader/blob/340732f03bef5d94f0396974a9212732b01a1fdd/frontend/ui/widget/container/inputcontainer.lua#L320

Comment (poire-z) [reply frontend/dispatcher.lua]: Pinging @NiLuJe for thoughts, and possible ideas for a less hackish solution to prevent showing InfoMsg and ConfirmBoxes (without touching their instantiation sites as there may be a lot and I also like to not add noise in all these places).

File: frontend/dispatcher.lua [hunk 2]
```diff
@@ -1076,6 +1076,23 @@ function Dispatcher:addSubMenu(caller, menu, location, settings)
             Dispatcher._sortActions(caller, location[settings])
         end,
         keep_menu_open = true,
+    })
+    table.insert(menu, {
+        text = _("Do not show action messages and dialogs"),
```
Comment (Commodore64user) [inline frontend/dispatcher.lua]: Hotkeys, removes some settings from dispatcher, and limits the number of settings to 9 per page, can you please check if this messes it up?

**Comment by mergen3107** [comment]
Is this the actual solution to the problem with multiple actions in a single profile? If so, shouldn’t it have more attention? 

What I am saying is that currently it seems to me that users probably won’t guess by themselves that this new option is the remedy for their failing profiles. 
Maybe at least it can be documented? Or enabled by default for multiple actions? There might be a popup shown after users select the 2nd action, for example, like “To make sure multiple actions work, notifications have been disabled.”

Alternatively, would it be feasible to have multiple actions profile to combine all info messages into one big one and shown just that at the very end of running such profile?

File: frontend/dispatcher.lua (hunk 2 above)
Comment (hius07) [reply frontend/dispatcher.lua]: Will do, thanks.

**Comment by hius07** [comment]
Moreover, maybe we do not need the setting at all.
The output should be suppressed for **every** action in **all** multi-actions gestures/profiles, except the last one.
Otherwise they just don't run.

File: frontend/dispatcher.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/dispatcher.lua]: Besides refactoring every call site with a mask like Notifications does, nothing really jumps to mind :/.

> (and what if it crashes and you won't reset it to nil, nothing will ever show again).

That's a good point; would it make sense to forcibly reset this on startup?

Comment (NiLuJe) [reply frontend/dispatcher.lua]: What I was going to say is that I'd have a mild preference for the logic to be handled inside the affected widgets, instead of branching in `UIManager`, but it's a tad more annoying than I initially thought it'd be.

(i.e., I was going to, say "just overload `onShow` and return early if the flag is set", but that wouldn't account for UIManager's `_window_stack` EDIT: And the dirty queue, either! :s).

Sooo, nope, no brighter ideas :/

Comment (NiLuJe) [reply frontend/dispatcher.lua]: Unless...

The widgets aren't instantiated yet when you start your bracketing, right?

In which case, instead of the two-pronged approach you have right now, just flip a `disable_show` in the affected widget's *class*, and just check `widget.disable_show` in the `UIManager` branch, as those instances created inside your bracket should have inherited it?

(Unless there's some more timing wonkyness involved?)

Comment (NiLuJe) [reply frontend/dispatcher.lua]: (If that approach actually works, I'd possibly move the actual flag twiddling in a public `UIManager` method, to make it easier to maintain in case new widgets need to be handled down the line, instead of having Dispatcher dig into base widget classes on its own).

Comment (NiLuJe) [reply frontend/dispatcher.lua]: Thinking out loud and a bit rusty here, sorry for the noise ;).

Comment (hius07) [reply frontend/dispatcher.lua]: I think this should work, but what are the benefits to set the flag in several widgets' classes instead of one UIManager?
If the program crashed inside an action running, on startup the flag is nil, no problems.

**Comment by poire-z** [comment]
Btw, why the ConfirmBoxes ? Which are they ?
Feels like they would require the user decision, so what is that decision when we don't show them ? Cancel ? Is it always welcome ?

File: frontend/dispatcher.lua (hunk 1 above)
Comment (poire-z) [reply frontend/dispatcher.lua]: Feels a little more elegant (as far as UIManager is concerned), just skipping harmless InfoMessages (and Notifications?) (and ConfirmBoxes if really appropriate), calling a UIManager:disableNagging(), which may be more generic and useful in other contexts - than just a "we won't show anything".

**Comment by hius07** [comment]
> why the ConfirmBoxes ?

https://github.com/koreader/koreader/issues/14116#issuecomment-3221011966

File: frontend/dispatcher.lua (hunk 1 above)
Comment (hius07) [reply frontend/dispatcher.lua]: > than just a "we won't show anything".

Not "anything" but widgets with `allow_disable_show = true`, that are InfoMessage and ConfirmBox.
Notifications don't prevent next actions running.

**Comment by poire-z** [comment]
> > why the ConfirmBoxes ?
> 
> [#14116 (comment)](https://github.com/koreader/koreader/issues/14116#issuecomment-3221011966)

If this is the only one, I'd rather not include ConfirmBox, and add in the calling site (that plugin) a call to see if nagging is disabled and do there the most appropriate action (instead of showing the ConfirmBox), with a comment saying "If nagging is disabled, the user would probably prefer that we do this".
Rather than disabling ConfirmBox and assume Cancel is always the preferred option.

**Comment by hius07** [comment]
> a call to see if nagging is disabled

It needs a flag in UIManager, doesn't it?

File: frontend/ui/uimanager.lua [hunk 3]
```diff
@@ -124,6 +124,18 @@ function UIManager:setIgnoreTouchInput(state)
...
 
+function UIManager:setSilentMode()
+    self.silent_mode = true
+end
+
+function UIManager:resetSilentMode()
+    self.silent_mode = nil
+end
+
+function UIManager:isSilentMode()
```
Comment (poire-z) [inline frontend/ui/uimanager.lua]: isInSilentMode() would sound better ?
Pinging @NiLuJe to approve these namings or suggest some alternative.
Fine with me with how it ended up.

Comment (NiLuJe) [reply frontend/ui/uimanager.lua]: I was actually thinking of a different approach entirely ;D.

Specifically:

* Dropping the UIManager *flag*
* But keeping an UIManager *method* that:
* Flips a `silent_mode` flag in the affected widgets *base class*
* e.g., `InfoMessage.silent_mode = true`
* Which means the `UIManager:show` test only really needs to check for `widget.silent_mode`

And hope that everything instantiated between the bracketing inherits that flag, and Bob's your uncle.

Comment (hius07) [reply frontend/ui/uimanager.lua]: What about `UIManager:isSilentMode()`?
We are going to use it in the MoveToArchive plugin, to not just suppress  the ConfirmBox, but to choose the code path.

Comment (NiLuJe) [reply frontend/ui/uimanager.lua]: If the approach works, it could just be an in-ConfirmBox check for `ConfirmBox.silent_mode` (possibly with a public getter if you need it outside of ConfirmBox).

If you do need a public getter, depending on how widespread this is, said public method might make more sense in UIManager than in ConfirmBox only (there's also an argument that can be made for moving the method to UIManager regardless, just for symmetry's sake with the `toggleSilentMode` one).

The main idea is just to flip flags in *widget*"s base class rather than an UIManager flag.

Comment (poire-z) [reply frontend/ui/uimanager.lua]: Feels a bit ugly to have UIManager knows about (having their names in uimanager.lua) the classes that can be silenced. (+ the possible require loop if UIManager would require(infomessage) which itself require(uimanager) . If it's just their name as a string, it's even uglier :)).
Feels better to have the flag in UIManager, and classes announcing they support silent mode with a property.

So, I guess you're fine with the name "silent mode" ? What about isSilentMode() vs is***In***SilentMode() ?

Comment (NiLuJe) [reply frontend/ui/uimanager.lua]: Oh, didn't think about the require loop, good point; that probably trumps all my pie in the sky musings (I mean, the requires *could* be locals to the methods, we have precedent for that, buuuut, yah, okay ;p) ;).

As far as naming goes, I liked your nagging proposal, but silent is probably easier to grok at a glance, so, yeah, just make it more grammatical (eg., either `isSilent` or `isInSilentMode`, probably the second one for symmetry w/ the toggles).

File: frontend/ui/uimanager.lua [hunk 4]
```diff
@@ -124,6 +124,14 @@ function UIManager:setIgnoreTouchInput(state)
     InputContainer:setIgnoreTouchInput(state)
 end
 
+function UIManager:toggleSilentMode()
+    self.silent_mode = not self.silent_mode or nil
```
Comment (poire-z) [inline frontend/ui/uimanager.lua]: I'd still prefer an explicite `:setSilentMode(toggle)` called with true or false.
With `toggleSilentMode()`, we trust the state, but if we miss one call (for some reason), things will go messy/inverted :)

**Comment by offset-torque** [comment]
@hius07 

Hard to follow the long discussion but from the new "Show notification on executing" menu item under the profile settings, I am guessing that implementation changed 

**From the initial:**

"Providing ability to turn off messages during profile execution"

**To:**

"Profiles are now executed silently by default, users can enable messages if they want"

Is this correct? If yes, default behavior is now safe and the option `Show notification on executing` is self-explaining so nothing to document for me here.

**Comment by Commodore64user** [comment]
that `Show notification on executing` sound wildly unnatural. should be `Show notification on execution` or `Show notification when run`

**Comment by hius07** [comment]
> "Profiles are now executed silently by default, users can enable messages if they want"

It's correct.
