### PR TITLE
Fix footer, stats, TOC position with cre in scroll mode

### LINKED ISSUE #3282: EPUB: Scroll mode page numbers broken
* KOReader version: 180f575 but likely going back much further
* Device: all

#### Issue
Enabling scroll mode in EPUB causes crashes related to page numbers and TOC markers.

#### Steps to reproduce
Almost any random EPUB with more than one page should do. For example, notice how 10_2-BF-01.epub from `Html401/` in the EPUB test suite, a 3 page document, claims to have a thousand.

screenshot_2017-10-01_09-28-18
screenshot_2017-10-01_09-28-23
screenshot_2017-10-01_09-28-27

Doing something that requires interaction with page numbers will trigger an error like this:

```
./luajit: frontend/ui/widget/bookstatuswidget.lua:259: attempt to perform arithmetic on field 'page' (a nil value)
stack traceback:
	frontend/ui/widget/bookstatuswidget.lua:259: in function 'genBookInfoGroup'
	frontend/ui/widget/bookstatuswidget.lua:125: in function 'getStatusContent'
	frontend/ui/widget/bookstatuswidget.lua:86: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/modules/readerstatus.lua:45: in function 'showStatus'
	frontend/apps/reader/modules/readerstatus.lua:29: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/apps/reader/modules/readerrolling.lua:440: in function 'onGotoViewRel'
	frontend/apps/reader/modules/readerrolling.lua:296: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:197: in function 'handleEvent'
	frontend/ui/uimanager.lua:442: in function 'sendEvent'
	frontend/ui/uimanager.lua:43: in function '__default__'
	frontend/ui/uimanager.lua:720: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:178: in main chunk
	[C]: at 0x55cc9d7590b0
~/src/kobo/koreader
```

### PR DESCRIPTION
**Pull request by poire-z**
This gives the page position to these modules even in scroll mode. Closes #3282

Also, in readerrolling: don't query battery/charging status when crengine does not need it (used only when it shows its top progress bar).

### CODE REVIEW

**Comment by poire-z** [comment]
By "innacurate", I mean that you can be on page 47 > tap > still on page 47 > tap > page 49.
@robert00s : is it a problem for the stats plugin if you get this sequence of pages in onPageUpdate : 47 > 47 > 49 > 50 > 51 > 51 > 53... ?

**Comment by robert00s** [comment]
@poire-z No this is no problem

File: frontend/apps/reader/modules/readerfooter.lua [hunk 1]
```diff
@@ -568,9 +568,14 @@ function ReaderFooter:onPageUpdate(pageno)
...
 end
 
-function ReaderFooter:onPosUpdate(pos)
+function ReaderFooter:onPosUpdate(pos, pageno)
     self.position = pos
     self.doc_height = self.view.document.info.doc_height
+    if pageno then
+        self.pageno = pageno
+        self.pages = self.view.document:getPageCount()
+        self.ui.doc_settings:saveSetting("doc_pages", self.pages) -- for Book information
```
Comment (robert00s) [inline frontend/apps/reader/modules/readerfooter.lua]: Do we need save doc_pages every time when we change book position?

Comment (poire-z) [reply frontend/apps/reader/modules/readerfooter.lua]: `saveSettings()` just updates the value of `doc_settings["doc_pages"]`, it does not save/flush/write do disk, so it costs nearly nothing. And it is there in onPageUpdate just above this onPosUpdate :)

**Comment by Frenzie** [comment]
I know there's a top status bar thingy that I don't use but what happens there exactly?

File: frontend/apps/reader/modules/readerfooter.lua (hunk 1 above)
Comment (robert00s) [reply frontend/apps/reader/modules/readerfooter.lua]: Thank. I thought that this line write to disk :)

**Comment by poire-z** [comment]
This bar is displayed and updated by crengine itself.
For it to show an accurate battery icon, koreader needs to give it to crengine. So, in readerrolling, there are lots of `self:updateBatteryState()` calls.
`self:updateBatteryState()` query powerd for battery (where there is a 'don't query hardware more than once every minute' thing), and isCharging (no 'once evey X' check). isCharging is reading a kernel file on kobo, calling a lib function on kindle: it can be costly.
This make sure these calls are not made when crengine does not display its statusbar.

readerfooter does it too when battery is among the footer visible items.
So, with battery in footer, and so (if there's a footer/mini bar) no top status bar, previously, each page turn was causing 2 calls for battery info.

**Comment by Frenzie** [comment]
I see, thanks!

File: plugins/statistics.koplugin/main.lua [hunk 2]
```diff
@@ -1568,6 +1568,10 @@ function ReaderStatistics:deleteBook(id_book)
     conn:close()
 end
 
+function ReaderStatistics:onPageUpdate(pos, pageno)
```
Comment (robert00s) [inline plugins/statistics.koplugin/main.lua]: @poire-z Should it be:
`ReaderStatistics:onPosUpdate(pos, pageno)`

Comment (Frenzie) [reply plugins/statistics.koplugin/main.lua]: Has to be, otherwise it makes no sense.

Comment (poire-z) [reply plugins/statistics.koplugin/main.lua]: Indeed :| Fortunatly, it is overwritten by the next one (good I put that one before the good one :) PR'ing a correction. Thanks!

Comment (Frenzie) [reply plugins/statistics.koplugin/main.lua]: I'm actually slightly surprised luacheck didn't complain about this.

**Comment by poire-z** [comment]
Adding a note: Go to, Skim to and taping on a TOC item does not work (= does not go to page) in scroll mode.

**Comment by Frenzie** [comment]
In crengine, I assume. I do that daily (in a manner of speaking) in PDF and DjVu.
