### PR TITLE
[Screensaver] add a cap to the number of random images processed

### LINKED ISSUE #14499: 20 second plus wait time to load sleep screen
### Device

Kindle

### KOReader version

2025.08

### Model and firmware version

Kindle Paperwhite (11th generation), Firmware version Kindle 5.18.5.0.1

### Issue description

I have downloaded all 5000 comic panel strips of Calvin and Hobbs from GoComics and placed them in a folder on my Kindle. This folder takes up around 1.5 GB, with each image being around 200-300 KB for the small panel strips, and 500-1500 KB for the full colored panels. Opening each image by itself using the file browser in koreader only takes 1-2 seconds, but when selecting this folder for the sleep screen to choose a random wallpaper from, it takes upwards of 20 seconds. This issue doesn't occur with smaller directories of images, or even larger images, or when selecting a single one of the images to use as a wallpaper instead of the directory. This issue both when choosing images randomly from the directory, and in a consistent order.

### Steps to reproduce

1. Import a directory with a large number of images onto your Kindle
2. Select that directory as the directory to choose images from to display on the sleep screen
3. Wait 20 seconds, instead of the usual 1-2 seconds for smaller directories

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

* Added a `file_cap` parameter to `util.findFiles` to limit the number of files scanned during directory traversal. The scan stops once the cap is reached.
* Updated `filemanagerutil.getRandomFile` to accept and pass the `file_cap` parameter to `util.findFiles`, ensuring random file selection respects the cap.
* Modified `_getRandomImage` to use the `screensaver_file_cap` setting (defaulting to 128) for both alphabetical cycling and random image selection, preventing performance issues with large image directories. 
* The cap is configurable via the `screensaver_file_cap` G_setting.

### related issues

* closes #14499

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14521)

### CODE REVIEW

File: frontend/ui/screensaver.lua [hunk 1]
```diff
@@ -87,20 +87,19 @@ local function _getRandomImage(dir)
...
     end
+    -- Limit the number of files we scan to avoid performance issues. Power users can always increase this cap if needed.
+    local file_cap = G_reader_settings:readSetting("screensaver_file_cap") or 128
     -- If the user has set the option to cycle images alphabetically, we sort the files instead of picking a random one.
     if G_reader_settings:isTrue("screensaver_cycle_images_alphabetically") then
         local start_time = time.now()
         local files = {}
-        local num_files = 0
+        -- Slippery slope ahead! Ensure the number of files does not become unmanageable, otherwise we'll have performance issues.
+        -- NOTE: empirically, a kindle 4 found and sorted 128 files in 0.274828 seconds.
```
Comment (Frenzie) [inline frontend/ui/screensaver.lua]: Shouldn't this go by the file_cap? I'm not too sure about the name btw: in a programming context it sounds more like capacity than like an arbitrary limit.

Anyway, the actual reason I'm commenting, and I may have said this before, but this sounds like it's a fairly low default even on a Kindle 4?

Comment (Commodore64user) [reply frontend/ui/screensaver.lua]: 256? 300? 500? what do you have in mind? to be fair though, no has complained about the 128. people with 5000+ tend to be the exception not the rule... we know 128 good, 5000 bad. and those same people can now change that value to anything the wish to.

a cap is a limit on something.

Comment (Frenzie) [reply frontend/ui/screensaver.lua]: The time measurement sounds like 256 or even 512 should still be okay even on the Kindle 4, which is pretty much the worst case scenario. But perhaps you disagree?

Iirc I did some measurements and tests on my old H2O once and decided it was basically okay up to about a thousand, but of course that device is much faster than a Kindle 4, even if it's much slower than my newer Libra 2.

Comment (Commodore64user) [reply frontend/ui/screensaver.lua]: the worst case scenario is really a kindle 2/3, I believe 128 is fine. Most people won't have more than perhaps a few dozen images, besides, is simple enough to increase the cap now. but if you want 256 I am happy to increase it.

Comment (Frenzie) [reply frontend/ui/screensaver.lua]: I'd make it 256 then, yes.

File: frontend/ui/screensaver.lua [hunk 2]
```diff
@@ -87,20 +87,19 @@ local function _getRandomImage(dir)
     local match_func = function(file) -- images, ignore macOS resource forks
         return not util.stringStartsWith(ffiUtil.basename(file), "._") and DocumentRegistry:isImageFile(file)
     end
+    -- Slippery slope ahead! Ensure the number of files does not become unmanageable, otherwise we'll have performance issues.
+    -- Power users can increase this cap if needed. Beware though, this grows at O(n * c) where c increases with the number of files.
+    -- NOTE: empirically, a kindle 4 found and sorted 128 files in 0.274828 seconds.
+    local file_cap = G_reader_settings:readSetting("screensaver_file_cap") or 256
```
Comment (Frenzie) [inline frontend/ui/screensaver.lua:93]: @hius07 @poire-z Thoughts on adding this setting?

Comment (hius07) [reply frontend/ui/screensaver.lua:93]: Okay.

**Comment by poire-z** [comment]
> * file_cap

I would have named it with `_nb` of `max_files`, something that reads like it's a number. But too late, so ok.

**Comment by Frenzie** [comment]
Not quite too late; no one's used it yet. Sorry, I thought you were on vacation so I figured I wouldn't wait for you.

**Comment by Commodore64user** [comment]
File-cap-nb? A cap is an upper limit imposed to something, it already means maximum and number etc. 

Edit: a little [example](https://tfl.gov.uk/fares/find-fares/capping)

> Sorry, I thought you were on vacation so I figured I wouldn't wait for you.

on the run, something to do with some jewels or something ;)

**Comment by poire-z** [comment]
> File-cap-nb? A cap is an upper limit imposed to something, it already means maximum and number etc.

May be in the wild - but not in our codebase, where explicite is better than english-scholar'ite.

> on the run, something to do with some jewels or something ;)

After my font list got ugly radio buttons, I thought I would change trade...
But after one week, I'm missing KOReader :/ I'll give them back if I get back my square checkboxes !

**Comment by Commodore64user** [comment]
> May be in the wild - but not in our codebase, where explicite is better than english-scholar'ite.

not sure what is scholar about that... what is it exactly that you want?

**Comment by poire-z** [comment]
`max`, `nb`, `files` in plural, something that would read like it's a number to someone not familiar with the word "cap" - `file_cap` would sound to me like a boolean: we cap or we don't cap (to some number defined elsewhere).

**Comment by Commodore64user** [comment]
but you now know what it means... `max` is already implied as a cap is a max point, `nb` is also implied as one can only have numerical maxes, and `files` is grammatically incorrect.

file_count_cap?
