### PR TITLE
Some more low power states related tweaks

### LINKED ISSUE #9038: Kobo Libra 2 freezes when dictionary lookup
* KOReader version: 2022.03.1-41   (Firmware: 4.31.19086)
* Device: Kobo Libra 2

#### Issue
The second time I lookup a word my Libra 2 freezes. A restart is needed.

KA1 & Kobo Sage don't behave like this.

#### Steps to reproduce
Lookup a word. Lookup another from inside the dictionary (or close window and lookup another word). Freeze.

It happens both when I lookup word from a book or when using the dictionary from the menu or a gesture.

Ususally it only takes two lookups to freeze, but sometimes it takes three or four.

Verbose log: 
[crash.log](https://github.com/koreader/koreader/files/8570390/crash.log)

### PR DESCRIPTION
**Pull request by NiLuJe**
* Disable all non power management related input during suspend. (This prevents wonky touch events from being tripped when closing a sleep cover on an already-in-suspend device, among other things).
* Kobo: Use our WakeupMgr instance, not the class.
* WakupMgr: split `removeTask` in two: 
* `removeTask`, which *only* takes a queue index as input, and only removes a single task. Greatly simplifies the function (i.e., it's just a `table.remove`).
* `removeTasks`, which takes an epoch or a cb ref, and removes *every* task that matches.
* Both of these will also *always* re-schedule the next task (if any) on exit, since we can have multiple WakeupMgr tasks queued, but we can only have a single RTC wake alarm set ;).
* `wakeupAction` now takes a `proximity` argument, which it passes on to its `validateWakeupAlarmByProximity` call, allowing call sites to avoir having to duplicate that call themselves when they want to use a custom proximity window.
* `wakeupAction` now re-schedules the next task (if any) on exit.
* Simplify `Kobo:checkUnexpectedWakeup`, by removing the duplicate `WakerupMgr:validateWakeupAlarmByProximity` call, now that we can pass a proximity window to `WakeuoMgr:wakeupAction`.
* The various network activity timeouts are now halved when autostandby is enabled.
* Autostandby: get rid of the dummy deadline_guard task, as it's no longer necessary since #9009.
* UIManager: The previous change allows us to simplify `getNextTaskTimes` into a simpler `getNextTaskTime` variant, getting rid of a table & a loop.
* ReaderFooter & ReaderHeader: Make sure we only perform a single refresh when exiting standby.
* Kobo: Rewrite sysfs writes to use ANSI C via FFI instead of stdio via Lua, as it obscured some common error cases (e.g., EBUSY on /sys/power/state).
* Kobo: Simplify `suspend`, now that we have sane error handling in sysfs writes.
* Kobo.powerd: Change `isCharging` & `isAuxCharging` behavior to match the behavior of the NTX ioctl (i.e., Charging == Plugged-in). This has the added benefit of making the AutoSuspend checks behave sensibly in the "fully-charged but still plugged in" scenario (because being plugged in is enough to break PM on `!canPowerSaveWhileCharging` devices).
* AutoSuspend: Disable our `AllowStandby` handler when auto standby is disabled, so as to not interfere with other modules using `UIManager:allowStandby` (fix #9038).
* PowerD: Allow platforms to implement `isCharged`, indicating that the battery is full while still plugged in to a power source (battery icon becomes a power plug icon).
* Kobo.powerd: Implement `isCharged`, and kill charging LEDs once battery is full.
* Kindle.powerd: Implement `isCharged` on post-Wario devices. (`isCharging` is still true in that state, as it ought to).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9036)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Draft because this was only lightly tested so far, but it seems to behave ;).

(Also, there's a minor debugging codepath left around the standby task that will be removed before merge ;)).

File: frontend/ui/network/networklistener.lua [hunk 1]
```diff
@@ -84,6 +84,12 @@ end
 -- Everything below is to handle auto_disable_wifi ;).
 local default_network_timeout_seconds = 5*60
 local max_network_timeout_seconds = 30*60
+-- If autostandby is enabled, shorten the timeouts
+local auto_standby = G_reader_settings:readSetting("auto_standby_timeout_seconds", -1)
+if auto_standby > 0 then
+    default_network_timeout_seconds = default_network_timeout_seconds / 2
+    max_network_timeout_seconds = max_network_timeout_seconds / 2
```
Comment (poire-z) [inline frontend/ui/network/networklistener.lua:91]: No need for rounding in anticipation of the upcoming TimeValReVamp ?
(A few TimeVal below that @zwim will have to not miss.)

Comment (NiLuJe) [reply frontend/ui/network/networklistener.lua:91]: Wouldn't hurt, but shouldn't change anything, since everything should fall on a full integer ;).

**Comment by NiLuJe** [comment]
Nasty `fwrite` shenanigans were nasty. >_<".

I must have been asleep since #2465, or only going by the strace output (... where `write` does throw an `EBUSY`), but as far as LuaJIT and stdio are concerned, `fwrite` happily returns 8 -_-".

File: frontend/device/input.lua [hunk 2]
```diff
@@ -1220,4 +1274,64 @@ function Input:waitEvent(now, deadline)
...
+            logger.info("Inhibiting user input")
+            self._key_ev_handler = self.handleKeyBoardEv
+            self.handleKeyBoardEv = self.handlePowerManagementOnlyEv
+        end
+        -- And send everything else to the void
+        if not self._oasis_ev_handler then
+            self._oasis_ev_handler = self.handleOasisOrientationEv
+            self.handleOasisOrientationEv = self.voidEv
+        end
+        if not self._abs_ev_handler then
```
Comment (zwim) [inline frontend/device/input.lua:1291]: Just a question: Are these mutually exclusive? If so an `elsif` might speed up a bit.

File: frontend/device/input.lua [hunk 3]
```diff
@@ -1220,4 +1274,64 @@ function Input:waitEvent(now, deadline)
...
+            self.handleGenericEv = self.voidEv
+        end
+    else
+        -- Restore event handlers, if any
+        if self._key_ev_handler then
+            logger.info("Restoring user input handling")
+            self.handleKeyBoardEv = self._key_ev_handler
+            self._key_ev_handler = nil
+        end
+        if self._oasis_ev_handler then
```
Comment (zwim) [inline frontend/device/input.lua:1314]: Same question here.

**Review by zwim — COMMENTED** [review]
Just skimmed through; I have not tested it now.

File: frontend/device/input.lua (hunk 2 above)
Comment (NiLuJe) [reply frontend/device/input.lua:1291]: I went defensive in case some platforms do weird shit with those.

Otherwise, I'd just have checked the basic & common EV_ABS handler ;).

Comment (NiLuJe) [reply frontend/device/input.lua:1291]: (It's also not in a performance critical codepath. Like, at all ;p).

File: frontend/device/wakeupmgr.lua [hunk 4]
```diff
@@ -75,29 +73,61 @@ function WakeupMgr:addTask(seconds_from_now, callback)
 end
```
Comment (zwim) [inline frontend/device/wakeupmgr.lua:73]: You could resue `new_upcoming_task` in `self:setWakeupAlarm` (a few lines above):
```
    local new_upcoming_task = self._task_queue[1].epoch

    if not old_upcoming_task or (new_upcoming_task < old_upcoming_task) then
        self:setWakeupAlarm(new_upcoming_task)
    end
```

Comment (NiLuJe) [reply frontend/device/wakeupmgr.lua:72]: Took me three days to grok what you meant, which should tell you how exhausted I was :D.

Done, thanks ;).

Comment (zwim) [reply frontend/device/wakeupmgr.lua:72]: In future, I will try to articulate myself clearer. But you could have asked. ;)

Anyway I enjoy the work here and with you (all).

Comment (NiLuJe) [reply frontend/device/wakeupmgr.lua:72]: Oh, that was definitely a *me* thing, not to worry ;).

(Case in point: it wasn't even actually three days, it just felt like it ^^).

**Comment by zwim** [comment]
A catch of @hius07 
In `autosuspend.koplugin/main.lua` there we have 
https://github.com/koreader/koreader/blob/f37699a12b893984690f0e433b7f048af3c621a7/plugins/autosuspend.koplugin/main.lua#L417-L419

and 
https://github.com/koreader/koreader/blob/f37699a12b893984690f0e433b7f048af3c621a7/plugins/autosuspend.koplugin/main.lua#L425-L426

In the former code we have the variable `time_string` and we do the cosmetics with a `time_string = .... :gsub`. In the later one we do it in one line. This is inconsistent. So I want to ask you, to do it both in the same way (my favorite would be the former variant).

**Comment by hius07** [comment]
Well, actually I meant that you have removed `default_value` in DTW in the latest pr...

**Comment by zwim** [comment]
> Well, actually I meant that you have removed `default_value` in DTW in the latest pr...

Let's shift "this" discussion to the relevant PR #9055. My request to avoid the `...:gsub:gsub` above holds despite this objection.

**Comment by NiLuJe** [comment]
@zwim: This possibly feels like something that should be handled directly in `util.secondsToClockDuration` (or a dedicated wrapper in `util` anyway), because the pattern trickery is error-prone and repetitive ;).

**Comment by NiLuJe** [comment]
Changed the milestone because #9038 is a blocker ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9036)* status: all files reviewed, 4 unresolved discussions (waiting on @zwim)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9036)* status: all files reviewed, 4 unresolved discussions (waiting on @zwim)

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/65510b7ed3179a7de8057b0fe356e0663cf97cfc/plugins/autosuspend.koplugin/main.lua#L421
DateTimeWidget after https://github.com/koreader/koreader/pull/9055 will not show the 'Default' button.

**Review by zwim — COMMENTED** [review]
@niluje : Yep, moving this to `util` makes more sense.

> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9036#-:-N0yMoRp6iQaZUTUAxWo:b-u32i89)* status: all files reviewed, 4 unresolved discussions (waiting on @Frenzie, @pazos, and @zwim)

**Review by zwim — APPROVED** [review]
lgtm

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 3 of 5 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9036)* status: all files reviewed, 4 unresolved discussions (waiting on @Frenzie, @pazos, and @zwim)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9036)* status: all files reviewed, 4 unresolved discussions (waiting on @Frenzie, @pazos, and @zwim)
