### PR TITLE
Remove run twice onPageUpdate() when document is opening

### LINKED ISSUE #2836: onPageUpdate methods run twice on book open
* KOReader version:all
* Device:all

#### Issue
`onPageUpdate()` methods runs twice on book open. It should run only one.

#### Steps to reproduce
Open new document in format epub or doc. For new and previously opened books.
I think that that line https://github.com/koreader/koreader/blame/master/frontend/apps/reader/modules/readerrolling.lua#L450 may be redundant for new books.
That line https://github.com/koreader/koreader/blame/master/frontend/apps/reader/modules/readerrolling.lua#L467 may be redundant for previously opened books.

I think that `self:_gotoXPointer(self.xpointer)` shouldn't be run when opening documents.

### PR DESCRIPTION
**Pull request by robert00s**
Close #2836 
Should fix problem: `onPageUpdate()` methods runs twice on book open.

### CODE REVIEW

**Comment by robert00s** [comment]
I have to find different solution :(

```
Failure → spec/front/unit/readerrolling_spec.lua @ 162
Readerrolling module switching screen mode should not change current page number for portrait-landscape-portrait switching
spec/front/unit/readerrolling_spec.lua:168: Expected objects to not be the same.
Passed in:
(number) 80
Did not expect:
(number) 80

stack traceback:
	spec/front/unit/readerrolling_spec.lua:168: in function <spec/front/unit/readerrolling_spec.lua:162>
Failure → spec/front/unit/readerrolling_spec.lua @ 173

Readerrolling module switching screen mode should not change current page number for landscape-portrait-landscape switching
spec/front/unit/readerrolling_spec.lua:179: Expected objects to not be the same.
Passed in:
(number) 110
Did not expect:
(number) 110
```

File: frontend/apps/reader/modules/readerrolling.lua [hunk 1]
```diff
@@ -153,6 +153,7 @@ end
 function ReaderRolling:onReaderReady()
     self:setupTouchZones()
     self.setupXpointer()
+    self.old_page = 0
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerrolling.lua]: Should this be 0 or 1? Just asking 'cause this is Lua.

Comment (robert00s) [inline frontend/apps/reader/modules/readerrolling.lua]: `self.old_page` should be `0`.
`0` means that the number of pages in the document has not yet been generated.
Previously was `1` but it's possible that document has one page.

Comment (Frenzie) [inline frontend/apps/reader/modules/readerrolling.lua]: In that case you could just check for  

if self.old_page then

I think being undefined should suffice? No need to initialize to 0 and check if larger.

Comment (robert00s) [inline frontend/apps/reader/modules/readerrolling.lua]: You're right.

File: frontend/apps/reader/modules/readerrolling.lua [hunk 2]
```diff
@@ -1,13 +1,12 @@
...
 local Device = require("device")
-local Input = require("device").input
+local InputContainer = require("ui/widget/container/inputcontainer")
 local Event = require("ui/event")
+local ReaderPanning = require("apps/reader/modules/readerpanning")
 local UIManager = require("ui/uimanager")
 local logger = require("logger")
 local _ = require("gettext")
-
+local Input = require("device").input
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerrolling.lua]: Sorry, I didn't notice this before and it's not your fault but would you mind changing this to `Device.input`?

File: frontend/apps/reader/modules/readerrolling.lua [hunk 3]
```diff
@@ -1,13 +1,12 @@
...
+local Screen = require("device").screen
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerrolling.lua]: And `Device.screen`?

Device is already required at the beginning, you see. :-)

File: frontend/apps/reader/modules/readerrolling.lua (hunk 1 above)
Comment (Frenzie) [inline frontend/apps/reader/modules/readerrolling.lua]: Hm, apparently that caused this problem: `frontend/apps/reader/modules/readerrolling.lua:268: attempt to perform arithmetic on field 'old_page' (a nil value)`

I guess line 267 could be changed to `if self.view.view_mode == "page" and self.old_page then` except I'm not really sure what the else condition would do there? (Also, shouldn't it also have crashed on trying to divide by 0? :-P)

**Comment by Frenzie** [comment]
Thanks!
