### PR TITLE
Fix remarkable pen input

### LINKED ISSUE #6030: Remarkable: Pen Input Broken
* KOReader version: 2020.03.2
* Device: ReMarkable

#### Issue

The pen does not work as an input device.  Either touching the screen with the pen has no result or, depending on where on the screen the pen makes contact, seemingly random behavior occurs.

#### Steps to reproduce

Start koreader and touch the screen with the pen.

### PR DESCRIPTION
**Pull request by dfhall**
This fixes issue #6030 and allows the ReMarkable pen to work as a touch input device.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6031)

### CODE REVIEW

**Comment by NiLuJe** [comment]
I was going to say: shouldn't this be an actual if ladder (i.e., if ... elseif .. elseif ... instead of a bunch of separate ifs), but apparently frontend/device/input.lua does the same thing, so, eh. :D.

File: frontend/device/remarkable/device.lua [hunk 1]
```diff
@@ -22,20 +22,37 @@ local ABS_Y = 01
 local ABS_MT_POSITION_X = 53
 local ABS_MT_POSITION_Y = 54
 -- Resolutions from libremarkable src/framebuffer/common.rs
+local screen_width = 1404
```
Comment (Frenzie) [inline frontend/device/remarkable/device.lua:25]:
```suggestion
local screen_width = 1404 -- unscaled_size_check: ignore
```
For all four of them of course. ;-)

Comment (dfhall) [reply frontend/device/remarkable/device.lua]: Done.
