### PR TITLE
A few Kobo input tweaks

### LINKED ISSUE #630: Kobo Touch Mark3 has trouble turning a page with tapping.
[On mobileread simonchik](http://www.mobileread.com/forums/showthread.php?p=2842283#post2842283) has posted his problem with installing koreader on the older Mark 3 Kobo Touch. 
He has done extensive testing and apparently he has a different hardware from other Mark 3 owners [such as tshering](http://www.mobileread.com/forums/showthread.php?p=2843886#post2843886) or a different way of touching the screen.

Because it is a nice case study and the Kobo Aura is also not behaving quite as you would like, we have delved into `gesturedetector.lua` and try to find a way to make it work for his hardware. First we'll try to change the parameters in `GestureDetector`.

Latest post by simonchik:
@markismus: about versions that 'work' on my kobo, I now have a clearer idea about what's happening: if I put my finger on the screen, I get 

```
# tev fed| 558 | 291854 | 342 | 307 | 1 | Evt 0
# in tap state...
# set up hold timer
# hold gesture detected in slot 0
# in hold state...
# tev fed| 558 | 405127 | 341 | 307 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 504107 | 341 | 308 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 688109 | 340 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 558 | 872074 | 339 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 27735 | 339 | 310 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 225903 | 338 | 311 | 1 | Evt 0
# in hold state...
# tev fed| 559 | 749673 | 337 | 311 | 1 | Evt 0
# in hold state...
# tev fed| 560 | 4570 | 337 | 309 | 1 | Evt 0
# in hold state...
# tev fed| 560 | 13418 | 337 | 309 | -1 | Evt 0
# in hold state...
# hold_release detected in slot 0
```

which means that tev is populated with touch events from very close coordinates, as if I were moving my finger, except I'm not. There is no multitouch, no "two finger-tap" and so on, so I think the best think would be to put a threshold, like 5 points or so on this device, below which a touch event on hold state would be discarded?

### LINKED ISSUE #4446: Enable inverted button mapping on Forma
* KOReader version: v2018.12-44-g41b885f_2019-01-03
* Device: Kobo Forma

#### Issue
On the Forma, I find the "default" (bottom next, top previous) button layout basically unusable. Nickel offers an option to invert the sense of the buttons, but Koreader doesn't.

(I could always just hack the mapping file manually for this one device, but that's annoying and fragile.)

#### Steps to reproduce
1. Invert button mapping in Nickel
2. Run Koreader
3. Notice buttons are still in default mapping, cringe with anticipated RSI

### LINKED ISSUE #4451: Option to disable automatic orientation switch
* KOReader version: v2018.12-44-g41b885f_2019-01-03
* Device: Kobo Forma

#### Issue
The orientation of the screen is set to automatically change based on the physical orientation of the device, via the accelerometer; this works correctly, but keeps firing when I don't want it to e.g. reading while lying down. It would be good to have an option to disable this and just set the orientation manually.

### LINKED ISSUE #4457: Kobo Forma not handling sleep cover correctly
When the magnetic cover is closed, the Forma usually does not sleep. Soon after the cover is opened, there's sometimes input lag or a period in which input is dropped. Also seems to cause significant battery drain, more than if the screen was simply on during this time.

Under Nickel, sleep and wake seems to work fine, so this does not seem like an issue with my Forma or with my sleep cover.

### PR DESCRIPTION
**Pull request by NiLuJe**
* Fix the Touch input probe on Trilogy devices that depend on the touch_probe_ev_epoch_time quirk (fix #630)
* Expose a "PageTurn button inversion" feature in the Navigation menu (for all devices with keys) (fix #4446)
* Allow ignoring the accelerometer on the Forma (Screen > Ignore accelerometer rotation events) (fix #4451)
* Fix SleepCover handling on the Forma (fix #4457)
* Make isWifiOn a tiny bit more accurate (check the actual WiFi module instead of sdio_wifi_pwr)

### CODE REVIEW

File: frontend/ui/elements/common_settings_menu_table.lua [hunk 1]
```diff
@@ -112,8 +112,7 @@ common_settings.screen = {
         require("ui/elements/screen_eink_opt_menu_table"),
         require("ui/elements/menu_activate"),
         require("ui/elements/screen_disable_double_tap_table"),
-        require("ui/elements/flash_ui"),
-        require("ui/elements/flash_keyboard"),
+        require("ui/elements/screen_toggle_gsensor"),
```
Comment (poire-z) [inline frontend/ui/elements/common_settings_menu_table.lua]: I think this sensor menu item should only be shown on device that has one :)
Could be done just like it's done just below for color screen and full screen on android.

File: frontend/ui/elements/common_settings_menu_table.lua [hunk 2]
```diff
@@ -199,6 +198,17 @@ if Device:hasKeys() then
                     G_reader_settings:flipNilOrTrue("enable_back_history")
                 end,
             },
+            {
+                text = _("Invert PageTurn Buttons"),
+                enabled_func = function() return Device:hasKeys() end,
```
Comment (poire-z) [inline frontend/ui/elements/common_settings_menu_table.lua]: The whole block that contains this item is already inside `if Device:hasKeys() then`, so this shouldn't be necessary :)

File: frontend/ui/elements/common_settings_menu_table.lua [hunk 3]
```diff
@@ -199,6 +198,17 @@ if Device:hasKeys() then
...
+                checked_func = function()
+                    return G_reader_settings:isTrue("input_invert_buttons")
+                end,
+                callback = function()
+                    G_reader_settings:flipNilOrFalse("input_invert_buttons")
```
Comment (poire-z) [inline frontend/ui/elements/common_settings_menu_table.lua]: `input_invert_buttons` could be made more explicit, like : `input_invert_page_turn_keys`

File: frontend/ui/elements/screen_eink_opt_menu_table.lua [hunk 4]
```diff
@@ -13,14 +13,15 @@ local eink_settings_table = {
                 G_reader_settings:saveSetting("low_pan_rate", Screen.low_pan_rate)
             end,
         },
+        require("ui/elements/flash_ui"),
+        require("ui/elements/flash_keyboard"),
```
Comment (poire-z) [inline frontend/ui/elements/screen_eink_opt_menu_table.lua]: I think these are not that eInk specific. But OK if you need to make room, as it's most probably only on eInk that one will want to disable them (even if I disabled them on my Android phone).

File: frontend/device/generic/device.lua [hunk 5]
```diff
@@ -27,6 +27,7 @@ local Device = {
     hasClipboard = no,
     hasColorScreen = no,
     hasBGRFrameBuffer = no,
+    canToggleGSensor = no,
```
[the remark this answers is not in the document]
Comment (NiLuJe) [reply frontend/device/generic/device.lua]: The Oasis has one, but it's trickier to toggle, so I went with something different/more accurate ;)

File: frontend/ui/elements/common_settings_menu_table.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/elements/common_settings_menu_table.lua]: Agreed, that was already on my TODO list ;).

File: frontend/ui/elements/common_settings_menu_table.lua (hunk 2 above)
Comment (NiLuJe) [reply frontend/ui/elements/common_settings_menu_table.lua]: Realized that when I checked on my H2O and wondered where the menu had gone ;p.

File: frontend/ui/elements/screen_eink_opt_menu_table.lua (hunk 4 above)
Comment (NiLuJe) [reply frontend/ui/elements/screen_eink_opt_menu_table.lua]: Yeah, I mainly wanted it to be near the "avoid mandatory black flashes" one, even if they're not *technically* eInk-specific ;).

Comment (NiLuJe) [reply frontend/ui/elements/screen_eink_opt_menu_table.lua]: The fact that the eInk submenu is never hidden anywhere cinched the deal ;).
