### PR TITLE
handle OPDS catalog responses accordingly

### LINKED ISSUE #5240: OPDS catalog does not follow redirects
* KOReader version: v2019.07
* Device: Android

#### Issue

It looks like the OPDS app does not follow redirects sent by a server

#### Steps to reproduce

Have a server redirect (HTTP status code 301) a request to a different URL (such as HTTPS upgrade requests or `example.com/root -> example.com/root/`) and the app pops up
an error message. About being redirected

The [fetching code](https://github.com/koreader/koreader/blob/fca51757af6dace42d72163816ca12b52a2ee3aa/frontend/ui/widget/opdsbrowser.lua#L289) works but treats everything else than 200 as an error.

### PR DESCRIPTION
**Pull request by edoput**
this will fix #5240 and provide some more feedback to users trying to use OPDS
catalogs

- handle moved permanently HTTP 301
- handle authentication required HTTP 401
- handle authentication errors HTTP 403
- handle catalog not found HTTP 404

### CODE REVIEW

File: frontend/ui/widget/opdsbrowser.lua [hunk 1]
```diff
@@ -298,6 +298,22 @@ function OPDSBrowser:fetchFeed(item_url, username, password, method)
...
+        UIManager:show(InfoMessage:new{
+            text = T(_("Authentication required for catalog, please add username and password")),
+        })
+    elseif code == 403 then
+        UIManager:show(InfoMessage:new{
+            text = T(_("Could not authenticate, check your username and password")),
+        })
+    elseif code == 404 then
+        UIManager:show(InfoMessage:new{
+            text = T(_("Catalog not found")),
```
Comment (Frenzie) [inline frontend/ui/widget/opdsbrowser.lua]:
```suggestion
            text = T(_("Catalog not found.")),
```

**Comment by edoput** [comment]
Ok all suggestions accepted!

File: frontend/ui/widget/opdsbrowser.lua [hunk 2]
```diff
@@ -298,9 +298,25 @@ function OPDSBrowser:fetchFeed(item_url, username, password, method)
...
+            text = T(_("Failed to authenticate. Please check your username and password.")),
+        })
+    elseif code == 404 then
+        UIManager:show(InfoMessage:new{
+            text = T(_("Catalog not found.")),
+        })
     else
         UIManager:show(InfoMessage:new{
-            text = T(_("Cannot get catalog. Server code response %1"), code),
+            text = T(_("Cannot get catalog. Server code response %1."), code),
```
Comment (Frenzie) [inline frontend/ui/widget/opdsbrowser.lua]:
```suggestion
            text = T(_("Cannot get catalog. Server response code %1."), code),
```

Sorry, I overlooked this one.

**Comment by Frenzie** [comment]
Thanks!
