### PR TITLE
ReaderRolling: quicker partial rerenderings with EPUBs

### LINKED ISSUE #6896: FR: Need A Paragraph Change Preview Page
Every change of paragraph would re-rander the whole document, It will take 10-15 mins for a new book setup.
Please add a page for this change, and  preview for multiple modifications。

### LINKED ISSUE #9087: Speeding up the text appearance adjustments
**TLDR:** Text appearance adjustments can be instantaneous instead of taking several seconds

I noticed that, with shorter documents around 10 pages, changes like the font size, font weight, line spacing are instantaneous (which is very satisfying). Obviously because device has to calculate much fewer pages. In contrast, each adjustment takes about 5 seconds on my device (Kobo Libra) for a ~600 (real) page book.

**Context:**
When a user is changing a setting like font weight, most of the time he doesn't know the exact value. He knows that he wants a bolder text but he doesn't know if it is +0.25 or +0.75 so he tries different values until he is satisfied with the look. Same scenario is valid for other text appearance settings.

- Currently when a user changes a value, the whole book is calculated. Each change triggers a whole book recalculation.
- E-readers have limited computing power, that's why this change can take like 5 seconds even on a fairly modern device.
- User doesn't immediately need these settings applied to page 832 if he is on page 20.

**So considering the points above, my proposal is (if it is feasible):**

When changing the text appearance, we can apply new settings only to the current page (because this is what the user is seeing) and to the next page (because text from the next page might be needed if the user selects a very small font size and shifts the bottom).

While doing this, a popup can appear at the top of the page:
instant adjustments

So user can freely change many settings. And when he is satisfied he can tap this button and settings would be applied to the rest of the book.

**What are the benefits of this approach ?**
- Changes related to the text appearance will become instantaneous even on older/slower devices
- Instant feedback is important for a better user experience
- KOReader will feel much snappier
- A bit of battery will be saved because changes will be applied only once to the whole book

**What are the downsides of this change ?**
I am not knowledgeable about how KOReader works, so this might be hard or impossible to implement. I can't think of other downsides, but I am sure discussion can reveal some.

### LINKED ISSUE #9547: FR: Faster text previews
This is a holidays' idea that probably is already discussed somewhere, but I didn't find anything on a fast search.
Well, here goes:
One of the main cons new users find in KOReader is the time it takes to apply the font appearance changes.
Every change ex. font size+1, size+2, size+3, size-2, ..., must compute all the book's text, again and again.
I know this is intentional and I agree with this.
The way I've done it, was to open a small file and find the defaults with that, but not many users do that, and I can also understand this.

My proposition is to use a sample of the book's text.
When the user changes something in the lower menu (that, in my opinion should also include the font selection even as a duplicate control), that change can be made visible using only the text in the current html (if its small enough) or the text from couple of pages before and after.
After a change like this, a simple 2 button pop-up with "Apply to document" and "Cancel" must open and stay open until the user closes it.
This pop-up must be modal, to prevent the user to interact with the text, but must let the user interact with the lower menu to make more changes or close it, so that she can see a full preview of the changes.

I know that this is a lot more complicated under the hood, but I think it's doable.
The reason that I don't put some code where my mouth is, it's my lack of lua knowledge (since I can't find a way to easily write code and see the results 😛 ).

Anyway, I leave this here as a placeholder for discussion..

### LINKED ISSUE #10073: Pagebreak not respecting margin
* KOReader version: 2023.01
* Device: Kindle Paperwhite 3

#### Issue
If an ebook has a forced pagebreak in a certain place (`page-break-after: always`), then the top margin of the element following it is not used. This means that the element is close to the top of the screen. This occurs whether the margin is stated in percentage or em.

### Expected Behaviour
The margin of the second element should be included. It should ignore the bottom margin of the element preceding it with the pagebreak, if possible.

### Calibre Viewer Screenshots
calibre_page1
calibre_page2

### Koreader Screenshots
Reader_2023-02-03_121910
Reader_2023-02-03_121927

#### Steps to reproduce
1. Create an ebook with an element that contains the css rule `page-break-after: always`. Assign this element a margin of some value.
2. Create an element after the above element, and assign this element a top margin.
3. Open the ebook, and see that the second element's top margin isn't respected.

### Sample epub3 ebook with the above elements, in zip file
[pagebreak.zip](https://github.com/koreader/koreader/files/10578006/pagebreak.zip)

### PR DESCRIPTION
**Pull request by poire-z**
#### Book style tweak: revamp sample tweak

Add comments and a new one with `-cr-hint: toc-level1` (that I've been using quite frequently lately for books with no or bad ToC, and had to go find the syntax in our style tweaks).

#### TouchMenu: allow help_text on disabled menu items

Also don't propagate tap/hold on disabled menu items.
(When top and bottom menu displayed at the same time, tap on a disabled top menu item could active some bottom toggle change.)

#### CreDocument: enable crengine cache with smaller documents

crengine would not create a cache for small documents, which could actually makes re-opening small files slower than big files!

#### bump crengine: support for partial rerenderings

Includes:
- https://github.com/koreader/crengine/pull/506
  - Cache: minor simplifications 
  - Cache: improve cache file reproducibility
- https://github.com/koreader/crengine/pull/507
  - CHM: minor cleanup
  - LVStream: minor cleanups
  - LVStream: fix and improve `LVZipDecodeStream` implementation
  - LVStream: disable CRC checks for ZIP streams
- https://github.com/koreader/crengine/pull/508
  - CSS: optimize :nth-child/of-type() and :nth-last-child/of-type()
  - Page splitting: fix oversight in flags handling.
    Closes #10073.
  - Update _doc_rendering_hash also when loading from cache
  - getDocumentRenderingHash(extended): add parameter
  - Toggleable support for partial rerenderings of individual DocFragments

#### ReaderRolling: quicker partial rerenderings with EPUBs

Only available with EPUBs containing 2 or more fragments, and a file size large enough to ensure a cache file is used.
The idea is simply, on any rendering setting change, to skip the rerendering of the full book and to defer any rerendering to the moment we draw a DocFragment, and render only it.
So, on a setting change, only the fragment containing the current page will be rerendered, and the new fragments we may cross while turning pages.
When having done so, KOReader is in a degraded state (the full page count is incorrect, the ToC is invalid...).
So, a full rerendering is needed, and one will happen in the background, and when the user is idle, we reload seamlessly and quickly from the cache file it has made.
ReaderFlipping will show the new icons proposed in #10086 in the top left corner to let it know at which steps in this procress we are (see screenshots there for the upcoming KOReader behaviour).

Discussed and details all along https://github.com/koreader/koreader/issues/9087#issuecomment-1407432928.
Closes #9087. Closes #9547. Closes #6896.

I've put the menu item under `Gear > Document >`, dunno if there is a better place (but it it works fine, we shouldn't need to touch it often):
image

Timings and behaviour of the automation open for tweaking.
I've enabled it by default, so nightly users can help testing it, we'll see how good or bad it behave and if we should let it enabled for next stable.
About the other modules with which it could have bad interactions, I just took care of disabling statistics, and trashing Page browser thumbnails.
People will probably find other places where thing may look odd, or crash. Feedback welcome.
(We'll take care of the crashes, but we may let the strange things be strange, and have them back to normal after the reload.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10124)

### CODE REVIEW

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/10124)* status: all files reviewed, 11 unresolved discussions (waiting on @poire-z)

___
*[`frontend/apps/reader/modules/readerrolling.lua` line 30 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH4Dcg5BBqr7fFe5at:-NOH4DchAMWzvspvZ8iG:bfzju17) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L30)):*
> ```Lua
> --   shared_state[2] = 0 or 1, set by main process when subprocess can go on saving cache
> local ffi = require("ffi")
> local shared_state_data = ffi.C.mmap(nil, 3*4, bit.bor(ffi.C.PROT_READ, ffi.C.PROT_WRITE),
> ```

nit: `3 * ffi.sizeof("uint32_t")`
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 507 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH5BBF98VaPj96j_MV:-NOH5BBF98VaPj96j_MW:b-5pn4v5) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L507)):*
> ```Lua
> After such partial rerenderings, the book and KOReader are in a degraded state: you can turn pages, but some info and features may be broken or disabled (ie. footer info, ToC, statistics…).
> To get back into a sane state, some full rerendering is made in the background, a cache saved, and the book will be reloaded seamlessly when you are idle reading.]])
>             if cre_partial_rerendering then
> ```

[...] `by only rendering the current chapter.`
[...] `partial rendering`
[...] `To get back to a sane state, a full rendering will happen in the background, get cached, and the document will be seamlessly reloaded after a brief period of inactivity.`



_Code quote:_
```Lua
With EPUB documents (having multiple fragments), text appearance adjustments can be made quicker by rerendering only the current chapter.
After such partial rerenderings, the book and KOReader are in a degraded state: you can turn pages, but some info and features may be broken or disabled (ie. footer info, ToC, statistics…).
To get back into a sane state, some full rerendering is made in the background, a cache saved, and the book will be reloaded seamlessly when you are idle reading.]])
```
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 508 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH5tZ93GEBKuMJRohI:-NOH5tZ93GEBKuMJRohJ:b-yr6ggt) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L508)):*
> ```Lua
> To get back into a sane state, some full rerendering is made in the background, a cache saved, and the book will be reloaded seamlessly when you are idle reading.]])
>             if cre_partial_rerendering then
>                 text = text .. "\n\n" .. _("The current default (★) is to enable partial rerenderings when possible.")
> ```

`partial rendering`

(That'll be a running gag ^^. `rerender` doesn't really exist, and as long as we qualify `render`, that should be enough ;)).
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 515 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH67d69WpXX0t5J1kT:-NOH67d69WpXX0t5J1kU:b-e387yt) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L515)):*
> ```Lua
>             UIManager:show(MultiConfirmBox:new{
>                 text = text,
>                 -- This text is a bit long, and MultiConfirmBox currenlt doesn't adjust the
> ```

typo: `currently`
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1069 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH6HhZ8-mhzqMfyNh-:-NOH6HhZ8-mhzqMfyNh0:b-dzt9pu) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1069)):*
> ```Lua
>         if self.ui.document:isRerenderingDelayed(true) then
>             -- Partial rerendering is enabled, rerendering is delayed
>             logger.dbg("  but rendering delayed, will do partial rerenderings on draw")
> ```

`partial rendering`
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1757 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH7B0O8BWCzs_0NBn-:-NOH7B0O8BWCzs_0NBn0:bm58xou) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1757)):*
> ```Lua
>                 return true
>             end
>         end
> ```

This could be achieved in a cleaner manner by simply tweaking `ffiutil.isSubProcessDone` to not always use `WNOHANG ` ;).



_Code quote:_
```Lua
        while true do
            ffiutil.usleep(200000)
            if ffiutil.isSubProcessDone(self._current_rerendering_pid) then
                self._current_rerendering_pid = nil
                return true
            end
        end
```
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1800 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH7mWa2cYmR-0hdFZJ:-NOH7mWa2cYmR-0hdFZK:btsypzo) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1800)):*
> ```Lua
>             self.rendering_state = self.RENDERING_STATE.FULL_RENDERING_IN_BACKGROUND
>             if self.valid_cache_rendering_hash and
>                         self.valid_cache_rendering_hash == self.ui.document:getDocumentRenderingHash(false) then
> ```

nit: stray space or intentional? (it looks crappy in reviewable, FWIW ;p).
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1804 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH7wER6Ri5p8A2EdA1:-NOH7wER6Ri5p8A2EdA2:bvufwdk) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1804)):*
> ```Lua
>                 -- We'll still show the rendering icon to keep the icon workflow consistent,
>                 -- it will just not display for long
>                 logger.dbg("background rerendering not needed, current cache is usable")
> ```

nit: I've stopped pointing out the `rerender` mentions ;p.
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1829 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH89Ig71A0kfmMEPZQ:-NOH89Ig71A0kfmMEPZR:b-lr4ehn) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1829)):*
> ```Lua
>                 -- is triggered, we'll be go at step 1).
>                 -- Let's go with a delay of 3s.
>                 local top_widget = UIManager:getNthTopWidget(1)
> ```

`local top_widget = UIManager:getTopmostVisibleWidget() or {}`

(Should account for AutoDim's Trapper shenanigans, and you can then drop the nil guard in the check below and just do a string comparison)
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 1870 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOH8_pi7Fm_G2zYNf7Y:-NOH8_pi7Fm_G2zYNf7Z:b-7ropln) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L1870)):*
> ```Lua
>                 -- Let's go with 5s of idle time
>                 local do_reload = false
>                 local top_widget = UIManager:getNthTopWidget(1)
> ```

ditto
___
*[`frontend/apps/reader/modules/readerrolling.lua` line 2007 at r1](https://reviewable.io/reviews/koreader/koreader/10124#-NOHAWl-BLGbEgvYFwFD:-NOHAWl-BLGbEgvYFwFE:b1tziyb) ([raw file](https://github.com/koreader/koreader/blob/0410470c0a90f753873144266b4fedf1458921c4/frontend/apps/reader/modules/readerrolling.lua#L2007)):*
> ```Lua
>                 os.exit(0)
>             end
>             if ffi.C.getppid() ~= koreader_pid then
> ```

The `getppid` result could be cached, it's unlikely to change at runtime ;o).

**Comment by poire-z** [comment]
> (That'll be a running gag ^^. rerender doesn't really exist, and as long as we qualify render, that should be enough ;)).

Well, I've explicitely used `partial RErendering` everywhere in the code to make it explicitely its a re-render, and needs a full rendering to have been done previously.
So, although in French we all re-make tons of new words prefixed by `re-`, if you find this really unnatural, I'll change it in the UI text, but let all these things in the code and logger().

> nit: stray space or intentional? (it looks crappy in reviewable, FWIW ;p).

It was too long on a single line, and I found no better way to make it stand out from the logical indent of the `if end` content. Would always looks crappy in all my attempts.
(We disccused how to indent them in other coding style discussions, each of use had his favorite way, which may look better than another in some contexts.)

> `local top_widget = UIManager:getTopmostVisibleWidget() or {}`
(Should account for AutoDim's Trapper shenanigans, and you can then drop the nil guard in the check below and just do a string comparison)

Well, not really knowing how those invisible things over ReaderUI are used, I would assume that if there is one, we'd rather not mess with it and wait for it to be gone.
So the use of `getNthTopWidget()` which doesn't skip/hide these invisible thingies.
Should I really not care ? and risk provoking a document reload while some other stuff is progressing and doing its thing, that may end incomplete ?

> The getppid result could be cached, it's unlikely to change at runtime ;o).

Except if you Ctrl-C the emulator (or koreader crashes), and you could get the child process running forever. So this check: if the parent pid become 1 (init) or something else: die.

**Comment by NiLuJe** [comment]
> So, although in French we all re-make tons of new words prefixed by `re-`, if you find this really unnatural, I'll change it in the UI text, but let all these things in the code and logger().

Yeah, I was mainly concerned with the UI; maybe the logger; but am definitely fine with leaving the code alone ;).



> Well, not really knowing how those invisible things over ReaderUI are used, I would assume that if there is one, we'd rather not mess with it and wait for it to be gone.

That may be a good point. That said: it may (theoretically) *never* be gone; and it'll do its thing regardless, so I *feel* okay with ignoring 'em?


> Except if you Ctrl-C the emulator (or koreader crashes), and you could get the child process running forever. So this check: if the parent pid become 1 (init) or something else: die.

Very good point ;).

**Comment by mergen3107** [comment]
So this is only for epub? How about fb2? :D

**Comment by NiLuJe** [comment]
Nope: https://github.com/koreader/crengine/blob/0c674ef9cc6b8fb8bd0b4530665f3b303bd22029/crengine/src/lvtinydom.cpp#L5146-L5153

**Comment by poire-z** [comment]
Yep, sorry FB2 :(

> This could be achieved in a cleaner manner by simply tweaking ffiutil.isSubProcessDone to not always use WNOHANG ;).

How would you rewrite its body if we wanted be util.isSubProcessDone(pid, wait) ? (Too lazy to think about it :)
(Would it be as interruptible with Ctrl-C as with these sleep ?)

**Comment by mergen3107** [comment]
Ok :D it is fb2epub batch converting time (jk)

**Comment by NiLuJe** [comment]
> How would you rewrite its body if we wanted be util.isSubProcessDone(pid, wait)

```diff
diff --git a/ffi/util.lua b/ffi/util.lua
index fa6476ea..2a1cc041 100644
--- a/ffi/util.lua
+++ b/ffi/util.lua
@@ -373,11 +373,11 @@ function util.runInSubProcess(func, with_pipe, double_fork)
 end
 
 --- Collect subprocess so it does not become a zombie.
--- This does not block. Returns true if process was collected or was already
--- no more running, false if process is still running
-function util.isSubProcessDone(pid)
+-- This does not block, unless `wait` is `true.
+-- Returns true if process was collected or has already exited, false if process is still running.
+function util.isSubProcessDone(pid, wait)
     local status = ffi.new('int[1]')
-    local ret = C.waitpid(pid, status, 1) -- 1 = WNOHANG : don't wait, just tell
+    local ret = C.waitpid(pid, status, wait and 0 or 1) -- 1 = WNOHANG: return immediately if pid is still alive
     -- status = tonumber(status[0])
     -- If still running: ret = 0 , status = 0
     -- If exited: ret = pid , status = 0 or 9 if killed
```

> Would it be as interruptible with Ctrl-C as with these sleep

Yup.

File: frontend/apps/reader/modules/readerrolling.lua [hunk 1]
```diff
@@ -1538,4 +1661,367 @@ function ReaderRolling:onToggleHideNonlinear()
...
+        UIManager.event_hook:unregister("InputEvent", self._watchInputEvent)
+        self._watchInputEvent = nil
+    end
+    -- Be sure we don't let any zombie
+    self:_waitOrKillCurrentRerenderingSubprocess(true, true)
+    Device:enableCPUCores(1)
+end
+
+function ReaderRolling:_rerenderInBackground()
+    Device:enableCPUCores(2)
```
Comment (zwim) [inline frontend/apps/reader/modules/readerrolling.lua:1945]: As I see KOReader is mostly single core by now. But hard coding `2` here might be not so clever for the future.
Maybe you could add something like `Device:getEnabledCPUCores()` and use `Device:enabledCPUCores(Device:getEnabledCPUCores() + 1)` and `Device:enabledCPUCores(Device:getEnabledCPUCores() - 1)` a few lines above?
    
Or even better a method like `Device:adjustEnabledCPUCores(+1)` and `Device:adjustEnabledCPUCores(-1)`?

Comment (poire-z) [reply frontend/apps/reader/modules/readerrolling.lua:1945]: Could probably make sense, or a bit like allow/preventStandby, incrementing/decrementing a counter so one "allow" doesn't cancel another "prevent" done somewhere else.
So, something like Device:gimmeOneMoreCore().
But not for me (without a multicore device) to try it, and not for this PR.

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerrolling.lua:1940]: While it sounds sensible in theory, given that Lua is single-threaded by nature, this won't ever make sense in practice ;).

**Comment by poire-z** [comment]
Fuck you unit tests for probably ruining my evening...

**Comment by Frenzie** [comment]
Hm, ReaderFooter? Bit confusing at a glance. Could there be a teardown missing somewhere with the separate process stuff?

**Comment by Frenzie** [comment]
> I could add also add a UIManager:quit() in before_each() to clean the stack. (Might be needed in other _spec.lua files if they one day fail).

I think you mean `after_each()`?

> Or can I force it in commonrequire.lua ?

That sounds sensible to me.

**Comment by poire-z** [comment]
Some do it in a before_each, but indeed, probably proper in after_each.

I think I'll stay with the above fix, mostly because I don't want to think any longer about unit tests, and how to handle a global test flag properly, but also because it somehow handle the case of unit test (by accident):
Unit tests, doing what they do best (besides annoying me :), should only test small features, and so should probably by design quit before nextTick() has a chance to enable partial_rendering - and so, partial rendering shouldn't have much impact on each of them.

**Comment by NiLuJe** [comment]
Yeah, your analysis is correct. UIManager doesn't necessarily "tick" in unit tests, as such, this may fire *after* teardown (i.e., from a zombie instance). A `nil` guard will paper over it, but, it's a deeper issue with many of the unit tests doing what can only be described as "very nasty shit" (that in no way, shape, or form reflect actual real world code flows; and, in fact, are very often extreme API breaks or blatant hackery) to handle stuff like that.

**Comment by poire-z** [comment]
So, let's call it quit() and move on :)
Can you merge your #10086 and I'll then merge this one ?

**Comment by poire-z** [comment]
I feared that adding `Input:inhibitInput(true) ... Input:inhibitInputUntil(0.2)` inside `ReaderUI:init()` could cause it to stay inhibited if some stuff might crash/fail in there...
And it just happened to me (because of fixes needed in my own private patch) that I got stuck on "No reader engine for this file or invalid file"...
(Fortunately, a power button press got me out of this without having to hard poweroff.)

**Comment by poire-z** [comment]
I guess this should handle such cases:
```diff
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -608,6 +608,9 @@ function ReaderUI:showReaderCoroutine(file, provider, seamless)
         if err ~= nil or ok == false then
             io.stderr:write('[!] doShowReader coroutine crashed:\n')
             io.stderr:write(debug.traceback(co, err, 1))
+            -- Restore input if we crashed before ReaderUI has restored it
+            Device:setIgnoreInput(false)
+            Input:inhibitInputUntil(0.2)
             UIManager:show(InfoMessage:new{
                 text = _("No reader engine for this file or invalid file.")
             })
```

Btw, lots of `INFO Inhibiting/Restoring user input` now, when we reload after rendeirng in background.
https://github.com/koreader/koreader/blob/e79f161516764c7f0fa7f950275489f3c5c65149/frontend/device/input.lua#L1338
https://github.com/koreader/koreader/blob/e79f161516764c7f0fa7f950275489f3c5c65149/frontend/device/input.lua#L1369
Should these be changed to DEBUG ? Or safer to keep as INFO to debug any "koreader locked" issue in user reports ?

**Comment by NiLuJe** [comment]
Yeah, they are sorta useful when we don't get debug logs ;).

It shouldn't be *too* chatty once per document open, right?

**Comment by poire-z** [comment]
> Oh, it gets tripped by the bg rendering process, too? Eeeeh :/.

Yep. I don't really really mind, it's an indicator we did a rerendering at that time. and it's soon followed by all the opening logs, so...

Another small issue: I took care of UIManager:show(ReaderUI, "ui") insted of "partial" when "seamless" reopening. But sometimes, I still get a flash - not super bothering, but it feels a bit inconsistent that you sometimes get it and most of the time not.
Logging the requests for "partial" after such reopenings, there are quite a few :)

```
02/18/23-17:50:34 DEBUG   rendering took 0.008 seconds
02/18/23-17:50:34 DEBUG validateAndFixToc(): quick scan
02/18/23-17:50:34 DEBUG validateAndFixToc(): TOC is fine
02/18/23-17:50:34 DEBUG CreDocument: goto page 544 flow 0
02/18/23-17:50:34 WARN  partial stack traceback:
        frontend/ui/uimanager.lua:534: in function 'setDirty'
        frontend/apps/reader/modules/readerview.lua:718: in function 'recalculate'
        frontend/apps/reader/modules/readerview.lua:938: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/apps/reader/modules/readerrolling.lua:1226: in function '_gotoPage'
        frontend/apps/reader/modules/readerrolling.lua:1235: in function '_gotoXPointer'
        frontend/apps/reader/modules/readerrolling.lua:245: in function 'setupXpointer'
        frontend/apps/reader/modules/readerrolling.lua:386: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/apps/reader/readerui.lua:476: in function 'init'
        frontend/ui/widget/widget.lua:46: in function 'new'
        frontend/apps/reader/readerui.lua:649: in function 'doShowReader'
        frontend/apps/reader/readerui.lua:605: in function <frontend/apps/reader/readerui.lua:604>
02/18/23-17:50:34 DEBUG _refresh: Enqueued partial update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG update_mode: Update refresh mode partial to full
02/18/23-17:50:34 DEBUG _refresh: Enqueued full update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty full from widget nil w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG ReaderStatistics: No timestamp for previous page 0
02/18/23-17:50:34 DEBUG CreDocument: goto xpointer /body/DocFragment[69]/body/section/div[1].0
02/18/23-17:50:34 WARN  partial stack traceback:
        frontend/ui/uimanager.lua:534: in function 'setDirty'
        frontend/apps/reader/modules/readerrolling.lua:1089: in function 'updatePos'
        frontend/apps/reader/modules/readerrolling.lua:101: in function 'v'
        frontend/apps/reader/readerui.lua:479: in function 'init'
        frontend/ui/widget/widget.lua:46: in function 'new'
        frontend/apps/reader/readerui.lua:649: in function 'doShowReader'
        frontend/apps/reader/readerui.lua:605: in function <frontend/apps/reader/readerui.lua:604>
02/18/23-17:50:34 DEBUG _refresh: Enqueued full update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG CreDocument: set bookmarks highlight and internal history false
02/18/23-17:50:34 WARN  partial stack traceback:
        frontend/ui/uimanager.lua:534: in function 'setDirty'
        frontend/apps/reader/modules/readerview.lua:718: in function 'recalculate'
        frontend/apps/reader/modules/readerview.lua:938: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/apps/reader/modules/readerrolling.lua:1120: in function 'onRedrawCurrentView'
        frontend/apps/reader/modules/readerrolling.lua:104: in function 'v'
        frontend/apps/reader/readerui.lua:479: in function 'init'
        frontend/ui/widget/widget.lua:46: in function 'new'
        frontend/apps/reader/readerui.lua:649: in function 'doShowReader'
        frontend/apps/reader/readerui.lua:605: in function <frontend/apps/reader/readerui.lua:604>
02/18/23-17:50:34 DEBUG _refresh: Enqueued full update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty partial from widget ReaderUI w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG _refresh: Enqueued full update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty full from widget nil w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG Spinning up new ReaderUI instance table: 0x7f35da1732a0
02/18/23-17:50:34 DEBUG show widget: ReaderUI
02/18/23-17:50:34 DEBUG _refresh: Enqueued full update for region 0 0 600 610 dithering: false
02/18/23-17:50:34 DEBUG setDirty ui from widget ReaderUI w/ NO region; dithering: nil
02/18/23-17:50:34 DEBUG painting widget: ReaderUI
```
and mine seems to be at the end ?!
Any thought about how to avoid it ? Resetting the FULL_REFRESH_COUNT to 0 ?

**Comment by NiLuJe** [comment]
> Any thought about how to avoid it ? Resetting the FULL_REFRESH_COUNT to 0 ?

I don' tthink I'd feel very nice about special-casing either RV's `recalculate` or RR's `updatePos` (especially the latter), sooo, yeah, poking at UIManager's refresh counter might be the lesser of evil?

(Plus, that might also be able to replace the `seamless` hack?)

**Comment by NiLuJe** [comment]
I would have mentioned temporarily monkey-patching `setDirty` via a wrapper to filter `partial` by replacing it by `ui` in said wrapper, but it's not viable because of the whole "refresh as a closure" thingy, where you *cannot* run the closure inside `setDirty` itself ;o).

**Comment by poire-z** [comment]
> (Plus, that might also be able to replace the seamless hack?)

I would still need that "seamless" parameter to avoid the `Opening ...epub` InfoMessage.
But yes, if I find another trick, I could get rid of the `UIManager:show(reader, seamless and "ui" or "full")`.

There is another trick that we use when scrolling, `UIManager.currently_scrolling = true` so it demotes everything to "fast".
Dunno if I could just wrap the whole seamless sequence with `UIManager.currently_seamless = true/false` :) that would demote "full" and "partial" to "ui" ? How would you feel about that ?

**Comment by NiLuJe** [comment]
Depends on how spidery the modifications have to be, I guess? It might end up simpler to just trick UIManager's refresh count.

**Comment by poire-z** [comment]
What about this (reusing/hijacking your `self.refresh_counted`) ?:
```diff
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua

 function ReaderUI:doShowReader(file, provider, seamless)
+    if seamless then
+        UIManager:avoidFlashOnNextRepaint()
+       -- have to do this that early because many thing happen before show(ReaderUI)
+    end
     logger.info("opening file", file)
     -- Only keep a single instance running
     if ReaderUI.instance then
diff --git a/frontend/ui/uimanager.lua b/frontend/ui/uimanager.lua
index ecc94210..09ec5a03 100644
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -1124,12 +1124,16 @@ function UIManager:_refresh(mode, region, dither)
     --       because it is implemented as "ui" over the full viewport, since we can't devise a proper bounding box).
     --       So we settle for only "partial", but treating full-screen ones slightly differently.
     if mode == "partial" and not self.refresh_counted then
-        self.refresh_count = (self.refresh_count + 1) % self.FULL_REFRESH_COUNT
+        if self.FULL_REFRESH_COUNT > 0 then -- just to avoid getting stuck with self.refresh_count = NaN
+            self.refresh_count = (self.refresh_count + 1) % self.FULL_REFRESH_COUNT
+        end
         if self.refresh_count == self.FULL_REFRESH_COUNT - 1 then
             -- NOTE: Promote to "full" if no region (reader), to "flashui" otherwise (UI)
             if region then
                 mode = "flashui"
             else
                 mode = "full"
             end
             logger.dbg("_refresh: promote refresh to", mode)
@@ -1290,6 +1295,11 @@ function UIManager:forceRePaint()

+function UIManager:avoidFlashOnNextRepaint()
+    self.refresh_counted = true
+end
```

**Comment by NiLuJe** [comment]
> What about this (reusing/hijacking your `self.refresh_counted`)

That sounds good, yeah ;).

(I'd just move the `self.FULL_REFRESH_COUNT > 0` check to the initial branch check (`if mode == "partial" and not self.refresh_counted`), as the whole thing is meaningless for 0 (never) and -- (chapters)).

**Comment by Frenzie** [comment]
I traced the introduction of the problem I mentioned in https://github.com/koreader/koreader/pull/10156#issuecomment-1442418882 to this PR.

Specifically:
1. Open the program in the file browser.
2. Open history.
3. Crash.

```
./luajit: frontend/ui/widget/touchmenu.lua:651: loop or previous error loading module 'apps/reader/readerui'
stack traceback:
        [C]: in function 'require'
        frontend/ui/widget/touchmenu.lua:651: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/uimanager.lua:191: in function 'close'
        frontend/apps/filemanager/filemanagermenu.lua:862: in function 'onCloseFileManagerMenu'
        frontend/apps/filemanager/filemanagermenu.lua:848: in function 'close_callback'
        frontend/ui/widget/touchmenu.lua:819: in function 'closeMenu'
        frontend/ui/widget/touchmenu.lua:920: in function 'onMenuSelect'
        frontend/ui/widget/touchmenu.lua:216: in function 'handleEvent'
        frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
        ...
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
        frontend/ui/uimanager.lua:875: in function 'sendEvent'
        frontend/ui/uimanager.lua:51: in function '__default__'
        frontend/ui/uimanager.lua:1404: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1502: in function 'handleInput'
        frontend/ui/uimanager.lua:1549: in function 'run'
        ./reader.lua:315: in main chunk
        [C]: at 0x55fa333127ab
~/src/koreader
```

**Comment by poire-z** [comment]
Can't reproduce, following your steps :/

> loop or previous error loading module 'apps/reader/readerui'

No previous error message about readerui failing loading ?
(base/cre.cpp correcting bumped, no stated libkoreader-cre and failed loading some symbol/methods ?)

**Comment by Frenzie** [comment]
The regular `git submodule update --recursive`, but indeed the submodule wasn't actually updated due to some local changes in base. D'oh. :-)
