### PR TITLE
A bundle of tweaks

### LINKED ISSUE #9556: 2022.8 page turn buttons need to be reversed when orientation is set to "horizontal"
* KOReader version: 2022.8 Tumbleweed
* Device: Pocketbook Era PB700

#### Steps to reproduce

Pocketbook Era page turn buttons are reversed when orientation is set to "horizontal", (which places the page turn buttons at the bottom of the device). Currently the left button advances the page number and the right button decreases it.

### LINKED ISSUE #9700: 2022.10 crashes if DCREREADER_CONFIG_MARGIN_SIZES present in defaults.persistent.lua
I got this when upgrading from something a few months old, maybe 2022.07:

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 10/28/22-19:17:57
 [*] Version: v2022.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
10/28/22-19:17:57 INFO  initializing for device Kobo_star 
10/28/22-19:17:57 INFO  framebuffer resolution: {
  h = 1024,
  w = 758
} --[[table: 0x2b0b2518]] 
[ko-input] Forked off fake event generator (pid: 26837)
10/28/22-19:17:57 WARN  Device:getKeyRepeat: EVIOCGREP ioctl failed: Function not implemented 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
10/28/22-19:17:57 INFO  Performing one-time migration for 20220819 
10/28/22-19:17:57 INFO  Performing one-time migration for 20220914 
10/28/22-19:17:57 INFO  Performing one-time migration for 20220930 
./luajit: ./defaults.persistent.lua:27: attempt to call global 'DCREREADER_CONFIG_MARGIN_SIZES' (a nil value)
stack traceback:
	./defaults.persistent.lua:27: in function 'load_defaults'
	frontend/ui/data/onetime_migration.lua:459: in main chunk
	[C]: in function 'require'
	./reader.lua:189: in main chunk
	[C]: at 0x000140bd
!!!!
```

related contents of defaults.persistent.lua:

```
-- page margins {left, top, right, bottom} in pixels
DCREREADER_CONFIG_MARGIN_SIZES {5, 2, 5, 5}
```

commenting out the DCREREADER_CONFIG_MARGIN_SIZES line fixed the crash, but it would have been a nicer user experience if it had ignored or converted the value instead of crashing.

### LINKED ISSUE #9704: can't seem to look up words with chinese dictionary
* KOReader version: v2022.10-28-gd7c63edc_2022-10-28
* Device: kindle paperwhite 3

looking up words with the chinese dictionary doesn't work. I simply get "no results" in the dialogue both when i select a word to look up with the tap gesture and when manually searching for one. i've tried the dictionary installed from within the app, manually installing the dictionary, using the stable release, using the nightly release, disabling the japanese plugin, disabling fuzzy search, and so on.

i'm sure the logs have some helpful info, i'm just not sure how to interpret them.

(not sure why the formatting below is broken) (nm, fixed <3)
<details>
  <summary>crash.log</summary>

```
--- 10.0.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 102.052/102.052/102.052 ms
10/28/22-21:25:27 INFO  opening file ./help/quickstart-en-v2022.10-28-gd7c63edc_2022-10-28.html 
CRE: font NotoSerifKR regular: updated weight from 500 to 400
CRE: font NotoSerifKR bold: updated weight from 900 to 700
CRE: font PMN Caecilia LT regular: updated weight from 500 to 400
CRE: font NotoSansKR bold: updated weight from 900 to 700
10/28/22-21:25:28 INFO  Loading plugins from directory: plugins 
10/28/22-21:25:28 INFO  CoverBrowser: setting default display modes 
10/28/22-21:25:28 WARN  BookInfo cache DB schema updated from version 0 to version 20201210 
10/28/22-21:25:28 WARN  Deleting existing ./settings/bookinfo_cache.sqlite3 to recreate it 
10/28/22-21:26:04 INFO  opening file /mnt/us/bks/神经漫游者三部曲 by 吉布森.epub 
CRE: document loaded, but styles re-init needed (cause: peculiar CSS pseudoclasses met)
CRE: styles re-init needed after load, re-rendering
./tar: stardict-chinese-eng-2.4.2/chinese-eng.ifo: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
./tar: stardict-chinese-eng-2.4.2/chinese-eng.dict.dz: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
./tar: stardict-chinese-eng-2.4.2/chinese-eng.idx: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
./tar: stardict-chinese-eng-2.4.2: Cannot change ownership to uid 1000, gid 1000: Operation not permitted
./tar: Exiting with failure status due to previous errors
10/28/22-21:26:38 WARN  unwrapped dismissablePopen(), falling back to blocking io.popen() 
10/28/22-21:27:24 WARN  unwrapped dismissablePopen(), falling back to blocking io.popen() 
10/28/22-21:27:58 INFO  no dialog left to show 
10/28/22-21:27:58 INFO  quitting uimanager with exit code: 0 
lipc-wait-event exited normally with status: 0
```
</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
* InputContainer: Drop dead code in the form of `seqtext` & `doc` fields. I'm not sure if they're remnants of KPV or of an aoborted design, but it's been very dead code for a very long while.
This spurred a bit of cleanup along the way ;p.
* Persist: Make sure data is flushed to disk on save (fix https://github.com/koreader/koreader/issues/9552#issuecomment-1287144009)
* GestureDetector: Only log adjusted gestures for gestures actually requiring a rotation adjustment ;).
* Kobo: Flag all the boards similar to the Libra 2 as broken^Wbuggy, and enable the full set of workarounds there (re: https://github.com/koreader/koreader/issues/9552).
* USBMS: Add a nicer info-level log message when entering USBMS, because apparently people are confused by the UIManager:quit ones.
* Kobo: Downgrade a few non-failure PM log messages to debug.
* Kindle: Ditto (that one's for you @hius07 ;p).
* GH: Update the issue template to mention that toggling verbose debug logging requires a restart.
* AutoSuspend: Update the standby help message to be friendlier to everyone, but specifically warn affected users on the aforementioned broken^Wbuggy boards ;).
* Input: Allow disabling rotation_map entirely, and do so on the PB700 (fix #9556)
* PocketBook: Move low-level input event type translation to the low-level input modules.
* OTM: Deal with a fun little quirk of the `defaults.lua` migration (fix #9700)
* Kindle: Make sure `Device:untar` actually works when targeting the userstore fuse proxy (fix #9704)

Depends on https://github.com/koreader/koreader-base/pull/1544 & https://github.com/koreader/koreader-base/pull/1545

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9691)

### CODE REVIEW

**Comment by NiLuJe** [comment]
(Rebase me).

First commit ended up sliiightly scarier than I expected :D.

**Review by poire-z — APPROVED** [review]

**Comment by poire-z** [comment]
(Approved as "ok on the principle", not that I approve the unit tests failing :)

**Comment by NiLuJe** [comment]
Yeah, unit tests *should* be fixed by the base bump ;p.

**Comment by hius07** [comment]
Side question. Should we use such alignment more often? (looks good)
https://github.com/koreader/koreader/blob/8921e8049d68a22051c59b7d7f40b42ce354da99/frontend/ui/widget/container/scrollablecontainer.lua#L82-L90

File: frontend/device/pocketbook/device.lua [hunk 1]
```diff
@@ -62,6 +62,10 @@ local PocketBook = Generic:extend{
     --- @fixme: Never actually set anywhere?
     is_using_raw_input = nil,
 
+    -- InkView may have started translating button codes based on rotation on newer devices...
+    -- That historically wasn't the case, hence this defaulting to false.
+    iv_translates_buttons = false,
```
Comment (poire-z) [inline frontend/device/pocketbook/device.lua:67]: You could prefix these with `inkview_` instead of the less explicite `iv_` ?

Comment (NiLuJe) [reply frontend/device/pocketbook/device.lua:67]: It also happens to be the standard prefix for iv functions, which is more of a reason *not* to use it here, ;).

File: .github/ISSUE_TEMPLATE/bug_report.md [hunk 2]
```diff
@@ -29,6 +29,7 @@ You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dra
 
 If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
 To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
+You will need to restart KOReader after toggling these on.
```
Comment (Frenzie) [inline .github/ISSUE_TEMPLATE/bug_report.md:32]: Since we're not being super formal, I'd go with:
```suggestion
You'll need to restart KOReader after toggling these on.
```
Or more impersonal:
```suggestion
KOReader will need to be restarted after toggling these on.
```

**Review by Frenzie — APPROVED** [review]

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 79 of 84 files at r1, 4 of 4 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9691)* status: all files reviewed, 2 unresolved discussions (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9691)* status: all files reviewed, 2 unresolved discussions (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/9691)* status: all files reviewed, 2 unresolved discussions (waiting on @Frenzie, @pazos, and @poire-z)

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 3]
```diff
@@ -233,8 +233,8 @@ function ReaderHighlight:init()
 end
 
 function ReaderHighlight:setupTouchZones()
-    -- deligate gesture listener to readerui
-    self.ges_events = {}
+    -- delegate gesture listener to readerui
+    self.ges_events = nil
```
Comment (yparitcher) [inline frontend/apps/reader/modules/readerhighlight.lua:237]: @NiLuJe 
Regression

The 4 places you changed `self.ges_events` from `{}` to `nil` do not let me do any gestures in the reader (even swipe to open the menu)

`./luajit: frontend/ui/widget/container/inputcontainer.lua:257: bad argument #1 to 'pairs' (table expected, got nil)`

**Comment by hius07** [comment]
(Writing here as it's one of the latest PR changing the Menu widget)

On a tap the coroutine is created:
https://github.com/koreader/koreader/blob/068809bb936edac2696818fee7a0929d887690ac/frontend/ui/widget/menu.lua#L487-L498
This was introduced in https://github.com/koreader/koreader/pull/1637 to support OPDS authorization. 
Since then OPDSBrowser has been changed a lot and now does not check for a coroutine existence.
So is this coroutine creation needed anymore?

**Comment by poire-z** [comment]
Not really familiar with corountines (or what I learned about them when I needed to make Trapper, I have forgotten), but indeed, we never really need to use coroutines, so I guess if we'd rewrite this menu select code now, we wouldn't even think about adding anything coroutine in there :)
So, if everything keeps working without, nothing against cleaning that out.

**Comment by Frenzie** [comment]
I forgot that was in there. What that code is doing seems sensible for that kind of scenario though? What happens now? I don't really use OPDS much, let alone with authorization.

**Comment by hius07** [comment]
> What happens now?

Earlier there was an option to authorize to opds server manually via the dialog entering login/pwd.
Now login/pwd must be saved to the server properties, no online dialog for login exists.
