### PR TITLE
TitleBar left and right buttons navigation on non-touch devices

### LINKED ISSUE #9027: Cloud Storage bug on Kindle 4NT
* KOReader version: 2022.03.1
* Device: Kindle 4NT

#### Issue
The **Cloud Storage** option is empty when I access this menu on my Kindle 4NT. 

I should see the "**Add new Cloud Storage**" button (for use with Dropbox or FTP) but it doesn't. I checked inside the folder "\Koreader\frontend\apps\cloustorage" and all the ".lua" files are there (dropbox.lua; ftpapi.lua; dropboxapi.lua; ftp.lua; webdav.lua; cloudstorage.lua).

I compared these files with those on a newer device and they appear to be the same

Did I miss some configuration?

##### `crash.log` 

```
[crash.log](https://github.com/koreader/koreader/files/8535212/crash.log)

```
</details>

### PR DESCRIPTION
**Pull request by comphilip**
## Preview
output

## Design
Fix #9027 

There are 22 `TitleBar:new` in source code. Only few of them have buttons other than just right `close` button (`PageBrowserWidget` has TitleBar with buttons while it is disabled for non-touch device.):
* File Manager
* History
* Folder Shortcuts
* Favorites
* Cloud Storage

All these pages are based on `Menu` widget. `Menu` widget replaces `FocusManager` move focus right key listener as menu item `Hold` event listener. It also turn off move focus left key listener on `hasFewKey()` device. It is hard to support horizontal focus movement between `TitleBar` buttons in `Menu` widget.

After several failure solutions, making `TitleBar` buttons layout in vertical is a simple and safe solution so far.

layout

## Code Changes
**frontend/ui/widget/titlebar.lua**
Show left and right on non-touch devices
Methods to generate FocusManager layout for parent widget to merge

**frontend/ui/widget/titlebar.lua**
`addTitleBarLayout` method to merge TitleBars' buttons layout
call `addTitleBarLayout` in `updateItems` method

**plugins/coverbrowser.koplugin/covermenu.lua**
call `Menu.addTitleBarLayout` in `updateItems` method

**frontend/ui/widget/filechooser.lua**
call `Menu.addTitleBarLayout` in `updateItems` method

**frontend/apps/filemanager/filemanager.lua**
pass TitleBar to FileChooser to merge layout

**frontend/ui/widget/inputtext.lua**
Hide `Show password` checkbox, it does not work with FocusManager

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9041)

### CODE REVIEW

File: frontend/ui/widget/menu.lua [hunk 1]
```diff
@@ -1107,6 +1108,26 @@ function Menu:updateItems(select_number)
     end)
 end
 
+-- merge TitleBar layout into self FocusManager layout
+function Menu:addTitleBarLayout()
+    local menu_item_layout_start_row = 1
+    local titlebars = {self.title_bar, self.outer_title_bar}
```
Comment (poire-z) [inline frontend/ui/widget/menu.lua:1114]: I can't visualize the fact that we have 2 title bars in File manager :/ Is this really the case ?

File: frontend/apps/filemanager/filemanager.lua [hunk 2]
```diff
@@ -146,6 +146,8 @@ function FileManager:setupLayout()
         return_arrow_propagation = true,
         -- allow Menu widget to delegate handling of some gestures to GestureManager
         filemanager = self,
+        -- let Menu widget to merge TitleBar's FocusManager layout
```
Comment (poire-z) [inline frontend/apps/filemanager/filemanager.lua:149]: Sorry, a few rewording to more correct English for easier future reading :)
As I understand it, so I may be wrong, correct me if my wording is not what you/the code means.
`-- let Menu widget merge our title_bar into its own TitleBar's FocusManager layout`

File: frontend/ui/widget/focusmanager.lua [hunk 3]
```diff
@@ -208,6 +208,7 @@ function FocusManager:onFocusMove(args)
     end
 
     if not self.layout[self.selected.y] or not self.layout[self.selected.y][self.selected.x] then
+        logger.dbg("FocusManager: Not found current selected widget")
```
Comment (poire-z) [inline frontend/ui/widget/focusmanager.lua:211]: `logger.dbg("FocusManager: no currently selected widget found")`

File: frontend/ui/widget/menu.lua [hunk 4]
```diff
@@ -1107,6 +1108,26 @@ function Menu:updateItems(select_number)
...
+    for _, v in ipairs(titlebars) do
+        -- Menu use right key for context menu trigger, there is no chances to move focus in horizontal directions
+        -- Add title bar buttons to layout in vertical directions
```
Comment (poire-z) [inline frontend/ui/widget/menu.lua:1117]:
```
-- Menu uses the right key to trigger the context menu: we can't use it to move focus in horizontal directions.
-- So, add title bar buttons to FocusManager's layout in a vertical-only layout
```

File: frontend/ui/widget/menu.lua [hunk 5]
```diff
@@ -1107,6 +1108,26 @@ function Menu:updateItems(select_number)
...
+        local title_bar_layout = v:generateVerticalLayout()
+        for _, row in ipairs(title_bar_layout) do
+            table.insert(self.layout, menu_item_layout_start_row, row)
+            menu_item_layout_start_row = menu_item_layout_start_row + 1
+        end
+    end
+    if menu_item_layout_start_row > #self.layout then -- no menu items
+        menu_item_layout_start_row = #self.layout -- void index overflow
```
Comment (poire-z) [inline frontend/ui/widget/menu.lua:1125]: -- **a**void index overflow

File: frontend/ui/widget/menu.lua [hunk 6]
```diff
@@ -1107,6 +1108,26 @@ function Menu:updateItems(select_number)
     end)
 end
 
+-- merge TitleBar layout into self FocusManager layout
+function Menu:addTitleBarLayout()
```
Comment (poire-z) [inline frontend/ui/widget/menu.lua:1112]: This function name feels a bit odd (it reads as "add a title bar layout").
Shouldn't it read as `Menu:addTitleBarToLayout()` or `Menu:mergeTitleBarIntoLayout()`

File: frontend/ui/widget/menu.lua (hunk 1 above)
Comment (comphilip) [reply frontend/ui/widget/menu.lua:1114]: Yes. File Manager has TitleBar with Home and Plus buttons. Its menu widget has its own Titlebar without buttons but showing current directory.

File: frontend/apps/filemanager/filemanager.lua (hunk 2 above)
Comment (comphilip) [reply frontend/apps/filemanager/filemanager.lua]: Comment message updated

File: frontend/ui/widget/menu.lua (hunk 5 above)
Comment (comphilip) [reply frontend/ui/widget/menu.lua]: Typo fixed

File: frontend/ui/widget/menu.lua (hunk 6 above)
Comment (comphilip) [reply frontend/ui/widget/menu.lua]: method renamed

File: frontend/ui/widget/menu.lua (hunk 4 above)
Comment (comphilip) [reply frontend/ui/widget/menu.lua]: comment updated

File: frontend/ui/widget/focusmanager.lua (hunk 3 above)
Comment (comphilip) [reply frontend/ui/widget/focusmanager.lua]: message updated

**Review by poire-z — APPROVED** [review]

File: frontend/ui/widget/menu.lua (hunk 1 above)
Comment (hius07) [reply frontend/ui/widget/menu.lua:1114]: > Its menu widget has its own Titlebar without buttons but showing current directory.

Can you please show it? I see that the current directory is a subtitle of the TitleBar.
https://github.com/koreader/koreader/blob/d6ff9832431a2141b5f509c9ac5006204ee475fb/frontend/apps/filemanager/filemanager.lua#L104-L109

Comment (poire-z) [reply frontend/ui/widget/menu.lua:1114]: Technically, FileManager makes its own title_bar, and use a FileChooser below.
FileChooser extends Menu, and Menu can have its own title_bar - but FileChooser extends Menu with providing `no_title=true`, which will have Menu builds its own title_bar, but actually _not_ inserting it into its main widget (which is indeed a bit confusing, and might be a old hack, but it's working :). Dunno if it inserts it into its focusmanager layout stuff.

So, it seems that even if we have the 2 title_bar built, the Menu/FileChooser one, not being in the displayed widget, won't be usable by FocusManager.
No issue with this merging trick? Should this trick be kept?

Comment (comphilip) [reply frontend/ui/widget/menu.lua:1114]: @hius07 You are right. Current directory is a subtitle of Titlebar in FileManager. As @poire-z said, FileChooser set `no_title=true` to hide Menu's Titlebar.  The `Menu:mergeTitleBarIntoLayout` works well for these scenarios.

self.title_bar never be nil even no_title=true
self.outer_title_bar can be nil, well table length is 1 if it is nil, no extra if branch needed
https://github.com/koreader/koreader/blob/fa76b9d61527b8f96c1f9f1e6b64ea7f63e8fb4a/frontend/ui/widget/menu.lua#L1114

`generateVerticalLayout` returns empty layout table if no buttons in title bar, and the following for will be skipped.
https://github.com/koreader/koreader/blob/fa76b9d61527b8f96c1f9f1e6b64ea7f63e8fb4a/frontend/ui/widget/menu.lua#L1118-L1122
