### PR TITLE
Kindle: Attempt to deal with sticky "waking up" hibernation banners

### LINKED ISSUE #9482: "Waking up" message no longer clears automatically after the update
* KOReader version: 2022.08

* Device: Kindle paperwhite (10th Gen)

#### Issue

Whenever the Kindle Paperwhite resumes the "_waking up_" message doesn't clear automatically as before, can only remove it once I advance/recede pages.

#### Steps to reproduce

Just resume/wake up the device

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #9482 (which, I, err, can't actually reproduce, the banner gets caught by the standard refresh on my device ^^).

Anyway, that was a fun investigation, many thanks to @yparitcher for playing along ;).

c.f., https://github.com/NiLuJe/koreader/commit/019f2b4a6f40435718765b877b1faec068907208 for more details.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9491)

### CODE REVIEW

File: frontend/device/kindle/device.lua [hunk 1]
```diff
@@ -204,10 +204,40 @@ function Kindle:supportsScreensaver()
...
+            appreg:rowexec("SELECT value FROM properties WHERE handlerId = 'dcd' AND name = 'hibernate.s2h.rtc.secs'") or
+            3600
+        appreg:close()
+        if hibernation_disabled == 1 then
+            self.canDeepSleep = false
+        else
+            self.canDeepSleep = true
+            self.hibernationDelay = tonumber(hibernation_delay)
+            logger.dbg("Kindle: Device supports hibernation, enters hibernation after", self.hibernationDelay, "seconds in suspend")
+        end
```
Comment (Frenzie) [inline frontend/device/kindle/device.lua:230]: Looks a bit brittle (in the what if they change it sense). What happens if the QUERY says that table doesn't exist or something?

**Review by Frenzie — APPROVED** [review]
See comment but I'm basically fine with it as is.

File: frontend/device/kindle/device.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/device/kindle/device.lua:230]: For the first query, EXISTS returns 0 and we assume ti's enabled, and for the other two, we fall back to 1H ;).

Comment (NiLuJe) [reply frontend/device/kindle/device.lua:230]: (Not a SQL wizard, so do feel free to poke hole in my assumptions ;p)

Comment (Frenzie) [reply frontend/device/kindle/device.lua:230]: I mean what if the query fueling hibernation_delay is effectively invalid, does it just return an otherwise harmless 1? It's not the SQL I'm asking about but how SQLite interacts with Lua here. :-)

Comment (NiLuJe) [reply frontend/device/kindle/device.lua:230]: Oh, `rowexec` returns `nil` on query failure, hence the chain of `or`s ;).

(And it throws an `error` on a malformed query).

Comment (Frenzie) [reply frontend/device/kindle/device.lua:230]: Alright, nil is good enough.

**Comment by yparitcher** [comment]
Looks good,
The only nit i might have is maybe check 15/30 sec not a minute, in case someone wakes up twice in a row, but not really important.

**Review by yparitcher — APPROVED** [review]
