### PR TITLE
Highlights: invert dialog colors in night mode

### LINKED ISSUE #14170: Preview of highlight colour displayed inverted
### Device

Android

### KOReader version

2025.04

### Model and firmware version

GrapheneOS, Pixel 8

### Issue description

Each of these colours is inverted and should not be:

Image

### Steps to reproduce

1. Open a book
2. Create a highlight
3. Set KoReader to night/dark mode
4. Tap the highlight and then select "Colour"
5. Observe that the colours are inverted

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hius07**
- Closes #14170

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14923)

### CODE REVIEW

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -50,8 +50,16 @@ function ReaderHighlight:getHighlightColorString(color_name)
...
 
 function ReaderHighlight:getHighlightColor(color_name)
-    return Blitbuffer.colorFromName(color_name) --- @todo fix in the night mode; issue #14170, #14667
-        or Blitbuffer.gray(G_reader_settings:readSetting("highlight_lighten_factor") or 0.2) -- 'gray' or unknown color name
+    local color = Blitbuffer.colorFromName(color_name)
+    if color then
+        if Screen.night_mode then
+            local r, g, b = Blitbuffer.HIGHLIGHT_COLORS[color_name]:match("#(..)(..)(..)")
+            return Blitbuffer.colorFromString(string.format("#%02x%02x%02x",
+                255 - tonumber(r, 16), 255 - tonumber(g, 16), 255 - tonumber(b, 16)))
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua:58]: I think bit.bxor(tonumber(r, 16), 0xFF) should do the same thing fwiw. (It doesn't matter here with just a few colors, but presumably it would when processing a picture pixel by pixel.)

Comment (hius07) [reply frontend/apps/reader/modules/readerhighlight.lua:58]: As far as AI advises, `bit.bxor(x, 0xFF)` is not faster than `255 - x`.

Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:58]: Better to use AI to write a test in less than a minute than to ask it things it can't know. ;-)

```lua
local bit = require("bit")
local bxor = bit.bxor  -- local cache

local function test(n)
  local clock = os.clock
  
  -- prebuild test data as hex strings, numbers
  local hex = {}
  local nums = {}
  for x = 0, 255 do
    hex[x]  = ("%02X"):format(x)
    nums[x] = x
  end

  -- warm-up
  for i = 1, 10000 do
    local x = nums[i % 256]
    local _ = bxor(x, 0xFF)
    local _ = 255 - x
  end

  print("=== Original: bxor(tonumber(x, 16), 0xFF) ===")
  local start = clock()
  for i = 1, n do
    local h = hex[i % 256]
    local x = tonumber(h, 16)
    local y = bxor(x, 0xFF)
  end
  print(("time: %.6f s"):format(clock() - start))

  print("=== Cached bxor(x, 0xFF) ===")
  start = clock()
  for i = 1, n do
    local x = nums[i % 256]
    local y = bxor(x, 0xFF)
  end
  print(("time: %.6f s"):format(clock() - start))

  print("=== 255 - x (arithmetic) ===")
  start = clock()
  for i = 1, n do
    local x = nums[i % 256]
    local y = 255 - x
  end
  print(("time: %.6f s"):format(clock() - start))
  
  print()
end

-- run with e.g. luajit test.lua 100000000
local n = tonumber(arg[1]) or 1e8
test(n)
```

```
=== Original: bxor(tonumber(x, 16), 0xFF) ===
time: 2.501012 s
=== Cached bxor(x, 0xFF) ===
time: 0.042331 s
=== 255 - x (arithmetic) ===
time: 0.044898 s
```

```
=== Original: bxor(tonumber(x, 16), 0xFF) ===
time: 2.486529 s
=== Cached bxor(x, 0xFF) ===
time: 0.042634 s
=== 255 - x (arithmetic) ===
time: 0.040219 s
```

tl;dr There's no difference, at least on this AMD Ryzen 7 7800X3D. So I'm still wrong. :-) (I'll have to double check if it's the same on some actual ereaders though.)
