### PR TITLE
[CRe] Ensure toggling nightmode invalidates the drawCurrentView cache

### LINKED ISSUE #6845: Nightmode bug
* KOReader version: v2020.10.1-28-g74c1813_2020-10-31/ 
* Device: Pocketbook InkPad 3

#### Issue
Images in books are shown in nightmode (inverted black & white) while text is shown normally, when book is reopened after closing it with nightmode activated.

#### Steps to reproduce
Open book with KOReader.
Activate nightmode (done via gesture). Text and images are shown inverted.
Close book.
Open same or other book. Splash screen is shown inverted, but book opens with black text on white background, i.e. like in normal mode. In the menu (gear) nightmode is shown as activated (checkbox). Images in the book, including the cover, are shown inverted.
Deactivating the checkbox or applying the nightmode gesture inverts text and background as in nightmode, but nightmode is shown as "off" in the menu.

In previous versions, images were not shown inverted at all with nightmode activated.

### PR DESCRIPTION
**Pull request by NiLuJe**
Instead of relying on `Screen.night_mode` at the actual call site, rely on an internal flag, toggled via a set* function, which ensures the cache framework will reset the cache, allowing the page to be re-rendered (and the image counter-inverted properly, and, more importantly, reliably ^^).

Fix #6845 (at least as far as I'm concerned, as I couldn't find anything else going awry on Kobo either with HW or SW invert ^^).

Now also includes minor ReaderHighlight tweaks to avoid spurious cache invalidations.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6854)

### CODE REVIEW

**Comment by NiLuJe** [comment]
@poire-z: I'm mildly interested about the comments around the `add_buffer_trash` flag. I don't know exactly what you had in mind, but I'd like to try something for `clearSelection`, because it'd make navigating menus much faster.

Any pointers?

(I started by checking if CRe could actually tell us is clearSelection actually did something, but that's apparently waaaay not in the cards ^^).

**Comment by poire-z** [comment]
> I don't know exactly what you had in mind, but I'd like to try something for clearSelection, because it'd make navigating menus much faster.

```
Mine:
            -- These may have crengine do native highlight or unhighlight
            -- (we could keep the original buffer and use a scratch buffer while
            -- these are used, but not worth bothering)
Yours:
            -- The only real interest would be for clearSelection, which can trigger
            -- without actual content change (e.g., toggling menus/footer).
```
I'm not sure what relation you mean between clearSelection and the menu/footer. clearSelection is the native highlighting done when you do text selection, while it is still in progress. And I think while this is in progress, you can't show/hide any menu (so, the only possible stuff is the footer auto update, but I think this is done above, over the CRE bb). Once the text selection is made, the drawing of already made highlights is done by ReaderView, over the cre bb that can, thanks to this cache, not need a re-render.

So, I guess my idea was that the original CRE bb could be cached, another bb used while text selection is in progress, and when done, instead of an additional CRE re-rendering with no native highlight, restore the original bb (so, saving one CRE rendering, to the expense of allocating another bb - not worth at all I think).

If it happens navigating the menus calls (unwillingly or too lazily) clearSelection, and that it is expensive, then it might be considered a bug and should be handled where this happens, may be by having a state somewhere `text_selection_in_progress`, set when on hold//hold_pan/hold_release, and unset once when we do clearSelection, that we won't redo if that flag is unset.

**Comment by NiLuJe** [comment]
I'm definitely almost reliably hitting a `clearSelection` when tapping... anywhere that can trigger a menu (top, bottom, footer).

**Comment by poire-z** [comment]
> (I started by checking if CRe could actually tell us if clearSelection actually did something, but that's apparently waaaay not in the cards ^^).

I think we could know via cre.cpp if crengine has "selections" that it would draw highlighted.
But I remember it might also use its "selections" framework to draw search results.

Or may be we could have cre.cpp's clearSelection return a boolean whether doc->text_view had or not some selections before we issued doc->text_view->clearSelection().

**Comment by NiLuJe** [comment]
To be precise, I'm getting a `clearSelection` *before* showing a menu, which invalidates the cache, making the subsequent potential redraws when navigating (i.e., if the next tab is smaller than the previous) full instead of light.

**Comment by NiLuJe** [comment]
e.g., 

```
11/06/20-20:19:10 DEBUG input event => type: 3, code: 57(nil), value: 1, time: 1604690350.125260
11/06/20-20:19:10 DEBUG input event => type: 3, code: 48(nil), value: 1, time: 1604690350.125268
11/06/20-20:19:10 DEBUG input event => type: 3, code: 50(nil), value: 1, time: 1604690350.125270
11/06/20-20:19:10 DEBUG input event => type: 3, code: 53(nil), value: 63, time: 1604690350.125271
11/06/20-20:19:10 DEBUG input event => type: 3, code: 54(nil), value: 597, time: 1604690350.125273
11/06/20-20:19:10 DEBUG input event => type: 0, code: 2(nil), value: 0, time: 1604690350.125277
11/06/20-20:19:10 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1604690350.125279
11/06/20-20:19:10 DEBUG in tap state...
11/06/20-20:19:10 DEBUG set up hold timer
11/06/20-20:19:10 DEBUG adjusted ges: touch
11/06/20-20:19:10 DEBUG AutoSuspend: onInputEvent
11/06/20-20:19:10 DEBUG AutoSuspend: onInputEvent
11/06/20-20:19:10 DEBUG AutoTurn: onInputEvent
11/06/20-20:19:10 DEBUG input event => type: 3, code: 57(nil), value: 1, time: 1604690350.128420
11/06/20-20:19:10 DEBUG input event => type: 3, code: 48(nil), value: 0, time: 1604690350.128426
11/06/20-20:19:10 DEBUG input event => type: 3, code: 50(nil), value: 0, time: 1604690350.128427
11/06/20-20:19:10 DEBUG input event => type: 3, code: 53(nil), value: 63, time: 1604690350.128429
11/06/20-20:19:10 DEBUG input event => type: 3, code: 54(nil), value: 597, time: 1604690350.128431
11/06/20-20:19:10 DEBUG input event => type: 0, code: 2(nil), value: 0, time: 1604690350.128433
11/06/20-20:19:10 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1604690350.128434
11/06/20-20:19:10 DEBUG in tap state...
11/06/20-20:19:10 DEBUG set up single/double tap timer
11/06/20-20:19:10 DEBUG in single/double tap timer true
11/06/20-20:19:10 DEBUG single tap detected in slot 1 {
    ["x"] = 494,
    ["y"] = 63,
    ["w"] = 0,
    ["h"] = 0
}
11/06/20-20:19:10 DEBUG adjusted ges: tap
11/06/20-20:19:10 DEBUG AutoSuspend: onInputEvent
11/06/20-20:19:10 DEBUG AutoSuspend: onInputEvent
11/06/20-20:19:10 DEBUG AutoTurn: onInputEvent
11/06/20-20:19:10 DEBUG callCache: getLinkFromPosition cache miss: getLinkFromPositionh0|w0|x494|y63
11/06/20-20:19:10 DEBUG getLinkFromPosition link_xpointer: 
11/06/20-20:19:10 DEBUG getLinkFromPosition a_xpointer:
11/06/20-20:19:10 DEBUG callCache: getPageLinks cache hit: getPageLinksfalse
11/06/20-20:19:10 DEBUG callCache: clearSelection reseting buffer
11/06/20-20:19:10 DEBUG clear selection
11/06/20-20:19:10 DEBUG document has no pages at {
    ["page"] = 1,
    ["x"] = 494,
    ["y"] = 63,
    ["w"] = 0,
    ["h"] = 0
}
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.page.corner.bookmark.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.page.text.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.settings.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.tools.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.magnify.browse.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.cabinet.files.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/menu-icon.png 72 72
11/06/20-20:19:10 DEBUG ImageWidget: initial offsets 0 0
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.chevron.left.png
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.chevron.right.png
11/06/20-20:19:10 DEBUG ImageWidget: _render'ing resources/icons/appbar.chevron.up.png
11/06/20-20:19:10 DEBUG setDirty via a func from widget table: 0x357d43f0
# 11/06/20-20:19:10  INFO: invalid widget for setDirty() stack traceback:
        frontend/ui/uimanager.lua:700: in function 'post_guard'
        frontend/dbg.lua:45: in function 'setDirty'
        frontend/ui/widget/touchmenu.lua:689: in function 'updateItems'
        frontend/ui/widget/touchmenu.lua:721: in function 'switchMenuTab'
        frontend/ui/widget/touchmenu.lua:340: in function 'callback'
        frontend/ui/widget/touchmenu.lua:384: in function 'switchToTab'
        frontend/ui/widget/touchmenu.lua:559: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/apps/reader/modules/readermenu.lua:313: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
        frontend/apps/reader/modules/readermenu.lua:399: in function 'handler'
        frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
        frontend/ui/uimanager.lua:801: in function 'sendEvent'
        frontend/ui/uimanager.lua:195: in function '__default__'
        frontend/ui/uimanager.lua:1195: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1263: in function 'handleInput'
        frontend/ui/uimanager.lua:1307: in function 'run'
        ./reader.lua:300: in main chunk
        [C]: at 0x00014131
11/06/20-20:19:10 DEBUG show widget: table: 0x357d43f0
11/06/20-20:19:10 DEBUG setDirty nil from widget table: 0x357d43f0 w/ NO region 
11/06/20-20:19:10 DEBUG painting widget: table: 0x357dc490
11/06/20-20:19:10 DEBUG blitFrom 29 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 163 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 297 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 431 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 565 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 699 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 979 16 0 0 72 72
11/06/20-20:19:10 DEBUG blitFrom 50 640 0 0 81 81
11/06/20-20:19:10 DEBUG _refresh: Enqueued flashui update for region 0 0 1080 735 
# 11/06/20-20:19:10  triggering refresh {
    ["mode"] = "flashui",
    ["region"] = {
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1080,
        ["h"] = 735
    }
}
11/06/20-20:19:10 DEBUG refresh: ui-mode w/ flash 0 11 1080 735
11/06/20-20:19:10 DEBUG mxc_update: 1080x735 region @ (0, 11) with marker 21 (WFM: 257 & UPD: 1)
11/06/20-20:19:10 DEBUG refresh: wait for completion of marker 21
```

**Comment by NiLuJe** [comment]
I'm testing on a cover page w/ smooth scaling enabled, to make it exceedingly visible, because...

```
11/06/20-20:22:24 DEBUG painting widget: ReaderUI
# 11/06/20-20:22:24  readerview painting {
    ["x"] = 0,
    ["y"] = 0,
    ["w"] = 1080,
    ["h"] = 1429
} to 0 0
11/06/20-20:22:24 DEBUG callCache: drawCurrentViewByPage setting tag
11/06/20-20:22:24 DEBUG callCache: ########## drawCurrentView: full draw
CreDocument:drawCurrentView: Rendering took   504.692 ms
CreDocument:drawCurrentView: Blitting took      3.622 ms
```

 ;).

**Comment by poire-z** [comment]
It comes from (`logger.warn(debug.traceback())` is our friend):
```
11/06/20-20:31:01 DEBUG getLinkFromPosition a_xpointer:
11/06/20-20:31:01 WARN  stack traceback:
 frontend/apps/reader/modules/readerhighlight.lua:206: in function 'clear'
 frontend/apps/reader/modules/readerhighlight.lua:228: in function 'handler'
 frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
 frontend/ui/uimanager.lua:800: in function 'sendEvent'
 frontend/ui/uimanager.lua:49: in function '__default__'
 frontend/ui/uimanager.lua:1194: in function 'handleInputEvent'
 frontend/ui/uimanager.lua:1262: in function 'handleInput'
 frontend/ui/uimanager.lua:1306: in function 'run'
 ./reader.lua:300: in main chunk
 [C]: at 0x55a496be77a2
11/06/20-20:31:01 DEBUG clear selection
```
So:
```
function ReaderHighlight:onTap(_, ges)
    if not self:clear() and ges then
```
On any tap :)
Might benefit from some flag if redrawing can take that much time.

**Comment by poire-z** [comment]
> Might benefit from some flag if redrawing can take that much time.

I would think that may be that should be handled by cre.cpp clearSelection, which can know if there is actually some text selection to clear (if that knowledge happens to be accurate and right).
But as the cache is done in cre.cpp before/after calling the wrapped function no matter its result, that would need some ugly tweaking in the call cache stuff.
So, may be simpler to set that flag in the things that could do text selection (ReaderHighlight, ReaderSearch) and clear it in ReaderHighlight:clear() (as ReaderSearch clears them via self.ui.highlight:clear()).

**Comment by NiLuJe** [comment]
@poire-z:

This naive approach seems to do the trick just fine, does it make sense?

```diff
diff --git a/frontend/apps/reader/modules/readerhighlight.lua b/frontend/apps/reader/modules/readerhighlight.lua
index 03269f6f..2655964a 100644
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -192,6 +192,7 @@ function ReaderHighlight:getClearId()
 end
 
 function ReaderHighlight:clear(clear_id)
+    print("ReaderHighlight:clear", clear_id or "nil")
     if clear_id then -- should be provided by delayed call to clear()
         if clear_id ~= self.clear_id then
             -- if clear_id is no more valid, highlight has already been
@@ -224,7 +225,13 @@ function ReaderHighlight:onClearHighlight()
 end
 
 function ReaderHighlight:onTap(_, ges)
-    if not self:clear() and ges then
+    print("ReaderHighlight:onTap", self.hold_pos, ges)
+    -- We only actually need to clear if we have something to clear in the first place.
+    -- (We mainly want to avoid CRe's clearSelection, which may incur a redraw, c.f., #6854)
+    local cleared_nothing = self.hold_pos and not self:clear()
+    -- But we *do* want to be able to tap on existing highlights ;)
+    if cleared_nothing or ges then
+        print("Actual tap, checking if it was on a HL")
         if self.ui.document.info.has_pages then
             return self:onTapPageSavedHighlight(ges)
         else
@@ -643,6 +650,7 @@ function ReaderHighlight:onPanelZoom(arg, ges)
 end
 
 function ReaderHighlight:onHold(arg, ges)
+    print("ReaderHighlight:onHold")
     if self.document.info.has_pages and self.panel_zoom_enabled then
         return self:onPanelZoom(arg, ges)
     end
@@ -709,6 +717,7 @@ function ReaderHighlight:onHold(arg, ges)
 end
 
 function ReaderHighlight:onHoldPan(_, ges)
+    print("ReaderHighlight:onHoldPan")
     if self.hold_pos == nil then
         logger.dbg("no previous hold position")
         self:_resetHoldTimer(true)
@@ -1039,6 +1048,7 @@ function ReaderHighlight:onTranslateText(text)
 end
 
 function ReaderHighlight:onHoldRelease()
+    print("ReaderHighlight:onHoldRelease")
     local long_final_hold = false
     if self.hold_last_tv then
         local hold_duration = TimeVal.now() - self.hold_last_tv
diff --git a/frontend/document/credocument.lua b/frontend/document/credocument.lua
index dfe8110a..b8a4ea93 100644
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -1067,7 +1067,7 @@ function CreDocument:setupCallCache()
     local do_stats = G_reader_settings:isTrue("use_cre_call_cache_log_stats")
     -- Tune these when debugging
     local do_stats_include_not_cached = false
-    local do_log = false
+    local do_log = true
 
     -- Beware below for luacheck warnings "shadowing upvalue argument 'self'":
     -- the 'self' we got and use here, and the one we may get implicitely
@@ -1278,8 +1278,6 @@ function CreDocument:setupCallCache()
             -- These may have crengine do native highlight or unhighlight
             -- (we could keep the original buffer and use a scratch buffer while
             -- these are used, but not worth bothering)
-            -- The only real interest would be for clearSelection, which can trigger
-            -- without actual content change (e.g., toggling menus/footer).
             elseif name == "clearSelection" then add_buffer_trash = true
             elseif name == "highlightXPointer" then add_buffer_trash = true
             elseif name == "getWordFromPosition" then add_buffer_trash = true
```

**Comment by poire-z** [comment]
Well (a bit hard to guess why there was all that), this looks indeed fine as quick fix for your case.
So, if it works fine too with PDF, fine with me.

**Comment by NiLuJe** [comment]
At a quick glance, everything's fine in PDFs.

Do you want me to do this here or in another PR?

**Comment by poire-z** [comment]
Here, for such a small thingie.

**Comment by NiLuJe** [comment]
Minor tweaks to hopefully make the logic more obvious.

Also, fixed `deleteHighlight` to prevent it from polluting the sidecar data with empty arrays when the last HL of a page has been deleted.

Vaguely attempted to optimize the hashwalk of doom in `onTapXPointerSavedHighlight`, but I don't really have a silver bullet without resorting to shitty heuristics, especially in continuous mode...

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -1343,6 +1356,10 @@ function ReaderHighlight:deleteHighlight(page, i, bookmark_item)
     self.ui:handleEvent(Event:new("DelHighlight"))
     logger.dbg("delete highlight", page, i)
     local removed = table.remove(self.view.highlight.saved[page], i)
+    -- Clear the hash if there aren't any more highlights on this page
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua:1359]: Clear the "hash" ? Do you mean "table" ?

File: frontend/device/devicelistener.lua [hunk 2]
```diff
@@ -26,6 +26,10 @@ end
 function DeviceListener:onToggleNightMode()
     local night_mode = G_reader_settings:isTrue("night_mode")
     Screen:toggleNightMode()
+    -- Make sure CRe will bypass the call cache
+    if self.ui and self.ui.document and self.ui.document.provider == "crengine" then
```
Comment (poire-z) [inline frontend/device/devicelistener.lua:30]: (You could just check `if self.ui and self.ui.rolling then` - a bit cleaner but less explicite, so ok :)

**Review by poire-z — APPROVED** [review]

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/apps/reader/modules/readerhighlight.lua:1359]: Yeah, that was my vague 4AM wording attempt at making it clear the it's indexed by hash, despite those hashes being plain ints, to explain why the nested items are table.removed because *those* are pure arrays, but not the outer one ^^.

File: frontend/device/devicelistener.lua (hunk 2 above)
Comment (NiLuJe) [reply frontend/device/devicelistener.lua:30]: Good to knows, thanks ;).
