### PR TITLE
Status bars: fix showing additional content

### LINKED ISSUE #15206: Read Timer in "alt status bar" not handled as a separate item
### Before submitting

- [x] Reproduced the issue with external plugins and user-patches disabled.
- [x] Searched existing issues for similar reports.
- [ ] Tested on the latest nightly build ([more information](/koreader/koreader/issues/11068)).

### Device

Kindle

### KOReader version

KOReader 2026.03 "Snowflake"

### Model and firmware version

Kindle Paperwhite 12th Gen, v5.17.1.0.4

### Issue description

With some similarities to the following report: [https://github.com/koreader/koreader/issues/15100](https://github.com/koreader/koreader/issues/15100) the read timer currently has no separate "external content" item for the "alt status bar".
This leads to the behaviour that if the read timer has been configured to be displayed in the alt status bar (via the checkbox when setting up the read timer), but no other item is activated for the alt status bar, the status bar is not displayed at all.
Only if another item is selected to be displayed in the alt status bar, the read timer is also displayed alongside.

### Steps to reproduce

1. Deactivate all items in the alt status bar
2. setup and activate the read timer. select "display in alt status bar" during read timer setup
3. Alt status bar is not displayed and therefore no read timer is displayed

### PR DESCRIPTION
**Pull request by hius07**
1. Status bar: auto enable "External content" item when additional content appears.
Closes https://github.com/koreader/koreader/pull/14601#issuecomment-4124223537

2. Alt status bar: show additional content when other items are disabled (in the frontend until/if fixed in crengine).
Closes #15206

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/15218)

### CODE REVIEW

File: frontend/apps/reader/modules/readercoptlistener.lua [hunk 1]
```diff
@@ -194,7 +194,13 @@ function ReaderCoptListener:updatePageInfoOverride(pageno)
...
     end
 
-    self.document:setPageInfoOverride(page_info)
+    if not self.page_info_override and additional_content ~= "" then
+        -- force showing additional content when other overrided items are disabled
+        self.document._document:setIntProperty("window.status.pos.page.number", 1)
+    else
+        self.document._document:setIntProperty("window.status.pos.page.number", self.page_number)
+    end
+    self.document:setPageInfoOverride(additional_content .. page_info)
```
Comment (poire-z) [inline frontend/apps/reader/modules/readercoptlistener.lua:203]: Not really familiar with all that, but can't you just set it to self.page_number in all cases (rather than to a lying `1`) ?

(`overrided` is not english, it's either `overridden` or `overriding`)

Comment (hius07) [reply frontend/apps/reader/modules/readercoptlistener.lua:203]: Additional content is not displayed when all items are disabled, i. e. self.page_number is 0.
I believe this can be fixed in crengine but didn't want to disturb you.

Comment (hius07) [reply frontend/apps/reader/modules/readercoptlistener.lua:203]: Not elegant but rather simple in the frontend.

Comment (poire-z) [reply frontend/apps/reader/modules/readercoptlistener.lua:203]: Oh, ok, it's a boolean setting (and not the current page number :)). I wasn't very inspired when naming all these things :/
OK then.

And thanks :) no time to look at crengine, and I'll be off soon for 10 days.
Fine with me that this stays in frontend.
