### PR TITLE
AutoSuspend: Make sure we send a LeaveStandby event ASAP

### LINKED ISSUE #9157: AutoStandby doesn't get activated as expected
* KOReader version: 2022.05.1-14
* Device: Sage

#### Issue
Standby gets activated way too late

#### Steps to reproduce
Disable almost all plugins (except power saving), disable WiFi. Plug in the device and check the current with a USB-tester.

You will see the device enter the first standby as expected. But later standbys come too late.

#### Possible cause

@NiLuJe
https://github.com/koreader/koreader/blob/b26d3e981534377f9ff8f9bddddaac99a366e871/plugins/autosuspend.koplugin/main.lua#L604 seems to delay the `self.leave_standby_task` too long.

##### `crash.log` (if applicable)

Excerpt from crash.log
```
06/01/22-15:12:48 DEBUG AutoSuspend: onAllowStandby
06/01/22-15:12:48 DEBUG AutoSuspend: entering standby with a wakeup alarm in 13 s
06/01/22-15:13:01 DEBUG AutoSuspend: left standby after 12.786388 s   ----- OK
06/01/22-15:13:13 DEBUG AutoSuspend: onLeaveStandby                      ---- to late by 13s
06/01/22-15:13:13 DEBUG AutoSuspend: unschedule suspend/shutdown timer
06/01/22-15:13:13 DEBUG AutoSuspend: start suspend/shutdown timer at 17664.527280
06/01/22-15:13:13 DEBUG AutoSuspend: scheduling next suspend check in 900
06/01/22-15:13:13 DEBUG AutoSuspend: scheduling next shutdown check in 259200
06/01/22-15:13:13 DEBUG AutoSuspend: start standby timer at 17664.527280
06/01/22-15:13:13 DEBUG AutoSuspend: blown deadline, delaying standby
06/01/22-15:13:13 DEBUG AutoSuspend: scheduling next standby check in 4
06/01/22-15:13:13 DEBUG AutoSuspend: preventStandby
06/01/22-15:13:17 DEBUG AutoSuspend: allowStandby
06/01/22-15:13:17 DEBUG AutoSuspend: onAllowStandby
06/01/22-15:13:17 DEBUG AutoSuspend: entering standby with a wakeup alarm in 44 s
06/01/22-15:14:01 DEBUG AutoSuspend: left standby after 43.080423 s  ----- OK
06/01/22-15:14:45 DEBUG AutoSuspend: onLeaveStandby                     ---- to late by 45 seconds
06/01/22-15:14:45 DEBUG AutoSuspend: unschedule suspend/shutdown timer
06/01/22-15:14:45 DEBUG AutoSuspend: start suspend/shutdown timer at 17664.527280
06/01/22-15:14:45 DEBUG AutoSuspend: scheduling next suspend check in 900
06/01/22-15:14:45 DEBUG AutoSuspend: scheduling next shutdown check in 259200
06/01/22-15:14:45 DEBUG AutoSuspend: start standby timer at 17664.527280
06/01/22-15:14:45 DEBUG AutoSuspend: blown deadline, delaying standby
06/01/22-15:14:45 DEBUG AutoSuspend: scheduling next standby check in 4
06/01/22-15:14:45 DEBUG AutoSuspend: preventStandby
06/01/22-15:14:49 DEBUG AutoSuspend: allowStandby
06/01/22-15:14:49 DEBUG AutoSuspend: onAllowStandby
06/01/22-15:14:49 DEBUG AutoSuspend: entering standby with a wakeup alarm in 12 s
06/01/22-15:15:01 DEBUG AutoSuspend: left standby after 11.925828 s   ------ OK
06/01/22-15:15:13 DEBUG AutoSuspend: onLeaveStandby                      ------ to late by 13 secs
06/01/22-15:15:13 DEBUG AutoSuspend: unschedule suspend/shutdown timer
06/01/22-15:15:13 DEBUG AutoSuspend: start suspend/shutdown timer at 17664.527280
```   

[crash.log](https://github.com/koreader/koreader/files/8814976/crash.log)

### PR DESCRIPTION
**Pull request by NiLuJe**
Even in corner cases where we're woken up *without* user input (e.g., rtc alarm).

Fix #9157

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9173)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Slightly roundabout parameter passing, because we can't really return a value from an Event handler to its sender/broadcaster.

I mean, we... could build a list of return values in `UIManager:broadcastEvent` and pass it along so that `UIManager:_standbyTransition` can pass it along to `UIManager:handleInput`, but that'd be a lot of scaffolding for a single use-case that works almost as well via an internal UIManager variable and a public setter used in the Event handler ;).

**Comment by NiLuJe** [comment]
Magic happens because setting the input deadline to 0 leads to

https://github.com/koreader/koreader/blob/c825d50c8f07eb85a28da9cbf92019c78f2c8c9b/frontend/device/input.lua#L1077-L1083

taking the "select returns immediately" branch ;).

**Comment by NiLuJe** [comment]
FWIW, the conditions in #9157 lead to every wakeup being caused by the rtc alarm, which might be tricky to test.

My own dirty hack to test this was to use a device that cannot suspend while plugged in (i.e., < Mk. 7), and fudge the `canPowerSaveWhileCharging` to `true` to make the plugin try it anyway, because that makes it fails and return immediately without input events ;).

**Review by Frenzie — APPROVED** [review]

File: frontend/ui/uimanager.lua [hunk 1]
```diff
@@ -1841,6 +1847,12 @@ function UIManager:_standbyTransition()
     self._prev_prevent_standby_count = self._prevent_standby_count
 end
 
+-- Used by a PM transition event handler to request an early return from input polling (value in s).
+-- NOTE: We can't re-use setInputTimeout to avoid interactions with ZMQ...
```
Comment (poire-z) [inline frontend/ui/uimanager.lua:1851]: ZMQ ? What's that ? :)
I remember seeing ZeroMQ in bits of code - but thought this was disabled (unless I'm confusing it with TurboSomething...).
Anyway, never had to meet this thing :) What is it used for and why ? Couldn't we don't go with it ?
(Thanks for a little 3 sentences primer to keep me in the know :)

Comment (Frenzie) [reply frontend/ui/uimanager.lua:1851]: Zmq is about communicating between different processes. I think it's used in a (deprecated?) plugin for document sharing between KOReader instances.

**Comment by zwim** [comment]
Seems to work after a quick test.

**Comment by NiLuJe** [comment]
Same comment as in #9124 for PB people re: #8638, the extra debugging facilities to trace that issue are now in https://github.com/koreader/koreader/pull/9173/commits/696db98323133f04d3d141d8e8e5cfe7c0456189 ;).
