### PR TITLE
android: minor fixes

### LINKED ISSUE #7724: Android update current reading position lost
* KOReader version: 2021.5–24
* Device: Android Tolino

#### Issue
When you read a book. If you update the Android app KOReader reinstalls itself. If you open the book again you are at an old reading positon.

#### Steps
Open koreader in FM. Open book. Read two pages. Update from the menu.
Reinstall ...
Open koreader in FM. Open book. You are on the old readig Position.

### PR DESCRIPTION
**Pull request by pazos**
* save settings before installing a new APK & after resume (fixes #7724)
* move Resume/Suspend events to Resume/Pause callbacks (might help with https://www.mobileread.com/forums/showthread.php?t=339597)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7753)

### CODE REVIEW

File: frontend/device/android/device.lua [hunk 1]
```diff
@@ -133,9 +133,10 @@ function Device:init()
         event_map = require("device/android/event_map"),
         handleMiscEv = function(this, ev)
             local UIManager = require("ui/uimanager")
+            local Event = require("ui/event")
```
Comment (Frenzie) [inline frontend/device/android/device.lua:136]: Does it need to come after UIManager?

File: frontend/device/android/device.lua [hunk 2]
```diff
@@ -486,10 +481,12 @@ end
 function Device:install()
     local UIManager = require("ui/uimanager")
     local ConfirmBox = require("ui/widget/confirmbox")
+    local Event = require("ui/event")
```
Comment (Frenzie) [inline frontend/device/android/device.lua:484]: Definitely doesn't need to come after ConfirmBox. ;-)

Comment (pazos) [reply frontend/device/android/device.lua:484]: https://github.com/koreader/koreader-base/wiki/Coding-style#order-of-requires

from top modules to specific modules  (following the alphabet whenever possible)

```lua
local Event = require("ui/event")
local UIManager = require("ui/uimanager")
local ConfirmBox = require("ui/widget/confirmbox")
```
strictly alphabetical

```lua
local ConfirmBox = require("ui/widget/confirmbox")
local Event = require("ui/event")
local UIManager = require("ui/uimanager")

```

Comment (pazos) [reply frontend/device/android/device.lua:484]: choose your own adventure :smile:

Comment (Frenzie) [reply frontend/device/android/device.lua:484]: Our style guide specifies alphabetical. ;-)

https://github.com/koreader/koreader-base/wiki/Coding-style

Comment (pazos) [reply frontend/device/android/device.lua:484]: Then I'm afraid I didn't understand your comment

> Definitely doesn't need to come after ConfirmBox. ;-)

Comment (Frenzie) [reply frontend/device/android/device.lua:483]: I thought you might've had a reason (e.g., ConfirmBox uses UIManager so the order might matter), which doesn't apply to Event. But apparently you simply added it at the bottom with no rationale. ^_^

**Review by Frenzie — APPROVED** [review]
