### PR TITLE
PluginLoader: call stop method on plugin when disabling

### LINKED ISSUE #14316: Disable option doesn't work for Syncthing plugin
Upstream link https://github.com/jasonchoimtt/koreader-syncthing/issues/18

Especially @kodermike 's comment
>  this is unsolvable without a change in koreader plugin management...The real problem is that the koreader plugin manager doesn't send stop signals, it just adds the marked plugin to the dictionary of plugins not to show as enabled.

### PR DESCRIPTION
**Pull request by Frenzie**
Closes #14316.

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/14318)

### CODE REVIEW

File: frontend/pluginloader.lua [hunk 1]
```diff
@@ -261,6 +265,23 @@ function PluginLoader:createPluginInstance(plugin, attr)
...
+    local instance = self.loaded_plugins and self.loaded_plugins[name]
+    if not instance then return false, "not loaded" end
+
+    local ok, err = false, "no stop method"
+    local fn = instance.stop
+    if type(fn) == "function" then
+        ok, err = pcall(fn, instance)
+    end
+
+    self.loaded_plugins[name] = nil
```
Comment (Frenzie) [inline frontend/pluginloader.lua]: I'm not too sure about this line but the alternative of potentially calling .stop() multiple times if the user does weird things on purpose also seems a bit odd.

File: frontend/pluginloader.lua [hunk 2]
```diff
@@ -261,6 +265,23 @@ function PluginLoader:createPluginInstance(plugin, attr)
...
 end
 
+--- Tries to stop and unload a specific plugin instance if it's currently running.
+function PluginLoader:stopPluginInstance(name)
+    if not name then return false, "no plugin name provided" end
+    local instance = self.loaded_plugins and self.loaded_plugins[name]
+    if not instance then return false, "not loaded" end
+
+    local ok, err = false, "no stop method"
+    local fn = instance.stop
```
Comment (Frenzie) [inline frontend/pluginloader.lua]: Maybe not the best name?

Comment (hius07) [reply frontend/pluginloader.lua]: They do it with a check:
https://github.com/koreader/koreader/blob/7e63f91c8e74af64089cefa187a17d664e261b35/plugins/SSH.koplugin/main.lua#L125-L126
https://github.com/koreader/koreader/blob/7e63f91c8e74af64089cefa187a17d664e261b35/plugins/httpinspector.koplugin/main.lua#L41-L42

Comment (Frenzie) [reply frontend/pluginloader.lua]: Yes, so maybe something like `stopPlugin`.

File: frontend/pluginloader.lua (hunk 1 above)
Comment (kodermike) [reply frontend/pluginloader.lua]: Shouldn't this at least be wrapped in an `if ok`? Otherwise won't it set it as not loaded even if the process isn't stopped for some reason?

[edit] realize this probably doesn't matter since there's no retry if stop fails

File: frontend/pluginloader.lua [hunk 3]
```diff
@@ -237,6 +237,10 @@ function PluginLoader:genPluginManagerSubItem()
                     plugins_disabled[plugin.name] = nil
                 else
                     plugins_disabled[plugin.name] = true
```
Comment (kodermike) [inline frontend/pluginloader.lua:284]: Should this line (239) be moved to an else condition if stop returns ok? Probably could place the loaded_plugin = nil here too, but meh, I'm just an observer :)

**Comment by kodermike** [comment]
@Frenzie What's the best way to test this? I don't think my lua skills are as up to the task as I'd hoped - I was looking at the SSH plugin if that matters (same issue - binary keeps running; really, relevant to any plugin that executes an external binary I suppose). I guess my question is really, where does `stopPlugin` live? I'd thought it might be a suggested new function to add to the plugin, but that doesn't seem to be it, and the only references I see to it in your fork are from this pr. Thanks!

File: frontend/pluginloader.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/pluginloader.lua]: I'll just remove it.

**Comment by Frenzie** [comment]
Yes, it calls stopPlugin if it's a function.

File: frontend/pluginloader.lua (hunk 3 above)
Comment (Frenzie) [reply frontend/pluginloader.lua:284]: Presently the problem is that a couple of plugins may have parts that could survive program restart, but if that's gated it means they might also survive a device restart.

I think something like this should work out better (see <https://github.com/koreader/koreader/pull/14318/commits/55e3d841fb4c39e45155765de39040e11674c439>):
```lua
                    if stop_ok then
                        UIManager:askForRestart()
                    else
                        UIManager:askForReboot(T(_("Plugin '%1' failed to stop. The device needs to be rebooted to disable it fully."), plugin.fullname or plugin.name))
                    end
```

File: frontend/pluginloader.lua [hunk 4]
```diff
@@ -231,17 +231,28 @@ function PluginLoader:genPluginManagerSubItem()
...
+                    end
                 end
                 G_reader_settings:saveSetting("plugins_disabled", plugins_disabled)
                 if self.show_info then
                     self.show_info = false
-                    UIManager:askForRestart()
+                    if stop_ok then
+                        UIManager:askForRestart()
+                    else
+                        UIManager:askForReboot(T(_("Plugin '%1' failed to stop. The device needs to be rebooted to disable it fully."), plugin.fullname or plugin.name))
```
Comment (Frenzie) [inline frontend/pluginloader.lua]: @kodermike I'm not sure if this is a good idea though. Maybe the plugin in question should just do a kill -9 after a waiting a short bit?

File: frontend/pluginloader.lua (hunk 3 above)
Comment (Frenzie) [reply frontend/pluginloader.lua:284]: I rewrote it as regular stop request (presumed `SIGTERM`) followed by force stop (presumed `SIGKILL`). That doesn't cover the possibility of things like zombie processes, but even if that should occur for some reason such a scenario doesn't sound harmful. After all, that's nothing but one tiny entry in the process table without any other resource usage.

Comment (kodermike) [reply frontend/pluginloader.lua:284]: > Presently the problem is that a couple of plugins may have parts that could survive program restart, but if that's gated it means they might also survive a device restart.
> 
> I think something like this should work out better (see [55e3d84](https://github.com/koreader/koreader/commit/55e3d841fb4c39e45155765de39040e11674c439))

Gotcha. I'll need to rework my plugin (not your problem) I think, or at least be more self aware of the response, but that restart vs reboot makes sense.

File: plugins/SSH.koplugin/main.lua [hunk 5]
```diff
@@ -99,15 +99,46 @@ function SSH:isRunning()
...
-    os.execute("cat /tmp/dropbear_koreader.pid | xargs kill")
-    UIManager:show(InfoMessage:new {
-        text = T(_("SSH server stopped.")),
-        timeout = 2,
-    })
+--- Stops the Dropbear process started by this plugin.
+--- @param force boolean If true, forces the process to stop if it doesn't exit gracefully.
+--- @return boolean Success, string|nil Error
+function SSH:stopPlugin(force)
+    if not self:isRunning() then
```
Comment (kodermike) [inline plugins/SSH.koplugin/main.lua:106]: I don't think this check is infallible. Stop currently removes the pid file, so isrunning returns false. My original lame approach to this originally was to check via ps and just ignore the pid file, otherwise you end up with this scenario:

```
[root@kobo ~]# more /tmp/dropbear_koreader.pid
more: /tmp/dropbear_koreader.pid: No such file or directory
[root@kobo ~]# ps -ef|grep drop
  973 root      0:00 /usr/bin/dropbear -P /usr/local/niluje/usbnet/run/sshd.pid -K 15 -n
 2933 root      0:00 ./dropbear -E -R -p2222 -P /tmp/dropbear_koreader.pid -n -2 8
 2958 root      0:00 grep drop
[root@kobo ~]#
```

A connected ssh session isn't removed even though the parent pid has been killed 

(fun party trick, you stay ssh'd even if you exit koreader and relaunch kobo at this stage)

Comment (Frenzie) [reply plugins/SSH.koplugin/main.lua:106]: > Stop currently removes the pid file

Emphasis on currently. ;-)

In this PR it now says:
```lua
    if not isProcAlive(pid) then
        os.remove(pid_path)
        return true
    end
```

Comment (Frenzie) [reply plugins/SSH.koplugin/main.lua:106]: > A connected ssh session isn't removed even though the parent pid has been killed

I replied too quickly, but this is normally considered a feature. They'll be gone once they disconnect. If we should want to change how this is handled I'm not quite convinced that's a matter for this PR.

Comment (kodermike) [reply plugins/SSH.koplugin/main.lua:106]: Poked around on this end at SSH.koplugin and dropbear, not seeing a clean way to kill the children of the proc without ps tomfoolery (which understandably is not ideal; or without patching dropbear further, which doesn't seem worth it). Just being paranoid, back to the hobbit hole I go

Comment (Frenzie) [reply plugins/SSH.koplugin/main.lua:106]: Did you try a simple `pkill -P $pid` already?

Comment (kodermike) [reply plugins/SSH.koplugin/main.lua:106]:
```
@@ -124,7 +124,7 @@ function SSH:stopPlugin(force)
     end

     local function send(sig, p)
-        return os.execute(string.format("kill -%s %d", sig, p)) == 0
+        return os.execute(string.format("pkill -%s -P %d && kill -%s %d", sig, p, sig, p)) == 0
     end

     send("TERM", pid)
```
 Have to kill the children and the parent separately. (tested)

File: frontend/pluginloader.lua [hunk 6]
```diff
@@ -276,13 +276,24 @@ function PluginLoader:genPluginManagerSubItem()
...
                 local UIManager = require("ui/uimanager")
-                local _ = require("gettext")
                 local plugins_disabled = G_reader_settings:readSetting("plugins_disabled") or {}
                 plugin.enable = not plugin.enable
                 if plugin.enable then
                     plugins_disabled[plugin.name] = nil
                 else
                     plugins_disabled[plugin.name] = true
+                    local instance = self:getPluginInstance(plugin.name)
+                    local stopPluginFn = instance and instance.stopPlugin
```
Comment (kodermike) [inline frontend/pluginloader.lua:286]: random question as I work through similar logic in airplanemode - should there be a check for isRunning framing the stop? (if that's a dumb question, ignore me :) )

Comment (Frenzie) [reply frontend/pluginloader.lua:286]: I'm inclined to think that such a thing is up to the plugin. Otherwise the logic here is more complex and the plugin would be forced to implement an isRunning function when maybe it's just cleaning up some temp files where it doesn't matter if any actually exist or not.

Comment (kodermike) [reply frontend/pluginloader.lua:286]: Thanks for enduring my random questions :) Appreciate it!
