### PR TITLE
A bunch of tweaks & fixes

### LINKED ISSUE #8031: Read timer goes negative when timer ends while device is sleeping
* KOReader version: v2021.07
* Device: Kobo Glo HD (kobo_alyssum)

#### Issue

image

#### Steps to reproduce

1. Set read timer for 30 minutes
2. Put device to sleep
3. Turn device back on after 2 hours (or any time greater than 30 minutes)
4. Open plugins menu
5. Note that read timer is negative

~If I leave it in the "negative state", sometimes device will display "Read timer alarm" notification about a minute after I bring it out of the standby, but other times it will just stay negative until I manually clear it.~

EDIT: If you wait 10-20 seconds, "Read timer alarm" notification will popup. But if you want to set the timer before that, you will be greeted with above picture.

Presumably, timer should clear itself if I turn the device and timer is overdue?

### LINKED ISSUE #8097: [kobo] Race condition in suspend with sleepcover
* KOReader version: 2021.07-47
* Device: Kobo H2o

config:
- [ ] ignore all sleep cover event
- [x] ignore sleep cover wake-up event

#### Issue

Race condition with suspend logic when suspending from power button then closing the sleep cover. 

When the sleep cover is close, suspend task is rescheduled but the suspend task has already started. The reschedule function don’t check that unscheduled fail and a new suspend task is created and is execute immediately after wake-up.

#### Possible fix 

Check the return of unschedule function before schedule a new suspend
This may be better in kobo/device.lua instead of generic/device.lua?

<details>
  <summary>patch.diff</summary>

``` diff
diff --git a/frontend/device/generic/device.lua b/frontend/device/generic/device.lua
index d316bad0..a5a0dc47 100644
--- a/frontend/device/generic/device.lua
+++ b/frontend/device/generic/device.lua
@@ -234,8 +234,9 @@ end
 
 function Device:rescheduleSuspend()
     local UIManager = require("ui/uimanager")
-    UIManager:unschedule(self.suspend)
-    UIManager:scheduleIn(self.suspend_wait_timeout, self.suspend)
+    if UIManager:unschedule(self.suspend) then
+        UIManager:scheduleIn(self.suspend_wait_timeout, self.suspend)
+    end
 end
 
 -- Only used on platforms where we handle suspend ourselves.
```
</details>

#### crash.log
<details>
  <summary>crash.log</summary>

```
08/17/21-03:43:53 DEBUG key event => code: 116 (Power), value: 1, time: 1629164633.847024
08/17/21-03:43:53 DEBUG AutoSuspend: onInputEvent
08/17/21-03:43:54 DEBUG key event => code: 116 (Power), value: 0, time: 1629164634.017029
08/17/21-03:43:54 DEBUG AutoSuspend: onInputEvent
08/17/21-03:43:54 DEBUG Rename  /mnt/onboard/testbook.sdr/metadata.epub.lua  to  /mnt/onboard/testbook.sdr/metadata.epub.lua.old
08/17/21-03:43:54 DEBUG Write to  /mnt/onboard/testbook.sdr/metadata.epub.lua
08/17/21-03:43:54 DEBUG UIManager: unschedule task not found (  function: 0x2dd226d8  )
08/17/21-03:43:54 DEBUG ReaderFooter.autoRefreshFooter unscheduled
08/17/21-03:43:54 DEBUG UIManager: unschedule task not found (  function: 0x2b949ad0  )
08/17/21-03:43:54 DEBUG UIManager: unschedule task not found (  function: 0x2b949e00  )
08/17/21-03:43:54 DEBUG UIManager: unschedule task not found (  function: 0x2b72d1d0  )
08/17/21-03:43:54 DEBUG ReaderCoptListener.headerRefresh unscheduled
08/17/21-03:43:54 DEBUG AutoSuspend: onSuspend
08/17/21-03:43:54 DEBUG AutoSuspend: unschedule
08/17/21-03:43:54 INFO  WakeupMgr: scheduling wakeup in 259200
08/17/21-03:43:54 DEBUG BackgroundRunnerWidget:onSuspend() @  1629164634
08/17/21-03:43:54 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:43:54 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:43:54  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2245: in function 'maybeUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2253: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/device/kobo/powerd.lua:391: in function 'beforeSuspend'
	frontend/device/generic/device.lua:281: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:131: in function 'Suspend'
	frontend/ui/uimanager.lua:1754: in function 'suspend'
	frontend/ui/uimanager.lua:153: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:43:54 DEBUG Suspending...
08/17/21-03:43:54 DEBUG Sleep cover is open
08/17/21-03:43:54 DEBUG refresh: full
08/17/21-03:43:54 DEBUG refresh: wait for completion of (previous) marker 4
08/17/21-03:43:54 DEBUG mxc_update: 1080x1440 region @ (0, 0) with marker 5 (WFM: 2 & UPD: 1)
08/17/21-03:43:54 DEBUG refresh: wait for completion of marker 5
08/17/21-03:43:55 DEBUG setDirty via a func from widget table: 0x2dbc6608
# 08/17/21-03:43:55  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/ui/widget/screensaverwidget.lua:55: in function 'update'
	frontend/ui/widget/screensaverwidget.lua:31: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/screensaver.lua:672: in function 'show'
	frontend/device/generic/device.lua:315: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:131: in function 'Suspend'
	frontend/ui/uimanager.lua:1754: in function 'suspend'
	frontend/ui/uimanager.lua:153: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:43:55 DEBUG show widget: table: 0x2dbc6608
08/17/21-03:43:55 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:43:55 DEBUG setDirty full from widget table: 0x2dbc6608 w/ NO region AND w/ HW dithering
08/17/21-03:43:55 DEBUG setDirty via a func from widget table: 0x2dbc6608
08/17/21-03:43:55 DEBUG not painting 1 covered widget(s)
08/17/21-03:43:55 DEBUG painting widget: table: 0x2d85b048
08/17/21-03:43:55 DEBUG ImageWidget: _render'ing /mnt/onboard/.adds/images/screensaver.png 1080 1429
08/17/21-03:43:55 DEBUG renderImageData: using MuPDF
08/17/21-03:43:56 DEBUG Mupdf.renderImage true cdata<struct BlitBufferRGB24>: 0x2bbc58d8
08/17/21-03:43:56 DEBUG ImageWidget: initial offsets 0 0
08/17/21-03:43:56 DEBUG blitFrom 0 0 0 0 1080 1429
08/17/21-03:43:56 DEBUG _repaint: it was dithered, infecting the refresh queue
08/17/21-03:43:56 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:43:56 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:43:56 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
# 08/17/21-03:43:56  triggering refresh {
    ["mode"] = "full",
    ["region"] = {
        ["h"] = 1429,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1080,
    },
}
08/17/21-03:43:56 DEBUG refresh: full 0 11 1080 1429
08/17/21-03:43:56 DEBUG mxc_update: 1080x1429 region @ (0, 11) with marker 6 (WFM: 2 & UPD: 1)
08/17/21-03:43:56 DEBUG refresh: wait for completion of marker 6
08/17/21-03:43:56 DEBUG key event => code: 59 (SleepCover), value: 1, time: 1629164635.455544
08/17/21-03:43:56 DEBUG AutoSuspend: onInputEvent
08/17/21-03:43:57 DEBUG Write to  /mnt/onboard/testbook.sdr/metadata.epub.lua
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2dd226d8  )
08/17/21-03:43:57 DEBUG ReaderFooter.autoRefreshFooter unscheduled
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2b949ad0  )
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2b949e00  )
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2b72d1d0  )
08/17/21-03:43:57 DEBUG ReaderCoptListener.headerRefresh unscheduled
08/17/21-03:43:57 DEBUG AutoSuspend: onSuspend
08/17/21-03:43:57 DEBUG AutoSuspend: unschedule
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2dc37960  )
08/17/21-03:43:57 INFO  WakeupMgr: scheduling wakeup in 259200
08/17/21-03:43:57 DEBUG BackgroundRunnerWidget:onSuspend() @  1629164637
08/17/21-03:43:57 DEBUG Already in screen saver mode, suspending...
08/17/21-03:43:57 DEBUG UIManager: unschedule task not found (  function: 0x2aecce80  )
08/17/21-03:43:57 DEBUG not painting 1 covered widget(s)
08/17/21-03:43:57 DEBUG not painting 1 covered widget(s)
08/17/21-03:44:12 INFO  Kobo suspend: going to sleep . . .
08/17/21-03:44:12 DEBUG UIManager: unschedule task not found (  function: 0x2aeccdf8  )
08/17/21-03:44:12 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
08/17/21-03:44:14 INFO  Kobo suspend: waited for 2s because of reasons...
08/17/21-03:44:14 INFO  Kobo suspend: synced FS
08/17/21-03:44:14 INFO  Kobo suspend: asking for a suspend to RAM . . .
08/17/21-03:44:14 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
08/17/21-03:45:24 INFO  Kobo suspend: woke up!
08/17/21-03:45:24 DEBUG Kobo suspend: scheduling unexpected wakeup guard
08/17/21-03:45:24 INFO  Kobo suspend: going to sleep . . .
08/17/21-03:45:24 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
08/17/21-03:45:26 INFO  Kobo suspend: waited for 2s because of reasons...
08/17/21-03:45:26 INFO  Kobo suspend: synced FS
08/17/21-03:45:26 INFO  Kobo suspend: asking for a suspend to RAM . . .
08/17/21-03:45:26 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
08/17/21-03:45:28 INFO  Kobo suspend: woke up!
08/17/21-03:45:28 DEBUG Kobo suspend: scheduling unexpected wakeup guard
08/17/21-03:45:28 DEBUG not painting 1 covered widget(s)
08/17/21-03:45:28 DEBUG not painting 1 covered widget(s)
08/17/21-03:45:28 DEBUG key event => code: 59 (SleepCover), value: 0, time: 1629164654.778798
08/17/21-03:45:28 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1629164655.164396
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 1, time: 1629164725.457958
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 0, time: 1629164725.667946
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 1, time: 1629164726.507935
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 0, time: 1629164726.670636
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 1, time: 1629164726.977902
08/17/21-03:45:28 DEBUG key event => code: 116 (Power), value: 0, time: 1629164727.077885
08/17/21-03:45:28 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1629164727.345264
08/17/21-03:45:28 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:28 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:28 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:28 DEBUG Resuming...
08/17/21-03:45:28 DEBUG UIManager: unschedule task not found (  function: 0x2aecce80  )
08/17/21-03:45:28 INFO  Kobo resume: clean up after wakeup
08/17/21-03:45:28 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
08/17/21-03:45:28 DEBUG close screensaver
08/17/21-03:45:28 DEBUG close widget: table: 0x2dbc6608
08/17/21-03:45:28 DEBUG setDirty via a func from widget nil
08/17/21-03:45:28 DEBUG Lower widget ReaderUI covers the full screen
08/17/21-03:45:28 DEBUG setDirty nil from widget ReaderUI w/ NO region 
08/17/21-03:45:28 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:45:28 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:45:28  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2245: in function 'maybeUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2253: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/device/kobo/powerd.lua:408: in function 'afterResume'
	frontend/device/generic/device.lua:270: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:134: in function 'Resume'
	frontend/ui/uimanager.lua:1769: in function 'resume'
	frontend/ui/uimanager.lua:151: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:29 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:45:29 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:45:29  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2218: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1167: in function 'broadcastEvent'
	frontend/ui/uimanager.lua:1728: in function '_afterResume'
	frontend/ui/uimanager.lua:135: in function 'Resume'
	frontend/ui/uimanager.lua:1769: in function 'resume'
	frontend/ui/uimanager.lua:151: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2dd226d8  )
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2b72d1d0  )
08/17/21-03:45:29 DEBUG AutoSuspend: onResume
08/17/21-03:45:29 DEBUG AutoSuspend: unschedule
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2dc37960  )
08/17/21-03:45:29 DEBUG AutoSuspend: start at 5819.1343
08/17/21-03:45:29 DEBUG AutoSuspend: scheduling next suspend check in 600
08/17/21-03:45:29 DEBUG AutoSuspend: scheduling next shutdown check in 259200
08/17/21-03:45:29 DEBUG BackgroundRunnerWidget:onResume() @  1629164729
08/17/21-03:45:29 DEBUG BackgroundRunnerWidget: no job, not running @  1629164729
08/17/21-03:45:29 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:29 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:29 DEBUG Rename  /mnt/onboard/testbook.sdr/metadata.epub.lua  to  /mnt/onboard/testbook.sdr/metadata.epub.lua.old
08/17/21-03:45:29 DEBUG Write to  /mnt/onboard/testbook.sdr/metadata.epub.lua
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2dd226d8  )
08/17/21-03:45:29 DEBUG ReaderFooter.autoRefreshFooter unscheduled
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2b949ad0  )
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2b949e00  )
08/17/21-03:45:29 DEBUG UIManager: unschedule task not found (  function: 0x2b72d1d0  )
08/17/21-03:45:29 DEBUG ReaderCoptListener.headerRefresh unscheduled
08/17/21-03:45:29 DEBUG AutoSuspend: onSuspend
08/17/21-03:45:29 DEBUG AutoSuspend: unschedule
08/17/21-03:45:29 INFO  WakeupMgr: scheduling wakeup in 259200
08/17/21-03:45:29 DEBUG BackgroundRunnerWidget:onSuspend() @  1629164729
08/17/21-03:45:29 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:45:29 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:45:29  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2245: in function 'maybeUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2253: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/device/kobo/powerd.lua:391: in function 'beforeSuspend'
	frontend/device/generic/device.lua:281: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:131: in function 'Suspend'
	frontend/ui/uimanager.lua:1754: in function 'suspend'
	frontend/ui/uimanager.lua:153: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:29 DEBUG Suspending...
08/17/21-03:45:29 DEBUG Sleep cover is open
08/17/21-03:45:29 DEBUG refresh: full
08/17/21-03:45:29 DEBUG mxc_update: 1080x1440 region @ (0, 0) with marker 7 (WFM: 2 & UPD: 1)
08/17/21-03:45:29 DEBUG refresh: wait for completion of marker 7
08/17/21-03:45:30 DEBUG setDirty via a func from widget table: 0x2dade088
# 08/17/21-03:45:30  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/ui/widget/screensaverwidget.lua:55: in function 'update'
	frontend/ui/widget/screensaverwidget.lua:31: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/screensaver.lua:672: in function 'show'
	frontend/device/generic/device.lua:315: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:131: in function 'Suspend'
	frontend/ui/uimanager.lua:1754: in function 'suspend'
	frontend/ui/uimanager.lua:153: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:30 DEBUG show widget: table: 0x2dade088
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG setDirty full from widget table: 0x2dade088 w/ NO region AND w/ HW dithering
08/17/21-03:45:30 DEBUG setDirty via a func from widget table: 0x2dade088
08/17/21-03:45:30 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:30 DEBUG AutoSuspend: onInputEvent
08/17/21-03:45:30 DEBUG Resuming...
08/17/21-03:45:30 DEBUG UIManager: unschedule task not found (  function: 0x2aecce80  )
08/17/21-03:45:30 INFO  Kobo resume: clean up after wakeup
08/17/21-03:45:30 DEBUG UIManager: unschedule task not found (  function: 0x2aeccdf8  )
08/17/21-03:45:30 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
08/17/21-03:45:30 DEBUG close screensaver
08/17/21-03:45:30 DEBUG close widget: table: 0x2dade088
08/17/21-03:45:30 DEBUG setDirty via a func from widget nil
08/17/21-03:45:30 DEBUG Lower widget ReaderUI covers the full screen
08/17/21-03:45:30 DEBUG setDirty nil from widget ReaderUI w/ NO region 
08/17/21-03:45:30 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:45:30 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:45:30  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2245: in function 'maybeUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2253: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/device/kobo/powerd.lua:408: in function 'afterResume'
	frontend/device/generic/device.lua:270: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:134: in function 'Resume'
	frontend/ui/uimanager.lua:1769: in function 'resume'
	frontend/ui/uimanager.lua:151: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:30 DEBUG Explicit widgetRepaint: table: 0x2b8ce1e0 @ ( 0 , 0 )
08/17/21-03:45:30 DEBUG setDirty via a func from widget table: 0x2b8ce1e0
# 08/17/21-03:45:30  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:873: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	frontend/apps/reader/modules/readerfooter.lua:2000: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:1897: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:1881: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2218: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1167: in function 'broadcastEvent'
	frontend/ui/uimanager.lua:1728: in function '_afterResume'
	frontend/ui/uimanager.lua:135: in function 'Resume'
	frontend/ui/uimanager.lua:1769: in function 'resume'
	frontend/ui/uimanager.lua:151: in function 'handler'
	frontend/ui/uimanager.lua:1572: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1654: in function 'handleInput'
	frontend/ui/uimanager.lua:1701: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014119
08/17/21-03:45:30 DEBUG UIManager: unschedule task not found (  function: 0x2dd226d8  )
08/17/21-03:45:30 DEBUG UIManager: unschedule task not found (  function: 0x2b72d1d0  )
08/17/21-03:45:30 DEBUG AutoSuspend: onResume
08/17/21-03:45:30 DEBUG AutoSuspend: unschedule
08/17/21-03:45:30 DEBUG UIManager: unschedule task not found (  function: 0x2dc37960  )
08/17/21-03:45:30 DEBUG AutoSuspend: start at 5819.1343
08/17/21-03:45:30 DEBUG AutoSuspend: scheduling next suspend check in 600
08/17/21-03:45:30 DEBUG AutoSuspend: scheduling next shutdown check in 259200
08/17/21-03:45:30 DEBUG BackgroundRunnerWidget:onResume() @  1629164730
08/17/21-03:45:30 DEBUG BackgroundRunnerWidget: no job, not running @  1629164730
08/17/21-03:45:30 DEBUG painting widget: ReaderUI
# 08/17/21-03:45:30  readerview painting {
    ["h"] = 1429,
    ["x"] = 0,
    ["y"] = 0,
    ["w"] = 1080,
} to 0 0
08/17/21-03:45:30 DEBUG CreDocument: goto page 1164 flow 0
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG _refresh: Enqueued full update for region 0 0 1080 1429 w/ HW dithering
08/17/21-03:45:30 DEBUG update_dither: Update dither hint false to true
# 08/17/21-03:45:30  triggering refresh {
    ["mode"] = "full",
    ["region"] = {
        ["h"] = 1429,
        ["x"] = 0,
        ["y"] = 0,
        ["w"] = 1080,
    },
}
08/17/21-03:45:30 DEBUG refresh: full 0 11 1080 1429
08/17/21-03:45:30 DEBUG mxc_update: 1080x1429 region @ (0, 11) with marker 8 (WFM: 2 & UPD: 1)
08/17/21-03:45:30 DEBUG refresh: wait for completion of marker 8
```
</details>

### LINKED ISSUE #8101: Hidden Folders 2021.07
* KOReader version:2021.07
* Device:Kobo Forma

#### Issue
After enabling shoq hidden files, /mnt/onboard/.Kobo folder is not showing. I have installed an older version 202011000000 of KOReader and it is working.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
* Bump DocumentCache hard cap to 512MB as discussed... somewhere :s.
* Fix #8101
* Fix #8097
* Fix #8031

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8106)

### CODE REVIEW

File: defaults.lua [hunk 1]
```diff
@@ -33,7 +33,7 @@ DGLOBAL_CACHE_SIZE_MINIMUM = 1024*1024*16
 DGLOBAL_CACHE_FREE_PROPORTION = 0.4
 
 -- maximum cache size
-DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*64
+DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*512
```
Comment (Frenzie) [inline defaults.lua:36]: Actually I said 1024, since it's either 0.4 of total or the other max. But 512 should be fine as a general default.

Comment (NiLuJe) [reply defaults.lua:36]: Yeah, that was half being very conservative, half having a hard time seeing where we could actually use > 512MB of cache ;p.

Comment (NiLuJe) [reply defaults.lua:36]: Sidebar: It seems like CircleCI is having yet another sad right now...

Comment (Frenzie) [reply defaults.lua:36]: > half having a hard time seeing where we could actually use > 512MB of cache ;p.

My old old phone has 4 GB RAM, my new phone has 8 GB RAM, my PC has 32 GB RAM, …

Comment (NiLuJe) [reply defaults.lua:36]: My bad, I meant "what for", not where as in platforms ;).

Comment (Frenzie) [reply defaults.lua:36]: But sure, on my H2O the 0.4 will limit it to 200 or so (unless I happen to have adjusted that, but iirc I only changed the DGLOBAL_CACHE_SIZE_MAXIMUM to something like 200 or 256).

Comment (NiLuJe) [reply defaults.lua:36]: FWIW, on the H2O:

```
08/19/21-19:24:31 DEBUG Allocating a 133MB budget for the global document cache
```

(Remember, it's 40% of *available* memory ;)).

Comment (Frenzie) [reply defaults.lua:36]: > My bad, I meant "what for", not where as in platforms ;).

A few pages add up pretty quickly, especially combined with zoom.

I even complained about Evince a few years ago.
https://fransdejonge.com/2017/10/fix-minuscule-zoom-limit-in-evince/

Going for less than this just didn't do it for me:
```
$ gsettings get org.gnome.Evince page-cache-size
uint32 1024
```

Comment (Frenzie) [reply defaults.lua:36]: > (Remember, it's (roughly) 40% of available memory ;)).

Which is a good thing, but yes, I did forget about that for the moment. :-P

**Review by Frenzie — APPROVED** [review]
lgtm to push into 2021.08 but it can wait if you prefer

File: plugins/readtimer.koplugin/main.lua [hunk 2]
```diff
@@ -187,4 +193,13 @@ function ReadTimer:addToMainMenu(menu_items)
     }
 end
 
+-- The UI ticks on a monotonic time domain, while this plugin deals with real time.
+-- Make sure we fire the alarm right away if it expired during suspend...
+function ReadTimer:onResume()
+    if self:remainingMinutes() == 0 then
+        self:alarm_callback()
+        self:unschedule()
+    end
```
Comment (Frenzie) [inline plugins/readtimer.koplugin/main.lua:202]: Actually, if larger than 0 then unschedule and reschedule subtracted version? :angel:

Comment (NiLuJe) [reply plugins/readtimer.koplugin/main.lua:202]: It's already effectively the subtracted version by virtue of being scheduled on the MONOTONIC timescale (i.e., it's scheduled in n seconds in the future, and those seconds only tick while awake) ;).

**Comment by NiLuJe** [comment]
> lgtm to push into 2021.08 but it can wait if you prefer

Looks harmless enough ;p (famous last words ;p).

File: plugins/readtimer.koplugin/main.lua (hunk 2 above)
Comment (Frenzie) [reply plugins/readtimer.koplugin/main.lua:202]: By subtracted I mean:

1. You set timer for 60 minutes.
2. At some point in, you sleep for 20 minutes.
3. You want the timer to go off at 60 minutes. *Not*, very, very, very much not at 60+20, and even less not at all.

So subtracted would be remaining - 20.

Comment (NiLuJe) [reply plugins/readtimer.koplugin/main.lua:202]: There's going to be precision loss because we're crossing time domains, and we'd essentially be checking against what the timer's expiration date *should* theoretically be in one domain (REAL) while it's actually scheduled and ticking in another (MONO) ;).

(Given the UI domain, race conditions are less likely this way around, though).

We don't actually have a way to query the current timer for a specific task in its native domain (i.e., MONO) and we also don't have a centralized way of computing the sleep duration (some of our target devices are too old to support BOOTTIME), and I'm not aware of any sane way to get at the accurate computation of this delay the kernel does as part of its timekeeping duties...

TL;DR: The only way I can see this being done is simply to compare os.time() from suspend & resume. If it drifts or shit happened, it's going to be even more broken ^^.
