### PR TITLE
TOC: validate and fix misordered page numbers

### LINKED ISSUE #3062: large nested epub file table of contents entries disappear and re-appear
* KOReader version: koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1087-gba96506
* Device: kobo aura(original)

It is awesome to find that multi-level table of contents are supported in koreader. I plan to make good use of that.

I have an epub document i have created with a lot of small files inside. Something like 1400 files. 
I have created a .ncx file with 3 levels of nesting. Documents are listed more than once, organizing them in different way.

What i find is when i expand some of the later sections in the table of contents, the items appear correctly. However when i collapse the same section, then some following sections disappear on the table of contents screen. I can re-open the .epub file and missing entries re-appear. If there is a higher level section containing the problematic portion of the table of contents, if i contract and then expand this, then also the lower level stuff gets fixed.

I did try the sample file i found here, juliet.epub. This has a similar structure in the table of contents, and it works fine on the kobo. 

I wonder if there is some limit i am hitting here about number of sections? 

I also have viewed this same epub with other tools and it works fine there too.

### PR DESCRIPTION
**Pull request by poire-z**
Our code expects (rightfully) the TOC items to be ordered and to have increasing page numbers, but we may occasionally not get that from the engines (usually, because of bugs or duplicated IDs in the document).
Check for that and fix page numbers (possibly making them wrong) to have a working TOC.
Some details in https://github.com/koreader/koreader/issues/3062#issuecomment-402746843
Closes #3062. Issue also met in #5194.

That China.EN.epub fixed TOC would then appear as:
<kbd>image</kbd>
(which is not super right, the real page number of that History entry is 14 - but I'm just attempting to have the TOC working, not to make tha page right, which is impossible, just less bogus enough to not be misordered).

On a TOC with randomly shifted page numbers, it would show as:
<kbd>image</kbd>

(Thought about saving toc_is_valid = true/false in the TOC, so that scan is only done on the first opening of a book - but that quick scan single loop is fast, so probably sane and cheap to do that on each opening or re-rendering.)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5907)

### CODE REVIEW

File: frontend/apps/reader/modules/readertoc.lua [hunk 1]
```diff
@@ -89,6 +91,113 @@ function ReaderToc:fillToc()
...
+
+    -- For testing: shuffle a bit a valid TOC and make it randomely invalid
+    -- for i = first, last do
+    --     toc[i].page = toc[i].page + math.random(10) - 5
+    -- end
+
+    -- Do a cheap quick scan first
+    logger.dbg("validateAndFixToc(): quick scan")
+    local has_bogus
+    local cur_page = -1
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua]: Not 0?

File: frontend/apps/reader/modules/readertoc.lua [hunk 2]
```diff
@@ -280,6 +389,9 @@ function ReaderToc:onShowToc()
         for _,v in ipairs(self.toc) do
             v.text = self.toc_indent:rep(v.depth-1)..self:cleanUpTocTitle(v.title)
             v.mandatory = v.page
+            if v.orig_page then -- bogus page fixed: show original page number
+                v.mandatory = T("(%1) %2", v.orig_page, v.page)
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readertoc.lua]: Bidi?

Comment (poire-z) [reply frontend/apps/reader/modules/readertoc.lua]: Looks like BiDi will handle it automagically:
<kbd>image</kbd>
(wider screen width, so not same numbers as first post screenshots)
