### PR TITLE
[ReaderHighlight] NT: Improve selection of hyphenated words

### LINKED ISSUE #13120: NT: Wrong positioning-selection with hyphenated words
* KOReader version: 2024.11
* Device: kindle 4 and all NT

#### Issue
when selecting hyphenated words (due to line breaks), the crosshair indicator which normally places itself in the middle of the selected word, jumps to the middle of the screen's width.

<p align="center">
 
</p>

#### Steps to reproduce
open book
start content selection
select a hyphenated word (the ones related to line breaks)

### PR DESCRIPTION
**Pull request by Commodore64user**
### what's new

The changes focus on improving the logic for handling highlight interactions and enhancing the accuracy of text selection.

* **Highlight Interaction Logic:**
  * Simplified the conditional checks and streamlined the logic for starting and stopping highlights.
  * Added a return statement to handle cases where there is no current indicator position early in the function.

* **Text Selection Accuracy:**
  * Introduced a heuristic approach to determine if a word is hyphenated due to line breaks, improving the accuracy of text selection.
  * Created a helper function `updatePositions` to centralize the logic for updating hold and indicator positions.

### screenshots

**before** 

<p align="center">
 
</p>

**after**

correct detection under extreme circumstances 

<p align="center">
 
 
</p>

correct detection in two column mode and landscape orientation

<p align="center">
 
</p> 

closes #13120

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/13129)

### CODE REVIEW

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -2460,37 +2460,85 @@ end
...
+    self._start_indicator_highlight = true
+    self:onHold(nil, self:_createHighlightGesture("hold"))
+
+    if not (self.ui.rolling and self.selected_text and self.selected_text.sboxes and #self.selected_text.sboxes > 0) then
+        return true
+    end
+    -- With crengine, selected_text.sboxes return good coordinates.
+    local pos = self.selected_text.sboxes[1]
+    local margins = self.ui.document.configurable.h_page_margins[1] + self.ui.document.configurable.h_page_margins[2]
+    local two_column_mode = self.ui.document.configurable.visible_pages == 2
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua:2484]: (Wording in the comment: selected_text.sboxes is a table, so it does not `return` anything, it (or they?) _has_ or _contains_.)

Tested with a PDF ? where I guess we don't have `configurable.h_page_margins` (so accessing its index may crash if nil) and neither visible_pages (but no crash).

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 2]
```diff
@@ -2460,37 +2460,85 @@ end
...
+    local effective_width = two_column_mode and (self.screen_w - margins) / 2 or self.screen_w - margins
+    -- Words hyphenated due to line breaks create almost-full-effective_width selection boxes, so we need to check if that is the case.
+    -- We cannot precisely recognise hyphenated words under all circumstances, so a heuristic approach is used, goes in two steps.
+    -- First step: check if the box is huge.
+    local is_word_hyphenated = pos.w > 0.7 * effective_width
+    -- Second step: weed out false positives by comparing words at different box coordinates.
+    if is_word_hyphenated then
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua:2491]: Is this function called (or this bit of code met) only on the first press, where only a single word will be selected ?
If no, I think you insisting in there on "word hyphenated" is wrong: it may be your main use case, but reading it is confusing. It would have a place in a comment.

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 3]
```diff
@@ -2460,37 +2460,85 @@ end
...
+        local word_at_pos = self.ui.document:getWordFromPosition({
+            x = BD.mirroredUILayout() and (pos.x + pos.w) or pos.x,
+            y = pos.y + pos.h * 1/4
+        })
+        -- If we get a word at those coordinates and it's the same word, then we're not actually a hyphenated word, just a very wide one.
+        if word_at_pos and word_at_pos.word == self.selected_text.text then
+            is_word_hyphenated = false -- check mate
+        else -- we're 99% sure we actually are hyphenated, now re-select original word
+            self.ui.document:getWordFromPosition({
+                x = BD.mirroredUILayout() and pos.x + pos.w or pos.x,
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua:2501]: You used parens 8 lines above - try to be consistent, parens or no parens in both places.

And how is it that we re-select original word while playing  with and changing coordinates?

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 4]
```diff
@@ -2460,37 +2460,85 @@ end
...
+    local effective_width = two_column_mode and (self.screen_w - margins) / 2 or self.screen_w - margins
+    -- Words hyphenated due to line breaks create almost-full-effective_width selection boxes, so we need to check if that is the case.
+    -- We cannot precisely recognise hyphenated words under all circumstances, so a heuristic approach is used, goes in two steps.
+    -- First step: check if the box is huge.
+    local is_word_hyphenated = pos.w > 0.7 * effective_width
+    -- Second step: weed out false positives by comparing words at different box coordinates.
+    if is_word_hyphenated then
+        local word_at_pos = self.ui.document:getWordFromPosition({
+            x = BD.mirroredUILayout() and (pos.x + pos.w) or pos.x,
+            y = pos.y + pos.h * 1/4
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerhighlight.lua:2494]: Not sure I understand this 1/4 and the 3/4 below - might be worth a comment.

**Review by poire-z — COMMENTED** [review]
Just some comments while reading for you to see if there's anything that makes sense - I'm not really interested in understanding it all as its quite contained to a NT only section.
There are already quite a few comments, but as it's not obvious, more would be welcome for when Little Timmy gets into coding in 10 years.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 2 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: I'm inclined to agree. It's trying to detect multiline words which may or may not be hyphenated. But perhaps most important absolutely no hyphenation detection of any sort is involved.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 4 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:2494]: In a single line 1/2 is the middle, so for two lines 1/4 and 3/4 would be line 1 and 2. Or in case of a false positive, a bit higher/lower than it'd otherwise be, probably harmless.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 1 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2484]: This beef, you should have had it when the comment was first introduced years ago, i am just moving it around ;). But i get your point

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 2 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: Function is only called when one word is selected. As i have stated already, i don’t know how to figure out if a word is being hyphenated, if you do know --i have been screaming about it-- speak up. I am going by Sherlock's approach, “When you have eliminated the impossible, whatever remains, however improbable, must be the truth.”

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 3 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2501]: Cool, my bad.

If we don't re-select, the user gets the crosshairs and hold are in the correct coordinates but the actual highlight stays with the intermediary word.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 2 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: Just because the word is split across multiple lines doesn't mean it's hyphenated. It just means it's split across multiple lines.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: ^ That's it. You can't know if it's really hyphenated in the frontend context (and trying to know would probably be complicated).
In your context of boxes (that's all you have), it is "split across multiple lines". In 99.99% it will indeed be because of hyphenation - but writing about hyphenation in your frontend code is confusing because it is a little lie (but you could write in a comment "most often, it will be because the word is hyphenated").

Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: Yes, but by process of elimination, it's a lot more likely we are breaking it up and hyphenating it. Therefore the system is 99% accurate. I invite you to put to the test.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: My comments all along were just about wording and naming in the code.
`is_word_hyphenated` => `is_word_splitted` (and "hyphenated" mentionned only in comments) would make me satistfied :) (split/splitted, not sure it's correct English, so another word that looks different as an adjective would be better, unless it reads naturally to you Englishmen).
(About testing, effectiveness, accuray, I trust you - because I won't use it - but I can read that code :)

Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: `is_word_split` seems fine to me then.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 4 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2494]: question: technically speaking to make the system 99.99% sure we are spliting words, we should also check the bottom right and compare the three results, what do you think? is it enough the way it is, or should i do both?

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 1 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua:2484]: works fine with pdf, we do have the `if not (self.ui.rolling and self.selected_text and self.selected_text.sboxes and #self.selected_text.sboxes > 0) then` early though

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 2 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:2491]: > You can't know if it's really hyphenated in the frontend context (and trying to know would probably be complicated).

Nor does it even matter. We don't want to limit this behavior to hyphenation — a dumb split should be treated the same way. :-)

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 3 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua:2501]: We normally don't use parentheses when they're not necessary, so for consistency with the rest of the code it's better to remove them.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 4 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua]: I figure you should probably go for the bottom center if you did. The end of the line may not be reached.

Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua]: looks like it's not really a problem, it seems to me crengine will always attach to the nearest word so you should always get 'something'  but also in the check we first make sure we do in fact have a word before trying to call it.
<p align="center">
 
</p>

**Comment by Commodore64user** [comment]
you are all going to love this one ;)

<p align="center">
 
 
</p>

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 4 above)
Comment (Frenzie) [reply frontend/apps/reader/modules/readerhighlight.lua]: > but also in the check we first make sure we do in fact have a word before trying to call it.

I didn't mean in the sense of it causing a crash, just in the sense of having useful results.

I didn't realize it'd select things all the way over on the left of the line.

**Comment by poire-z** [comment]
> you are all going to love this one ;)

Not that much :) it's a known "issue" among many small ones we can live with, when a text node is broken inside a word (by these stupid (kobo?) spans): we mostly handle things text node by text node, so when these span happen, it marks the end of a text node, and so of its last word.
Searching for "reconsidered" would not find it. A ligature would not happen...
The one thing that may work - as seen there - is hyphenation.

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 4 above)
Comment (Commodore64user) [reply frontend/apps/reader/modules/readerhighlight.lua]: Well, we could always make it 99.9999% accurate ;)

**Comment by Commodore64user** [comment]
I see. Noted

> more would be welcome for when Little Timmy gets into coding in 10 years.

btw, Little Timmy is more into construction and that sort of thing, he wants to be a quantity surveyor when he grows up

**Comment by poire-z** [comment]
> do you need more comments or is it fine now?

Looks ok aesthetically :) (I haven't focused on the logic and results, trusting you.)

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 5]
```diff
@@ -2460,37 +2460,94 @@ end
...
+        local word_at_pos2 = self.ui.document:getWordFromPosition({
+            x = BD.mirroredUILayout() and pos.x or pos.x + pos.w,
+            y = pos.y + pos.h * 3/4 -- puts us at a potential line 2 of 2
+        })
+        local does_word_at_pos1_match = word_at_pos1 and word_at_pos1.word == self.selected_text.text
+        local does_word_at_pos2_match = word_at_pos2 and word_at_pos2.word == self.selected_text.text
+        -- If all 3 words are a match, then we're likely not a split word, just a very long one, something worthy of floccinaucinihilipilification.
+        if does_word_at_pos1_match and does_word_at_pos2_match then
+            is_word_split = false -- check mate
+        else -- We're 99.99% sure the word was split (and hyphenated). Re-select the original word to ensure the correct word is highlighted.
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua:2508]: Nit, but better for future clarity. ;-)
```suggestion
        else -- We're reasonably sure the word was split (and hyphenated). Re-select the original word to ensure the correct word is highlighted.
```

**Comment by Commodore64user** [comment]
just an idea, but should not be needed because centred text should not hyphenate in the first place. 

```lua
    -- With crengine, selected_text.sboxes have good coordinates, so we'll borrow them.
    local pos = self.selected_text.sboxes[1]
    local font_size = self.ui.document.configurable.font_size
    local saved_mbh = self.ui.doc_settings:readSetting("min_box_height")
    if saved_mbh and saved_mbh.font_size ~= font_size then
        saved_mbh = nil
    end
    local tally = saved_mbh and saved_mbh.tally or {}
    tally[pos.h] = (tally[pos.h] or 0) + 1
    self.ui.doc_settings:saveSetting("min_box_height", { tally = tally, font_size = font_size })

    local min_box_height = pos.h
    local best_count = 0
    for h, count in pairs(tally) do
        if count > best_count then
            best_count = count
            min_box_height = h
        end
    end
    local margins = self.ui.document.configurable.h_page_margins[1] + self.ui.document.configurable.h_page_margins[2]
    local two_column_mode = self.ui.document.configurable.visible_pages == 2
    local effective_width = two_column_mode and (self.screen_w - margins) / 2 or self.screen_w - margins
    -- When words are split (and hyphenated) due to line breaks, they create selection boxes that are almost as wide as the
    -- effective_width, so we need to check if that is the case, in order to handle those cases properly. We cannot precisely
    -- and easily recognise hyphenated words in the front end, so a heuristic approach is used, it goes in two steps.
    -- Step one: check if our box is a 'big boy'. We must allow some room for unknown variables like publisher-embedded padding, etc.
    local is_word_split = pos.w > 0.7 * effective_width
    if pos.h > min_box_height then
        -- If the box is also very tall, it's likely a split word that got an extra tall box instead of two separate boxes.
        is_word_split = true
    end
```

**Comment by Commodore64user** [comment]
this seems like a better idea

```lua
    local is_word_split = false
    if pos.w > 0.5 * effective_width then
        is_word_split = true
    elseif pos.w > 0.25 * effective_width and (pos.h/pos.w) > 0.2 then
        is_word_split = true
    end
```
