### PR TITLE
Optimize cre highlights onTap and drawing

### LINKED ISSUE #3503: KOreader slowing down as i added highlights
* KOReader version:
v2015.11-1412-g819212f (this issue didn't apprear with this version)
* Device:
Kobo Aura one
#### Issue
As put highlights in my book, the device goes slower and slower.
The device is slow only when the book is opened.
I have to purge the ".sdr" to get the device back at normal speed.
#### Steps to reproduce
Add highlights
#### Data
This is an example (it's a free book from wikisource) and the sdr file.
[data.zip](https://github.com/koreader/koreader/files/1485844/data.zip)

You'r doing a great work.
Thank's for your help.

### PR DESCRIPTION
**Pull request by poire-z**
drawXPointerSavedHighlight() and onTapXPointerSavedHighlight were looping thru all credocuments highlights, which was expensive.
Now, we first check with cheaper getPageFromXPointer() the highlights are on the current page before doing more expensive stuff.

Hope I got that right and that won't start ignoring some highlights...
Closes #3503.

### CODE REVIEW

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 1]
```diff
@@ -189,18 +189,33 @@ function ReaderHighlight:onTapPageSavedHighlight(ges)
...
+                local page0 = self.ui.document:getPageFromXPointer(pos0)
+                local page1 = self.ui.document:getPageFromXPointer(pos1)
+                local start_page = math.min(page0, page1)
+                local end_page = math.max(page0, page1)
+                if start_page <= cur_page + neigbour_pages and end_page >= cur_page - neigbour_pages then
+                    local boxes = self.ui.document:getScreenBoxesFromPositions(pos0, pos1)
+                    if boxes then
+                        for index, box in pairs(boxes) do
+                            if inside_box(pos, box) then
+                                logger.dbg("Tap on hightlight")
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua]: "hightlight" :-P

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 2]
```diff
@@ -189,18 +189,33 @@ function ReaderHighlight:onTapPageSavedHighlight(ges)
 end
 
 function ReaderHighlight:onTapXPointerSavedHighlight(ges)
+    local cur_page
+    -- In scroll mode, we'll need to check for highlights in previous or next
+    -- page too as some parts of them may be displayed
+    local neigbour_pages = self.view.view_mode ~= "page" and 1 or 0
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua]: neighbor/neighbour

File: frontend/apps/reader/modules/readerhighlight.lua [hunk 3]
```diff
@@ -189,18 +189,33 @@ function ReaderHighlight:onTapPageSavedHighlight(ges)
...
-                        if inside_box(pos, box) then
-                            logger.dbg("Tap on hightlight")
-                            return self:onShowHighlightDialog(page, i)
+                -- document:getScreenBoxesFromPositions() is expensive, so we
+                -- first check this item is on current page
+                local page0 = self.ui.document:getPageFromXPointer(pos0)
+                local page1 = self.ui.document:getPageFromXPointer(pos1)
+                local start_page = math.min(page0, page1)
+                local end_page = math.max(page0, page1)
+                if start_page <= cur_page + neigbour_pages and end_page >= cur_page - neigbour_pages then
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerhighlight.lua]: Are you sure that `+` and  `-` are the right way around?

NB This is all untested but this is how I'd intuitively write it myself unless I'm misunderstanding what's supposed to happen. At least to me it seems clearer to say "this is how we're adjusting the start page" than "let's pretend the current page is a slightly different one."

```lua
start_page - neigbour_pages <= cur_page and end_page + neigbour_pages >= cur_page
```

File: frontend/apps/reader/modules/readerview.lua [hunk 4]
```diff
@@ -473,21 +473,36 @@ function ReaderView:drawPageSavedHighlight(bb, x, y)
 end
 
 function ReaderView:drawXPointerSavedHighlight(bb, x, y)
+    local cur_page
+    -- In scroll mode, we'll need to check for highlights in previous or next
+    -- page too as some parts of them may be displayed
+    local neigbour_pages = self.view_mode ~= "page" and 1 or 0
```
Comment (Frenzie) [inline frontend/apps/reader/modules/readerview.lua]: Same comments as above in this file, of course. :-P

File: frontend/apps/reader/modules/readerhighlight.lua (hunk 3 above)
Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua]: Yes, I'm sure, and it also feels a bit strange to me.

We want to check the highlight start_page in on the current_page (in page mode), so it could be start_page == cur_page.
In scroll mode, we may be displaying a part of cur_page AND some parts of cur_page -1 OR cur_page +1 : so, we want the highlight start_page to be on cur_page -1, cur_page or cur_page+1 , so : start_page <= cur_page +1.
Same thinking with highlight's end_page, and we got : end_page >= cur_page -1.
It's really cur_page we are adjusting. I can't thing of an alternative writing.

Comment (poire-z) [reply frontend/apps/reader/modules/readerhighlight.lua]: And if some big highlight starts on cur_page - 23 and ends on cur_page + 17, it is a highlight to consider.
