### PR TITLE
InputDialog: fix adding widget with 'use available height'

### LINKED ISSUE #15002: Keyboard occludes InputDialog when addWidget() called
### Device

Linux (Deb / generic)

### KOReader version

2025.10-114

### Model and firmware version

_No response_

### Issue description

When displaying an `InputDialog` with following conditions:
- buttons are defined
- `use_available_height = true`
- added a widget using `inputDialog:addWidget()` 

The keyboard will occlude the buttons of the InputDialog - calculating available height does not take into account the size of the added widget.

Screenshot showing InputDialog with occluded buttons:

Image
After keyboard hidden:
Image

Expected behavior:
Keyboard does not occlude the buttons, and the entire InputDialog is visible

### Steps to reproduce

1. Install the following plugin for testing
[inputdialog-test.koplugin.zip](https://github.com/user-attachments/files/25383117/inputdialog-test.koplugin.zip)
2. Go to Tools
3. Click on 'Test input dialog'
4. Observe Keyboard occludes the buttons of the displayed InputDialog

### Log

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hius07**
- Closes #15002

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/15010)

### CODE REVIEW

File: frontend/ui/widget/inputdialog.lua [hunk 1]
```diff
@@ -516,9 +521,15 @@ function InputDialog:addWidget(widget, re_init)
             self._added_widgets = {}
         end
         table.insert(self._added_widgets, widget)
+        if self.use_available_height then
+            self.text_height = nil
+            self:init()
+        end
```
Comment (poire-z) [inline frontend/ui/widget/inputdialog.lua:527]: This self:init() inside InputDialog:addWidget() feels like we may get caught in a loop, as :init() can call :addWidget().
Are there conditions that prevent that from happening ? (If any, a comment saying so and why would provide some comfort :))

Comment (hius07) [reply frontend/ui/widget/inputdialog.lua:527]: Yes, init calls addWidget with re_init=true:
https://github.com/koreader/koreader/blob/7c33042aea18dae4f9696e6d5d5d9031cd75f99d/frontend/ui/widget/inputdialog.lua#L470
addWidget calls init within
https://github.com/koreader/koreader/blob/7c33042aea18dae4f9696e6d5d5d9031cd75f99d/frontend/ui/widget/inputdialog.lua#L507

**Review by Frenzie — APPROVED** [review]

**Comment by j-v** [comment]
yay thanks for the fix!

**Comment by j-v** [comment]
@hius07 the fix only works if i change the `re_init` arg in my repro code from `sample_input:addWidget(button, true)` to `sample_input:addWidget(button, false)` 
Is that expected? I might not be totally clear on what is the appropriate use of the `re_init` arg.

**Comment by poire-z** [comment]
You should indeed just use `sample_input:addWidget(button)`.
The default for `re_init` is nil/false. Its intended use is internal, by InputDialog itself when things change too much (virtual keyboard toggled, screen rotation), it will re-init() itself, calling :addWidget(..., true).

**Comment by j-v** [comment]
> You should indeed just use `sample_input:addWidget(button)`. The default for `re_init` is nil/false. Its intended use is internal, by InputDialog itself when things change too much (virtual keyboard toggled, screen rotation), it will re-init() itself, calling :addWidget(..., true).

Cool thanks for the tip @poire-z 
Would be nice to have the function commented with the intended arg usage, i could create a small PR?
