### PR TITLE
Individually Invert page turners on kindle

### LINKED ISSUE #9350: [Legacy Kindle/K3GB]  Buttons mapped incorrectly when in landscape mode
* KOReader version: 2022.05.1-58
* Device:  Kindle 3GB [Legacy Kindle]

#### Issue
Related to #7561. The buttons are mapped in the wrong way when the screen is rotated to landscape mode.

#### Steps to reproduce

1. Open any document (I opened a PDF)
2. Press Aa on the keyboard
3. Scroll to the rotation setting and set it to landscape 
photo_2022-07-19_15-53-05

4. Now when you press the button which is facing downwards, the pages go backwards. And when you press the button pointing upwards, the pdf turns pages forwards. I think it should be the opposite way around on this device.

### PR DESCRIPTION
**Pull request by Commodore64user**
As seen on this [picture](https://newatlas.com/4th-gen-kindle-review/20722/), K4 is ergonomically designed to be held with one hand (one's hand wrapped around the back and both thumb and middle finger on either `PgFwd` buttons).

90 copy

This PR allows users to individually invert left and right page turners such that it can be operated just with one hand. It also closes #9350 

Not sure if there are any other devices with two sets of page turn buttons, so currently limited to kindle, excluding kindle Voyage, but could be added too, albeit with some gymnastics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/11963)

### CODE REVIEW

File: frontend/ui/elements/physical_buttons.lua [hunk 1]
```diff
@@ -19,6 +19,28 @@ local PhysicalButtons = {
     },
 }
 
+if Device:hasScreenKB() or Device:hasSymKey() then
```
Comment (Commodore64user) [inline frontend/ui/elements/physical_buttons.lua:22]:
```suggestion
if Device: useDPadAsActionKeys() then
```

**Comment by Commodore64user** [comment]
I don't know if this is something that could/should be included here, but it would be nice to have a user patch that displays a dog ear in the bottom right corner of the screen, that indicates that one set of page turn buttons is currently inverted.

File: frontend/ui/elements/physical_buttons.lua (hunk 1 above)
Comment (Frenzie) [reply frontend/ui/elements/physical_buttons.lua:26]: Please make it hasDPad and useDPadAsActionKeys in that case.

File: frontend/device/devicelistener.lua [hunk 2]
```diff
@@ -313,6 +313,16 @@ function DeviceListener:onSwapPageTurnButtons()
     Device:invertButtons()
 end
 
+function DeviceListener:onSwapLeftPageTurnButtons()
```
Comment (Frenzie) [inline frontend/device/devicelistener.lua:316]: @hius07 any thoughts on adding an event?

Comment (hius07) [reply frontend/device/devicelistener.lua:316]: I don't think these new actions are worth to be added to Dispatcher, hence no need of proxy methods in DeviceListener.
All can be done in the menu elements module, with direct calls of `Device:`.

Comment (Frenzie) [reply frontend/device/devicelistener.lua:316]: I agree.

Comment (Commodore64user) [reply frontend/device/devicelistener.lua:316]: is this what you mean?

```lua
table.insert(PhysicalButtons.sub_item_table, {
        text = _("Invert left side page-turn buttons"),
        checked_func = function()
            return G_reader_settings:isTrue("input_invert_left_page_turn_keys")
        end,
        callback = function()
            -- UIManager:broadcastEvent(Event:new("SwapLeftPageTurnButtons"))
            G_reader_settings:flipNilOrFalse("input_invert_left_page_turn_keys")
            Device:invertButtonsLeft()
        end,
    })
```

**Comment by Commodore64user** [comment]
Wondering if you guys noticed https://github.com/koreader/koreader/pull/11963#issuecomment-2147876605

**Comment by poire-z** [comment]
> However, if I restart KOReader, when the programme is back up and running again, even though the option is selected (`[✓] invert right-side page turn buttons`) the inversion does not actually occur, meaning both sets of page turn button continue to operate in a regular fashion

I guess that on koreader startup, nowhere you call `Device:invertButtonsRight()` so nothing happens.
You'd need to, somewhere, the same place other such key behavour settings are checked and activated, you should `if settings:isTrue("blahright") then Device:invertButtonsRight() end`

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/7a84cfef4a648f5c0e00980acfebec8a80eaec54/frontend/device/generic/device.lua#L197
https://github.com/koreader/koreader/blob/7a84cfef4a648f5c0e00980acfebec8a80eaec54/frontend/device/generic/device.lua#L255-L260

**Comment by Commodore64user** [comment]
> https://github.com/koreader/koreader/blob/7a84cfef4a648f5c0e00980acfebec8a80eaec54/frontend/device/generic/device.lua#L197
> 
> 
> https://github.com/koreader/koreader/blob/7a84cfef4a648f5c0e00980acfebec8a80eaec54/frontend/device/generic/device.lua#L255-L260

oops, I swear I did not see that.

**Comment by Commodore64user** [comment]
Any chance we could help a guy out with this https://github.com/koreader/koreader/pull/11963#issuecomment-2146336376, i keep forgetting the buttons are inverted and madness occurs.
