### PR TITLE
Input: Process input events in batches

### LINKED ISSUE #7485: reader cannot start on cervantes after upgrade from v2021.03 to v2021.03-15
BQ Cervantes,

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/02/21-12:45:58
 [*] Version: v2021.03-15-g8a923e3_2021-04-01

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
FB: Enforcing portrait mode by doing an initial BB rotation./luajit: frontend/ui/timeval.lua:31: ./luajit: undefined symbol: clock_getres
stack traceback:
	[C]: in function '__index'
	frontend/ui/timeval.lua:31: in main chunk
	[C]: in function 'require'
	frontend/device/gesturedetector.lua:46: in main chunk
	[C]: in function 'require'
	frontend/device/input.lua:8: in main chunk
	[C]: in function 'require'
	frontend/device/cervantes/device.lua:133: in function 'init'
	frontend/device.lua:54: in main chunk
	[C]: in function 'require'
	./reader.lua:142: in main chunk
	[C]: at 0x00013f31
```

### PR DESCRIPTION
**Pull request by NiLuJe**
Requires https://github.com/koreader/koreader-base/pull/1344 & https://github.com/koreader/koreader-base/pull/1346 (fix #7485)

Assorted input fixes:

* Actually handle errors in the "there's a callback timer" input polling loop.
* Don't break timerfd when the clock probe was inconclusive.

Not directly related, but noticed because of duplicate onInputEvent handlers:

* HookContainer: Fix deregistration to actually deregister properly. "Regression" extant since its inception in #2933 (!).
* Made sure the three plugins (basically the trio of AutoThingies ;p) that were using HookContainer actually unschedule their task on teardown.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7483)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Which makes a single tap much clearer:

```
[pid 20342] 01:44:59.697013 [2ac7ae90] _newselect(8, [5</dev/input/event0> 6</dev/input/event1> 7<pipe:[61890]>], NULL, NULL, {tv_sec=1753, tv_usec=413589}) = 1 (in [6], left {tv_sec=1750, tv_usec=964175}) <2.449473>
[pid 20342] 01:45:02.148073 [2ac828dc] timerfd_create(CLOCK_REALTIME, TFD_CLOEXEC|TFD_NONBLOCK) = 11<anon_inode:[timerfd]> <0.000052>
[pid 20342] 01:45:02.148423 [2ac828fc] timerfd_settime(11<anon_inode:[timerfd]>, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=1617320702, tv_nsec=647130000}}, NULL) = 0 <0.000037>
[pid 20342] 01:45:02.151177 [2ac9031c] clock_gettime(CLOCK_MONOTONIC, {tv_sec=533936, tv_nsec=736409837}) = 0 <0.000037>
[pid 20342] 01:45:02.151590 [2ac7ae90] _newselect(12, [5</dev/input/event0> 6</dev/input/event1> 7<pipe:[61890]> 11<anon_inode:[timerfd]>], NULL, NULL, {tv_sec=1750, tv_usec=959005}) = 1 (in [6], left {tv_sec=1750, tv_usec=952839}) <0.006217>
[pid 20342] 01:45:02.161924 [2ac9031c] clock_gettime(CLOCK_MONOTONIC, {tv_sec=533936, tv_nsec=747137840}) = 0 <0.000034>
[pid 20342] 01:45:02.162312 [2ac7ae90] _newselect(8, [5</dev/input/event0> 6</dev/input/event1> 7<pipe:[61890]>], NULL, NULL, {tv_sec=1750, tv_usec=948277}
```

 :}

**Review by poire-z — APPROVED** [review]
Looks ok.

File: frontend/device/input.lua [hunk 1]
```diff
@@ -1028,14 +1029,17 @@ function Input:waitEvent(now, deadline)
                             -- This is why we clear the full list of timers on the first match ;).
                             self:clearTimeouts()
                             self:gestureAdjustHook(touch_ges)
-                            return Event:new("Gesture",
+                            return { Event:new("Gesture",
```
Comment (Frenzie) [inline frontend/device/input.lua:1032]: Not sure what to think of the exact spacing/layout.

**Review by Frenzie — APPROVED** [review]
lgtm

File: frontend/device/input.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/device/input.lua:1032]: Yeah, possibly break after the brace like we usually do for constructors & stuff?

File: spec/unit/device_spec.lua [hunk 2]
```diff
@@ -273,15 +273,15 @@ describe("device module", function()
 
             mock_ffi_input = require('ffi/input')
             stub(mock_ffi_input, "waitForEvent")
-            mock_ffi_input.waitForEvent.returns(true, {
+            mock_ffi_input.waitForEvent.returns(true, { {
```
Comment (Frenzie) [inline spec/unit/device_spec.lua:276]: @NiLuJe https://github.com/koreader/koreader/commit/2a2d2baf739dd5bb89078c798c7474719849b311#commitcomment-49028640
> Meaning you prefer the "with a break" variant?

I think so, less for the one liner as for situations like these.

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 2 files at r3, 3 of 3 files at r4.
> Dismissed @Frenzie from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/7483)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pazos)

___
*[frontend/device/input.lua, line 1032 at r2](https://reviewable.io/reviews/koreader/koreader/7483#-MXEl8dkIZvRuh9W233W-r2-1032:-MXJjV-r5Ly8Kon1HP6b:b-896fix) ([raw file](https://github.com/koreader/koreader/blob/38e9ebf3569eb548850678a176de5a14330708d8/frontend/device/input.lua#L1032)):*
<details><summary><i>Previously, NiLuJe (NiLuJe) wrote…</i></summary><blockquote>

Yeah, possibly break after the brace like we usually do for constructors & stuff?
</blockquote></details>

Done.
___
*[spec/unit/device_spec.lua, line 276 at r3](https://reviewable.io/reviews/koreader/koreader/7483#-MXEq3PtbmecfXdqTwzf-r3-276:-MXJkQV-2j5GUNu7Gm05:b-896fix) ([raw file](https://github.com/koreader/koreader/blob/2a2d2baf739dd5bb89078c798c7474719849b311/spec/unit/device_spec.lua#L276)):*
<details><summary><i>Previously, Frenzie (Frans de Jonge) wrote…</i></summary><blockquote>

@NiLuJe https://github.com/koreader/koreader/commit/2a2d2baf739dd5bb89078c798c7474719849b311#commitcomment-49028640
> Meaning you prefer the "with a break" variant?

I think so, less for the one liner as for situations like these.
</blockquote></details>

Done.
