### PR TITLE
[fix, UX] Allow modal widget on top of modal widget

### LINKED ISSUE #2653: Screensaver renders underneath InfoMessage
* KOReader version: v2015.11-898-gdccbf4c
* Device: Kobo Glo HD

#### Issue
Screensaver renders underneath InfoMessages such as
* Connected to network …
* Your KOReader is up to date
* KOReader will be updated on next restart

I'm using a custom screensaver

settings.reader.lua:
```
    ["suspend_screensaver"] = {
        ["path"] = "/mnt/onboard/.adds/img/sleeping.png"
    },
```

#### Steps to reproduce
1. Touch Hamburger menu -> Version
2. Push power button to suspend device or wait for the device to fall asleep

### PR DESCRIPTION
**Pull request by Frenzie**
Fixes #2653.

### CODE REVIEW

File: frontend/ui/uimanager.lua [hunk 1]
```diff
@@ -189,7 +189,7 @@ function UIManager:show(widget, refreshtype, refreshregion, x, y)
     for i = #self._window_stack, 0, -1 do
         local top_window = self._window_stack[i]
         -- skip modal window
-        if not top_window or not top_window.widget.modal then
+        if not top_window or not (top_window.widget.modal and window.modal) then
```
Comment (Frenzie) [inline frontend/ui/uimanager.lua]: Actually don't merge this. I messed up the logic.

File: frontend/ui/uimanager.lua [hunk 2]
```diff
@@ -189,7 +189,10 @@ function UIManager:show(widget, refreshtype, refreshregion, x, y)
     for i = #self._window_stack, 0, -1 do
         local top_window = self._window_stack[i]
         -- skip modal window
-        if not top_window or not top_window.widget.modal then
+        if widget.modal then
```
Comment (Frenzie) [inline frontend/ui/uimanager.lua]: I could just stick this in line with the other ors couldn't I. Silly me. I was making it too complicated. :-p
