### PR TITLE
Translate file size unit

### LINKED ISSUE #5649: No localized string for file size unit (B, KB, MB, GB)
* KOReader version: 2019.11
* Device: Kobo Forma

#### Issue
I'm in the process of translating the KOReader to Romanian. I found that there is no way to localize the file size units (B, KB, MB, GB) because there is no customizable string in the koreader.po files.
For example in Russian should be Б, КБ, МБ, ГБ, in Romanian and Moldavian O, KO, MO, GO.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

### PR DESCRIPTION
**Pull request by robert00s**
Close #5649

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5651)

### CODE REVIEW

File: frontend/util.lua [hunk 1]
```diff
@@ -656,17 +656,21 @@ end
...
     size = tonumber(size)
     if not size or type(size) ~= "number" then return end
-    local s
     if size > 1024*1024*1024 then
-        s = string.format("%4.1f GB", size/1024/1024/1024)
-    elseif size > 1024*1024 then
-        s = string.format("%4.1f MB", size/1024/1024)
-    elseif size > 1024 then
-        s = string.format("%4.1f KB", size/1024)
+        -- @translators This is abbreviation for the gigabyte, a unit of computer memory or data storage capacity.
```
Comment (Frenzie) [inline frontend/util.lua]:
```suggestion
        -- @translators This is an abbreviation of the gigabyte, a unit of computer memory or data storage capacity.
```

Comment (Frenzie) [reply frontend/util.lua]: For is fine though. Just that "an". :+1:
