### PR TITLE
[fix] Reintroduce "Start with" default to prevent nil string on startup

### LINKED ISSUE #10368: "Start with" menu initializes as nil
* KOReader version: 0db042f
* Device: emulator

#### Issue
Screenshot_20230429_110911

Regression from <https://github.com/koreader/koreader/pull/10198>?

#### Steps to reproduce
Close the program and start it.

Clicking on the nil and going back up fixes the string.

### PR DESCRIPTION
**Pull request by Frenzie**
Regression from #10198.

Fixes #10368.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10369)

### CODE REVIEW

File: frontend/apps/filemanager/filemanagermenu.lua [hunk 1]
```diff
@@ -889,7 +889,7 @@ function FileManagerMenu:getStartWithMenuTable()
     end
     return {
         text_func = function()
-            local start_with = G_reader_settings:readSetting("start_with")
+            local start_with = G_reader_settings:readSetting("start_with") or "filemanager"
```
Comment (NiLuJe) [inline frontend/apps/filemanager/filemanagermenu.lua:892]: I was going to say `G_reader_settings:readSetting("start_with", "filemanager")` is also an option now, but since we don't actually do anything write-related to the settings here, this is probably still clearer.

**Review by NiLuJe — APPROVED** [review]

**Review by hius07 — APPROVED** [review]
