### PR TITLE
ButtonTable, ReaderDogear and TextEditor tweaks and fixes

### LINKED ISSUE #9973: Text Editor list update
* KOReader version: 2022.11-56
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
Text Editor file list doesn’t update after deletion

#### Steps to reproduce
1) Let’s say there are three files that were opened by Text Editor. They will look like this list in the top menu:
1. File1
2. File2
3. File3 

2) If I now delete File2, the list will have the same numbering, but missing “2”:
1. File1
3. File3 

3) If top menu is closed and opened again, the list numbering will be ok:
1. File1
2. File3

I think such update of numbering should happend after each deletion of file history.

### PR DESCRIPTION
**Pull request by poire-z**
#### ButtonTable: reset MovableContainer state on button tap

Prevent any later hold_release event from being handled by MovableContainer as a moving touch+hold_release.
This issue was noticable when closing DictQuickLookup with long-press on close, resulting in the movable highlight actions ButtonTable moving to where the long-press happened.
Issue described at https://github.com/koreader/koreader/pull/9507#issuecomment-1328103992, and various alternative solutions proposed in next posts.

#### ReaderDogear: fix no y-offset after load with top status bar

Regression since #9651, fix item 4 of #9979, https://github.com/koreader/koreader/issues/9979#issuecomment-1368258192.

#### TextEditor: use a file symbol instead of numbers in history

Closes #9973 , by getting rid of the numbers :) and going with:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9985)

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

File: frontend/apps/reader/modules/readerdogear.lua [hunk 1]
```diff
@@ -71,7 +71,7 @@ function ReaderDogear:onReadSettings(config)
 end
 
 function ReaderDogear:onSetPageMargins(margins)
-    if self.ui.document.info.has_pages then
+    if not self.ui.rolling then
```
Comment (hius07) [inline frontend/apps/reader/modules/readerdogear.lua:74]: self.ui.paging doesn't work here?

**Comment by mergen3107** [comment]
Icons look neat!

File: frontend/apps/reader/modules/readerdogear.lua (hunk 1 above)
Comment (poire-z) [reply frontend/apps/reader/modules/readerdogear.lua:74]: It does, but I thought it would be more readable to just use `ui.rolling` here, as all this stuff mostly regards ReaderRolling - than mixing `not ui.paging` and `ui.rolling`.
(And I assume the cost of `not`, if any, is cheap enough :)

**Review by NiLuJe — APPROVED** [review]

File: frontend/apps/reader/modules/readerdogear.lua (hunk 1 above)
Comment (hius07) [reply frontend/apps/reader/modules/readerdogear.lua:74]: Let me disagree and not to follow this.

Comment (Frenzie) [reply frontend/apps/reader/modules/readerdogear.lua:74]: I'd glanced over this change but yeah, this doesn't strike me as a case where using `not` adds clarity.
