### PR TITLE
AutoSuspend: Don't send LeaveStandby events from a zombie plugin instance

### LINKED ISSUE #9112: Random crashes after opening books
* KOReader version: v2022.03.1-63-g84dd58f9_2022-05-09
* Device: Kobo Libra H2O

#### Issue
Koreader crashes seconds after opening a book. It happened a couple of times in the last week or so. Bellow is the log for the most recent one.
#### Steps to reproduce
It seems to be at random 
##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
05/13/22-17:53:13 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
05/13/22-17:53:19 INFO  WakeupMgr: scheduling wakeup in 594
05/13/22-17:53:19 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:53:30 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:53:32 INFO  Thumbnails cache: 12/500 (2.5 MB/10.6 MB)
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
05/13/22-17:53:37 INFO  WakeupMgr: scheduling wakeup in 596
05/13/22-17:53:37 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:05 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:54:05 INFO  opening file /mnt/onboard/books/Frank Herbert's Dune Saga Collection_ Books 1 - 6 - Frank Herbert (2833).epub
GET https://sync.koreader.rocks:443/syncs/progress/71fca90c8a826d667e04f621b5c21966
host or service not provided, or not known
05/13/22-17:54:50 INFO  WakeupMgr: scheduling wakeup in 556
05/13/22-17:54:50 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:52 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
05/13/22-17:54:55 INFO  WakeupMgr: scheduling wakeup in 596
05/13/22-17:54:55 INFO  Kobo standby: asking to enter standby . . .
05/13/22-17:54:58 INFO  Kobo standby: zZz zZz zZz zZz... And woke up!
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
05/13/22-17:55:03 INFO  opening file /mnt/onboard/books/Complete Witcher, The - Andrzej Sapkowski (2835).epub
GET https://sync.koreader.rocks:443/syncs/progress/d62a9a8828816f6ebfe9cb8d541ede87
host or service not provided, or not known
./luajit: frontend/ui/uimanager.lua:1212: attempt to call field 'action' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:1212: in function '_checkTasks'
	frontend/ui/uimanager.lua:1643: in function 'handleInput'
	frontend/ui/uimanager.lua:1754: in function 'run'
	./reader.lua:324: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 05/13/22 @ 17:55:08)
Running FW 4.32.19501 on Linux 4.1.15-00417-g0c800cffe1f9 (#102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021)
Attempting to restart KOReader . . .
!!!!
```
</details>

### PR DESCRIPTION
**Pull request by NiLuJe**
Long story short: the LeaveStandby event is sent via `tickAfterNext`, so if we tear down the plugin right after calling it (in this case, that means that the very input event that wakes the device up from suspend is one that kills ReaderUI or FileManager), what's in UIManager's task queue isn't the actual function, but the anonymous nextTick wrapper constructed by `tickAfterNext` (c.f., 
https://github.com/koreader/koreader/issues/9112#issuecomment-1133999385).

Tweak `UIManager:tickAfterNext` to return a reference to said wrapper, so that we can store it and unschedule that one, too, in `AutoSuspend:onCloseWidget`.

Fix #9112 (many thanks to [@boredhominid](https://github.com/boredhominid) for his help in finding a repro for this ;)).
Re: #8638, as the extra debugging facilities (i.e., ebb81b98451e2a8f54c46f51e861c19fdfb40499) added during testing might help pinpoint the root issue for that one, too.

Also includes a minor simplification to `UIManager:_checkTasks`, and various other task queue related codepaths (e.g., `WakeupMgr`) ;).

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/9124)

### CODE REVIEW

**Comment by NiLuJe** [comment]
At a quick glance, AutoSuspend was the only problematic call site for such a pôtentially race-y use of tickAfterNext ;).

File: frontend/ui/uimanager.lua [hunk 1]
```diff
@@ -527,7 +527,7 @@ function UIManager:schedule(sched_time, action, ...)
     if e ~= 0 then
         -- Do a binary insert.
         repeat
-            p = math.floor((e + s) / 2) -- Not necessary to use (s + (e -s) / 2) here!
+            p = bit.rshift(e + s, 1) -- Not necessary to use (s + (e -s) / 2) here!
```
Comment (zwim) [inline frontend/ui/uimanager.lua:530]: Should work for small number, but not for big ones (>1e10). 
I think the jit does the same for us, but the code would stay more readable.

Comment (NiLuJe) [reply frontend/ui/uimanager.lua:530]: I've just re-read https://bitop.luajit.org/semantics.html ;).

We're only dealing with array indices here, so we should be well and truly safe.

(I'd be more worried if we were chopping the time field).

Comment (NiLuJe) [reply frontend/ui/uimanager.lua:530]: It also seems like arrays can only hold UINT32_MAX slots anyway, and that works just fine over here ;).

```lua
> print(bit.rshift(4294967295, 1))
2147483647
```
