### PR TITLE
Random bug triage!

### LINKED ISSUE #4366: Does not work
* KOReader version: v2018.11.1
* Device: PocketBook PB625

#### Issue
Hello, such a problem. New versions of the Koreader on PB625 are not running. Old ones are working. I don’t remember the latest working version. Help me please.
------
##### `crash.log`     
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/21/18-01:35:27
 [*] Version: v2018.11.1

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
ffi.load: inkview
11/21/18-01:35:27 INFO  SoftwareVersion:  R625.4.4.1815
./luajit: frontend/device/pocketbook/device.lua:243: unrecognized PocketBook model PB625
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:243: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:48: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/centercontainer.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:96: in main chunk
	[C]: at 0x0000c059

### LINKED ISSUE #4387: Wifi non functional on Kobo Glo HD
* KOReader version: 12.0 and 11.1
* Device: Kobo glo HD

#### Issue

When enabling wifi it says "scanning..." and then just a gray bar appears. I can't select my network. On the version previous to 11.0 it worked more or less flawless.

##### `crash.log` (if applicable)
shows just:
12/08/18-08:54:18 INFO  Kobo WiFi: enabling WiFi                                                                                                               
12/08/18-08:55:44 INFO  Kobo WiFi: disabling WiFi                                                                                                              
12/08/18-08:55:48 INFO  Kobo WiFi: enabling WiFi                                                                                                               
12/08/18-08:56:26 INFO  Kobo WiFi: disabling WiFi

### PR DESCRIPTION
**Pull request by NiLuJe**
* Detect the PocketBook Basic Touch 2 (fix #4366)
* Workaround a few WiFi corner-cases on some Kobo devices (i.e., make the 'Wi-Fi connection' menu less stupid) (fix #4387)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Still no clue why Travis is getting tacked on to the checks ;p.

CircleCI is alone when opening the PR, and then, poof, a wild Travis appears! It's super not effective!

File: frontend/ui/network/manager.lua [hunk 1]
```diff
@@ -124,7 +124,7 @@ function NetworkMgr:getWifiMenuTable()
         enabled_func = function() return Device:isAndroid() or Device:isCervantes() or Device:isKindle() or Device:isKobo() or Device:isSonyPRSTUX() end,
         checked_func = function() return NetworkMgr:isWifiOn() end,
         callback = function(touchmenu_instance)
-            local wifi_status = NetworkMgr:isWifiOn()
+            local wifi_status = NetworkMgr:isWifiOn() and NetworkMgr:isConnected()
```
Comment (Frenzie) [inline frontend/ui/network/manager.lua]: You might want to git blame check here since I think this line has had some weirdness associated with it.

File: frontend/ui/network/manager.lua [hunk 2]
```diff
@@ -273,6 +273,16 @@ function NetworkMgr:showNetworkMenu(complete_callback)
             UIManager:show(InfoMessage:new{text = err})
             return
         end
+        -- NOTE: Fairly hackish workaround for #4387,
```
Comment (Frenzie) [inline frontend/ui/network/manager.lua]: Oh, nmind, I guess that's what this is for.

**Comment by Frenzie** [comment]
The deprecated Travis CI service integration was still set up. It's not supposed to run without a .travis.yml but anyway, I deleted that and I figure that should stop it doing whatever it's doing. ;-)

**Comment by NiLuJe** [comment]
Yeah ;). No perceptible delay on my end w/ isConnected, BTW :).
