### PR TITLE
pdfdocument: cache page text

### LINKED ISSUE #10443: Highlighting using stylus input causes SDL to terminate KOReader
* KOReader version: 2023.04
* Device: PineNote (Arch Linux): sway (affects both wayland and x11 SDL backend)

#### Issue
I was using the pen tool to highlight a PDF file that I got from https://en.wikipedia.org/w/index.php?title=Special:DownloadAsPdf&page=Mathematical_formulation_of_quantum_mechanics&action=show-download-screen. I can reliably cause KOReader to quit by performing a selection in said file using a stylus input. I cannot using touch input. I'll see if I can reproduce this using a regular mouse later or another tablet device. The log shows that an Alt-F4 triggers the shutdown. This one is triggered by https://github.com/koreader/koreader-base/blob/e2778f3863136c5b885c8ba560ea603bb699abc7/ffi/SDL2_0.lua#L503 in turn, which is probably sent by SDL, as I did not see any relevant wayland events. Disabling the handling of the event causes the window to close without the process terminating.

Have you seen anything like this before? I can start debugging this sometime this week.

#### Steps to reproduce
1. Open document
2. Use stylus to start selection, change selection by moving the stylus a lot for a few seconds
3. Witness KOReader terminating

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/11478802/crash.log)

### PR DESCRIPTION
**Pull request by hrdl-github**
Updating the selection queries the same page tens of times per second. This prevents KOReader to keep up high-frequency input event streams.

Fixes #10443. Relies on koreader/koreader-base#1612.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/10450)

### CODE REVIEW

File: frontend/document/pdfdocument.lua [hunk 1]
```diff
@@ -103,10 +103,17 @@ function PdfDocument:comparePositions(pos1, pos2)
 end
 
 function PdfDocument:getPageTextBoxes(pageno)
-    local page = self._document:openPage(pageno)
-    local text = page:getPageText()
-    page:close()
-    return text
+    local hash = "textbox|"..self.file.."|"..pageno
```
Comment (Frenzie) [inline frontend/document/pdfdocument.lua:106]: Is this also sufficient in case of zoom changes and the like?

Comment (Frenzie) [reply frontend/document/pdfdocument.lua:106]: I'm talking about playing around with this a bit basically.

Screenshot_20230517_183217

**Review by Frenzie — APPROVED** [review]
