### PR TITLE
Fix #2433

### LINKED ISSUE #2433: Fails to download book from OPDS with colon in filename
* KOReader version: 2015.11-696
* Device: Kindle Paperwhite 3

#### Issue

I have a calibre server set up on the local network that I want to pull books from into koreader. This is functional for all books except books with colons in the filename, where koreader throws the error: "Could not save file to [local directory]"

### PR DESCRIPTION
**Pull request by robert00s**
close #2433 
Fix: #2433

### CODE REVIEW

File: frontend/ui/widget/opdsbrowser.lua [hunk 1]
```diff
@@ -474,6 +474,8 @@ function OPDSBrowser:downloadFile(item, format, remote_url)
     -- download to user selected directory or last opened dir
     local lastdir = G_reader_settings:readSetting("lastdir")
     local download_dir = G_reader_settings:readSetting("download_dir") or lastdir
+    item.author = item.author:gsub('[\\,%/,:,%*,%?,%",%<,%>,%|]','')
+    item.title = item.title:gsub('[\\,%/,:,%*,%?,%",%<,%>,%|]','')
```
Comment (Frenzie) [inline frontend/ui/widget/opdsbrowser.lua]: While this particular bit of repetition is one thing, the primary reason I proposed it as a util function is that this is hardly the only place where files are being downloaded or written. Of lesser importance is that at least in theory such a utility function could have additional logic related to detecting inferior filesystems.

Comment (Frenzie) [inline frontend/ui/widget/opdsbrowser.lua]: PS I should probably clarify that I'm talking about something that would fit in alongside these bunch of functions: https://github.com/koreader/koreader-base/blob/c198ca05d904f61f655cf7adbe2f361098e653ac/ffi/util.lua#L101-L194

Comment (houqp) [inline frontend/ui/widget/opdsbrowser.lua]: Agreed, let's create a helper function in utils to handle filesystem filename compatibility issues. KOReader also runs on systems that does these characters in filenames. Smart detection for inferior filesystems at runtime would be ideal. But you can skip it if you don't want to work on it.

Also, can we replace those characters with something like `-` or `_`?

Comment (Frenzie) [inline frontend/ui/widget/opdsbrowser.lua]: Just brainstorming here as it might be a bad idea, but there are characters that look similar or the same but aren't those characters so they could be replaced by something more specific.

Regular question mark: `?`
Fullwidth question mark: `？`
Small question mark: `﹖`
Ornamental question mark: `❓` (less likely to be supported)

Similarly you have `꞉` (Modifier Letter Colon), etc.

You can use the search on https://unicode-table.com/en/ to find many of these, but note that some (like `�`) have names like "replacement character" and the search isn't intelligent enough to show such characters as well.

Anyway, just a thought. I'm sure there must be plenty of objections to performing such replacements automagically.

**Comment by KenMaltby** [comment]
One of the more useful differences between KOReader and the stock Kobo software, is KOReader's ability to tolerate "imperfect" ebook files.  Replacing incompatible characters with compatible place holders, would be a good way to keep the perfect from becoming the enemy of the useable.

File: frontend/ui/widget/opdsbrowser.lua (hunk 1 above)
Comment (robert00s) [inline frontend/ui/widget/opdsbrowser.lua]: I think characters that look similar may be confusing. User might think that e.g question mark or colon are correct characters in file name.
We can remove incorrect characters or like @houqp replace those with `_`.
I cannot find easy way to detect filesystems in LUA so I propose to remove all those characters : `\,/,:,*,?,",<,>,|`

Comment (houqp) [inline frontend/ui/widget/opdsbrowser.lua]: Let's replace invalid chars with `_` for now then. I think what @Frenzie proposed should work in practice. If getFilesystemType returns `nil`, then just assume there is no restriction on filenames.

Some minor fixes for the snipet:

```lua
function util.getFilesystemType(path)
    local type
    mounts = io.open("/proc/mounts", "r")
    if not mounts then return nil end
    while true do
        local line, mount
        line = mounts:read()
        if line == nil then
            break
        end
        mount = line:split(" ")
        -- FIXME: do a prefix compare. this should pass as long as mount[2] is a prefix of path
        if (mount[2] == path) then
            type = mount[3]
            break
        end
    end
    mounts:close()
    return type
end
```

**Comment by houqp** [comment]
Sorry for the late response. One last request from me ;)

Can we change the behavior to only run replaceInvalidChars when vfat is detected as the filesystem type? Modern fileystems on android and PC(emulator) should be able to handle those characters properly.

**Comment by robert00s** [comment]
@houqp 
On Kindle /mnt/us is detected as "fuse.fsp" so I add also that pseudo FS instead of vfat in condition clause.

**Comment by houqp** [comment]
Looks good to me, thanks!
