### PR TITLE
Kobo: Refactor various aspects of the Kaleido/MTK support

### LINKED ISSUE #12218: KOReader does a full refresh whenever anything changes on the screen (including time) when image is visible
* KOReader version: 2024.07-25
* Device: Kobo Libra Colour

#### Issue

Any time an epub is open with an image on screen, the screen will do a full refresh at least once, even if a menu is blocking the image from view. The setting `Always flash on pages with images` will decrease the time it takes for the extra refresh to occur, but it will still do it regardless. I also noticed that even when all of the screen flash settings are disabled (such that it shouldn't flash the screen automatically at all), it will still flash every time you flip to a page with an image.

It does not appear to flash an extra time when viewing a CBZ file.

Ok, I think I've figured out the trigger. Every time any changes on the screen, even the time or the "Frontlight enabled/disabled" popup, when an image is on the screen in an epub, the entire screen will do a full refresh. It doesn't do it in a CBZ file since the time on mine is in the Alt Status Bar which isn't visible in a CBZ file. (Side note, would be great to get the option to enable the Alt Status Bar in a CBZ file) It does start doing it in a CBZ file if I have the menu open so the time is visible, but the time in the menu doesn't change automatically, only when you switch to a different menu, so it's really odd that it's flashing the whole screen when the menu's time is visible.

This is the first time I've read a graphic novel or comic on my Kobo, so I don't know if it's always done this or if it was something that changed recently. Either way, I don't think it should be doing a full refresh when it doesn't need to, and instead should only flash the little bit of the screen that did change. Time probably doesn't need a refresh at all, or at least it should be controlled by the option "Flash buttons and menu items".

#### Steps to reproduce

1. Open epub with images
2. Turn on Time in the status bar
3. Flip to page that has an image on it.

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/16370920/crash.log)

### PR DESCRIPTION
**Pull request by NiLuJe**
NOTE: Initial, deprecated, comment about the original approach that tried to handle this in UIManager:

This... is not pretty, and was mostly not a problem previously, because it mostly did not affect flashing updates, which means that, even if we were to request spuriously full-screen refreshes, they wouldn't do anything visible, because most waveform modes do not visibly affect unmodified pixels.

~~I'm hoping to be able to shove it under the rug once more once the kernel sources come out, because I suspect we don't actually need dedicated public color/colortext modes, and can instead just implement it silently behind the scenes in fb_mxcfb based on the dither flag.~~

EDIT: Turns out most of my issues with my initial test of the above were due to stupid bugs, so, done. Meaning this now depends on https://github.com/koreader/koreader-base/pull/1865

Fix #12218

----

Actual changelog now that things are simpler (via the magic of deleting code \o/):

* UIManager: Let the fb backend deal with Kaleido wfm promotion. This fixes a number of quirks that poisoned the refresh queue with spurious full-screen refreshes. See https://github.com/koreader/koreader-base/pull/1865 for more details.
* This also means we now disable Kaleido waveform modes when color rendering is disabled (remember to trash your thumbnail cache if you don't want to mix color w/ grayscale thumbnails, though).
* UIManager: Merge refreshes that share an edge, because that was driving me nuts (and would have most likely been merged by the kernel anyway). A perfect test-case is the FM, which trips two separate refreshes because of its title bar.
* ReaderFlipping: Use sensible dimensions, so that we only refresh the icon's region.
* ReaderBookmark: Only refresh the dogear instead of the whole page when toggling bookmarks.
* NetworkSetting: Make it a real boy, so it consistently refreshes properly on dismiss instead of relying on UIManager saving the day.
* Kobo: Aggressively prevent *both* suspend & standby while MTK devices are plugged-in, as both will horribly implode the kernel (we previously only prevent standby while charging).
* Kobo: Switch to 8bpp on B&W MTK devices (or when color rendering is disabled on Kaleido panels).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/12221)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Not that a much simpler test-case than the stuff mentioned in the linked issue is to simply dismiss the status bar ;).

Similarly, it definitely affected stuff like the CRe reloading icons, possibly even the loading progress bar I guess?

**Comment by NiLuJe** [comment]
Toggling a bookmark still flashes, because https://github.com/koreader/koreader/blob/761cf1822258da62b5c72063f2b8b12d348b5cb4/frontend/apps/reader/modules/readerbookmark.lua#L315

I'm unfamiliar with the whole bookmark icons and how/where they're rendered, but dogear is already annoying enough that I don't think we have a much better way to deal with this without basically rewriting the both of them to be less annoying to catch as partial refreshes.

**Comment by hius07** [comment]
Toggling a bookmark also updates the footer (Number of bookmarks indicator).

**Comment by NiLuJe** [comment]
There, clobbered ReaderBookmark into submission.

----

> Toggling a bookmark also updates the footer (Number of bookmarks indicator).

There's already an onUpdateFooter call that handles that ;). (a bit optimistcally, mind you, as it refreshes even when you don't actually display the bookmark count).

**Comment by NiLuJe** [comment]
> (a bit optimistcally, mind you, as it refreshes even when you don't actually display the bookmark count

Eeh, we don't really have a sane way to tell from outside ReaderFooter. I'll let the kernel optimize that one out.

**Comment by NiLuJe** [comment]
> I'm hoping to be able to shove it under the rug once more once the kernel sources come out, because I suspect we don't actually need dedicated public color/colortext modes, and can instead just implement it silently behind the scenes in fb_mxcfb based on the dither flag.

Tried it, turns out I kinda like the granularity afforded by the current approach. :D.

**Comment by NiLuJe** [comment]
> Tried it, turns out I kinda like the granularity afforded by the current approach. :D.

Granularity issue turned out to be a bug, so that works just fine, and greatly simplifies this mess, so I'm happy.

File: frontend/ui/geometry.lua [hunk 1]
```diff
@@ -208,6 +208,32 @@ function Geom:intersectWith(rect_b)
     return not self:notIntersectWith(rect_b)
 end
 
+--[[--
+Returns true if self does not share any area with rect_b
+
+@tparam Geom rect_b
+]]
+function Geom:notOpenIntersectWith(rect_b)
```
Comment (poire-z) [inline frontend/ui/geometry.lua:216]: What does "open" means in this context ? If it is about the edges being shared, "open" does not intuitively relate to that for me :)

File: frontend/apps/reader/modules/readerflipping.lua [hunk 2]
```diff
@@ -40,18 +40,13 @@ function ReaderFlipping:init()
         alpha = true,
     }
     self[1] = LeftContainer:new{
-        dimen = Geom:new{w = Screen:getWidth(), h = self.flipping_widget:getSize().h},
+        dimen = Geom:new{w = self.flipping_widget:getSize().w, h = self.flipping_widget:getSize().h},
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerflipping.lua:43]: I guess this LeftContainer is a no-op/null-container then :) and we could have `self[1] = self.flipping_widget`
But ok for keeping it as-is and not change anything else that works.

**Review by poire-z — APPROVED** [review]
Looks ok and trusting you.

File: frontend/ui/geometry.lua (hunk 1 above)
Comment (NiLuJe) [reply frontend/ui/geometry.lua:216]: Half-open range, e.g., `[x, x + w)` instead of [x, x+ w]`.

File: frontend/apps/reader/modules/readerflipping.lua (hunk 2 above)
Comment (NiLuJe) [reply frontend/apps/reader/modules/readerflipping.lua:43]: Huh, yeah, looks like it.

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerflipping.lua:43]: Oh, wait, it might be useful to handle mirroring in RTL mode?

Comment (poire-z) [reply frontend/apps/reader/modules/readerflipping.lua:43]: Oh, possibly indeed :)
So, may be your change of reducing its width from the screen width to the icon size is wrong ?

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerflipping.lua:43]: Oh, dammit, I was just thinking this might at least break the *refreshes* in RTL, but you're right, it probably breaks positioning, too :/.

Welp, I desperately need a nap, so, more on that later ;).

Comment (NiLuJe) [reply frontend/apps/reader/modules/readerflipping.lua]: There, fixed it. And did something slightly more elegant for the refresh region (i.e., we can just use the IconWidget's dimen object).

File: frontend/apps/reader/modules/readerbookmark.lua [hunk 3]
```diff
@@ -310,9 +310,15 @@ end
...
-    self.view.footer:onUpdateFooter(self.view.footer_visible)
     self.view.dogear:onSetDogearVisibility(not self.view.dogear_visible)
-    UIManager:setDirty(self.view.dialog, "ui")
+    -- Refresh the dogear first, because it might inherit ReaderUI refresh hints.
+    UIManager:setDirty(self.view.dialog, function()
+        return "ui",
+        self.view.dogear:getRefreshRegion()
+    end)
+    -- And ask for a footer refresh, in case we have bookmark_count enabled.
+    -- Assuming the footer is visible, it'll request a refresh regardless, but the EPDC should optimize it out if no content actually changed.
```
Comment (poire-z) [inline frontend/apps/reader/modules/readerbookmark.lua:320]: Is that true for older boards ? (ie. my GloHD :))

**Review by poire-z — APPROVED** [review]

File: frontend/apps/reader/modules/readerbookmark.lua (hunk 3 above)
Comment (NiLuJe) [reply frontend/apps/reader/modules/readerbookmark.lua:320]: Even if the driver doesn't actually optimize it out, even GC16 won't visually affect unchanged pixels, and that's been the case forever ;).

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 2 files at r3, 6 of 7 files at r6, 1 of 1 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12221)* status: all files reviewed, 3 unresolved discussions (waiting on @Frenzie, @pazos, and @poire-z)

**Review by NiLuJe — COMMENTED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/koreader/12221)* status: all files reviewed, 3 unresolved discussions (waiting on @Frenzie, @pazos, and @poire-z)

**Comment by KraXen72** [comment]
do these also improve things on android-based kaleido tablets like the onyx boox go color 7? or is this kobo specific?

**Comment by NiLuJe** [comment]
Nope, Kobo only. There's (mostly) nothing we can do about Android. Cue my usual "anybody using an Android eInk tablet is some kind of masochist" comment ;).

**Comment by KraXen72** [comment]
> anybody using an Android eInk tablet is some kind of masochist
  
why though? and why couldn't these improvements, if even necessary, be applied to android eink tablets?

i have a pocketboox touch lux 4 but i just bought a boox go color 7 because it's much easier to get manga on it right from the device (either using mihon/tachiyomi or an android torrent client)

**Comment by NiLuJe** [comment]
Because we have nowhere *near* this level of low-level control on Android (or PocketBook, for that matter).

**Comment by KraXen72** [comment]
Hello. sorry to necro this, I just got a Kindle Paperwhite 2024. How's the e-ink control story there? Thanks.

**Comment by NiLuJe** [comment]
Pretty good, why?

**Comment by KraXen72** [comment]
Wanted to know if the e-ink supports partial updates when inside of koreader, and also, if i can expect it to be meaningfully faster in page-turning compared to my old onyx boox page, which is an android-based e-reader. and any other meaningful differences between those two in terms of koreader, i fyou can think of some off the top of your head.
Thanks!

**Comment by NiLuJe** [comment]
Yes, to all of those. Android is terrible for eInk.

**Comment by KraXen72** [comment]
Alright, Thank you! and have a nice day :)))
