### PR TITLE
Blacklist a few Amazon Ember styles to get the main ones to behave.

### LINKED ISSUE #5950: Some fonts render too bold
* KOReader version: v2020.03.01
* Device: Kindle PW3 (5.9.7)

#### Issue
This is not a critical bug, but I still would like to report it. Maybe you can enhance the font rendering engine.

Fonts like Amazon Ember and Futura from stock Amazon firmware, and side-loaded such as Futura v1.001 ([Literata_v1.001.zip](https://github.com/koreader/koreader/files/4331317/Literata_v1.001.zip) are rendered too bold in KOReader. However, a [newer](https://fonts.google.com/specimen/Literata) version of Futura is fine.

Stock fonts are in /usr/java/lib/fonts/ (I don't know if I can upload them here from my Kindle due to copyright), side-loaded fonts are in /mnt/us/fonts/ folder. All fonts are given in sets of 4 ttf files (regular, bold, italic, bold-italic). 

No font settings affect this behavior (e.g. render modes, hinting, kerning, embedded styles).
A book is of fb2.zip format (if this matters).

P.S. By the way, what is the difference between render modes "book" and "web"? Also between hinting "native" and "auto"?

**Amazon Ember:**
Reader_2020-Mar-13_152524

**Futura:**
Reader_2020-Mar-13_152553

**Literata v1.001:**
Reader_2020-Mar-13_154657

##### `crash.log` 
[crash_fonts.log](https://github.com/koreader/koreader/files/4331925/crash_fonts.log)
It says some errors about Amazon Ember, old Literata and Caecelia fonts. Nothing about Futura though.

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #5950

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/5951)

### CODE REVIEW

File: frontend/fontlist.lua [hunk 1]
```diff
@@ -48,10 +50,28 @@ local kindle_fonts_blacklist = {
...
+    ["AmazonEmberBold-Regular.ttf"] = true,
+    ["Caecilia_LT_65_Medium.ttf"] = false,
+    ["Caecilia_LT_66_Medium_Italic.ttf"] = false,
+    ["Caecilia_LT_75_Bold.ttf"] = false,
+    ["Caecilia_LT_76_Bold_Italic.ttf"] = false,
     ["Caecilia_LT_67_Cond_Medium.ttf"] = true,
     ["Caecilia_LT_68_Cond_Medium_Italic.ttf"] = true,
     ["Caecilia_LT_77_Cond_Bold.ttf"] = true,
     ["Caecilia_LT_78_Cond_Bold_Italic.ttf"] = true,
+    ["Futura-Bold.ttf"] = true,
```
Comment (Frenzie) [inline frontend/fontlist.lua]: Must be annoying for Kindle users that they use normal font names for these weird fonts.

**Comment by NiLuJe** [comment]
I think some of it might stem from licensing restrictions (can't rename a font).
