### PR TITLE
Text/HTML widgets: allow scrolling with the scrollbar

### LINKED ISSUE #5308: FR: Jump to arbitrary location using scrollbar
Scrollbar just moves down no matter where I press.

scroll

### LINKED ISSUE #5387: reflowed PDFs, containing scanned images only: koreader crashes on trying to set a bookmark
* KOReader version: v2019.09.3
* Device: Kobo Clara HD

#### Issue
1) while reading a PDF that contains photos / scaleable pictures of the printed page;
2) I use reflow (when the text is is decoded from graphics embedded into PDF, and re-rendered as reformatted lines, glued back into paragraphs according to the font size);
3) the view mode = "continuous", when I tap and get the next page completely new (not the "page" view mode - it's very inconvenient when I tap and move from first half of the page to the last half of the page with some overlapped content that I've read already);
4) when trying to set a bookmark by the click on the right upper corner;
5) I receive a crash and no bookmarks are stored;

#### Steps to reproduce
- open a PDF with scanned printed pages (I will find one for you soon);
- set PDF reflow = on
- set the View mode = continuous when you flip the page and it contains non-overlapping piece;
- tap in the upper right corner;

##### `crash.log` (if applicable)

```
 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/16/19-01:41:03
 [*] Version: v2019.09.3

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 3342336
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 3072
FB: bpp          : 8
09/16/19-01:41:03 INFO  initializing for device Kobo_nova
09/16/19-01:41:03 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:15451).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
09/16/19-01:41:03 INFO  opening file /mnt/onboard/_books-kobo/books-2019-07-commIsTheKey/kak_razgovarivat_s_mudakami.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
09/16/19-01:41:03 INFO  Loading plugins from directory: plugins
09/16/19-01:41:03 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
09/16/19-01:41:03 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
09/16/19-01:41:03 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
09/16/19-01:41:03 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
09/16/19-01:41:03 INFO  setting zoom mode to page
warning: expected name after CMapName in cmap
ffi.load: pthread
ffi.load (warning): libpthread.so: cannot open shared object file: No such file or directory
ffi.load: libpthread.so.0
09/16/19-01:41:14 INFO  opening file /mnt/onboard/_books-kobo/books-2019-01-psycho/XXX.pdf
09/16/19-01:41:14 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
09/16/19-01:41:14 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
09/16/19-01:41:15 INFO  setting zoom mode to page
09/16/19-01:41:15 INFO  setting zoom mode to pageheight
./luajit: frontend/apps/reader/modules/readerbookmark.lua:348: attempt to index field 'pos0' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerbookmark.lua:348: in function 'isBookmarkSame'
	frontend/apps/reader/modules/readerbookmark.lua:363: in function 'addBookmark'
	frontend/apps/reader/modules/readerbookmark.lua:523: in function 'toggleBookmark'
	frontend/apps/reader/modules/readerbookmark.lua:171: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/apps/reader/modules/readergesture.lua:1354: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:251: in function 'handleEvent'
	frontend/ui/uimanager.lua:670: in function 'sendEvent'
	frontend/ui/uimanager.lua:174: in function '__default__'
	frontend/ui/uimanager.lua:1010: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1071: in function 'handleInput'
	frontend/ui/uimanager.lua:1115: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash n°1: 09/16/19 @ 01:41:26)
Attempting to restart KOReader . . .
!!!!
```

### LINKED ISSUE #6487: FR: Add "Start with favorites" option
Currently, the settings for the file browser contain options to start with the file browser, history, folder shortcuts or the last file.
I believe that the option to start with the favorites would be a good addition. This would allow booting KOReader into a curated list or mosaic of favorited books, which in the mosaic case would effect a sort of bookcase.

### PR DESCRIPTION
**Pull request by poire-z**
- Bookmarks: avoid possible crash. See https://github.com/koreader/koreader/issues/5387#issuecomment-675551293. Closes #5387 
- Start with: adds Favorites. Closes #6487 
- Text/HTML widgets: allows scrolling with the scrollbar. Closes #5308 
Little difference from what we are used to on computers: tapping jumps to where we tap, instead of paging just one page in that direction as on computers - as we can already page one page by tapping in the text or via other buttons (and it makes it a little easier to use).
Not super easy with dictionaries and Wikipedia (I made the touch area 3 times the width of the scrollbar, to not make the scrollbar larger and ugly, so I hope people were not tapping that near the scrollbar for browsing down current result or going to next...)
But quite fine with the TextEditor where the scrollbar is near the screen edge. May be easier on sunken screen like on my GloHD where we can follow the screen edge, dunno about flush screens.

(Just closing a few issues. 317 left to go at :)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/6577)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Oh, cool, I tried to do just that the other day and was mildly miffed it didn't work ;).

File: frontend/ui/widget/scrollhtmlwidget.lua [hunk 1]
```diff
@@ -89,7 +92,10 @@ end
 
 function ScrollHtmlWidget:scrollToRatio(ratio)
     ratio = math.max(0, math.min(1, ratio)) -- ensure ratio is between 0 and 1 (100%)
-    local page_num = 1 + Math.round((self.htmlbox_widget.page_count - 1) * ratio)
+    local page_num = 1 + math.floor((self.htmlbox_widget.page_count) * ratio)
```
Comment (Frenzie) [inline frontend/ui/widget/scrollhtmlwidget.lua:95]: What does this change do precisely?

**Review by Frenzie — APPROVED** [review]

File: frontend/ui/widget/scrollhtmlwidget.lua (hunk 1 above)
Comment (poire-z) [reply frontend/ui/widget/scrollhtmlwidget.lua:94]: Precisely? It makes it works :) 
I added these methods scrollToRatio initially as some generic stuff, but it was only needed until now to do scrollToRatio(1) (100%) in DictQuickLookup to go at the bottom of previous result when paging back.
I never really tested it with other real ratios between 0 and 1, and never wondered what has to be positionned at this ratio: the top? the middle?
Math.round() I think could possibly position at the next page, so the position in the scrollbar you tapped on might be not in the black part you'll be then displaying.
With math.floor(), we go to the nearest top of page before your tap position, so your tap position is in the black bar.
(I'm getting old, more and more of these arithmetic stuff, I get to the end of them with trial and errors... my first intuition rarely works out... The +1 / -1 was that. Tested with a dict result spanning 3 pages, then 4, seemed to work, had a drink :)
