### PR TITLE
Various fixes: footnotes, HTML dictionary, Button

### LINKED ISSUE #7946: Numbering of definitions in dictionary pop-up misaligned (on KOA3)
* KOReader version: 2021.06 "Catkin"
* Device: Kindle Oasis 3

#### Issue
In the dictionary pop-up, the numbering of definitions is misaligned to the left leaving the numbers partly cut out (see the screenshot attached)
Dictionay

#### Steps to reproduce
Bring up the dictionary pop-up

### LINKED ISSUE #8033: epub:type="endnote" doesn't trigger on-page endnotes
* KOReader version: 2021.06-27
* Device: Kobo Clara/Emulator

#### Issue

Footnotes with the `epub:type="doc-endnote"` don't trigger in-page footnotes. `epub:type="doc-rearnote"` does.

According to https://idpf.github.io/epub-vocabs/structure/#endnote `rearnote` is deprecated and `endnote` is the replacement. I have seen `endnote` used on a real document. 

#### Steps to reproduce

Open the attached file, observe only one footnote shown on the page, despite two being defined.

[endnote.epub.zip](https://github.com/koreader/koreader/files/6889196/endnote.epub.zip)

I _think_ this could be resolved by just adding to the selectors here: https://github.com/koreader/koreader/blob/acfc5eec2b62196104f779cb7b57b37c80dc01ac/frontend/ui/data/css_tweaks.lua#L731-L741

### PR DESCRIPTION
**Pull request by poire-z**
`Footnote popups/in-page: support type/role=endnote` closes #8033

`Dict: avoid list items bullet/digit truncation with HTML dicts` closes #7946

`Button: avoid cut words when switching to multilines` See https://github.com/koreader/koreader/pull/8078#issuecomment-899242126

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/8092)

### CODE REVIEW

File: frontend/ui/widget/dictquicklookup.lua [hunk 1]
```diff
@@ -751,7 +751,18 @@ function DictQuickLookup:getHtmlDictionaryCss()
         blockquote, dd {
             margin: 0 1em;
         }
+
+        ol, ul, menu {
+            margin: 0; padding: 0 1.7em;
```
Comment (Frenzie) [inline frontend/ui/widget/dictquicklookup.lua:756]: 1.7? :-)

**Review by Frenzie — APPROVED** [review]

File: frontend/ui/widget/dictquicklookup.lua (hunk 1 above)
Comment (poire-z) [reply frontend/ui/widget/dictquicklookup.lua:756]: Yep, with 1.5 I got "21..." truncated with various DPI settings:
image image

With 1.6 it looks ok, but 1.7 just to be sure it really is :)
